/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Czech
export default {
  'dragonfruit-utils.error-boundary.detailed.click-here': 'Kliknutím sem',
  'dragonfruit-utils.error-boundary.detailed.hide-details': 'Skrýt podrobnosti',
  'dragonfruit-utils.error-boundary.detailed.see-browser-console':
    'Úplný popis chyby najdete v konzole prohlížeče.',
  'dragonfruit-utils.error-boundary.detailed.show-details':
    'Zobrazit podrobnosti',
  'dragonfruit-utils.error-boundary.detailed.unexpected-error':
    'Došlo k neočekávané chybě. {clickHereLink} znovu načtete stránku.',
};
