/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Spanish
export default {
  'dragonfruit-utils.error-boundary.detailed.click-here': 'Haz clic aquí',
  'dragonfruit-utils.error-boundary.detailed.hide-details': 'Ocultar detalles',
  'dragonfruit-utils.error-boundary.detailed.see-browser-console':
    'Consulta la consola del navegador para ver el error al completo.',
  'dragonfruit-utils.error-boundary.detailed.show-details': 'Mostrar detalles',
  'dragonfruit-utils.error-boundary.detailed.unexpected-error':
    'Se ha producido un error inesperado. {clickHereLink} para volver a cargar la página',
};
