// LIMITS FOR LINKS
export const MAX_COMPASS_LINKS_PER_SECTION = 5;

export const MAX_COMPASS_LINK_NAME_LENGTH = 140;
export const MAX_COMPASS_LINK_URL_LENGTH = 2000;

// LIMITS FOR RELATIONSHIPS
export const MAX_RELATIONSHIPS_PER_COMPONENT = 25;

// LIMITS FOR LABELS
export const MAX_COMPONENT_LABEL_INPUT_VALUES = 10;
export const MAX_COMPONENT_LABELS_PER_COMPONENT = 10;
export const MAX_COMPONENT_LABEL_NAME_LENGTH = 40;
