#!/bin/bash
export RELEASE_DASHBOARD_URL=$RELEASE_DASHBOARD_URL
export RELEASE_DASHBOARD_TOKEN=$PIPELINES_JWT_TOKEN
export STASH_USER_BOT=$STASH_USER_BOT
export STASH_TOKEN_BOT=$STASH_TOKEN_BOT

yarn update-deployment-info
