schema: ./src/__generated__/schema.json
documents:
  - ./src/**/*.{ts,tsx}
generates:
  ./src/__generated__/graphqlTypes.tsx:
    plugins:
      - typescript
      - typescript-operations
config:
  namingConvention:
    enumValues: keep # https://github.com/dotansimha/graphql-code-generator/issues/642#issuecomment-495919863