//==============================================================
/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */
// @generated
// This file was automatically generated and should not be edited.
//==============================================================

export interface PossibleTypesResultData {
        possibleTypes: {
          [key: string]: string[]
        }
      }
const result: PossibleTypesResultData = {
  possibleTypes: {
    Node: [
      'ActivitiesItem',
      'ActivitiesObject',
      'ActivitiesEvent',
      'AppLog',
      'BitbucketRepository',
      'DevOpsServiceAndRepositoryRelationship',
      'DevOpsService',
      'DevOpsServiceRelationship',
      'DevOpsServiceAndJiraProjectRelationship',
      'JiraProject',
      'JiraProjectCategory',
      'JiraProjectAndOpsgenieTeamRelationship',
      'OpsgenieTeam',
      'DevOpsServiceAndOpsgenieTeamRelationship',
      'JiraProjectAndRepositoryRelationship',
      'BitbucketWorkspace',
      'BoardFeatureGroup',
      'BoardFeatureView',
      'CompassComponent',
      'CompassScorecard',
      'DeploymentSummary',
      'JiraApplicationProperty',
      'JiraDefaultGrantTypeValue',
      'JiraGroupGrantTypeValue',
      'JiraIssueFieldGrantTypeValue',
      'JiraProjectRoleGrantTypeValue',
      'JiraUserGrantTypeValue',
      'JiraIssue',
      'JiraWorklog',
      'JiraIssueType',
      'JiraSprint',
      'JiraVersion',
      'JiraPermissionScheme',
      'TownsquareComment',
      'TownsquareGoal',
      'TownsquareProject',
      'WebTriggerUrl',
      'JiraCmdbObject',
      'JiraOption',
      'JiraComponent',
      'JiraIssueLinkTypeRelation',
      'JiraPriority',
      'JiraResolution',
      'JiraStatusCategory',
      'JiraPlatformAttachment',
      'JiraPlatformComment',
      'JiraSecurityLevel',
      'JiraServiceManagementActiveApproval',
      'JiraServiceManagementCompletedApproval',
      'JiraServiceManagementAttachment',
      'JiraServiceManagementComment',
      'JiraServiceManagementRequestType',
      'JiraStatus',
      'JiraTeam',
    ],
    User: ['AppUser', 'AtlassianAccountUser', 'CustomerUser'],
    ActivitiesEventExtension: [
      'ActivitiesCommentedEvent',
      'ActivitiesTransitionedEvent',
    ],
    ActivitiesObjectExtension: ['ActivitiesJiraIssue'],
    AppDeploymentEvent: [
      'AppDeploymentLogEvent',
      'AppDeploymentSnapshotLogEvent',
      'AppDeploymentTransitionEvent',
    ],
    MarketplaceAppDeployment: [
      'MarketplaceCloudAppDeployment',
      'MarketplaceConnectAppDeployment',
      'MarketplaceInstructionalAppDeployment',
      'MarketplacePlugins1AppDeployment',
      'MarketplacePlugins2AppDeployment',
      'MarketplaceWorkflowAppDeployment',
    ],
    CompatibleAtlassianProduct: [
      'CompatibleAtlassianCloudProduct',
      'CompatibleAtlassianDataCenterProduct',
      'CompatibleAtlassianServerProduct',
    ],
    AppInstallationTask: [
      'AppInstallationCreationTask',
      'AppInstallationDeletionTask',
      'AppInstallationSubscribeTask',
      'AppInstallationUnsubscribeTask',
      'AppInstallationUpgradeTask',
    ],
    MutationErrorExtension: [
      'GenericMutationErrorExtension',
      'InvokeExtensionPayloadErrorExtension',
    ],
    FunctionInvocationMetadata: ['AppLog'],
    CompassComponentResult: ['CompassComponent', 'QueryError'],
    CompassScorecardAppliedToComponentsQueryResult: [
      'CompassScorecardAppliedToComponentsConnection',
      'QueryError',
    ],
    QueryErrorExtension: ['GenericQueryErrorExtension'],
    CompassScorecardCriteria: [
      'CompassHasDescriptionScorecardCriteria',
      'CompassHasFieldScorecardCriteria',
      'CompassHasLinkScorecardCriteria',
      'CompassHasOwnerScorecardCriteria',
    ],
    CompassEventsQueryResult: ['CompassEventConnection', 'QueryError'],
    CompassEvent: ['CompassDeploymentEvent'],
    CompassField: ['CompassEnumField'],
    CompassFieldDefinitionOptions: ['CompassEnumFieldDefinitionOptions'],
    CompassRelationshipConnectionResult: [
      'CompassRelationshipConnection',
      'QueryError',
    ],
    CompassFieldDefinitionsResult: ['CompassFieldDefinitions', 'QueryError'],
    CompassScorecardResult: ['CompassScorecard', 'QueryError'],
    CompassScorecardsQueryResult: ['CompassScorecardConnection', 'QueryError'],
    CompassComponentLabelsQueryResult: [
      'CompassSearchComponentLabelsConnection',
      'QueryError',
    ],
    CompassComponentQueryResult: [
      'CompassSearchComponentConnection',
      'QueryError',
    ],
    CompassStarredComponentQueryResult: [
      'CompassStarredComponentConnection',
      'QueryError',
    ],
    SupportRequestCommonRequest: [
      'SupportRequestHierarchyRequest',
      'SupportRequest',
    ],
    DevOpsMetricsCycleTimeMetrics: [
      'DevOpsMetricsCycleTimeMean',
      'DevOpsMetricsCycleTimePercentile',
    ],
    JiraGrantTypeValue: [
      'JiraDefaultGrantTypeValue',
      'JiraGroupGrantTypeValue',
      'JiraIssueFieldGrantTypeValue',
      'JiraProjectRoleGrantTypeValue',
      'JiraUserGrantTypeValue',
    ],
    JiraIssueField: [
      'JiraAffectedServicesField',
      'JiraAssetField',
      'JiraAtlassianTeamField',
      'JiraAttachmentsField',
      'JiraCMDBField',
      'JiraCascadingSelectField',
      'JiraCheckboxesField',
      'JiraColorField',
      'JiraComponentsField',
      'JiraConnectMultipleSelectField',
      'JiraConnectNumberField',
      'JiraConnectRichTextField',
      'JiraConnectSingleSelectField',
      'JiraConnectTextField',
      'JiraDatePickerField',
      'JiraDateTimePickerField',
      'JiraEpicLinkField',
      'JiraFlagField',
      'JiraForgeGroupField',
      'JiraForgeNumberField',
      'JiraForgeStringField',
      'JiraForgeStringsField',
      'JiraForgeUserField',
      'JiraIssueLinkField',
      'JiraIssueRestrictionField',
      'JiraIssueTypeField',
      'JiraLabelsField',
      'JiraMultipleGroupPickerField',
      'JiraMultipleSelectField',
      'JiraMultipleSelectUserPickerField',
      'JiraMultipleVersionPickerField',
      'JiraNumberField',
      'JiraParentIssueField',
      'JiraPeopleField',
      'JiraPriorityField',
      'JiraProjectField',
      'JiraRadioSelectField',
      'JiraResolutionField',
      'JiraRichTextField',
      'JiraSecurityLevelField',
      'JiraServiceManagementApprovalField',
      'JiraServiceManagementDateTimeField',
      'JiraServiceManagementIncidentLinkingField',
      'JiraServiceManagementMultipleSelectUserPickerField',
      'JiraServiceManagementOrganizationField',
      'JiraServiceManagementPeopleField',
      'JiraServiceManagementRequestFeedbackField',
      'JiraServiceManagementRequestLanguageField',
      'JiraServiceManagementRequestTypeField',
      'JiraServiceManagementRespondersField',
      'JiraSingleGroupPickerField',
      'JiraSingleLineTextField',
      'JiraSingleSelectField',
      'JiraSingleSelectUserPickerField',
      'JiraSingleVersionPickerField',
      'JiraSprintField',
      'JiraStatusField',
      'JiraSubtasksField',
      'JiraTeamField',
      'JiraTimeTrackingField',
      'JiraUrlField',
      'JiraVotesField',
      'JiraWatchesField',
    ],
    JiraAttachment: [
      'JiraPlatformAttachment',
      'JiraServiceManagementAttachment',
    ],
    JiraComment: ['JiraPlatformComment', 'JiraServiceManagementComment'],
    JiraIssueItemContainersResult: ['JiraIssueItemContainers', 'QueryError'],
    JiraIssueItemContainerItem: [
      'JiraIssueItemFieldItem',
      'JiraIssueItemGroupContainer',
      'JiraIssueItemPanelItem',
      'JiraIssueItemTabContainer',
    ],
    JiraIssueItemGroupContainerItem: [
      'JiraIssueItemFieldItem',
      'JiraIssueItemPanelItem',
    ],
    JiraIssueItemTabContainerItem: ['JiraIssueItemFieldItem'],
    JiraJqlFieldValue: [
      'JiraJqlOptionFieldValue',
      'JiraJqlIssueTypeFieldValue',
      'JiraJqlProjectFieldValue',
      'JiraJqlSprintFieldValue',
      'JiraJqlUserFieldValue',
      'JiraJqlGroupFieldValue',
      'JiraJqlVersionFieldValue',
      'JiraJqlCascadingOptionFieldValue',
      'JiraJqlComponentFieldValue',
      'JiraJqlIssueFieldValue',
      'JiraJqlLabelFieldValue',
      'JiraJqlPriorityFieldValue',
      'JiraJqlResolutionFieldValue',
      'JiraJqlStatusCategoryFieldValue',
      'JiraJqlStatusFieldValue',
    ],
    JiraJqlFieldConnectionResult: ['JiraJqlFieldConnection', 'QueryError'],
    JiraJqlHydratedQueryResult: ['JiraJqlHydratedQuery', 'QueryError'],
    JiraJqlQueryHydratedFieldResult: [
      'JiraJqlQueryHydratedError',
      'JiraJqlQueryHydratedField',
    ],
    JiraJqlQueryHydratedValueResult: [
      'JiraJqlQueryHydratedError',
      'JiraJqlQueryHydratedValue',
    ],
    JiraVersionResult: ['JiraVersion', 'QueryError'],
    JiraPermissionSchemeViewResult: ['JiraPermissionSchemeView', 'QueryError'],
    PolarisAnonymousVisitorHash: ['PolarisAnonymousVisitorViewHash'],
    PolarisIdeaField: [
      'PolarisIdeaPlayField',
      'PolarisIdeaArchivedByField',
      'PolarisIdeaArchivedField',
      'PolarisIdeaArchivedOnField',
      'PolarisIdeaDateField',
      'PolarisIdeaDateTimeField',
      'PolarisIdeaDocumentField',
      'PolarisIdeaIssueCommentsField',
      'PolarisIdeaIssueIdField',
      'PolarisIdeaIssueTypeField',
      'PolarisIdeaKeyField',
      'PolarisIdeaLabelsField',
      'PolarisIdeaLinkedIssuesField',
      'PolarisIdeaLinkedIssuesProgressField',
      'PolarisIdeaNumberField',
      'PolarisIdeaOptionField',
      'PolarisIdeaOptionsField',
      'PolarisIdeaSpecialField',
      'PolarisIdeaStatusField',
      'PolarisIdeaStringField',
      'PolarisIdeaUserField',
      'PolarisIdeaUsersField',
      'PolarisIdeaVotesField',
    ],
    SearchResult: [
      'SearchConfluencePageBlogAttachment',
      'SearchConfluenceSpace',
      'SearchDefaultResult',
    ],
    Payload: [
      'DeleteAppStoredEntityPayload',
      'SetAppStoredEntityPayload',
      'ApplyPolarisProjectTemplatePayload',
      'ArchivePolarisInsightsPayload',
      'CompassAcknowledgeAnnouncementPayload',
      'AddCompassComponentLabelsPayload',
      'ApplyCompassScorecardToComponentPayload',
      'AttachCompassComponentDataManagerPayload',
      'AttachEventSourcePayload',
      'CompassCreateAnnouncementPayload',
      'CreateCompassComponentPayload',
      'CreateCompassComponentExternalAliasPayload',
      'CreateCompassComponentLinkPayload',
      'CreateDeploymentEventsPayload',
      'CreateEventSourcePayload',
      'CreateCompassRelationshipPayload',
      'CreateCompassScorecardPayload',
      'CreateCompassScorecardCriteriasPayload',
      'CreateCompassStarredComponentPayload',
      'CompassCreateTeamCheckinPayload',
      'CompassDeleteAnnouncementPayload',
      'DeleteCompassComponentPayload',
      'DeleteCompassComponentExternalAliasPayload',
      'DeleteCompassComponentLinkPayload',
      'DeleteEventSourcePayload',
      'DeleteCompassRelationshipPayload',
      'DeleteCompassScorecardPayload',
      'DeleteCompassScorecardCriteriasPayload',
      'DeleteCompassStarredComponentPayload',
      'CompassDeleteTeamCheckinPayload',
      'DetachCompassComponentDataManagerPayload',
      'DetachEventSourcePayload',
      'RemoveCompassComponentLabelsPayload',
      'RemoveCompassScorecardFromComponentPayload',
      'UnlinkExternalSourcePayload',
      'CompassUpdateAnnouncementPayload',
      'UpdateCompassComponentPayload',
      'UpdateCompassComponentDataManagerMetadataPayload',
      'UpdateCompassComponentLinkPayload',
      'UpdateCompassScorecardPayload',
      'UpdateCompassScorecardCriteriasPayload',
      'CompassUpdateTeamCheckinPayload',
      'ConfigurePolarisRefreshPayload',
      'CopyPolarisInsightsPayload',
      'CreateAppResponse',
      'CreateAppDeploymentResponse',
      'CreateAppDeploymentUrlResponse',
      'CreateAppTunnelResponse',
      'CreateDevOpsServicePayload',
      'CreateDevOpsServiceAndJiraProjectRelationshipPayload',
      'CreateDevOpsServiceAndOpsgenieTeamRelationshipPayload',
      'CreateDevOpsServiceAndRepositoryRelationshipPayload',
      'CreateDevOpsServiceRelationshipPayload',
      'CreateHostedResourceUploadUrlPayload',
      'CreateJiraProjectAndOpsgenieTeamRelationshipPayload',
      'CreateJiraProjectAndRepositoryRelationshipPayload',
      'CreatePolarisAnonymousVisitorHashPayload',
      'CreatePolarisCalculatedFieldPayload',
      'CreatePolarisCommentPayload',
      'CreatePolarisDecorationPayload',
      'CreatePolarisInsightPayload',
      'CreatePolarisStandardFieldPayload',
      'CreatePolarisViewPayload',
      'CreatePolarisViewSetPayload',
      'DeleteAppResponse',
      'DeleteAppEnvironmentVariablePayload',
      'GenericMutationResponse',
      'DeleteDevOpsContainerRelationshipEntityPropertiesPayload',
      'DeleteDevOpsServicePayload',
      'DeleteDevOpsServiceAndJiraProjectRelationshipPayload',
      'DeleteDevOpsServiceAndOpsgenieTeamRelationshipPayload',
      'DeleteDevOpsServiceAndRepositoryRelationshipPayload',
      'DeleteDevOpsServiceEntityPropertiesPayload',
      'DeleteDevOpsServiceRelationshipPayload',
      'DeleteJiraProjectAndOpsgenieTeamRelationshipPayload',
      'DeleteJiraProjectAndRepositoryRelationshipPayload',
      'DeletePolarisAnonymousVisitorHashPayload',
      'DeletePolarisDecorationPayload',
      'DeletePolarisFieldPayload',
      'DeletePolarisFieldOptionPayload',
      'DeletePolarisInsightPayload',
      'DeletePolarisViewPayload',
      'DeletePolarisViewSetPayload',
      'DeleteUserGrantPayload',
      'UpdateAppHostServiceScopesResponsePayload',
      'AppInstallationResponse',
      'InvokeAuxEffectsResponse',
      'InvokeExtensionResponse',
      'InvokePolarisObjectPayload',
      'JiraPermissionSchemeAddGrantPayload',
      'JiraDismissDevOpsIssuePanelBannerPayload',
      'JiraOptoutDevOpsIssuePanelNotConnectedPayload',
      'JiraPermissionSchemeRemoveGrantPayload',
      'RefreshPolarisSnippetsPayload',
      'ResolvePolarisObjectPayload',
      'SetAppEnvironmentVariablePayload',
      'SetExternalAuthCredentialsPayload',
      'SetPolarisProjectOnboardedPayload',
      'SetPolarisSelectedDeliveryProjectPayload',
      'SetPolarisSnippetPropertiesConfigPayload',
      'AppSubscribePayload',
      'UnarchivePolarisInsightsPayload',
      'AppUninstallationResponse',
      'AppUnsubscribePayload',
      'UnwatchMarketplaceAppPayload',
      'UpdateAppDetailsResponse',
      'UpdateAtlassianOAuthClientResponse',
      'UpdateDevOpsContainerRelationshipEntityPropertiesPayload',
      'UpdateDevOpsServicePayload',
      'UpdateDevOpsServiceAndJiraProjectRelationshipPayload',
      'UpdateDevOpsServiceAndOpsgenieTeamRelationshipPayload',
      'UpdateDevOpsServiceAndRepositoryRelationshipPayload',
      'UpdateDevOpsServiceEntityPropertiesPayload',
      'UpdateDevOpsServiceRelationshipPayload',
      'UpdateDeveloperLogAccessPayload',
      'UpdateJiraProjectAndOpsgenieTeamRelationshipPayload',
      'UpdateJiraProjectAndRepositoryRelationshipPayload',
      'UpdatePolarisCalculatedFieldPayload',
      'UpdatePolarisCommentPayload',
      'UpdatePolarisDecorationPayload',
      'UpdatePolarisFieldDescriptionPayload',
      'UpdatePolarisFieldOptionWeightPayload',
      'UpdatePolarisIdeaPayload',
      'UpdatePolarisInsightPayload',
      'UpdatePolarisTermsConsentPayload',
      'UpdatePolarisViewPayload',
      'UpdatePolarisViewRankV2Payload',
      'UpdatePolarisViewSetPayload',
      'AppInstallationUpgradeResponse',
      'UserAuthTokenForExtensionResponse',
      'WatchMarketplaceAppPayload',
    ],
    MutationResponse: [
      'AssignIssueParentOutput',
      'CompleteSprintResponse',
      'CardParentCreateOutput',
      'CreateColumnOutput',
      'CustomFilterCreateOutput',
      'CreateSprintResponse',
      'CreateWebTriggerUrlResponse',
      'DeleteColumnOutput',
      'DeleteWebTriggerUrlResponse',
      'SprintResponse',
      'InvokeAuxEffectsResponse',
      'InvokeExtensionResponse',
      'MoveSprintDownResponse',
      'MoveSprintUpResponse',
      'RankColumnOutput',
      'SetColumnLimitOutput',
      'SetColumnNameOutput',
      'SetSwimlaneStrategyResponse',
      'UnassignIssueParentOutput',
    ],
    LocalizationContext: ['AtlassianAccountUser', 'CustomerUser'],
    JiraIssueFieldConfiguration: [
      'JiraAffectedServicesField',
      'JiraAssetField',
      'JiraAtlassianTeamField',
      'JiraAttachmentsField',
      'JiraCMDBField',
      'JiraCascadingSelectField',
      'JiraCheckboxesField',
      'JiraColorField',
      'JiraComponentsField',
      'JiraConnectMultipleSelectField',
      'JiraConnectNumberField',
      'JiraConnectRichTextField',
      'JiraConnectSingleSelectField',
      'JiraConnectTextField',
      'JiraDatePickerField',
      'JiraDateTimePickerField',
      'JiraEpicLinkField',
      'JiraFlagField',
      'JiraForgeGroupField',
      'JiraForgeNumberField',
      'JiraForgeStringField',
      'JiraForgeStringsField',
      'JiraForgeUserField',
      'JiraIssueLinkField',
      'JiraIssueRestrictionField',
      'JiraIssueTypeField',
      'JiraLabelsField',
      'JiraMultipleGroupPickerField',
      'JiraMultipleSelectField',
      'JiraMultipleSelectUserPickerField',
      'JiraMultipleVersionPickerField',
      'JiraNumberField',
      'JiraParentIssueField',
      'JiraPeopleField',
      'JiraPriorityField',
      'JiraProjectField',
      'JiraRadioSelectField',
      'JiraResolutionField',
      'JiraRichTextField',
      'JiraSecurityLevelField',
      'JiraServiceManagementApprovalField',
      'JiraServiceManagementDateTimeField',
      'JiraServiceManagementIncidentLinkingField',
      'JiraServiceManagementMultipleSelectUserPickerField',
      'JiraServiceManagementOrganizationField',
      'JiraServiceManagementPeopleField',
      'JiraServiceManagementRequestFeedbackField',
      'JiraServiceManagementRequestLanguageField',
      'JiraServiceManagementRequestTypeField',
      'JiraServiceManagementRespondersField',
      'JiraSingleGroupPickerField',
      'JiraSingleLineTextField',
      'JiraSingleSelectField',
      'JiraSingleSelectUserPickerField',
      'JiraSingleVersionPickerField',
      'JiraSprintField',
      'JiraStatusField',
      'JiraSubtasksField',
      'JiraTeamField',
      'JiraTimeTrackingField',
      'JiraUrlField',
      'JiraVotesField',
      'JiraWatchesField',
    ],
    JiraUserIssueFieldConfiguration: [
      'JiraAffectedServicesField',
      'JiraAssetField',
      'JiraAtlassianTeamField',
      'JiraAttachmentsField',
      'JiraCascadingSelectField',
      'JiraCheckboxesField',
      'JiraColorField',
      'JiraComponentsField',
      'JiraConnectMultipleSelectField',
      'JiraConnectNumberField',
      'JiraConnectRichTextField',
      'JiraConnectSingleSelectField',
      'JiraConnectTextField',
      'JiraDatePickerField',
      'JiraDateTimePickerField',
      'JiraEpicLinkField',
      'JiraFlagField',
      'JiraForgeGroupField',
      'JiraForgeNumberField',
      'JiraForgeStringField',
      'JiraForgeStringsField',
      'JiraForgeUserField',
      'JiraIssueLinkField',
      'JiraIssueRestrictionField',
      'JiraLabelsField',
      'JiraMultipleGroupPickerField',
      'JiraMultipleSelectField',
      'JiraMultipleSelectUserPickerField',
      'JiraMultipleVersionPickerField',
      'JiraNumberField',
      'JiraParentIssueField',
      'JiraPeopleField',
      'JiraPriorityField',
      'JiraProjectField',
      'JiraRadioSelectField',
      'JiraResolutionField',
      'JiraRichTextField',
      'JiraSecurityLevelField',
      'JiraServiceManagementApprovalField',
      'JiraServiceManagementDateTimeField',
      'JiraServiceManagementMultipleSelectUserPickerField',
      'JiraServiceManagementOrganizationField',
      'JiraServiceManagementPeopleField',
      'JiraServiceManagementRequestFeedbackField',
      'JiraServiceManagementRequestLanguageField',
      'JiraSingleGroupPickerField',
      'JiraSingleLineTextField',
      'JiraSingleSelectField',
      'JiraSingleSelectUserPickerField',
      'JiraSingleVersionPickerField',
      'JiraSprintField',
      'JiraStatusField',
      'JiraTeamField',
      'JiraTimeTrackingField',
      'JiraUrlField',
      'JiraVotesField',
      'JiraWatchesField',
    ],
    JiraMediaUploadTokenResult: ['JiraMediaUploadToken', 'QueryError'],
    JiraServiceManagementApproverPrincipal: [
      'JiraServiceManagementGroupApproverPrincipals',
      'JiraServiceManagementUserApproverPrincipal',
      'JiraServiceManagementUserApproverPrincipalConnection',
    ],
    JiraServiceManagementResponder: [
      'JiraServiceManagementTeamResponder',
      'JiraServiceManagementUserResponder',
    ],
  },
};
export default result;
