/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Dutch
export default {
  'com.atlassian.migrations-platform.mpt-timeago.ui.just-now': 'nu net',
};
