/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Korean
export default {
  'jsm.gettingStartedPanel.add': '추가',
  'jsm.gettingStartedPanel.addChangeApproversDescription':
    '특정 서비스의 모든 변경 사항에 대한 승인자입니다.',
  'jsm.gettingStartedPanel.addChangeApproversDescriptionNote':
    '참고: 변경 승인자의 그룹을 만든 후에 변경 승인자를 선택할 수 있습니다.',
  'jsm.gettingStartedPanel.addChangeApproversLearnMore':
    '서비스 및 변경 승인자 만들기에 대해 알아보기',
  'jsm.gettingStartedPanel.addChangeApproversStep1':
    '1. {serviceHub}(으)로 이동합니다',
  'jsm.gettingStartedPanel.addChangeApproversStep2':
    '2. (새 서비스에 승인자를 추가하려면) {createService}을(를) 선택합니다.',
  'jsm.gettingStartedPanel.addChangeApproversStep3':
    '3. (기존 서비스에 승인자를 추가하려면) 연결된 서비스 이름 > {ellipsis} > {editService}을(를) 선택합니다',
  'jsm.gettingStartedPanel.addChangeApproversStep4':
    '4. {changeApprovers}을(를) 선택합니다.',
  'jsm.gettingStartedPanel.addChangeApproversStep5':
    '5. {saveService}을(를) 선택합니다',
  'jsm.gettingStartedPanel.addLogo': '로고 추가',
  'jsm.gettingStartedPanel.addPeople': '사용자 추가',
  'jsm.gettingStartedPanel.addTemplateRules': '템플릿 규칙 추가',
  'jsm.gettingStartedPanel.addingUsersDescription':
    '서비스 프로젝트에 팀을 에이전트로 추가하여 프로젝트에 참여하게 하세요.',
  'jsm.gettingStartedPanel.addingUsersLearnMore':
    '팀원 추가에 대해 자세히 알아보기',
  'jsm.gettingStartedPanel.addingUsersStep1':
    '1. {projectSettings} > {people}으로 이동합니다',
  'jsm.gettingStartedPanel.addingUsersStep2': '2. {addPeople}을(를) 선택합니다',
  'jsm.gettingStartedPanel.addingUsersStep3':
    '3. 에이전트의 사용자 이름 또는 이메일을 입력합니다.',
  'jsm.gettingStartedPanel.addingUsersStep4':
    '4. 드롭다운에서 역할을 선택합니다(서비스 프로젝트 팀)',
  'jsm.gettingStartedPanel.addingUsersStep5': '5. {add}을(를) 선택합니다',
  'jsm.gettingStartedPanel.addingUsersStep6':
    '6. 프로젝트에 링크를 포함한 이메일을 받게 됩니다',
  'jsm.gettingStartedPanel.alerts': '알림',
  'jsm.gettingStartedPanel.assignOwnerDescription':
    '즉시 인시던트를 해결하기 시작하도록 적합한 팀에 정보를 제공합니다.',
  'jsm.gettingStartedPanel.assignOwnerDescriptionNote':
    '참고: 서비스는 동기화되며 Opsgenie 및 Jira Service Management 모두에 나타납니다.',
  'jsm.gettingStartedPanel.assignOwnerLearnMore':
    '팀과 서비스 연결에 대해 자세히 알아보기',
  'jsm.gettingStartedPanel.assignOwnerStep1':
    '1. Opsgenie에서 {services}(으)로 이동하여 모든 서비스를 나열합니다',
  'jsm.gettingStartedPanel.assignOwnerStep2':
    '2. {addService}을(를) 선택합니다.',
  'jsm.gettingStartedPanel.assignOwnerStep3':
    '3. {serviceName}을(를) 입력하고 {ownerTeam}을(를) 선택합니다',
  'jsm.gettingStartedPanel.assignOwnerStep4':
    '4. {addServiceSubmit}을(를) 선택하여 서비스를 저장합니다',
  'jsm.gettingStartedPanel.assignOwnerStep5':
    '5. 이후에 팀의 서비스 설정으로 이동하여 더 많은 옵션을 살펴봅니다',
  'jsm.gettingStartedPanel.automationRulesDescription':
    '변경 관리를 시작하기 위해 활성화할 수 있는 몇 가지 샘플 자동화 규칙이 있습니다.',
  'jsm.gettingStartedPanel.automationRulesLearnMore':
    '자동화 규칙에 대해 자세히 알아보기',
  'jsm.gettingStartedPanel.automationRulesStep1':
    '1. {projectSettings} > {projectAutomation}으로 이동합니다',
  'jsm.gettingStartedPanel.automationRulesStep2':
    '2. {addTemplateRules}을(를) 선택합니다',
  'jsm.gettingStartedPanel.back': '뒤로',
  'jsm.gettingStartedPanel.bestPracticesForChangeManagement':
    '변경 관리 모범 사례',
  'jsm.gettingStartedPanel.bestPracticesForITTeams': 'IT 팀 모범 사례',
  'jsm.gettingStartedPanel.bestPracticesForIncidentManagement':
    '인시던트 관리 모범 사례',
  'jsm.gettingStartedPanel.changeApprovers': '변경 승인자',
  'jsm.gettingStartedPanel.changeManagement': '변경 관리',
  'jsm.gettingStartedPanel.changeManagementDescription':
    '이제 변경 관리의 기본 사항을 설정했으므로, Atlassian 설명서를 확인하여 변경 사항으로 할 수 있는 더 많은 기능을 확인해보세요.',
  'jsm.gettingStartedPanel.changeManagementStep1':
    '1. {bestPracticesForChangeManagement}(으)로 이동합니다',
  'jsm.gettingStartedPanel.changeManagementStep2':
    '2. 관심이 가는 문서를 찾습니다.',
  'jsm.gettingStartedPanel.changeTemplate': '템플릿 변경',
  'jsm.gettingStartedPanel.checklist.basics.setupAService': '서비스 설정',
  'jsm.gettingStartedPanel.checklist.basics.tabDescription':
    '프로젝트를 사용할 수 있는 사람, 프로젝트 디자인 및 연결 대상 등 프로젝트의 기본 사항을 설정합니다.',
  'jsm.gettingStartedPanel.checklist.changes.tabDescription':
    '{changes}을(를) 사용하면 변경 사항을 기록, 검토 및 승인하여 팀이 변경 사항을 빠르게 배포하고 위험을 최소화할 수 있습니다.',
  'jsm.gettingStartedPanel.checklist.incidents.setupResponseTeam':
    '대응 팀 설정',
  'jsm.gettingStartedPanel.checklist.incidents.tabDescription':
    '{incidents}을(를) 사용하면 서비스 품질 저해 요소를 해결하거나 체계적인 대응을 받을 수 있도록 대기 중인 팀에 에스컬레이션할 수 있습니다.',
  'jsm.gettingStartedPanel.collapsePanel': '패널 접기',
  'jsm.gettingStartedPanel.common.tabTitle.checklist.basic': '기본',
  'jsm.gettingStartedPanel.common.tabTitle.checklist.changes': '변경 사항',
  'jsm.gettingStartedPanel.common.tabTitle.checklist.incidents': '인시던트',
  'jsm.gettingStartedPanel.common.tourDescription.changeManagement':
    '변경 관리를 안내하는 투어를 둘러보세요. 이전 변경 관리 투어에서 남은 데모 티켓은 종료됩니다.',
  'jsm.gettingStartedPanel.common.tourDescription.incidentManagement':
    '인시던트 관리를 안내하는 투어를 둘러보세요. 이전 인시던트 관리 투어에서 남은 데모 티켓은 종료됩니다.',
  'jsm.gettingStartedPanel.common.tourDescription.welcome':
    '필수 요소를 둘러보는 가이드 투어를 시작하세요.',
  'jsm.gettingStartedPanel.common.tourTitle.changeManagement': '변경 관리',
  'jsm.gettingStartedPanel.common.tourTitle.incidentManagement':
    '인시던트 관리',
  'jsm.gettingStartedPanel.common.tourTitle.welcome': '환영합니다',
  'jsm.gettingStartedPanel.connectPipeline': '파이프라인 연결',
  'jsm.gettingStartedPanel.connectPipelineDescription':
    '이렇게 하면 변경 사항을 제출할 때 요청이 자동으로 만들어집니다.',
  'jsm.gettingStartedPanel.connectPipelineLearnMore':
    '파이프라인 연결하기에 대해 자세히 알아보기',
  'jsm.gettingStartedPanel.connectPipelineStep1':
    '1. {projectSettings} > {changeManagement}으로 이동합니다',
  'jsm.gettingStartedPanel.connectPipelineStep2':
    '2. {connectPipeline}을(를) 선택합니다',
  'jsm.gettingStartedPanel.connectPipelineStep3': '3. 제공된 단계를 따릅니다.',
  'jsm.gettingStartedPanel.countCompleted':
    '{completedTaskCount}/{totalTaskCount}개 완료됨',
  'jsm.gettingStartedPanel.create': '만들기',
  'jsm.gettingStartedPanel.createProject': '프로젝트 만들기',
  'jsm.gettingStartedPanel.createProjectDescription':
    'IT 서비스 관리 템플릿을 사용하여 프로젝트를 만듭니다.',
  'jsm.gettingStartedPanel.createProjectLearnMore':
    '프로젝트 만들기에 대해 자세히 알아보기',
  'jsm.gettingStartedPanel.createProjectStep1':
    '1. 상단 탐색에서 {projects} 드롭다운을 선택합니다.',
  'jsm.gettingStartedPanel.createProjectStep2':
    '2. {createProject}을(를) 선택합니다.',
  'jsm.gettingStartedPanel.createProjectStep3':
    '3. 프로젝트 이름을 입력합니다.',
  'jsm.gettingStartedPanel.createProjectStep4':
    '4. (다른 템플릿 유형을 찾아보려면) {changeTemplate}을(를) 선택합니다.',
  'jsm.gettingStartedPanel.createProjectStep5': '5. {create}을(를) 선택합니다.',
  'jsm.gettingStartedPanel.createService': '서비스 만들기',
  'jsm.gettingStartedPanel.customizePortalLogoDescription':
    '가능하면 사용자가 알아볼 수 있고 친숙한 브랜드 로고를 사용하세요.',
  'jsm.gettingStartedPanel.customizePortalLogoLearnMore':
    '포털에 대해 자세히 알아보기',
  'jsm.gettingStartedPanel.customizePortalLogoStep1':
    '1. {projectSettings} > {portalSettings}(으)로 이동합니다.',
  'jsm.gettingStartedPanel.customizePortalLogoStep2':
    '2. {serviceProjectInformation} 섹션에서 {addLogo}을(를) 클릭합니다.',
  'jsm.gettingStartedPanel.customizePortalLogoStep3':
    '3. 이미지를 끌어다 놓거나, {uploadAnImage}을(를) 클릭하여 컴퓨터에서 선택합니다.',
  'jsm.gettingStartedPanel.customizePortalLogoStep4':
    '4. {upload}을(를) 클릭합니다.',
  'jsm.gettingStartedPanel.customizePortalNameDescription':
    '사용자가 원하는 곳을 찾아왔는지 확실히 알 수 있도록 명확하고 관련성 있게 유지하세요.',
  'jsm.gettingStartedPanel.customizePortalNameLearnMore':
    '포털에 대해 자세히 알아보기',
  'jsm.gettingStartedPanel.customizePortalNameStep1':
    '1. {projectSettings} > {portalSettings}(으)로 이동합니다.',
  'jsm.gettingStartedPanel.customizePortalNameStep2':
    '2. {serviceProjectInformation} 섹션에서 {namePortal}에 새 포털 이름을 입력합니다.',
  'jsm.gettingStartedPanel.customizePortalNameStep3':
    '3. {savePortal}을(를) 클릭합니다.',
  'jsm.gettingStartedPanel.editService': '서비스 편집',
  'jsm.gettingStartedPanel.ellipsis': '…',
  'jsm.gettingStartedPanel.emailRequests': '이메일 요청',
  'jsm.gettingStartedPanel.emailSetupDescription':
    '최종 사용자가 프로젝트에 직접 이메일로 요청을 보낼 수 있도록 이메일 주소를 추가하세요.',
  'jsm.gettingStartedPanel.emailSetupLearnMore':
    '이메일 설정에 대해 자세히 알아보기',
  'jsm.gettingStartedPanel.emailSetupStep1':
    '1. {projectSettings} > {emailRequests}으로 이동합니다',
  'jsm.gettingStartedPanel.emailSetupStep2':
    '2. 이메일 서비스 공급자를 선택하고 계정 연결 단계를 완료합니다.',
  'jsm.gettingStartedPanel.exitQuickStart': '빠른 시작 닫기',
  'jsm.gettingStartedPanel.exitYourCoach': '코치 끝내기',
  'jsm.gettingStartedPanel.goBeyondBasicsBestPractisesStep1':
    '1. {bestPractices}(으)로 이동합니다',
  'jsm.gettingStartedPanel.goBeyondBasicsDescription':
    '이제 기본 사항을 완료했으므로 유용한 방법 가이드, 설명서 및 문서 모음을 활용하여 프로젝트를 다음 수준으로 올리세요. 더 알아볼 내용이 많이 남아 있습니다.',
  'jsm.gettingStartedPanel.goBeyondBasicsDiscoverNewStep2':
    '2. 새로운 것을 발견하세요!',
  'jsm.gettingStartedPanel.goBeyondBasicsDiscoverNewStep3':
    '3. 새로운 것을 발견하세요!',
  'jsm.gettingStartedPanel.goBeyondBasicsDownloadAppStep2':
    '2. {jsmMobileApp}을(를) 다운로드하세요',
  'jsm.gettingStartedPanel.guidedTour': '둘러보기',
  'jsm.gettingStartedPanel.incidentManagementBestPractisesStep1':
    '1. {bestPracticesForIncidentManagement}(으)로 이동합니다',
  'jsm.gettingStartedPanel.incidentManagementBestPractisesStep2':
    '2. {bestPracticesForIncidentManagement}을(를) 확인하세요',
  'jsm.gettingStartedPanel.incidentManagementDescription':
    '이제 최고의 속도로 인시던트에 대응할 준비가 되었으므로, 다음 단계로 나아갈 방법을 알아보세요.',
  'jsm.gettingStartedPanel.incidentManagementImproveFurtherStep2':
    '2. 더 발전할 수 있는 방법을 알아보세요!',
  'jsm.gettingStartedPanel.incidentManagementImproveFurtherStep3':
    '3. 더 발전할 수 있는 방법을 알아보세요!',
  'jsm.gettingStartedPanel.incidentManagementSettings': '인시던트 관리',
  'jsm.gettingStartedPanel.incidentManagementSettingsStep1':
    '1. 프로젝트 설정 > {incidentManagementSettings}(으)로 이동하여 구성하고 새 기능에 대해 알아보세요',
  'jsm.gettingStartedPanel.jsmMobileApp': '모바일용 Jira Service Management',
  'jsm.gettingStartedPanel.lozenge.close': '닫기',
  'jsm.gettingStartedPanel.lozenge.tickIconLabel': '확인 아이콘',
  'jsm.gettingStartedPanel.lozenge.yourCoach': '코치',
  'jsm.gettingStartedPanel.namePortal': '이름',
  'jsm.gettingStartedPanel.notificationsDescription':
    '주요 인시던트에 대한 알림을 받으려면 우선 프로필을 설정해야 합니다.',
  'jsm.gettingStartedPanel.notificationsLearnMore':
    'Opsgenie 알림에 대해 자세히 알아보기',
  'jsm.gettingStartedPanel.notificationsStep1':
    '1. Jira Service Management에서 기본 탐색 사이드바의 {alerts}을(를) 선택하여 Opsgenie로 이동합니다.',
  'jsm.gettingStartedPanel.notificationsStep2':
    '2. {settings} > {notifications}을(를) 선택합니다',
  'jsm.gettingStartedPanel.notificationsStep3':
    '3. {sms} 및 {voice}에 전화번호를 입력합니다.',
  'jsm.gettingStartedPanel.notificationsStep4':
    '4. 페이지를 아래로 스크롤하여 {notificationRules}을(를) 설정합니다.',
  'jsm.gettingStartedPanel.people': '사용자',
  'jsm.gettingStartedPanel.portalSettings': '포털 설정',
  'jsm.gettingStartedPanel.projectAutomation': '프로젝트 자동화',
  'jsm.gettingStartedPanel.projectSettings': '프로젝트 설정',
  'jsm.gettingStartedPanel.projects': '프로젝트',
  'jsm.gettingStartedPanel.quickStart': '빠른 시작',
  'jsm.gettingStartedPanel.savePortal': '저장',
  'jsm.gettingStartedPanel.saveService': '저장',
  'jsm.gettingStartedPanel.serviceHub': '서비스',
  'jsm.gettingStartedPanel.serviceProjectInformation': '서비스 프로젝트 정보',
  'jsm.gettingStartedPanel.setupServicesDescription':
    '조직에서 사용하는 제품 또는 애플리케이션을 추가합니다.',
  'jsm.gettingStartedPanel.setupServicesLearnMore':
    '서비스에 대해 자세히 알아보기',
  'jsm.gettingStartedPanel.setupServicesStep1':
    '1. {serviceHub}(으)로 이동합니다',
  'jsm.gettingStartedPanel.setupServicesStep2':
    '2. {createService}을(를) 선택합니다',
  'jsm.gettingStartedPanel.setupTeamDashboardLearnMore':
    'Opsgenie의 팀 대시보드에 대해 자세히 알아보기',
  'jsm.gettingStartedPanel.setupTeamDescription':
    '다음으로 인시던트에 대응할 수 있는 팀을 구축하고 대기 일정을 사용자 지정하여 누구에게 언제 알림을 보내는지 결정합니다.',
  'jsm.gettingStartedPanel.setupTeamStep1':
    '1. Opsgenie에서 {teams}(으)로 이동합니다.',
  'jsm.gettingStartedPanel.setupTeamStep2': '2. {addTeam}을(를) 선택합니다.',
  'jsm.gettingStartedPanel.setupTeamStep3': '3. 팀에 {name}을(를) 지정합니다.',
  'jsm.gettingStartedPanel.setupTeamStep4':
    '4. 계정 사용자 중에 검색하여 {addMembers}. 그런 다음 {addTeam}을(를) 선택합니다.',
  'jsm.gettingStartedPanel.setupTeamStep5':
    '5. 팀이 준비되었으며, 이제 페이지를 살펴보며 기본 대기 일정, 회람 규칙 및 에스컬레이션 정책을 편집합니다.',
  'jsm.gettingStartedPanel.showLess': '간략히 보기',
  'jsm.gettingStartedPanel.showMore': '더 보기',
  'jsm.gettingStartedPanel.startChangeManagement': '변경 관리 투어 시작하기',
  'jsm.gettingStartedPanel.startIcon': '시작 아이콘',
  'jsm.gettingStartedPanel.startIncidentManagement':
    '인시던트 관리 투어 시작하기',
  'jsm.gettingStartedPanel.startWelcome': '환영 투어 시작하기',
  'jsm.gettingStartedPanel.taskTitle.checklist.basics.addLogoToPortal':
    '포털에 로고 추가',
  'jsm.gettingStartedPanel.taskTitle.checklist.basics.addTeamMember':
    '팀원 추가',
  'jsm.gettingStartedPanel.taskTitle.checklist.basics.createYourItsmProject':
    'ITSM 프로젝트 만들기',
  'jsm.gettingStartedPanel.taskTitle.checklist.basics.customizeYourPortal':
    '포털 이름 업데이트',
  'jsm.gettingStartedPanel.taskTitle.checklist.basics.goBeyondBasics':
    '자세한 사항 알아보기',
  'jsm.gettingStartedPanel.taskTitle.checklist.basics.setupEmailRequests':
    '이메일 요청 설정',
  'jsm.gettingStartedPanel.taskTitle.checklist.changes.addChangeApprovers':
    '서비스에 변경 승인자 추가',
  'jsm.gettingStartedPanel.taskTitle.checklist.changes.connectCiCdPipeline':
    'CI/CD 파이프라인 연결',
  'jsm.gettingStartedPanel.taskTitle.checklist.changes.makeTheMostOfChangeManagement':
    '변경 관리 최대한 활용',
  'jsm.gettingStartedPanel.taskTitle.checklist.changes.turnOnAutomationRules':
    '자동화 규칙 활성화',
  'jsm.gettingStartedPanel.taskTitle.checklist.incidents.assignTeamToServices':
    '서비스에 소유자 팀 할당',
  'jsm.gettingStartedPanel.taskTitle.checklist.incidents.levelUpIncidentManagement':
    '인시던트 관리 대응 수준 높이기',
  'jsm.gettingStartedPanel.taskTitle.checklist.incidents.setupNotifications':
    '알림 수신을 위해 프로필 설정',
  'jsm.gettingStartedPanel.upload': '업로드',
  'jsm.gettingStartedPanel.uploadAnImage': '이미지 업로드',
  'jsm.gettingStartedPanel.walkthroughs': '살펴보기',
  'jsm.gettingStartedPanel.yourCoach': '내 코치',
  'jsm.gettingStartedPanel.yourCoach.checklistDescription':
    '설정 작업의 체크리스트 따라하기',
  'jsm.gettingStartedPanel.yourCoach.checklistIconLabel': '빠른 시작으로 이동',
  'jsm.gettingStartedPanel.yourCoach.checklistTitle': '빠른 시작',
  'jsm.gettingStartedPanel.yourCoach.documentationDescription':
    '빠른 참조 가이드 읽기',
  'jsm.gettingStartedPanel.yourCoach.documentationIconLabel': '문서로 이동',
  'jsm.gettingStartedPanel.yourCoach.documentationTitle': '설명서',
  'jsm.gettingStartedPanel.yourCoach.sampleProjectDescription':
    '예시 데이터로 시험해 보세요',
  'jsm.gettingStartedPanel.yourCoach.sampleProjectIconLabel':
    '샘플 스페이스로 이동',
  'jsm.gettingStartedPanel.yourCoach.sampleProjectTitle': '샘플 스페이스',
  'jsm.gettingStartedPanel.yourCoach.walkthroughsDescription':
    '둘러보기 시작 또는 다시 시작',
  'jsm.gettingStartedPanel.yourCoach.walkthroughsIconLabel': '살표보기로 이동',
  'jsm.gettingStartedPanel.yourCoach.walkthroughsTitle': '살펴보기',
};
