/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Portuguese (Brazil)
export default {
  'jsm.gettingStartedPanel.add': 'Adicionar',
  'jsm.gettingStartedPanel.addChangeApproversDescription':
    'Esses vão ser os aprovadores de referência para qualquer alteração em um serviço específico.',
  'jsm.gettingStartedPanel.addChangeApproversDescriptionNote':
    'Nota: pode ser necessário criar um grupo de aprovadores de alteração antes que você possa selecioná-los.',
  'jsm.gettingStartedPanel.addChangeApproversLearnMore':
    'Saiba como criar serviços e alterar aprovadores',
  'jsm.gettingStartedPanel.addChangeApproversStep1': '1. Vá para {serviceHub}',
  'jsm.gettingStartedPanel.addChangeApproversStep2':
    '2. (Para adicionar aprovadores a um serviço novo) Selecione {createService}',
  'jsm.gettingStartedPanel.addChangeApproversStep3':
    '3. (Para adicionar aprovadores a um serviço existente) Selecione o nome do serviço conectado > {ellipsis} > {editService}',
  'jsm.gettingStartedPanel.addChangeApproversStep4':
    '4. Selecione os {changeApprovers}',
  'jsm.gettingStartedPanel.addChangeApproversStep5':
    '5. Selecione {saveService}',
  'jsm.gettingStartedPanel.addLogo': 'Adicionar logo',
  'jsm.gettingStartedPanel.addPeople': 'Adicionar pessoas',
  'jsm.gettingStartedPanel.addTemplateRules': 'Adicionar regras do template',
  'jsm.gettingStartedPanel.addingUsersDescription':
    'Faça com que sua equipe se envolva adicionando-os como agentes a um projeto de serviço.',
  'jsm.gettingStartedPanel.addingUsersLearnMore':
    'Saiba mais sobre como adicionar membros da equipe',
  'jsm.gettingStartedPanel.addingUsersStep1':
    '1. Vá para {projectSettings} > {people}',
  'jsm.gettingStartedPanel.addingUsersStep2': '2. Selecione {addPeople}',
  'jsm.gettingStartedPanel.addingUsersStep3':
    '3. Insira o nome de usuário ou o e-mail do agente',
  'jsm.gettingStartedPanel.addingUsersStep4':
    '4. Escolha a função no menu suspenso (equipe da central de atendimento)',
  'jsm.gettingStartedPanel.addingUsersStep5': '5. Selecione {add}',
  'jsm.gettingStartedPanel.addingUsersStep6':
    '6. O agente vai receber um e-mail com o link do projeto',
  'jsm.gettingStartedPanel.alerts': 'Alertas',
  'jsm.gettingStartedPanel.assignOwnerDescription':
    'Informe as equipes certas para que possam começar a trabalhar na resolução dos incidentes na hora.',
  'jsm.gettingStartedPanel.assignOwnerDescriptionNote':
    'Nota: os serviços são sincronizados e vão aparecer tanto no Opsgenie como no Jira Service Management.',
  'jsm.gettingStartedPanel.assignOwnerLearnMore':
    'Saiba mais sobre como conectar equipes e serviço',
  'jsm.gettingStartedPanel.assignOwnerStep1':
    '1. Do Opsgenie, vá para {services} para listar todos os serviços',
  'jsm.gettingStartedPanel.assignOwnerStep2': '2. Selecione {addService}',
  'jsm.gettingStartedPanel.assignOwnerStep3':
    '3. Digite um {serviceName} e selecione uma {ownerTeam}',
  'jsm.gettingStartedPanel.assignOwnerStep4':
    '4. Selecione {addServiceSubmit} para salvar o serviço',
  'jsm.gettingStartedPanel.assignOwnerStep5':
    '5. Depois, vá para as configurações de serviço da equipe para explorar mais opções',
  'jsm.gettingStartedPanel.automationRulesDescription':
    'Há várias regras de automação de amostra que podem ser ativadas para começar o gerenciamento de alterações.',
  'jsm.gettingStartedPanel.automationRulesLearnMore':
    'Saiba mais sobre regras de automação',
  'jsm.gettingStartedPanel.automationRulesStep1':
    '1. Vá para {projectSettings} > {projectAutomation}',
  'jsm.gettingStartedPanel.automationRulesStep2':
    '2. Selecione {addTemplateRules}',
  'jsm.gettingStartedPanel.back': 'Voltar',
  'jsm.gettingStartedPanel.bestPracticesForChangeManagement':
    'Práticas recomendadas para gerenciamento de alterações',
  'jsm.gettingStartedPanel.bestPracticesForITTeams':
    'Práticas recomendadas para equipes de TI',
  'jsm.gettingStartedPanel.bestPracticesForIncidentManagement':
    'Práticas recomendadas para gerenciamento de incidentes',
  'jsm.gettingStartedPanel.changeApprovers': 'Aprovadores de alterações',
  'jsm.gettingStartedPanel.changeManagement': 'Gerenciamento de alterações',
  'jsm.gettingStartedPanel.changeManagementDescription':
    'Agora que você já configurou os aspectos essenciais do gerenciamento de alterações, consulte a documentação para ver como fazer ainda mais com as alterações.',
  'jsm.gettingStartedPanel.changeManagementStep1':
    '1. Vá para {bestPracticesForChangeManagement}',
  'jsm.gettingStartedPanel.changeManagementStep2':
    '2. Busque um artigo que seja do seu interesse',
  'jsm.gettingStartedPanel.changeTemplate': 'Alterar template',
  'jsm.gettingStartedPanel.checklist.basics.setupAService':
    'Configurar um serviço',
  'jsm.gettingStartedPanel.checklist.basics.tabDescription':
    'Configure os aspectos essenciais do projeto (quem pode usar, qual a aparência e com o que ele se conecta).',
  'jsm.gettingStartedPanel.checklist.changes.tabDescription':
    '{changes} ajudam a registrar, analisar e aprovar alterações, para que suas equipes possam implementar rápido alterações e minimizar os riscos.',
  'jsm.gettingStartedPanel.checklist.incidents.setupResponseTeam':
    'Configurar uma equipe de resposta',
  'jsm.gettingStartedPanel.checklist.incidents.tabDescription':
    '{incidents} ajudam a resolver interferências na qualidade do serviço ou encaminhar para equipes de plantão para uma resposta coordenada.',
  'jsm.gettingStartedPanel.collapsePanel': 'Recolher painel',
  'jsm.gettingStartedPanel.common.tabTitle.checklist.basic': 'Fundamentos',
  'jsm.gettingStartedPanel.common.tabTitle.checklist.changes': 'Alterações',
  'jsm.gettingStartedPanel.common.tabTitle.checklist.incidents': 'Incidentes',
  'jsm.gettingStartedPanel.common.tourDescription.changeManagement':
    'Faça um tour guiado pelo gerenciamento de mudanças. Os tickets de demonstração restantes de tours de gerenciamento de mudanças anteriores vão ser fechados.',
  'jsm.gettingStartedPanel.common.tourDescription.incidentManagement':
    'Faça um tour guiado pelo gerenciamento de incidentes. Os tickets de demonstração restantes de tours de gerenciamento de incidentes anteriores vão ser fechados.',
  'jsm.gettingStartedPanel.common.tourDescription.welcome':
    'Comece com uma visita guiada pelos aspectos essenciais.',
  'jsm.gettingStartedPanel.common.tourTitle.changeManagement':
    'Gerenciamento de alterações',
  'jsm.gettingStartedPanel.common.tourTitle.incidentManagement':
    'Gerenciamento de incidentes',
  'jsm.gettingStartedPanel.common.tourTitle.welcome': 'Boas-vindas',
  'jsm.gettingStartedPanel.connectPipeline': 'Conectar pipeline',
  'jsm.gettingStartedPanel.connectPipelineDescription':
    'Isso vai permitir a criação automática de solicitações quando as alterações forem enviadas.',
  'jsm.gettingStartedPanel.connectPipelineLearnMore':
    'Saiba mais sobre como conectar o pipeline',
  'jsm.gettingStartedPanel.connectPipelineStep1':
    '1. Vá para {projectSettings} > {changeManagement}',
  'jsm.gettingStartedPanel.connectPipelineStep2':
    '2. Selecione {connectPipeline}',
  'jsm.gettingStartedPanel.connectPipelineStep3': '3. Siga as etapas indicadas',
  'jsm.gettingStartedPanel.countCompleted':
    '{completedTaskCount} de {totalTaskCount} concluído(s)',
  'jsm.gettingStartedPanel.create': 'Criar',
  'jsm.gettingStartedPanel.createProject': 'Criar projeto',
  'jsm.gettingStartedPanel.createProjectDescription':
    'Crie seu projeto usando o template de gerenciamento de serviço de TI.',
  'jsm.gettingStartedPanel.createProjectLearnMore':
    'Saiba mais sobre como criar projetos',
  'jsm.gettingStartedPanel.createProjectStep1':
    '1. Selecione o menu suspenso {projects} na parte superior da navegação',
  'jsm.gettingStartedPanel.createProjectStep2': '2. Selecione {createProject}',
  'jsm.gettingStartedPanel.createProjectStep3': '3. Escolha o nome do projeto',
  'jsm.gettingStartedPanel.createProjectStep4':
    '4. (Para buscar outros tipos de templates) Selecione {changeTemplate}',
  'jsm.gettingStartedPanel.createProjectStep5': '5. Selecione {create}',
  'jsm.gettingStartedPanel.createService': 'Criar serviço',
  'jsm.gettingStartedPanel.customizePortalLogoDescription':
    'Use o logo da sua marca se possível, algo que os usuários possam identificar e reconheçam como familiar.',
  'jsm.gettingStartedPanel.customizePortalLogoLearnMore':
    'Saiba mais sobre o portal',
  'jsm.gettingStartedPanel.customizePortalLogoStep1':
    '1. Vá para {projectSettings} > {portalSettings}',
  'jsm.gettingStartedPanel.customizePortalLogoStep2':
    '2. Na seção {serviceProjectInformation}, clique em {addLogo}',
  'jsm.gettingStartedPanel.customizePortalLogoStep3':
    '3. Arraste e solte a imagem ou clique em {uploadAnImage} para selecionar do computador',
  'jsm.gettingStartedPanel.customizePortalLogoStep4': '4. Clique em {upload}',
  'jsm.gettingStartedPanel.customizePortalNameDescription':
    'Mantenha clareza e relevância para que os usuários saibam que estão no lugar certo.',
  'jsm.gettingStartedPanel.customizePortalNameLearnMore':
    'Saiba mais sobre o portal',
  'jsm.gettingStartedPanel.customizePortalNameStep1':
    '1. Vá para {projectSettings} > {portalSettings}',
  'jsm.gettingStartedPanel.customizePortalNameStep2':
    '2. Na seção {serviceProjectInformation}, digite o nome novo do portal em {namePortal}',
  'jsm.gettingStartedPanel.customizePortalNameStep3':
    '3. Clique em {savePortal}',
  'jsm.gettingStartedPanel.editService': 'Editar serviço',
  'jsm.gettingStartedPanel.ellipsis': '…',
  'jsm.gettingStartedPanel.emailRequests': 'Solicitações de e-mail',
  'jsm.gettingStartedPanel.emailSetupDescription':
    'Adicione um endereço de e-mail para que os usuários finais possam enviar as solicitações por e-mail direto para o projeto.',
  'jsm.gettingStartedPanel.emailSetupLearnMore':
    'Saiba mais sobre como configurar o e-mail',
  'jsm.gettingStartedPanel.emailSetupStep1':
    '1. Vá para {projectSettings} > {emailRequests}',
  'jsm.gettingStartedPanel.emailSetupStep2':
    '2. Escolha o provedor de serviços de e-mail e conclua as etapas para vincular a conta',
  'jsm.gettingStartedPanel.exitQuickStart': 'Fechar Início rápido',
  'jsm.gettingStartedPanel.exitYourCoach': 'Sair do guia',
  'jsm.gettingStartedPanel.goBeyondBasicsBestPractisesStep1':
    '1. Vá para {bestPractices}',
  'jsm.gettingStartedPanel.goBeyondBasicsDescription':
    'Agora que você concluiu as etapas básicas, leve o seu projeto a outro nível com uma coleção de guias de instruções, explicações e documentos úteis. Há muito mais para aprender…',
  'jsm.gettingStartedPanel.goBeyondBasicsDiscoverNewStep2':
    '2. Descubra algo novo!',
  'jsm.gettingStartedPanel.goBeyondBasicsDiscoverNewStep3':
    '3. Descubra algo novo!',
  'jsm.gettingStartedPanel.goBeyondBasicsDownloadAppStep2':
    '2. Baixe o {jsmMobileApp}',
  'jsm.gettingStartedPanel.guidedTour': 'Tour guiado',
  'jsm.gettingStartedPanel.incidentManagementBestPractisesStep1':
    '1. Vá para {bestPracticesForIncidentManagement}',
  'jsm.gettingStartedPanel.incidentManagementBestPractisesStep2':
    '2. Consulte {bestPracticesForIncidentManagement}',
  'jsm.gettingStartedPanel.incidentManagementDescription':
    'Agora que você está pronto para responder a incidentes no menor tempo possível, descubra como levar isso a um outro nível.',
  'jsm.gettingStartedPanel.incidentManagementImproveFurtherStep2':
    '2. Descubra como melhorar ainda mais!',
  'jsm.gettingStartedPanel.incidentManagementImproveFurtherStep3':
    '3. Descubra como melhorar ainda mais!',
  'jsm.gettingStartedPanel.incidentManagementSettings':
    'Gerenciamento de incidentes',
  'jsm.gettingStartedPanel.incidentManagementSettingsStep1':
    '1. Vá para Configurações do projeto > {incidentManagementSettings} para configurar e aprender sobre novos recursos',
  'jsm.gettingStartedPanel.jsmMobileApp':
    'Jira Service Management para dispositivos móveis',
  'jsm.gettingStartedPanel.lozenge.close': 'Fechar',
  'jsm.gettingStartedPanel.lozenge.tickIconLabel': 'Ícone de seleção',
  'jsm.gettingStartedPanel.lozenge.yourCoach': 'Guia',
  'jsm.gettingStartedPanel.namePortal': 'Nome',
  'jsm.gettingStartedPanel.notificationsDescription':
    'Para receber notificações de incidentes graves, é preciso primeiro configurar o seu perfil.',
  'jsm.gettingStartedPanel.notificationsLearnMore':
    'Saiba mais sobre as notificações do Opsgenie',
  'jsm.gettingStartedPanel.notificationsStep1':
    '1. Em Jira Service Management, selecione {alerts} na barra lateral de navegação principal para ir para o Opsgenie',
  'jsm.gettingStartedPanel.notificationsStep2':
    '2. Selecione {settings} > {notifications}',
  'jsm.gettingStartedPanel.notificationsStep3':
    '3. Digite o número do seu telefone em {sms} e {voice}',
  'jsm.gettingStartedPanel.notificationsStep4':
    '4. Role para baixo na página para configurar as {notificationRules}',
  'jsm.gettingStartedPanel.people': 'Pessoas',
  'jsm.gettingStartedPanel.portalSettings': 'Configurações do portal',
  'jsm.gettingStartedPanel.projectAutomation': 'Automação do projeto',
  'jsm.gettingStartedPanel.projectSettings': 'Configurações do projeto',
  'jsm.gettingStartedPanel.projects': 'Projetos',
  'jsm.gettingStartedPanel.quickStart': 'Início rápido',
  'jsm.gettingStartedPanel.savePortal': 'Salvar',
  'jsm.gettingStartedPanel.saveService': 'Salvar',
  'jsm.gettingStartedPanel.serviceHub': 'Serviços',
  'jsm.gettingStartedPanel.serviceProjectInformation':
    'Informações do projeto de serviço',
  'jsm.gettingStartedPanel.setupServicesDescription':
    'Adicione um produto ou aplicativo que sua organização usa.',
  'jsm.gettingStartedPanel.setupServicesLearnMore':
    'Saiba mais sobre os serviços',
  'jsm.gettingStartedPanel.setupServicesStep1': '1. Vá para {serviceHub}',
  'jsm.gettingStartedPanel.setupServicesStep2': '2. Selecione {createService}',
  'jsm.gettingStartedPanel.setupTeamDashboardLearnMore':
    'Saiba mais sobre o painel da equipe no Opsgenie',
  'jsm.gettingStartedPanel.setupTeamDescription':
    'Em seguida, crie uma equipe que possa reagir a incidentes e decida quem vai ser notificado e quando, personalizando o cronograma de plantão.',
  'jsm.gettingStartedPanel.setupTeamStep1': '1. Do Opsgenie, vá para {teams}',
  'jsm.gettingStartedPanel.setupTeamStep2': '2. Selecione {addTeam}',
  'jsm.gettingStartedPanel.setupTeamStep3': '3. Dê um {name} para a equipe',
  'jsm.gettingStartedPanel.setupTeamStep4':
    '4. {addMembers} pesquisando entre usuários de conta. Em seguida, selecione {addTeam}',
  'jsm.gettingStartedPanel.setupTeamStep5':
    '5. Sua equipe está pronta — agora, explore a página para editar o on-call schedule padrão, a regra de roteamento e a política de escalonamento',
  'jsm.gettingStartedPanel.showLess': 'Mostrar menos',
  'jsm.gettingStartedPanel.showMore': 'Mostrar mais',
  'jsm.gettingStartedPanel.startChangeManagement':
    'Iniciar tour de gerenciamento de mudanças',
  'jsm.gettingStartedPanel.startIcon': 'Ícone iniciar',
  'jsm.gettingStartedPanel.startIncidentManagement':
    'Iniciar tour de gerenciamento de incidentes',
  'jsm.gettingStartedPanel.startWelcome': 'Iniciar tour de boas-vindas',
  'jsm.gettingStartedPanel.taskTitle.checklist.basics.addLogoToPortal':
    'Adicionar um logotipo ao portal',
  'jsm.gettingStartedPanel.taskTitle.checklist.basics.addTeamMember':
    'Adicionar um membro da equipe',
  'jsm.gettingStartedPanel.taskTitle.checklist.basics.createYourItsmProject':
    'Criar um projeto de ITSM',
  'jsm.gettingStartedPanel.taskTitle.checklist.basics.customizeYourPortal':
    'Atualize o nome do portal',
  'jsm.gettingStartedPanel.taskTitle.checklist.basics.goBeyondBasics':
    'Ir além do básico',
  'jsm.gettingStartedPanel.taskTitle.checklist.basics.setupEmailRequests':
    'Configurar solicitações de e-mail',
  'jsm.gettingStartedPanel.taskTitle.checklist.changes.addChangeApprovers':
    'Adicione aprovadores de alterações a um serviço',
  'jsm.gettingStartedPanel.taskTitle.checklist.changes.connectCiCdPipeline':
    'Conecte um pipeline de integração contínua/implementação contínua',
  'jsm.gettingStartedPanel.taskTitle.checklist.changes.makeTheMostOfChangeManagement':
    'Aproveitar ao máximo o gerenciamento de alterações',
  'jsm.gettingStartedPanel.taskTitle.checklist.changes.turnOnAutomationRules':
    'Acionar as regras de automação',
  'jsm.gettingStartedPanel.taskTitle.checklist.incidents.assignTeamToServices':
    'Atribua uma equipe proprietária para um serviço',
  'jsm.gettingStartedPanel.taskTitle.checklist.incidents.levelUpIncidentManagement':
    'Aumentar o nível das respostas do gerenciamento de incidentes',
  'jsm.gettingStartedPanel.taskTitle.checklist.incidents.setupNotifications':
    'Configurar o perfil para receber notificações',
  'jsm.gettingStartedPanel.upload': 'Carregar',
  'jsm.gettingStartedPanel.uploadAnImage': 'Carregar uma imagem',
  'jsm.gettingStartedPanel.walkthroughs': 'Apresentação',
  'jsm.gettingStartedPanel.yourCoach': 'Guia',
  'jsm.gettingStartedPanel.yourCoach.checklistDescription':
    'Seguir um checklist de tarefas configuradas',
  'jsm.gettingStartedPanel.yourCoach.checklistIconLabel':
    'Ir para o Início rápido',
  'jsm.gettingStartedPanel.yourCoach.checklistTitle': 'Início rápido',
  'jsm.gettingStartedPanel.yourCoach.documentationDescription':
    'Ler os guias de referência rápida',
  'jsm.gettingStartedPanel.yourCoach.documentationIconLabel':
    'Ir para Documentação',
  'jsm.gettingStartedPanel.yourCoach.documentationTitle': 'Documentação',
  'jsm.gettingStartedPanel.yourCoach.sampleProjectDescription':
    'Brinque com dados de exemplo',
  'jsm.gettingStartedPanel.yourCoach.sampleProjectIconLabel':
    'Vá para o espaço de amostra',
  'jsm.gettingStartedPanel.yourCoach.sampleProjectTitle': 'Espaço de amostra',
  'jsm.gettingStartedPanel.yourCoach.walkthroughsDescription':
    'Iniciar ou reiniciar visitas guiadas',
  'jsm.gettingStartedPanel.yourCoach.walkthroughsIconLabel':
    'Ir para Apresentação',
  'jsm.gettingStartedPanel.yourCoach.walkthroughsTitle': 'Apresentação',
};
