/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Thai
export default {
  'jsm.gettingStartedPanel.add': 'เพิ่ม',
  'jsm.gettingStartedPanel.addChangeApproversDescription':
    'การเปลี่ยนแปลงใด ๆ ในบริการที่เฉพาะเจาะจงจะส่งไปยังผู้อนุมัติ',
  'jsm.gettingStartedPanel.addChangeApproversDescriptionNote':
    'หมายเหตุ: คุณอาจจำเป็นต้องสร้างกลุ่มของผู้อนุมัติการเปลี่ยนแปลงขึ้นมาก่อน จึงจะสามารถเลือกสมาชิกได้',
  'jsm.gettingStartedPanel.addChangeApproversLearnMore':
    'เรียนรู้เกี่ยวกับการสร้างผู้อนุมัติการบริการและการเปลี่ยนแปลง',
  'jsm.gettingStartedPanel.addChangeApproversStep1': '1. ไปที่ {serviceHub}',
  'jsm.gettingStartedPanel.addChangeApproversStep2':
    '2. (ในการเพิ่มผู้อนุมัติไปยังบริการใหม่) ให้เลือก {createService}',
  'jsm.gettingStartedPanel.addChangeApproversStep3':
    '3. (ในการเพิ่มผู้อนุมัติไปยังบริการที่มีอยู่) ให้เลือกชื่อบริการที่เชื่อมต่อ > {ellipsis} > {editService}',
  'jsm.gettingStartedPanel.addChangeApproversStep4':
    '4. เลือก {changeApprovers}',
  'jsm.gettingStartedPanel.addChangeApproversStep5': '5. เลือก {saveService}',
  'jsm.gettingStartedPanel.addLogo': 'เพิ่มโลโก้',
  'jsm.gettingStartedPanel.addPeople': 'เพิ่มผู้คน',
  'jsm.gettingStartedPanel.addTemplateRules': 'เพิ่มกฎแม่แบบ',
  'jsm.gettingStartedPanel.addingUsersDescription':
    'ให้ทีมของคุณมีส่วนร่วมโดยการเพิ่มทีมของคุณเป็นพนักงานบริการลูกค้าไปยังโปรเจกต์การบริการ',
  'jsm.gettingStartedPanel.addingUsersLearnMore':
    'เรียนรู้เพิ่มเติมเกี่ยวกับการเพิ่มสมาชิกทีม',
  'jsm.gettingStartedPanel.addingUsersStep1':
    '1. ไปที่ {projectSettings} > {people}',
  'jsm.gettingStartedPanel.addingUsersStep2': '2. เลือก {addPeople}',
  'jsm.gettingStartedPanel.addingUsersStep3':
    '3. ป้อนชื่อผู้ใช้หรืออีเมลของตัวแทน',
  'jsm.gettingStartedPanel.addingUsersStep4':
    '4. เลือกบทบาทของพวกเขาจากเมนูแบบเลื่อนลง (ทีม Service Desk)',
  'jsm.gettingStartedPanel.addingUsersStep5': '5. เลือก {add}',
  'jsm.gettingStartedPanel.addingUsersStep6':
    '6. พวกเขาจะได้รับอีเมลพร้อมลิงก์ที่เชื่อมโยงไปยังโครงการของคุณ',
  'jsm.gettingStartedPanel.alerts': 'การแจ้งเตือน',
  'jsm.gettingStartedPanel.assignOwnerDescription':
    'แจ้งให้ทีมที่เหมาะสมทราบ เพื่อให้สามารถเริ่มต้นแก้ไขปัญหาของเหตุการณ์ต่าง ๆ ได้อย่างทันท่วงที',
  'jsm.gettingStartedPanel.assignOwnerDescriptionNote':
    'หมายเหตุ: มีการซิงค์บริการและบริการจะปรากฎทั้งใน Opsgenie และ Jira Service Management',
  'jsm.gettingStartedPanel.assignOwnerLearnMore':
    'เรียนรู้เพิ่มเติมเกี่ยวกับการเชื่อมต่อทีมและบริการต่าง ๆ',
  'jsm.gettingStartedPanel.assignOwnerStep1':
    '1. จาก Opsgenie ให้ไปที่ {services} เพื่อทำรายการบริการทั้งหมด',
  'jsm.gettingStartedPanel.assignOwnerStep2': '2. เลือก {addService}',
  'jsm.gettingStartedPanel.assignOwnerStep3':
    '3. ป้อน {serviceName} และเลือก {ownerTeam}',
  'jsm.gettingStartedPanel.assignOwnerStep4':
    '4. เลือก {addServiceSubmit} เพื่อบันทึกบริการ',
  'jsm.gettingStartedPanel.assignOwnerStep5':
    '5. หลังจากนั้น ไปที่การตั้งค่าบริการของทีมของคุณเพื่อสำรวจตัวเลือกเพิ่มเติม',
  'jsm.gettingStartedPanel.automationRulesDescription':
    'มีตัวอย่างจำนวนหนึ่งของกฎการเปลี่ยนเป็นระบบอัตโนมัติที่สามารถเปิดใช้เพื่อให้คุณเริ่มต้นใช้งานการจัดการเปลี่ยนแปลงได้',
  'jsm.gettingStartedPanel.automationRulesLearnMore':
    'เรียนรู้เพิ่มเติมเกี่ยวกับกฎการเปลี่ยนเป็นระบบอัตโนมัติ',
  'jsm.gettingStartedPanel.automationRulesStep1':
    '1. ไปที่ {projectSettings} > {projectAutomation}',
  'jsm.gettingStartedPanel.automationRulesStep2': '2. เลือก {addTemplateRules}',
  'jsm.gettingStartedPanel.back': 'ย้อนกลับ',
  'jsm.gettingStartedPanel.bestPracticesForChangeManagement':
    'วิธีปฏิบัติที่ดีที่สุดสำหรับการจัดการการเปลี่ยนแปลง',
  'jsm.gettingStartedPanel.bestPracticesForITTeams':
    'วิธีปฏิบัติที่ดีที่สุดสำหรับทีม IT',
  'jsm.gettingStartedPanel.bestPracticesForIncidentManagement':
    'วิธีปฏิบัติที่ดีที่สุดสำหรับการจัดการเหตุการณ์',
  'jsm.gettingStartedPanel.changeApprovers': 'ผู้อนุมัติการเปลี่ยนแปลง',
  'jsm.gettingStartedPanel.changeManagement': 'การจัดการการเปลี่ยนแปลง',
  'jsm.gettingStartedPanel.changeManagementDescription':
    'เมื่อคุณกำหนดองค์ประกอบสำคัญสำหรับการจัดการการเปลี่ยนแปลงแล้ว ให้ดูเอกสารของเราเพื่อศึกษาวิธีการดำเนินการเพิ่มเติมกับการเปลี่ยนแปลง',
  'jsm.gettingStartedPanel.changeManagementStep1':
    '1. ไปที่ {bestPracticesForChangeManagement}',
  'jsm.gettingStartedPanel.changeManagementStep2':
    '2. ค้นหาบทความที่ทำให้คุณสนใจ!',
  'jsm.gettingStartedPanel.changeTemplate': 'เปลี่ยนแม่แบบ',
  'jsm.gettingStartedPanel.checklist.basics.setupAService': 'ตั้งค่าการบริการ',
  'jsm.gettingStartedPanel.checklist.basics.tabDescription':
    'กำหนดองค์ประกอบสำคัญของโครงการของคุณ เช่น ผู้ที่สามารถใช้ได้ โครงการมีหน้าตาเป็นอย่างไร และเชื่อมโยงกับสิ่งใด',
  'jsm.gettingStartedPanel.checklist.changes.tabDescription':
    '{changes} ช่วยให้คุณเก็บบันทึก ตรวจสอบ และอนุมัติการเปลี่ยนแปลงได้เพื่อให้ทีมของคุณนั้นสามารถใช้การเปลี่ยนแปลงและลดความเสี่ยงได้อย่างรวดเร็ว',
  'jsm.gettingStartedPanel.checklist.incidents.setupResponseTeam':
    'ตั้งค่าทีมตอบสนอง',
  'jsm.gettingStartedPanel.checklist.incidents.tabDescription':
    '{incidents} ช่วยให้คุณแก้ไขการขัดข้องในคุณภาพบริการของคุณ หรือขยายเพิ่มทีมที่พร้อมให้บริการสำหรับการตอบกลับร่วมกัน',
  'jsm.gettingStartedPanel.collapsePanel': 'ย่อแผงการเริ่มต้นใช้งาน',
  'jsm.gettingStartedPanel.common.tabTitle.checklist.basic': 'พื้นฐาน',
  'jsm.gettingStartedPanel.common.tabTitle.checklist.changes': 'การเปลี่ยนแปลง',
  'jsm.gettingStartedPanel.common.tabTitle.checklist.incidents': 'เหตุการณ์',
  'jsm.gettingStartedPanel.common.tourDescription.changeManagement':
    'ศึกษาคำแนะนำผ่านการจัดการกับการเปลี่ยนแปลง คำสั่งทดลองใด ๆ ที่นอกเหนือจากการเรียนรู้การจัดการกับการเปลี่ยนแปลงก่อนหน้านี้จะถูกปิดทำการ',
  'jsm.gettingStartedPanel.common.tourDescription.incidentManagement':
    'ศึกษาคำแนะนำผ่านการจัดการกับเหตุการณ์ คำสั่งทดลองใด ๆ ที่นอกเหนือจากการเรียนรู้การจัดการเหตุการณ์ก่อนหน้านี้จะถูกปิดทำการ',
  'jsm.gettingStartedPanel.common.tourDescription.welcome':
    'เริ่มต้นด้วยการศึกษาคำแนะนำสิ่งที่จำเป็น',
  'jsm.gettingStartedPanel.common.tourTitle.changeManagement':
    'การจัดการการเปลี่ยนแปลง',
  'jsm.gettingStartedPanel.common.tourTitle.incidentManagement':
    'การจัดการกับเหตุการณ์',
  'jsm.gettingStartedPanel.common.tourTitle.welcome': 'ยินดีต้อนรับ',
  'jsm.gettingStartedPanel.connectPipeline': 'เชื่อมต่อ Pipeline',
  'jsm.gettingStartedPanel.connectPipelineDescription':
    'วิธีการนี้จะทำให้คุณสามารถสร้างคำขอได้โดยอัตโนมัติเมื่อมีการส่งการเปลี่ยนแปลงแล้ว',
  'jsm.gettingStartedPanel.connectPipelineLearnMore':
    'เรียนรู้เพิ่มเติมเกี่ยวกับการเชื่อมต่อ Pipeline ของคุณ',
  'jsm.gettingStartedPanel.connectPipelineStep1':
    '1. ไปที่ {projectSettings} > {changeManagement}',
  'jsm.gettingStartedPanel.connectPipelineStep2': '2. เลือก {connectPipeline}',
  'jsm.gettingStartedPanel.connectPipelineStep3': '3. ทำตามขั้นตอนที่ให้ไว้',
  'jsm.gettingStartedPanel.countCompleted':
    '{completedTaskCount} จาก {totalTaskCount} งานเสร็จสมบูรณ์แล้ว',
  'jsm.gettingStartedPanel.create': 'สร้าง',
  'jsm.gettingStartedPanel.createProject': 'สร้างโปรเจกต์',
  'jsm.gettingStartedPanel.createProjectDescription':
    'สร้างโครงการของคุณโดยใช้แม่แบบการจัดการบริการ IT',
  'jsm.gettingStartedPanel.createProjectLearnMore':
    'เรียนรู้เพิ่มเติมเกี่ยวกับการสร้างโครงการ',
  'jsm.gettingStartedPanel.createProjectStep1':
    '1. เลือกตัวเลือกแบบเลื่อนลงของ {projects} ที่แถบนำทางด้านบนสุด',
  'jsm.gettingStartedPanel.createProjectStep2': '2. เลือก {createProject}',
  'jsm.gettingStartedPanel.createProjectStep3': '3. ป้อนชื่อโครงการของคุณ',
  'jsm.gettingStartedPanel.createProjectStep4':
    '4. (หากต้องการค้นหาประเภทแม่แบบอื่น ๆ) ให้เลือก {changeTemplate}',
  'jsm.gettingStartedPanel.createProjectStep5': '5. เลือก {create}',
  'jsm.gettingStartedPanel.createService': 'สร้างบริการ',
  'jsm.gettingStartedPanel.customizePortalLogoDescription':
    'หากเป็นไปได้ให้ใช้โลโก้แบรนด์ของคุณ ซึ่งเป็นสิ่งที่ผู้ใช้สามารถจดจำได้และรู้สึกคุ้นเคยด้วย',
  'jsm.gettingStartedPanel.customizePortalLogoLearnMore':
    'เรียนรู้เพิ่มเติมเกี่ยวกับพอร์ทัลของคุณ',
  'jsm.gettingStartedPanel.customizePortalLogoStep1':
    '1. ไปที่ {projectSettings} > {portalSettings}',
  'jsm.gettingStartedPanel.customizePortalLogoStep2':
    '2. ในส่วน {serviceProjectInformation} ให้คลิก {addLogo}',
  'jsm.gettingStartedPanel.customizePortalLogoStep3':
    '3. ลากและวางรูปภาพ หรือคลิก {uploadAnImage} เพื่อเลือกรูปใดรูปหนึ่งจากคอมพิวเตอร์ของคุณ',
  'jsm.gettingStartedPanel.customizePortalLogoStep4': '4. คลิก {upload}',
  'jsm.gettingStartedPanel.customizePortalNameDescription':
    'ทำให้ชัดเจนและตรงประเด็นเพื่อให้ผู้ใช้มั่นใจว่าพวกเขาอยู่ในจุดที่ใช่แล้ว',
  'jsm.gettingStartedPanel.customizePortalNameLearnMore':
    'เรียนรู้เพิ่มเติมเกี่ยวกับพอร์ทัลของคุณ',
  'jsm.gettingStartedPanel.customizePortalNameStep1':
    '1. ไปที่ {projectSettings} > {portalSettings}',
  'jsm.gettingStartedPanel.customizePortalNameStep2':
    '2. ในส่วน {serviceProjectInformation} ให้ป้อนชื่อพอร์ทัลใหม่ใต้ {namePortal}',
  'jsm.gettingStartedPanel.customizePortalNameStep3': '3. คลิก {savePortal}',
  'jsm.gettingStartedPanel.editService': 'แก้ไขบริการ',
  'jsm.gettingStartedPanel.ellipsis': '...',
  'jsm.gettingStartedPanel.emailRequests': 'คำขออีเมล',
  'jsm.gettingStartedPanel.emailSetupDescription':
    'เพิ่มที่อยู่อีเมลเพื่อให้ผู้ใช้ของคุณสามารถส่งคำขอมาทางอีเมลถึงโครงการของคุณได้โดยตรง',
  'jsm.gettingStartedPanel.emailSetupLearnMore':
    'เรียนรู้เพิ่มเติมเกี่ยวกับการตั้งค่าอีเมล',
  'jsm.gettingStartedPanel.emailSetupStep1':
    '1. ไปที่ {projectSettings} > {emailRequests}',
  'jsm.gettingStartedPanel.emailSetupStep2':
    '2. เลือกผู้ให้บริการอีเมลของคุณและดำเนินการตามขั้นตอนเพื่อเชื่อมโยงบัญชีของคุณให้เสร็จสมบูรณ์',
  'jsm.gettingStartedPanel.exitQuickStart': 'ปิดคู่มือการใช้งานแรกเข้า',
  'jsm.gettingStartedPanel.exitYourCoach': 'ออกจากเครื่องมือแนะนำของคุณ',
  'jsm.gettingStartedPanel.goBeyondBasicsBestPractisesStep1':
    '1. ไปที่ {bestPractices}',
  'jsm.gettingStartedPanel.goBeyondBasicsDescription':
    'ขณะนี้เมื่อคุณดำเนินการเบื้องต้นเสร็จสิ้นแล้ว คุณสามารถนำโครงการของคุณขึ้นไปอีกขั้นได้ด้วยการรวบรวมของเราที่มีคู่มือวิธีการ ผู้ชี้แจง และเอกสารที่เป็นประโยชน์ มีสิ่งต่าง ๆ อีกมากมายให้ได้เรียนรู้…',
  'jsm.gettingStartedPanel.goBeyondBasicsDiscoverNewStep2':
    '2. ค้นพบสิ่งใหม่ ๆ!',
  'jsm.gettingStartedPanel.goBeyondBasicsDiscoverNewStep3':
    '3. ค้นพบสิ่งใหม่ ๆ!',
  'jsm.gettingStartedPanel.goBeyondBasicsDownloadAppStep2':
    '2. ดาวน์โหลด {jsmMobileApp}',
  'jsm.gettingStartedPanel.guidedTour': 'คู่มือแนะนำ',
  'jsm.gettingStartedPanel.incidentManagementBestPractisesStep1':
    '1. ไปที่ {bestPracticesForIncidentManagement}',
  'jsm.gettingStartedPanel.incidentManagementBestPractisesStep2':
    '2. ดู {bestPracticesForIncidentManagement}',
  'jsm.gettingStartedPanel.incidentManagementDescription':
    'ขณะนี้เมื่อคุณพร้อมที่จะตอบสนองต่อเหตุการณ์ในเวลาที่มีการบันทึกแล้ว ให้ดูวิธีการดำเนินการสู่ขั้นต่อไป',
  'jsm.gettingStartedPanel.incidentManagementImproveFurtherStep2':
    '2. ดูวิธีการพัฒนาขึ้นไปอีกขั้น!',
  'jsm.gettingStartedPanel.incidentManagementImproveFurtherStep3':
    '3. ดูวิธีการพัฒนาขึ้นไปอีกขั้น!',
  'jsm.gettingStartedPanel.incidentManagementSettings': 'การจัดการกับเหตุการณ์',
  'jsm.gettingStartedPanel.incidentManagementSettingsStep1':
    '1. ไปที่การตั้งค่าโครงการ > {incidentManagementSettings} เพื่อกำหนดค่าและเรียนรู้เกี่ยวกับคุณสมบัติใหม่',
  'jsm.gettingStartedPanel.jsmMobileApp':
    'Jira Service Management สำหรับโทรศัพท์มือถือ',
  'jsm.gettingStartedPanel.lozenge.close': 'ปิด',
  'jsm.gettingStartedPanel.lozenge.tickIconLabel': 'ไอคอนเครื่องหมายถูก',
  'jsm.gettingStartedPanel.lozenge.yourCoach': 'เครื่องมือแนะนำของคุณ',
  'jsm.gettingStartedPanel.namePortal': 'ชื่อ',
  'jsm.gettingStartedPanel.notificationsDescription':
    'เพื่อรับการแจ้งเตือนของเหตุการณ์สำคัญ คุณจำเป็นต้องสร้างโปรไฟล์ของคุณก่อนเป็นอันดับแรก',
  'jsm.gettingStartedPanel.notificationsLearnMore':
    'เรียนรู้เพิ่มเติมเกี่ยวกับการแจ้งเตือนของ Opsgenie',
  'jsm.gettingStartedPanel.notificationsStep1':
    '1. จาก Jira Service Management ให้เลือก {alerts} ในแถบนำทางหลักด้านข้างเพื่อไปยัง Opsgenie',
  'jsm.gettingStartedPanel.notificationsStep2':
    '2. เลือก {settings} > {notifications}',
  'jsm.gettingStartedPanel.notificationsStep3':
    '3. ป้อนหมายเลขโทรศัพท์ของคุณใต้ {sms} และ {voice}',
  'jsm.gettingStartedPanel.notificationsStep4':
    '4. เลื่อนลงด้านล่างของหน้าเพื่อตั้ง {notificationRules} ของคุณ',
  'jsm.gettingStartedPanel.people': 'ผู้คน',
  'jsm.gettingStartedPanel.portalSettings': 'การตั้งค่าพอร์ทัล',
  'jsm.gettingStartedPanel.projectAutomation': 'Automation ของโปรเจกต์',
  'jsm.gettingStartedPanel.projectSettings': 'การตั้งค่าโปรเจกต์',
  'jsm.gettingStartedPanel.projects': 'โปรเจกต์',
  'jsm.gettingStartedPanel.quickStart': 'คู่มือการใช้งานแรกเข้า',
  'jsm.gettingStartedPanel.savePortal': 'บันทึก',
  'jsm.gettingStartedPanel.saveService': 'บันทึก',
  'jsm.gettingStartedPanel.serviceHub': 'บริการ',
  'jsm.gettingStartedPanel.serviceProjectInformation':
    'ข้อมูลของฝ่ายบริการด้านโปรเจกต์',
  'jsm.gettingStartedPanel.setupServicesDescription':
    'เพิ่มผลิตภัณฑ์หรือแอปพลิเคชันที่องค์กรของคุณใช้งาน',
  'jsm.gettingStartedPanel.setupServicesLearnMore':
    'เรียนรู้เพิ่มเติมเกี่ยวกับบริการ',
  'jsm.gettingStartedPanel.setupServicesStep1': '1. ไปที่ {serviceHub}',
  'jsm.gettingStartedPanel.setupServicesStep2': '2. เลือก {createService}',
  'jsm.gettingStartedPanel.setupTeamDashboardLearnMore':
    'เรียนรู้เพิ่มเติมเกี่ยวกับแดชบอร์ดทีมของ Opsgenie',
  'jsm.gettingStartedPanel.setupTeamDescription':
    'ขั้นต่อไป สร้างทีมที่สามารถตอบสนองต่อเหตุการณ์และตัดสินใจว่าใครจะเป็นผู้ได้รับการแจ้งเตือนและได้รับการแจ้งเตือนเวลาใดโดยกำหนดตารางลงงานของคุณเอง',
  'jsm.gettingStartedPanel.setupTeamStep1': '1. จาก Opsgenie ให้ไปที่ {teams}',
  'jsm.gettingStartedPanel.setupTeamStep2': '2. เลือก {addTeam}',
  'jsm.gettingStartedPanel.setupTeamStep3':
    '3. ตั้งชื่อ {name} ให้กับทีมของคุณ',
  'jsm.gettingStartedPanel.setupTeamStep4':
    '4. {addMembers} โดยการค้นหาจากผู้ใช้บัญชี จากนั้นเลือก {addTeam}',
  'jsm.gettingStartedPanel.setupTeamStep5':
    '5. ทีมของคุณพร้อมแล้ว สำรวจหน้าได้เลยตอนนี้เพื่อแก้ไขกำหนดตารางงานเริ่มต้น กฎการกำหนดเส้นทาง และนโยบายการปรับระดับของคุณ',
  'jsm.gettingStartedPanel.showLess': 'แสดงน้อยลง',
  'jsm.gettingStartedPanel.showMore': 'แสดงเพิ่มเติม',
  'jsm.gettingStartedPanel.startChangeManagement':
    'เริ่มการเรียนรู้การจัดการกับการเปลี่ยนแปลง',
  'jsm.gettingStartedPanel.startIcon': 'ไอคอนเริ่มต้น',
  'jsm.gettingStartedPanel.startIncidentManagement':
    'เริ่มการเรียนรู้การจัดการเหตุการณ์',
  'jsm.gettingStartedPanel.startWelcome': 'เริ่มการเรียนรู้คำแนะนำเบื้องต้น',
  'jsm.gettingStartedPanel.taskTitle.checklist.basics.addLogoToPortal':
    'เพิ่มโลโก้ไปยังพอร์ทัลของคุณ',
  'jsm.gettingStartedPanel.taskTitle.checklist.basics.addTeamMember':
    'เพิ่มสมาชิกในทีม',
  'jsm.gettingStartedPanel.taskTitle.checklist.basics.createYourItsmProject':
    'สร้างโปรเจกต์ ITSM ของคุณ',
  'jsm.gettingStartedPanel.taskTitle.checklist.basics.customizeYourPortal':
    'อัปเดตชื่อพอร์ทัลของคุณ',
  'jsm.gettingStartedPanel.taskTitle.checklist.basics.goBeyondBasics':
    'ก้าวไปให้ไกลกว่าระดับพื้นฐาน',
  'jsm.gettingStartedPanel.taskTitle.checklist.basics.setupEmailRequests':
    'ตั้งค่าคำขออีเมล',
  'jsm.gettingStartedPanel.taskTitle.checklist.changes.addChangeApprovers':
    'เพิ่มผู้อนุมัติการเปลี่ยนแปลงไปยังบริการ',
  'jsm.gettingStartedPanel.taskTitle.checklist.changes.connectCiCdPipeline':
    'เชื่อมต่อ Pipeline CI/CD',
  'jsm.gettingStartedPanel.taskTitle.checklist.changes.makeTheMostOfChangeManagement':
    'ใช้ประโยชน์จากการจัดการการเปลี่ยนแปลงให้มากที่สุด',
  'jsm.gettingStartedPanel.taskTitle.checklist.changes.turnOnAutomationRules':
    'เปิดใช้งานกฎการเปลี่ยนเป็นระบบอัตโนมัติ',
  'jsm.gettingStartedPanel.taskTitle.checklist.incidents.assignTeamToServices':
    'มอบหมายทีมเจ้าของไปยังบริการ',
  'jsm.gettingStartedPanel.taskTitle.checklist.incidents.levelUpIncidentManagement':
    'ยกระดับการตอบสนองการจัดการกับเหตุกาณ์ขึ้นไปอีกขั้น',
  'jsm.gettingStartedPanel.taskTitle.checklist.incidents.setupNotifications':
    'ตั้งค่าโปรไฟล์ของคุณเพื่อรับการแจ้งเตือนต่าง ๆ',
  'jsm.gettingStartedPanel.upload': 'อัปโหลด',
  'jsm.gettingStartedPanel.uploadAnImage': 'อัปโหลดภาพ',
  'jsm.gettingStartedPanel.walkthroughs': 'การแนะแนว',
  'jsm.gettingStartedPanel.yourCoach': 'เครื่องมือแนะนำของคุณ',
  'jsm.gettingStartedPanel.yourCoach.checklistDescription':
    'ติดตามรายการการตรวจสอบของงานที่ตั้งไว้',
  'jsm.gettingStartedPanel.yourCoach.checklistIconLabel':
    'ไปที่คู่มือการใช้งานแรกเข้า',
  'jsm.gettingStartedPanel.yourCoach.checklistTitle': 'คู่มือการใช้งานแรกเข้า',
  'jsm.gettingStartedPanel.yourCoach.documentationDescription':
    'อ่านคู่มืออ้างอิงฉบับย่อของเรา',
  'jsm.gettingStartedPanel.yourCoach.documentationIconLabel':
    'ไปที่เอกสารประกอบ',
  'jsm.gettingStartedPanel.yourCoach.documentationTitle': 'เอกสารประกอบ',
  'jsm.gettingStartedPanel.yourCoach.sampleProjectDescription':
    'ลองสำรวจเล่น ๆ กับข้อมูลตัวอย่าง',
  'jsm.gettingStartedPanel.yourCoach.sampleProjectIconLabel':
    'ไปยังพื้นที่ตัวอย่าง',
  'jsm.gettingStartedPanel.yourCoach.sampleProjectTitle': 'พื้นที่ตัวอย่าง',
  'jsm.gettingStartedPanel.yourCoach.walkthroughsDescription':
    'เริ่มต้นหรือเริ่มศึกษาคำแนะนำอีกครั้ง',
  'jsm.gettingStartedPanel.yourCoach.walkthroughsIconLabel': 'ไปที่การแนะแนว',
  'jsm.gettingStartedPanel.yourCoach.walkthroughsTitle': 'การแนะแนว',
};
