import {
  AttributeSpec,
  MarkSpec,
  Node,
  NodeSpec,
  ParseRule,
  Schema,
} from 'prosemirror-model';
import { paragraph, createSchema } from '@atlaskit/adf-schema';

export { Node, Schema };
export type { AttributeSpec, MarkSpec, NodeSpec, ParseRule };

export const defaultSchema = createSchema({
  nodes: [
    'doc',
    'paragraph',
    'text',
    'bulletList',
    'orderedList',
    'listItem',
    'heading',
    'blockquote',
    'codeBlock',
    'panel',
    'rule',
    'hardBreak',
    'mention',
    'emoji',
    'image',
    'media',
    'mediaGroup',
    'confluenceUnsupportedBlock',
    'confluenceUnsupportedInline',
    'confluenceJiraIssue',
    'mediaSingle',
    'caption',
    'plain',
    'table',
    'tableCell',
    'tableHeader',
    'tableRow',
    'decisionList',
    'decisionItem',
    'taskList',
    'taskItem',
    'extension',
    'inlineExtension',
    'bodiedExtension',
    'date',
    'status',
    'placeholder',
    'layoutSection',
    'layoutColumn',
    'inlineCard',
    'blockCard',
    'expand',
    'nestedExpand',
    'unsupportedBlock',
    'unsupportedInline',
    'embedCard',
  ],
  marks: [
    'em',
    'strong',
    'code',
    'strike',
    'underline',
    'link',
    'subsup',
    'typeAheadQuery',
    'textColor',
    'confluenceInlineComment',
    'breakout',
    'alignment',
    'indentation',
    'annotation',
    'unsupportedMark',
    'unsupportedNodeAttribute',
    'dataConsumer',
  ],
  customNodeSpecs: {
    plain: { ...paragraph, content: 'text*', marks: '' },
  },
});

export default defaultSchema;
