/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Norwegian Bokmål
export default {
  'dragonfruit-services-components.component-search.component-search-placeholder':
    'Velg komponent',
  'dragonfruit-services-components.inline-description.edit-label':
    'Rediger komponentbeskrivelse',
  'dragonfruit-services-components.inline-description.error-too-long':
    'Beskrivelsen må være på under 1000 tegn',
  'dragonfruit-services-components.inline-name.error-too-long':
    'Navnet må være på under 100 tegn',
  'dragonfruit-services-components.team-select.placeholder':
    'Velg komponenteier',
  'dragonfruit-services-components.team-select.team-name-fetch-failure-message':
    'Feil ved innlasting av data',
  'dragonfruit-services-componnets.inline-name.edit-label':
    'Rediger komponentnavn',
};
