/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// English (Instrumented)
export default {
  'jsm.calendar.calendar-provider.event-content-wrapper.no-title':
    '⁣⁢(No title)⁫‍‌‌⁬⁭⁪؜⁫⁪⁯⁭‌⁭؜‌⁬‍‍⁬⁮⁠⁫⁮⁣⁤',
  'jsm.calendar.calendar-provider.more-link-popup.close':
    '⁣⁢Close⁮⁫⁠⁯؜؜⁭⁠‌⁪⁯‌⁡⁪⁠⁬⁯⁭؜‌‌‍⁫⁠⁭⁣⁤',
};
