/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Dutch
export default {
  'dragonfruit-components.tier-field-picker.error-component-not-found':
    'De component die je probeert te bewerken, kon niet worden gevonden. Mogelijk is deze verwijderd.',
  'dragonfruit-components.tier-field-picker.error-saving':
    'Probeer het niveau opnieuw bij te werken.',
  'dragonfruit-components.tier-field-picker.error-title':
    'Fout opgetreden bij het bijwerken van niveauveld',
  'dragonfruit-page-component-list.actions-cell.delete-component-description':
    'Hiermee wordt de component uit Compass verwijderd, maar niet verwijderd uit andere systemen. Alle afhankelijkheids-, links en eigendomsinformatie zijn permanent verwijderd',
  'dragonfruit-page-component-list.actions-cell.remove-component':
    'Component verwijderen?',
  'dragonfruit-teams.links.link-section.chat-channel-section-description':
    'Chatkanalen zijn een plek waar mensen hulp kunnen krijgen voor deze component.',
  'dragonfruit-teams.links.link-section.on-call-section-description':
    'Op afroep-roosters geven aan wie incidenten voor dit team behandelt.',
  'dragonfruit.components.links.add-chat-channel': 'Chatlinks toevoegen',
  'dragonfruit.components.links.add-dashboard': 'Dashboard toevoegen',
  'dragonfruit.components.links.add-document': 'Document toevoegen',
  'dragonfruit.components.links.add-link-form.component-link-name-too-long':
    'De opgegeven componentlink is te lang.',
  'dragonfruit.components.links.add-link-form.component-link-url-too-long':
    'De opgegeven URL-link is te lang.',
  'dragonfruit.components.links.add-link-form.component-not-found':
    'De component die je probeert te bewerken, kon niet worden gevonden. Mogelijk is deze verwijderd.',
  'dragonfruit.components.links.add-link-form.error-saving-chat-channel-title':
    'Fout bij opslaan chatlink',
  'dragonfruit.components.links.add-link-form.error-saving-dashboard-title':
    'Fout bij opslaan dashboardlink',
  'dragonfruit.components.links.add-link-form.error-saving-description':
    'Er is een fout opgetreden bij het opslaan van je link. Probeer hem opnieuw toe te voegen.',
  'dragonfruit.components.links.add-link-form.error-saving-document-title':
    'Fout bij opslaan documentlink',
  'dragonfruit.components.links.add-link-form.error-saving-invalid-link':
    'De opgegeven URL is ongeldig.',
  'dragonfruit.components.links.add-link-form.error-saving-on-call-title':
    'Fout bij opslaan op afroep-rooster',
  'dragonfruit.components.links.add-link-form.error-saving-other-title':
    'Fout bij opslaan andere link',
  'dragonfruit.components.links.add-link-form.error-saving-project-title':
    'Fout bij opslaan projectlink',
  'dragonfruit.components.links.add-link-form.error-saving-repo-title':
    'Fout bij opslaan van repository-link',
  'dragonfruit.components.links.add-link-form.link-field': 'Linktekst',
  'dragonfruit.components.links.add-link-form.link-field-placeholder':
    'Te tonen tekst',
  'dragonfruit.components.links.add-link-form.url-field-label': 'URL',
  'dragonfruit.components.links.add-on-call': 'Op afroep-roosters toevoegen',
  'dragonfruit.components.links.add-other': 'Andere link toevoegen',
  'dragonfruit.components.links.add-project': 'Project toevoegen',
  'dragonfruit.components.links.add-repository': 'Repository toevoegen',
  'dragonfruit.components.links.chat-channel-link-limit-reached-flag-description':
    'Het maximale aantal chatlinks dat je kunt hebben is 5.',
  'dragonfruit.components.links.chat-channel-link-limit-reached-flag-title':
    'Limiet chatlinks bereikt',
  'dragonfruit.components.links.dashboard-link-limit-reached-flag-title':
    'Limiet dashboardlinks bereikt',
  'dragonfruit.components.links.documentation-link-limit-reached-flag-title':
    'Limiet documentatielinks bereikt',
  'dragonfruit.components.links.empty-state.add-first-chat-channel':
    'Chatlinks toevoegen',
  'dragonfruit.components.links.empty-state.add-first-dashboard':
    'Voeg de dashboards toe met informatie over deze component',
  'dragonfruit.components.links.empty-state.add-first-document':
    'Voeg documentatie toe zoals runbooks, interne procesdocumenten of specificaties',
  'dragonfruit.components.links.empty-state.add-first-on-call':
    'Op afroep-roosters toevoegen',
  'dragonfruit.components.links.empty-state.add-first-project':
    'Voeg een project toe om deze component te koppelen aan een Jira-project',
  'dragonfruit.components.links.empty-state.add-first-repository':
    'Voeg de repository toe waar de code voor deze component is opgeslagen',
  'dragonfruit.components.links.empty-state.add-other-link':
    'Andere relevante links toevoegen',
  'dragonfruit.components.links.empty-state.first-chat-channel-disabled':
    'Geen chatlinks',
  'dragonfruit.components.links.empty-state.first-dashboard-disabled':
    'Geen dashboards',
  'dragonfruit.components.links.empty-state.first-document-disabled':
    'Geen documentatie',
  'dragonfruit.components.links.empty-state.first-on-call-disabled':
    'Geen op afroep-roosters',
  'dragonfruit.components.links.empty-state.first-project-disabled':
    'Geen projecten',
  'dragonfruit.components.links.empty-state.first-repository-disabled':
    "Geen repository's",
  'dragonfruit.components.links.empty-state.other-link-disabled':
    'Geen andere links',
  'dragonfruit.components.links.link-limit-reached-flag-description':
    'Het maximale aantal links dat je kunt hebben voor elk componentdetail is 5.',
  'dragonfruit.components.links.on-call-link-limit-reached-flag-description':
    'Het maximale aantal links voor op afroeproosters dat je kunt hebben is 5.',
  'dragonfruit.components.links.on-call-link-limit-reached-flag-title':
    'Limiet op afroep-roosters bereikt',
  'dragonfruit.components.links.other-link-limit-reached-flag-title':
    'Limiet voor andere links bereikt',
  'dragonfruit.components.links.project-link-limit-reached-flag-title':
    'Limiet projectlinks bereikt',
  'dragonfruit.components.links.repository-link-limit-reached-flag-title':
    'Limiet repositorylinks bereikt',
  'dragonfruit.services-components.ui.tier-field-picker.tier-picker-tooltip':
    'Een serviceniveau geeft aan hoe belangrijk een service is voor je onderneming.',
};
