/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// undefined
export default {
  'dragonfruit-components.tier-field-picker.error-component-not-found':
    '找不到您嘗試編輯的元件，可能已遭到移除。',
  'dragonfruit-components.tier-field-picker.error-saving':
    '請嘗試再次更新階層。',
  'dragonfruit-components.tier-field-picker.error-title':
    '更新階層欄位時發生錯誤',
  'dragonfruit-page-component-list.actions-cell.delete-component-description':
    '這會在 Compass 中移除此元件，但不會在任何其他系統中刪除。所有相依性、連結與擁有權資訊都將永久移除',
  'dragonfruit-page-component-list.actions-cell.remove-component':
    '要移除元件嗎？',
  'dragonfruit-teams.links.link-section.chat-channel-section-description':
    '聊天頻道可讓人員取得此元件的說明。',
  'dragonfruit-teams.links.link-section.on-call-section-description':
    '待命排程會顯示誰正在處理這個團隊的事件。',
  'dragonfruit.components.links.add-chat-channel': '新增聊天連結',
  'dragonfruit.components.links.add-dashboard': '新增儀表板',
  'dragonfruit.components.links.add-document': '新增文件',
  'dragonfruit.components.links.add-link-form.component-link-name-too-long':
    '提供的元件連結名稱太長。',
  'dragonfruit.components.links.add-link-form.component-link-url-too-long':
    '提供的 URL 連結太長。',
  'dragonfruit.components.links.add-link-form.component-not-found':
    '找不到您嘗試編輯的元件，可能已遭到移除。',
  'dragonfruit.components.links.add-link-form.error-saving-chat-channel-title':
    '儲存聊天連結時發生錯誤',
  'dragonfruit.components.links.add-link-form.error-saving-dashboard-title':
    '儲存儀表板連結時發生錯誤',
  'dragonfruit.components.links.add-link-form.error-saving-description':
    '儲存連結時發生錯誤。請嘗試再次新增。',
  'dragonfruit.components.links.add-link-form.error-saving-document-title':
    '儲存文件連結時發生錯誤',
  'dragonfruit.components.links.add-link-form.error-saving-invalid-link':
    '提供的網址無效。',
  'dragonfruit.components.links.add-link-form.error-saving-on-call-title':
    '儲存待命排程時發生錯誤',
  'dragonfruit.components.links.add-link-form.error-saving-other-title':
    '儲存其他連結時發生錯誤',
  'dragonfruit.components.links.add-link-form.error-saving-project-title':
    '儲存專案連結時發生錯誤',
  'dragonfruit.components.links.add-link-form.error-saving-repo-title':
    '儲存存放庫連結時發生錯誤',
  'dragonfruit.components.links.add-link-form.link-field': '連結文字',
  'dragonfruit.components.links.add-link-form.link-field-placeholder':
    '要顯示的文字',
  'dragonfruit.components.links.add-link-form.url-field-label': '網址',
  'dragonfruit.components.links.add-on-call': '新增待命排程',
  'dragonfruit.components.links.add-other': '新增其他連結',
  'dragonfruit.components.links.add-project': '新增專案',
  'dragonfruit.components.links.add-repository': '新增存放庫',
  'dragonfruit.components.links.chat-channel-link-limit-reached-flag-description':
    '您可以擁有的聊天連結數目上限是 5 個。',
  'dragonfruit.components.links.chat-channel-link-limit-reached-flag-title':
    '已達到聊天連結上限',
  'dragonfruit.components.links.dashboard-link-limit-reached-flag-title':
    '已達到儀表板連結上限',
  'dragonfruit.components.links.documentation-link-limit-reached-flag-title':
    '已達到說明文件連結上限',
  'dragonfruit.components.links.empty-state.add-first-chat-channel':
    '新增聊天連結',
  'dragonfruit.components.links.empty-state.add-first-dashboard':
    '新增具有此元件相關資訊的儀表板',
  'dragonfruit.components.links.empty-state.add-first-document':
    '新增說明文件，例如 Runbook、內部程序文件或規格',
  'dragonfruit.components.links.empty-state.add-first-on-call': '新增待命排程',
  'dragonfruit.components.links.empty-state.add-first-project':
    '新增專案，以將此元件與 Jira 專案建立連結',
  'dragonfruit.components.links.empty-state.add-first-repository':
    '新增儲存此元件程式碼的存放庫',
  'dragonfruit.components.links.empty-state.add-other-link':
    '新增任何其他相關連結',
  'dragonfruit.components.links.link-limit-reached-flag-description':
    '您針對每個元件詳細資料可擁有的連結數目上限是 5 個。',
  'dragonfruit.components.links.on-call-link-limit-reached-flag-description':
    '您可以擁有的待命排程連結數目上限是 5 個。',
  'dragonfruit.components.links.on-call-link-limit-reached-flag-title':
    '已達到待命排程上限',
  'dragonfruit.components.links.other-link-limit-reached-flag-title':
    '已達到其他連結上限',
  'dragonfruit.components.links.project-link-limit-reached-flag-title':
    '已達到專案連結上限',
  'dragonfruit.components.links.repository-link-limit-reached-flag-title':
    '已達到存放庫連結上限',
  'dragonfruit.services-components.ui.tier-field-picker.tier-picker-tooltip':
    '服務階層會指出服務對您業務的重要性。',
};
