/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Hungarian
export default {
  'ptc.pt.member-picker.error.msg.exceed.limited.number.error2':
    '{maxNumber, plural, one {Több mint {maxNumber} embert adtál meg.} other {Több mint {maxNumber} embert adtál meg.}}',
  'ptc.pt.member-picker.msg.exceed.limited.number.info':
    '{maxNumber, plural, one {Egyszerre legfeljebb {maxNumber} személyt hívhatsz meg.} other {Egyszerre legfeljebb {maxNumber} személyt hívhatsz meg.}}',
  'ptc.pt.member-picker.no-option': 'Nincs egyezés.',
  'ptc.pt.member-picker.placeholder': 'A nevük vagy @említés',
  'ptc.pt.team-create-dialog.button.cancel': 'Mégse',
  'ptc.pt.team-create-dialog.button.submit': 'Csapat indítása',
  'ptc.pt.team-create-dialog.flag-error.desc':
    'Nem sikerült menteni a csapatodat. Próbáld újra.',
  'ptc.pt.team-create-dialog.flag-error.title': 'Sajnáljuk, hiba történt.',
  'ptc.pt.team-create-dialog.flag-success.action': 'Csapat megtekintése',
  'ptc.pt.team-create-dialog.flag-success.desc':
    'Említsd meg az új csapatodat, hogy azonnal elkezdhessétek az együttműködést, vagy módosítsd a csapatot a csapat profiljában.',
  'ptc.pt.team-create-dialog.flag-success.title':
    'Létrehoztad a csapatodat „{teamName}“ néven',
  'ptc.pt.team-create-dialog.invite-members.failed.desc':
    'Létrehoztuk a csapatot, de újból hozzá kell adnia a kívánt csapattagokat.',
  'ptc.pt.team-create-dialog.invite-members.failed.title':
    'Hiba történt a meghívókkal.',
  'ptc.pt.team-create-dialog.learn-more': 'További információ',
  'ptc.pt.team-create-dialog.modal.fields.invite-emails.label':
    'Hívj meg másokat a csapatodba',
  'ptc.pt.team-create-dialog.modal.team-name-field.placeholder':
    'Mi a csapatod neve?',
  'ptc.pt.team-create-dialog.pretext.with.mention':
    'Mindenki közös munkatérben dolgozhat, ha hozzáadod őket egy csapathoz.     @említésekkel tarthatod a kapcsolatot, együtt dolgozhatsz másokkal, és hatékonyan kezelhetsz mindent a csapat profiloldaláról. {learnMoreLink}',
  'ptc.pt.team-create-dialog.team-name-field.label': 'Csapat neve',
  'ptc.pt.team-create-dialog.title': 'Új csapat indítása',
};
