/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Italian
export default {
  'ptc.pt.member-picker.error.msg.exceed.limited.number.error2':
    '{maxNumber, plural, one {Hai inserito più di {maxNumber} persona.} other {Hai inserito più di {maxNumber} persone.}}',
  'ptc.pt.member-picker.msg.exceed.limited.number.info':
    '{maxNumber, plural, one {Puoi invitare 1 persona per volta.} other {Puoi invitare fino a {maxNumber} persone per volta.}}',
  'ptc.pt.member-picker.no-option': 'Nessun risultato.',
  'ptc.pt.member-picker.placeholder': 'Nome o @menzione',
  'ptc.pt.team-create-dialog.button.cancel': 'Annulla',
  'ptc.pt.team-create-dialog.button.submit': 'Crea team',
  'ptc.pt.team-create-dialog.flag-error.desc':
    'Non è stato possibile salvare il tuo team. Riprova.',
  'ptc.pt.team-create-dialog.flag-error.title': 'Si è verificato un errore',
  'ptc.pt.team-create-dialog.flag-success.action': 'Visualizza il team',
  'ptc.pt.team-create-dialog.flag-success.desc':
    'Menziona il nuovo team per iniziare subito la collaborazione oppure modifica il team nel relativo profilo.',
  'ptc.pt.team-create-dialog.flag-success.title': 'Hai creato "{teamName}"',
  'ptc.pt.team-create-dialog.invite-members.failed.desc':
    'Il team è stato creato, ma è necessario aggiungere di nuovo i membri del team.',
  'ptc.pt.team-create-dialog.invite-members.failed.title':
    'Qualcosa è andato storto con gli inviti',
  'ptc.pt.team-create-dialog.learn-more': 'Maggiori informazioni',
  'ptc.pt.team-create-dialog.modal.fields.invite-emails.label':
    'Invita persone al tuo team',
  'ptc.pt.team-create-dialog.modal.team-name-field.placeholder':
    'Come si chiama il tuo team?',
  'ptc.pt.team-create-dialog.pretext.with.mention':
    'Crea un team per dare il via alla collaborazione. Non perderti le novità grazie alle @menzioni, lavora in modo collaborativo con gli altri e gestisci tutto in maniera efficiente dalla pagina di profilo del team. {learnMoreLink}',
  'ptc.pt.team-create-dialog.team-name-field.label': 'Nome team',
  'ptc.pt.team-create-dialog.title': 'Avvia un nuovo team',
};
