/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Spanish
export default {
  'dragonfruit-application-list.empty-state-description':
    'Utiliza Compass para gestionar los detalles de las aplicaciones móviles y web de tu equipo y buscar las aplicaciones de otros equipos.',
  'dragonfruit-application-list.empty-state-heading':
    'Añade las aplicaciones que está creando tu equipo',
  'dragonfruit-application-list.error-description':
    'No se han podido cargar tus aplicaciones.',
  'dragonfruit-library-list.empty-state-description':
    'Gestiona las bibliotecas que usas junto con tus servicios como, por ejemplo, las bibliotecas de diseño o las de C++.',
  'dragonfruit-library-list.empty-state-heading':
    'Añade las bibliotecas que usa tu equipo',
  'dragonfruit-library-list.error-description':
    'No se han podido cargar tus bibliotecas.',
  'dragonfruit-other-list.empty-state-description':
    'Añade aquí otros componentes para que tu equipo y los demás puedan encontrarlos fácilmente.',
  'dragonfruit-other-list.empty-state-heading':
    '¿Quieres realizar el seguimiento de algo más?',
  'dragonfruit-other-list.error-description':
    'No se han podido cargar tus componentes',
  'dragonfruit-page-component-list.application-list.add-application':
    'Crear aplicaciones',
  'dragonfruit-page-component-list.library-list.add-library':
    'Crear bibliotecas',
  'dragonfruit-page-component-list.other-list.add-component':
    'Crear otros componentes',
  'dragonfruit-page-component-list.services-list.add-service':
    'Crear servicios',
  'dragonfruit-services-list.empty-state-description':
    'Gestiona los servicios que ofrecen capacidades a tus usuarios o a tu equipo, con información sobre la propiedad y otros detalles importantes.',
  'dragonfruit-services-list.empty-state-heading':
    'Añade los servicios que posee tu equipo',
  'dragonfruit-services-list.error-description':
    'No se han podido cargar tus servicios.',
  'page-component-list.left-sidebar-skip-link-title':
    'Exploración de los componentes',
  'page-component-list.main-skip-link-title': 'Lista de componentes',
};
