/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// French
export default {
  'dragonfruit-application-list.empty-state-description':
    "Utilisez Compass pour gérer les informations des apps mobiles et web de votre équipe, et pour rechercher les apps d'autres équipes.",
  'dragonfruit-application-list.empty-state-heading':
    'Ajoutez des apps que votre équipe développe',
  'dragonfruit-application-list.error-description':
    'Impossible de charger vos apps.',
  'dragonfruit-library-list.empty-state-description':
    'Gérez les bibliothèques que vous utilisez avec vos services, comme des bibliothèques de design ou C++.',
  'dragonfruit-library-list.empty-state-heading':
    'Ajouter les bibliothèques que votre équipe utilise',
  'dragonfruit-library-list.error-description':
    'Impossible de charger vos bibliothèques.',
  'dragonfruit-other-list.empty-state-description':
    "Ajoutez d'autres composants ici pour que votre équipe et les autres puissent les trouver facilement.",
  'dragonfruit-other-list.empty-state-heading':
    'Vous souhaitez suivre un autre élément ?',
  'dragonfruit-other-list.error-description':
    'Impossible de charger vos composants',
  'dragonfruit-page-component-list.application-list.add-application':
    'Créer des apps',
  'dragonfruit-page-component-list.library-list.add-library':
    'Créer des bibliothèques',
  'dragonfruit-page-component-list.other-list.add-component':
    "Créer d'autres composants",
  'dragonfruit-page-component-list.services-list.add-service':
    'Créer des services',
  'dragonfruit-services-list.empty-state-description':
    "Gérez les services qui fournissent des capacités à vos utilisateurs ou à votre équipe, grâce à des informations sur la propriété et à d'autres renseignements importants.",
  'dragonfruit-services-list.empty-state-heading':
    'Ajoutez les services qui appartiennent à votre équipe',
  'dragonfruit-services-list.error-description':
    'Impossible de charger vos services.',
  'page-component-list.left-sidebar-skip-link-title':
    'Navigation dans les composants',
  'page-component-list.main-skip-link-title': 'Liste des composants',
};
