/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Portuguese (Brazil)
export default {
  'dragonfruit-application-list.empty-state-description':
    'Use o Compass para gerenciar as informações de aplicativos móveis e web da sua equipe e encontrar aplicativos de outras equipes.',
  'dragonfruit-application-list.empty-state-heading':
    'Adicione os aplicativos que a equipe está criando',
  'dragonfruit-application-list.error-description':
    'Não foi possível carregar os aplicativos.',
  'dragonfruit-library-list.empty-state-description':
    'Gerencie as bibliotecas que você usa junto com os serviços – como bibliotecas de design ou de C++, por exemplo.',
  'dragonfruit-library-list.empty-state-heading':
    'Adicione as bibliotecas que a sua equipe usa',
  'dragonfruit-library-list.error-description':
    'Não foi possível carregar as bibliotecas.',
  'dragonfruit-other-list.empty-state-description':
    'Adicione outros componentes aqui para que a sua e outras equipes os encontrem com tranquilidade.',
  'dragonfruit-other-list.empty-state-heading': 'Quer acompanhar outra coisa?',
  'dragonfruit-other-list.error-description':
    'Não foi possível carregar os componentes',
  'dragonfruit-page-component-list.application-list.add-application':
    'Criar aplicativos',
  'dragonfruit-page-component-list.library-list.add-library':
    'Criar bibliotecas',
  'dragonfruit-page-component-list.other-list.add-component':
    'Criar outros componentes',
  'dragonfruit-page-component-list.services-list.add-service': 'Criar serviços',
  'dragonfruit-services-list.empty-state-description':
    'Gerencie os serviços que oferecem recursos aos usuários ou equipe, com informações sobre propriedade e outros aspectos importantes.',
  'dragonfruit-services-list.empty-state-heading':
    'Adicione os serviços pertencentes à equipe',
  'dragonfruit-services-list.error-description':
    'Não foi possível carregar os serviços.',
  'page-component-list.left-sidebar-skip-link-title':
    'Navegação de componentes',
  'page-component-list.main-skip-link-title': 'Lista de componentes',
};
