/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Vietnamese
export default {
  'dragonfruit-application-list.empty-state-description':
    'Sử dụng Compass để quản lý chi tiết về các ứng dụng di động và ứng dụng web của nhóm bạn, đồng thời tìm các ứng dụng khác của nhóm.',
  'dragonfruit-application-list.empty-state-heading':
    'Thêm các ứng dụng mà nhóm bạn đang xây dựng',
  'dragonfruit-application-list.error-description':
    'Chúng tôi không thể tải các ứng dụng của bạn.',
  'dragonfruit-library-list.empty-state-description':
    'Quản lý các thư viện bạn sử dụng cùng các dịch vụ của bạn – ví dụ như thư viện thiết kế hoặc thư viện C++.',
  'dragonfruit-library-list.empty-state-heading':
    'Thêm các thư viện mà nhóm bạn sử dụng',
  'dragonfruit-library-list.error-description':
    'Chúng tôi không thể tải các thư viện của bạn.',
  'dragonfruit-other-list.empty-state-description':
    'Thêm các thành phần khác vào đây để nhóm bạn và các nhóm khác có thể dễ dàng tìm thấy.',
  'dragonfruit-other-list.empty-state-heading':
    'Bạn muốn theo dõi nội dung khác?',
  'dragonfruit-other-list.error-description':
    'Chúng tôi không thể tải các thành phần của bạn',
  'dragonfruit-page-component-list.application-list.add-application':
    'Tạo ứng dụng',
  'dragonfruit-page-component-list.library-list.add-library': 'Tạo thư viện',
  'dragonfruit-page-component-list.other-list.add-component':
    'Tạo các thành phần khác',
  'dragonfruit-page-component-list.services-list.add-service': 'Tạo dịch vụ',
  'dragonfruit-services-list.empty-state-description':
    'Quản lý các dịch vụ cung cấp chức năng cho người dùng hoặc nhóm của bạn, với thông tin về quyền sở hữu và các chi tiết quan trọng khác.',
  'dragonfruit-services-list.empty-state-heading':
    'Thêm các dịch vụ mà nhóm bạn sở hữu',
  'dragonfruit-services-list.error-description':
    'Chúng tôi không thể tải dịch vụ của bạn.',
  'page-component-list.left-sidebar-skip-link-title': 'Điều hướng thành phần',
  'page-component-list.main-skip-link-title': 'Danh sách thành phần',
};
