/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Dutch
export default {
  'cross_product_search_dialog.bitbucket.tab_label': 'Bitbucket',
  'cross_product_search_dialog.confluence.tab_label': 'Confluence',
  'cross_product_search_dialog.jira.tab_label': 'Jira',
  'cross_product_search_dialog.recently_viewed_title':
    '{sectionTitle} onlangs bekeken',
  'cross_product_search_dialog.view_all_results_link':
    'Alle {sectionTitle} bekijken',
  'global_search.jira.advanced_issue_search_label': 'Geavanceerd issues zoeken',
  'global_search.jira.advanced_search_boards': 'Borden',
  'global_search.jira.advanced_search_filters': 'Filters',
  'global_search.jira.advanced_search_issues': 'Issues',
  'global_search.jira.advanced_search_label': 'Naar alle:',
  'global_search.jira.advanced_search_people': 'Personen',
  'global_search.jira.advanced_search_plans': 'Plannen',
  'global_search.jira.advanced_search_projects': 'Projecten',
  'global_search.jira.search_placeholder': 'Jira doorzoeken',
  'product_search_dialog.bitbucket.bitbucket_advanced_search':
    'Code zoeken in Bitbucket',
  'product_search_dialog.bitbucket.bitbucket_recent_repositories':
    "Onlangs bijgewerkte repository's",
  'product_search_dialog.bitbucket.bitbucket_repositories_section_title':
    "Repository's",
  'product_search_dialog.bitbucket.expanded.input-placeholder':
    'Zoeken in Bitbucket',
  'product_search_dialog.bitbucket.repository_heading': "Repository's",
  'product_search_dialog.common.site_filters': 'Op site filteren',
  'product_search_dialog.confluence.advanced_search_with_product_prefix':
    'Confluence geavanceerd zoeken',
  'product_search_dialog.confluence.assignee_filters_find_more':
    'Een uitvoerder vinden',
  'product_search_dialog.confluence.clear_filters': 'Filters verwijderen',
  'product_search_dialog.confluence.contributor_filters':
    'Op bijdrager filteren',
  'product_search_dialog.confluence.contributor_filters_find_more':
    'Vind een bijdrager',
  'product_search_dialog.confluence.filters_applied':
    'Het lijkt erop dat je een aantal filters hebt toegepast',
  'product_search_dialog.confluence.pages_blogs_attachments_section_heading':
    "Pagina's, blogs en bijlagen",
  'product_search_dialog.confluence.people_section_heading': 'Mensen',
  'product_search_dialog.confluence.search_input_expanded_placeholder':
    'Doorzoek Confluence',
  'product_search_dialog.confluence.space_filters': 'Op space filteren',
  'product_search_dialog.confluence.space_filters_find_more': 'Vind een space',
  'product_search_dialog.confluence.spaces_section_heading': 'Spaces',
  'product_search_dialog.empty.no_results_body':
    'Probeer het opnieuw met een andere term, of verfijn je resultaten met <a>Geavanceerd zoeken</a>',
  'product_search_dialog.empty.no_results_body_no_advanced_search':
    'Probeer het opnieuw met een andere term',
  'product_search_dialog.empty.no_results_heading':
    'We hebben geen overeenkomsten gevonden voor je zoekopdracht.',
  'product_search_dialog.empty_prequery.error_heading':
    'Er is iets misgegaan bij het tonen van de eerste resultaten',
  'product_search_dialog.empty_prequery.no_results_heading':
    'Zoek naar wat je nodig hebt',
  'product_search_dialog.error.failed_search_body':
    'Dit is mogelijk gewoon een foutje. Het beste kun je het <a>nogmaals proberen.</a>',
  'product_search_dialog.error.failed_search_heading':
    'Het lukt ons niet om te zoeken.',
  'product_search_dialog.give_feedback': 'Feedback geven',
  'product_search_dialog.inline_onboarding_action': 'Oké',
  'product_search_dialog.inline_onboarding_body':
    'Gebruik de tabbladen Jira en Confluence om recente items op beide locaties te bekijken.',
  'product_search_dialog.inline_onboarding_title':
    'Zoeken in Jira en Confluence',
  'product_search_dialog.jira.advanced_search_with_product_prefix':
    'Jira geavanceerd issues zoeken',
  'product_search_dialog.jira.assignee_filters': 'Op uitvoerder filteren',
  'product_search_dialog.jira.boards_icon_accessibility_text': 'Pictogram bord',
  'product_search_dialog.jira.boards_projects_filters_plans_section_heading':
    'Borden, projecten, filters en plannen',
  'product_search_dialog.jira.boards_projects_filters_section_heading':
    'Borden, projecten en filters',
  'product_search_dialog.jira.issue_filter_done': 'Gereed',
  'product_search_dialog.jira.issue_filter_open': 'Bekijken',
  'product_search_dialog.jira.issue_filters': 'Filteren op status',
  'product_search_dialog.jira.issues_section_heading': 'Issues',
  'product_search_dialog.jira.project_filters': 'Op project filteren',
  'product_search_dialog.jira.project_filters_find_more': 'Een project vinden',
  'product_search_dialog.jira.projects_filters_section_heading':
    'Projecten en filters',
  'product_search_dialog.jira.recent_boards_projects_filters_plans_section_heading':
    'Recente borden, projecten, filters en plannen',
  'product_search_dialog.jira.recent_boards_projects_filters_section_heading':
    'Recente borden, projecten en filters',
  'product_search_dialog.jira.recent_projects_filters_section_heading':
    'Recente projecten en filters',
  'product_search_dialog.jira.recently_viewed_issues_section_heading':
    'Onlangs bekeken issues',
  'product_search_dialog.jira.site_filters_find_more': 'Een site zoeken',
  'product_search_dialog.jira.view_all_issues': 'Geavanceerd issues zoeken',
  'product_search_dialog.more_filters': 'Alle filters bekijken',
  'product_search_dialog.multi_site_advanced_search_label': 'Zoeken naar:',
  'product_search_dialog.multi_site_advanced_search_more_dropdown':
    '{count} meer',
  'product_search_dialog.recent_spaces_section_heading': 'Recente spaces',
  'product_search_dialog.recently_viewed_heading': 'Geavanceerd zoeken',
  'product_search_dialog.recently_viewed_section_heading': 'Onlangs bekeken',
  'product_search_dialog.recently_worked_with_section_heading':
    'Recent gewerkt met',
  'product_search_dialog.search_input_collapsed_placeholder': 'Zoeken',
  'product_search_dialog.search_people_link': 'Mensen zoeken',
  'product_search_dialog.show_all_results_link': 'Alle resultaten bekijken',
  'product_search_dialog.show_more_results_link': 'Meer tonen',
  'search_dialog.filters.group.show-more': 'Meer tonen',
};
