version: '3.8'

services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
    restart: always
    environment:
      NODE_ENV: development
      STATLAS_NAMESPACE: ${STATLAS_NAMESPACE}
      MICROS_ENV: ${MICROS_ENV}
    depends_on:
      - slauth-proxy
      - dockerhost

  slauth-proxy:
    image: docker.atl-paas.net/micros/slauth-mock-sidecar:stable
    ports:
      - 8081:8081
    environment:
      BACKEND_HOST: dockerhost
      BACKEND_PORT: 8080
    depends_on:
      - dockerhost

  dockerhost:
    image: qoomon/docker-host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: on-failure
    mem_limit: 8M
    cpu_count: 1
