/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Danish
export default {
  'com.atlassian.migrations-platform.migration-details.advanced-roadmaps-task-card.attachments-only-disabled-text':
    'Da der kun er valgt projektvedhæftninger, kan ingen planer overføres.',
  'com.atlassian.migrations-platform.migration-details.advanced-roadmaps-task-card.config-only-disabled-text':
    'Da der kun er valgt projektkonfiguration, kan ingen planer overføres.',
  'com.atlassian.migrations-platform.migration-details.advanced-roadmaps-task-card.fix-error-button-text':
    'Spring planer over',
  'com.atlassian.migrations-platform.migration-details.advanced-roadmaps-task-card.no-selection-text':
    'Der er ikke valgt nogen abonnementer',
  'com.atlassian.migrations-platform.migration-details.advanced-roadmaps-task-card.not-migrating-text':
    'Du har ikke valgt nogen abonnementer.',
  'com.atlassian.migrations-platform.migration-details.advanced-roadmaps-task-card.plans-count-description':
    'Omfatter alle tilknyttede sagskilder og -enheder',
  'com.atlassian.migrations-platform.migration-details.advanced-roadmaps-task-card.plans-count-title':
    '{count, plural, one {{count} abonnement} other {{count} abonnementer}}',
  'com.atlassian.migrations-platform.migration-details.advanced-roadmaps-task-card.skip-button-text':
    'Spring planer over',
  'com.atlassian.migrations-platform.migration-details.advanced-roadmaps-task-card.task-name':
    'Advanced Roadmaps-abonnementer',
  'com.atlassian.migrations-platform.migration-details.app-migrations-task-card.apps-count-description':
    'Alle apps, der er markerede som nødvendige i skyen med en overførselssti.',
  'com.atlassian.migrations-platform.migration-details.app-migrations-task-card.apps-count-title':
    '{count, plural, one {{count} app} other {{count} apps}}',
  'com.atlassian.migrations-platform.migration-details.app-migrations-task-card.no-selection-text':
    'Ingen apps valgt',
  'com.atlassian.migrations-platform.migration-details.app-migrations-task-card.not-selected':
    'Ingen apps til overførsel',
  'com.atlassian.migrations-platform.migration-details.app-migrations-task-card.task-name':
    'Apps',
  'com.atlassian.migrations-platform.migration-details.configuration.cloud-migration-group-membership-content':
    "Gruppemedlemskab bevares ikke. Brugere tilføjes ikke til relevante grupper på destinationswebstedet i skyen. Du skal manuelt <a href='{'url'}' target='_blank'>tilføje brugere til grupper, når migreringen er fuldført.</a>",
  'com.atlassian.migrations-platform.migration-details.configuration.cloud-migration-group-membership-link':
    'føj brugere til grupper efter migreringen.',
  'com.atlassian.migrations-platform.migration-details.configuration.group-membership-content.migrate-separately':
    'Brugere og grupper bliver migreret separat. Brugerne får ikke projekttilladelser og bliver ikke føjet til din licens.',
  'com.atlassian.migrations-platform.migration-details.configuration.group-membership-content.preserve':
    'Gruppemedlemskab bevares. Brugerne får produktadgang, og føjes til din skylicens.',
  'com.atlassian.migrations-platform.migration-details.configuration.users-and-groups-content.all-users-and-groups':
    'Du har valgt at overføre alle brugere og grupper fra Jira-biblioteket',
  'com.atlassian.migrations-platform.migration-details.configuration.users-and-groups-content.include-role-actors':
    'Alle brugere og grupper, der er tildelt roller',
  'com.atlassian.migrations-platform.migration-details.configuration.users-and-groups-content.include-users-in-groups':
    'Enhver bruger, der er medlem af en relateret gruppe',
  'com.atlassian.migrations-platform.migration-details.configuration.users-and-groups-content.referenced-users-and-groups':
    'Brugere og grupper, der er relateret til de valgte projekter.',
  'com.atlassian.migrations-platform.migration-details.configuration.users-and-groups-content.referenced-users-and-groups-options':
    'Brugere og grupper, der er relateret til de valgte projekter. Samt:',
  'com.atlassian.migrations-platform.migration-details.customers-task-card.all-customers.title':
    'Alle kunder fra Jira-biblioteket',
  'com.atlassian.migrations-platform.migration-details.customers-task-card.no-customers.description':
    'Du har ikke valgt nogen kunder.',
  'com.atlassian.migrations-platform.migration-details.customers-task-card.no-selection-text':
    'Ingen kunder er valgt',
  'com.atlassian.migrations-platform.migration-details.customers-task-card.referenced-project-customers.description':
    'Omfatter kunder, der har oprettet en anmodning, eller som der refereres til i en anmodning.',
  'com.atlassian.migrations-platform.migration-details.customers-task-card.referenced-project-customers.title':
    'Kun kunder, der er relateret til de valgte projekter',
  'com.atlassian.migrations-platform.migration-details.customers-task-card.task-name':
    'Kunder',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.app-data-content-plural':
    '{count, plural, one {{count} app} other {{count} apps}}',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.app-data-header':
    'App-data',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.cloud-migration-users-and-groups-content':
    'Alle brugere og grupper vil blive migreret til destinationswebstedet i skyen.',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.cloud-plan-content.cloud-plan':
    '{productName} {productEdition}-plan',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.configuration-caption':
    'Konfiguration',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.destination-cloud-plan-header':
    '{count, plural, one {Skyplan} other {Skyplaner}}',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.destination-url-header':
    'Destination',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.edit-migration':
    'Rediger',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.edit-migration-tooltip':
    'Rediger migrering',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.group-membership-header':
    'Gruppemedlemskab',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.migration-name-header':
    'Overførselsnavn',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.project-configuration-content.all':
    '{numberOfProjectsString}, {numberOfIssuesString} og {attachmentsBytesSizeString} af vedhæftede filer.',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.project-configuration-content.attachments-only':
    '{numberOfProjectsString}: kun vedhæftede filer ({attachmentsBytesSizeString})',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.project-configuration-content.config-only':
    '{numberOfProjectsString}: kun konfiguration',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.project-configuration-content.issues-count-string':
    '{count, plural, one {{count} sag} other {{count} sager}}',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.project-configuration-content.projects-count-string':
    '{count, plural, one {{count} projekt} other {{count} projekter}}',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.projects-header':
    'Projekter',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.source-url-header':
    'Kildewebsted',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.users-and-groups-header':
    'Brugere og grupper',
  'com.atlassian.migrations-platform.migration-details.jira-migration-tasklist.back-button':
    'Tilbage',
  'com.atlassian.migrations-platform.migration-details.jira-migration-tasklist.check-for-errors-button':
    'Tjek, om der er fejl',
  'com.atlassian.migrations-platform.migration-details.migration-status.checks-blocking-errors.description':
    'Opdater for at prøve igen, eller kontakt support, hvis du fortsætter med at få vist denne meddelelse.',
  'com.atlassian.migrations-platform.migration-details.migration-status.checks-blocking-errors.title':
    'Vi kunne ikke kontrollere din migrering',
  'com.atlassian.migrations-platform.migration-details.migration-status.checks-errors.description':
    'Løs disse fejl, før du kører din migrering.',
  'com.atlassian.migrations-platform.migration-details.migration-status.checks-errors.title':
    'Fejl fundet',
  'com.atlassian.migrations-platform.migration-details.migration-status.checks-execution-errors.description':
    'Vi kunne ikke kontrollere en del af din migrering for fejl. Du kan køre din migrering, men der er risiko for, at den kan mislykkes.',
  'com.atlassian.migrations-platform.migration-details.migration-status.checks-execution-errors.title':
    'Vi kunne ikke kontrollere en del af din migrering',
  'com.atlassian.migrations-platform.migration-details.migration-status.checks-header':
    'Kontroller',
  'com.atlassian.migrations-platform.migration-details.migration-status.checks-running-auto-save.description':
    'Vi er stadig ved at kontrollere nogle af dine data. Du kan se resultaterne af disse kontroller senere.',
  'com.atlassian.migrations-platform.migration-details.migration-status.checks-running.description':
    'Vi er stadig ved at kontrollere nogle af dine data. Du kan se resultaterne af disse kontroller senere. Gem din migrering, eller gå tilbage for at se kontrollerne nu.',
  'com.atlassian.migrations-platform.migration-details.migration-status.checks-running.title':
    'Kontrollerer din migrering',
  'com.atlassian.migrations-platform.migration-details.migration-status.checks-success.description':
    'Der blev ikke fundet fejl eller advarsler.',
  'com.atlassian.migrations-platform.migration-details.migration-status.checks-success.title':
    'Din migrering er klar til at køre',
  'com.atlassian.migrations-platform.migration-details.migration-status.checks-warning.description':
    'Gennemse disse advarsler, før du kører din migrering.',
  'com.atlassian.migrations-platform.migration-details.migration-status.checks-warnings.title':
    'Advarsler fundet',
  'com.atlassian.migrations-platform.migration-details.migration-status.container-access-jira-header':
    'Projektadgang',
  'com.atlassian.migrations-platform.migration-details.migration-status.creation-header':
    'Migrering oprettet',
  'com.atlassian.migrations-platform.migration-details.migration-status.creation-header-info':
    'Migreringsoplysninger vil være tilgængelige på dashboardet i 14 dage fra den dag, migreringen blev oprettet.',
  'com.atlassian.migrations-platform.migration-details.migration-status.current-checks-status-blocking-execution-error.title':
    'Vis advarsler',
  'com.atlassian.migrations-platform.migration-details.migration-status.current-checks-status-error.title':
    'Vis fejl og advarsler',
  'com.atlassian.migrations-platform.migration-details.migration-status.current-checks-status-execution-error.title':
    'Vis advarsler',
  'com.atlassian.migrations-platform.migration-details.migration-status.current-checks-status-running.title':
    'Kører',
  'com.atlassian.migrations-platform.migration-details.migration-status.current-checks-status-success.title':
    'Ingen advarsler eller fejl',
  'com.atlassian.migrations-platform.migration-details.migration-status.current-checks-status-warning.title':
    'Vis advarsler',
  'com.atlassian.migrations-platform.migration-details.migration-status.default-cloud-destination':
    'destination i skyen',
  'com.atlassian.migrations-platform.migration-details.migration-status.estimated-time-to-migrate-header':
    'Anslået tid til migrering',
  'com.atlassian.migrations-platform.migration-details.migration-status.last-checked-header':
    'Sidst opdateret',
  'com.atlassian.migrations-platform.migration-details.migration-status.migration-complete.description':
    'Det kan tage lidt tid, før migrerede data vises i din {cloudDestination}.',
  'com.atlassian.migrations-platform.migration-details.migration-status.migration-complete.title':
    'Migreringen er gennemført',
  'com.atlassian.migrations-platform.migration-details.migration-status.migration-failed.description':
    'Vi kunne ikke fuldføre migreringen. Gennemse fejllogfilen for at få flere oplysninger, og prøv at køre en ny migrering.',
  'com.atlassian.migrations-platform.migration-details.migration-status.migration-failed.description.without.reports':
    'Vi kunne ikke fuldføre migreringen.',
  'com.atlassian.migrations-platform.migration-details.migration-status.migration-failed.title':
    'Migreringen mislykkedes',
  'com.atlassian.migrations-platform.migration-details.migration-status.migration-incomplete.cloud.description':
    'Vi kunne ikke migrere nogle data.',
  'com.atlassian.migrations-platform.migration-details.migration-status.migration-incomplete.description':
    'Vi kunne ikke migrere nogle data. Gennemgå fejllogfilerne for at få flere oplysninger.',
  'com.atlassian.migrations-platform.migration-details.migration-status.migration-incomplete.title':
    'Migreringen blev ikke fuldført',
  'com.atlassian.migrations-platform.migration-details.migration-status.migration-running.description':
    'Migreringen er i gang på nuværende tidspunkt.',
  'com.atlassian.migrations-platform.migration-details.migration-status.migration-running.title':
    'Migreringen kører',
  'com.atlassian.migrations-platform.migration-details.migration-status.migration-stopped.description':
    'Vi har allerede migreret de data, der er markeret som fuldstændige. Hvis du vil migrere dem igen senere, skal du slette dem fra din migreringsdestination.',
  'com.atlassian.migrations-platform.migration-details.migration-status.migration-stopped.title':
    'Migreringen blev stoppet',
  'com.atlassian.migrations-platform.migration-details.migration-status.migration-stopping.description':
    'Migreringen er ved at blive stoppet.',
  'com.atlassian.migrations-platform.migration-details.migration-status.migration-stopping.title':
    'Stopper migrering',
  'com.atlassian.migrations-platform.migration-details.migration-status.migration-validating.description':
    'Vi er stadig ved at kontrollere nogle af dine data.',
  'com.atlassian.migrations-platform.migration-details.migration-status.migration-validating.title':
    'Kontrollerer din migrering',
  'com.atlassian.migrations-platform.migration-details.migration-status.site-cloud-destination':
    'destinationsside',
  'com.atlassian.migrations-platform.migration-details.migration-status.status-message.refresh':
    'Opdater',
  'com.atlassian.migrations-platform.migration-details.select-all-customers-button.text':
    'Vælg alle kunder',
  'com.atlassian.migrations-platform.migration-details.skip-all-customers-button.text':
    'Spring alle kunder over',
  'com.atlassian.migrations-platform.migration-details.status.anonymous-access-content.containers':
    'Data vil være offentligt tilgængelige',
  'com.atlassian.migrations-platform.migration-details.status.anonymous-access-content.projects':
    'Projekter og data vil være offentligt tilgængelige',
  'com.atlassian.migrations-platform.migration-details.status.estimated-time-content.estimated-time-at-16-mbps':
    '(anslået tid ved 16 Mbps)',
  'com.atlassian.migrations-platform.migration-details.status.estimated-time-content.five-to-ten-minutes':
    '5-10 min.',
  'com.atlassian.migrations-platform.migration-details.status.estimated-time-content.five-to-twelve-hours':
    '5-12 timer',
  'com.atlassian.migrations-platform.migration-details.status.estimated-time-content.half-day-to-a-day':
    '12 timer-1 dag',
  'com.atlassian.migrations-platform.migration-details.status.estimated-time-content.half-hour-to-an-hour':
    '30 min.-1 time',
  'com.atlassian.migrations-platform.migration-details.status.estimated-time-content.less-than-a-minute':
    '0 min.',
  'com.atlassian.migrations-platform.migration-details.status.estimated-time-content.more-than-a-week':
    '~ 1 uge',
  'com.atlassian.migrations-platform.migration-details.status.estimated-time-content.not-available':
    'Intet estimat tilgængeligt',
  'com.atlassian.migrations-platform.migration-details.status.estimated-time-content.one-to-five-minutes':
    '1-5 min.',
  'com.atlassian.migrations-platform.migration-details.status.estimated-time-content.one-to-two-days':
    '1-2 dage',
  'com.atlassian.migrations-platform.migration-details.status.estimated-time-content.one-to-two-hours':
    '1-2 timer',
  'com.atlassian.migrations-platform.migration-details.status.estimated-time-content.ten-to-thirty-minutes':
    '10-30 min.',
  'com.atlassian.migrations-platform.migration-details.status.estimated-time-content.two-to-five-days':
    '2-5 dage',
  'com.atlassian.migrations-platform.migration-details.status.estimated-time-content.two-to-five-hours':
    '2-5 timer',
  'com.atlassian.migrations-platform.migration-details.task-card.edit-button':
    'Redigér',
  'com.atlassian.migrations-platform.migration-details.task-card.select-button':
    'Vælg',
  'com.atlassian.migrations-platform.migration-details.task-card.skip-button':
    'Spring {lowerCaseTaskName} over',
  'com.atlassian.migrations-platform.migration-details.task-card.status-indicator-error-icon-label':
    'Fejl',
  'com.atlassian.migrations-platform.migration-details.task-card.status-indicator-not-selected-icon-label':
    'Ikke udført',
  'com.atlassian.migrations-platform.migration-details.task-card.status-indicator-selected-icon-label':
    'Udført',
  'com.atlassian.migrations-platform.migration-details.task-list-errors.attachments-only-error-description':
    'Da du kun overfører vedhæftninger for udvalgte projekter, kan du ikke overføre alle elementerne nedenfor. Du kan enten springe disse elementer over eller ændre markeringen Kun vedhæftninger.',
  'com.atlassian.migrations-platform.migration-details.task-list-errors.config-only-error-description':
    'Da du kun overfører konfiguration for udvalgte projekter, kan du ikke overføre alle elementerne nedenfor. Du kan enten springe disse elementer over eller ændre markeringen Kun konfiguration.',
  'com.atlassian.migrations-platform.migration-details.task-list-errors.invalid-selection-error-title':
    'Ugyldigt valg',
  'com.atlassian.migrations-platform.migration-details.task-list-errors.skip-projects-but-referenced-users-groups-error-description':
    'Da du ikke har valgt nogen projekter, kan du ikke overføre brugere og grupper, der er relateret til disse projekter. Føj projekter til din overførsel, eller vælg alle brugere og grupper.',
  'com.atlassian.migrations-platform.migration-details.task-list-errors.skip-projects-but-referenced-users-groups-error-title':
    'Ugyldigt valg af brugere og grupper',
  'com.atlassian.migrations-platform.migration-details.task-list-errors.skip-projects-referenced-customers-error-description':
    'Da du ikke har valgt nogen projekter, kan du ikke overføre kunder, der er relateret til disse projekter. Du skal føje projekter til din overførsel eller vælge alle kunder.',
  'com.atlassian.migrations-platform.migration-details.task-list-errors.skip-projects-referenced-customers-error-title':
    'Ugyldigt kundevalg',
  'com.atlassian.migrations-platform.migration-details.task-list-errors.skip-projects-referenced-users-groups-customers-error-description':
    'Da du ikke har valgt nogen projekter, kan du ikke overføre relaterede brugere og grupper eller kunder. Du skal enten føje projekter til din overførsel eller skifte dine valg.',
  'com.atlassian.migrations-platform.migration-details.task-list-errors.skip-projects-referenced-users-groups-customers-error-title':
    'Ugyldigt valg',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.all-users-and-groups':
    'Alle brugere og grupper fra Jira-biblioteket',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.attachments-only-disabled-description':
    'Da der kun er valgt projektvedhæftninger, kan ingen brugere, grupper eller gruppemedlemskaber overføres.',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.include-role-actors':
    'Alle brugere og grupper, der er tildelt påkrævede roller.',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.include-users-in-groups':
    'Alle brugere, der er medlem af en gruppe i denne migrering.',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.migrate-users-groups-separately-description':
    'Brugerne får ikke projekttilladelser og bliver ikke føjet til din licens.',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.migrate-users-groups-separately-title':
    'Migrer brugere og grupper separat',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.no-selection-text':
    'Der er ikke valgt brugere, grupper eller gruppemedlemskab',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.preserver-group-membership-description':
    'Brugerne får produktadgang, og føjes til din skylicens.',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.preserver-group-membership-title':
    'Bevar gruppemedlemskaber',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.referenced-users-and-groups-with-options':
    'Brugere og grupper, der henvises til i projekter.',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.refrenced-users-and-groups-minimum':
    'Brugere og grupper, der henvises til i projekter.',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.refrenced-users-and-groups-title':
    'Kun brugere og grupper, der er relateret til de valgte projekter',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.select-all-users-and-groups-button-text':
    'Vælg alle brugere og grupper',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.skip-all-users-and-groups-button-text':
    'Spring alle brugere og grupper over',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.task-name':
    'Brugere og grupper',
};
