/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// English (Instrumented)
export default {
  'com.atlassian.migrations-platform.migration-details.advanced-roadmaps-task-card.attachments-only-disabled-text':
    '⁣⁢Since only project attachments are selected, no plans can be migrated.⁡⁫؜‌⁪⁠⁡⁯⁭؜‌⁠⁭⁪⁭؜⁫⁮‌؜‌⁭⁡⁪⁣⁤',
  'com.atlassian.migrations-platform.migration-details.advanced-roadmaps-task-card.config-only-disabled-text':
    '⁣⁢Since only project configuration is selected, no plans can be migrated.‌⁯⁬⁯‍‍‍⁮‌⁠⁬⁭⁭‌⁫⁫⁬⁠⁠⁮⁮⁮⁠⁭‍⁣⁤',
  'com.atlassian.migrations-platform.migration-details.advanced-roadmaps-task-card.fix-error-button-text':
    '⁣⁢Skip plans⁠⁡⁮⁯⁬⁫‌⁪⁭⁠‍⁮⁬‌⁫‍⁫⁡⁡⁠⁮⁣⁤',
  'com.atlassian.migrations-platform.migration-details.advanced-roadmaps-task-card.no-selection-text':
    '⁣⁢No plans selected⁭؜⁬‍⁬⁭⁬⁬⁪⁪‌⁡⁠⁡‍⁪⁠؜‍⁫⁫⁭⁫⁪⁣⁤',
  'com.atlassian.migrations-platform.migration-details.advanced-roadmaps-task-card.not-migrating-text':
    '⁣⁢You haven’t selected any plans.⁬⁫⁯⁯⁭؜⁡⁠‌⁫⁬⁡⁭⁭‌⁬⁠⁠⁫⁫؜⁮⁯⁡⁮⁮⁭⁣⁤',
  'com.atlassian.migrations-platform.migration-details.advanced-roadmaps-task-card.plans-count-description':
    '⁣⁢Includes all associated issue sources and entities⁡؜⁠‍⁫⁪⁭؜‍‍⁫‌⁫⁠⁠⁫⁠‍⁯⁣⁤',
  'com.atlassian.migrations-platform.migration-details.advanced-roadmaps-task-card.plans-count-title':
    '{count, plural, one {⁣⁢{count} plan⁡⁠‌⁠⁮⁮⁯⁭‌⁠؜؜‍‍؜⁭⁠‌⁣⁤} other {⁣⁢{count} plans⁡⁠‌⁠⁮⁮⁯⁭‌⁠؜؜‍‍؜⁭⁠‌⁣⁤}}',
  'com.atlassian.migrations-platform.migration-details.advanced-roadmaps-task-card.skip-button-text':
    '⁣⁢Skip plans⁠‍‌⁡⁠⁯⁭⁯؜⁭‌⁪⁬⁭⁮⁠⁭⁪⁮‌⁪⁣⁤',
  'com.atlassian.migrations-platform.migration-details.advanced-roadmaps-task-card.task-name':
    '⁣⁢Advanced Roadmaps plans⁠⁫⁬⁮⁯⁠⁠⁠⁮‌‍⁯⁠⁫⁬⁫⁬⁯‌⁮؜⁮⁠⁠⁫⁣⁤',
  'com.atlassian.migrations-platform.migration-details.app-migrations-task-card.apps-count-description':
    '⁣⁢All apps marked as ‘Needed in cloud’ with a migration path.⁬⁫؜⁡؜‍⁭⁬‌‌‍؜⁯⁭؜⁯⁭⁮⁯⁪⁭⁭؜⁫⁣⁤',
  'com.atlassian.migrations-platform.migration-details.app-migrations-task-card.apps-count-title':
    '{count, plural, one {⁣⁢{count} app⁬⁠⁮⁭⁬؜⁬⁠؜‌⁡⁠⁠‍⁯؜⁫⁮‌⁫⁭⁣⁤} other {⁣⁢{count} apps⁬⁠⁮⁭⁬؜⁬⁠؜‌⁡⁠⁠‍⁯؜⁫⁮‌⁫⁭⁣⁤}}',
  'com.atlassian.migrations-platform.migration-details.app-migrations-task-card.no-selection-text':
    '⁣⁢No apps selected⁫⁮؜‌⁭⁬⁭‍‍⁠⁬‌⁯⁬‌⁪⁫‍⁫⁠⁬؜⁪⁣⁤',
  'com.atlassian.migrations-platform.migration-details.app-migrations-task-card.not-selected':
    '⁣⁢No apps to be migrated⁮⁮⁬‍‌⁪‍⁡⁡⁭⁯‌⁭⁪‍⁯⁮‌⁬؜⁯⁣⁤',
  'com.atlassian.migrations-platform.migration-details.app-migrations-task-card.task-name':
    '⁣⁢Apps⁫‌⁮؜⁡⁯⁬⁯‍⁬‍؜‍⁪⁮⁮⁠؜⁪⁪⁯‍⁣⁤',
  'com.atlassian.migrations-platform.migration-details.configuration.cloud-migration-group-membership-content':
    "⁣⁢Users and groups will be migrated separately. Users will not be added to groups in the destination site. You'll need to manually <a href='{'url'}' target='_blank'>add users to groups</a> after migration.⁯؜⁯⁡‍⁯⁭⁠⁡⁯⁪⁬‌⁫‍⁡⁬؜⁫⁪⁡‌؜‌⁭⁣⁤",
  'com.atlassian.migrations-platform.migration-details.configuration.cloud-migration-group-membership-link':
    '⁣⁢add users to groups after the migration.⁭⁯⁫⁮⁯⁭⁯⁯⁯⁫⁮⁮⁪⁯‌⁫؜‌⁠؜⁭⁣⁤',
  'com.atlassian.migrations-platform.migration-details.configuration.group-membership-content.migrate-separately':
    '⁣⁢Users and groups will be migrated separately. Users will not be given project permissions and will not be added to your license.⁫؜⁭⁡⁯⁯⁡؜؜⁡⁮⁪⁠⁮⁪⁭⁯⁣⁤',
  'com.atlassian.migrations-platform.migration-details.configuration.group-membership-content.preserve':
    '⁣⁢Group membership will be preserved. Users will get product access and will be added to your cloud license.⁠⁮⁮⁯⁡⁡؜؜‌⁠⁭⁭⁭؜⁡؜⁠؜⁣⁤',
  'com.atlassian.migrations-platform.migration-details.configuration.users-and-groups-content.all-users-and-groups':
    '⁣⁢You have chosen to migrate all users and groups from the Jira directory⁫⁭⁭⁪⁮⁫‍؜‍‌⁪⁠⁡⁠⁬⁠⁪⁪⁪⁪⁭؜⁣⁤',
  'com.atlassian.migrations-platform.migration-details.configuration.users-and-groups-content.include-role-actors':
    '⁣⁢All users and groups assigned to roles⁮⁬⁭⁪‌⁮⁡⁭‍‌‌‌⁭⁫⁪⁪⁯⁬؜⁪؜⁣⁤',
  'com.atlassian.migrations-platform.migration-details.configuration.users-and-groups-content.include-users-in-groups':
    '⁣⁢Any user who is a member of any related group؜⁮⁪‌؜⁫⁡⁬⁫⁠⁬⁮‍⁯⁪‍⁭⁮⁪⁭⁯⁪⁣⁤',
  'com.atlassian.migrations-platform.migration-details.configuration.users-and-groups-content.referenced-users-and-groups':
    '⁣⁢Users and groups related to the selected projects.⁮⁬⁯⁮‌⁠⁯‌⁬⁯⁯⁠⁠⁯؜⁮⁭⁭⁫؜⁯⁯⁫⁮⁫⁣⁤',
  'com.atlassian.migrations-platform.migration-details.configuration.users-and-groups-content.referenced-users-and-groups-options':
    '⁣⁢Users and groups related to the selected projects. Plus:⁬⁫‌⁡⁯⁠؜⁬‌‌⁪‌⁠⁬‌‍⁯⁮‍⁬⁮⁪⁣⁤',
  'com.atlassian.migrations-platform.migration-details.customers-task-card.all-customers.description':
    '{customers, plural, one {⁣⁢Currently, {customers} customer.⁬؜⁭‌⁡⁭⁫‌⁮⁬‌‍‌‌⁯⁫⁭؜⁯⁬⁯⁡⁣⁤} other {⁣⁢Currently, {customers} customers.⁬؜⁭‌⁡⁭⁫‌⁮⁬‌‍‌‌⁯⁫⁭؜⁯⁬⁯⁡⁣⁤}}',
  'com.atlassian.migrations-platform.migration-details.customers-task-card.all-customers.title':
    '⁣⁢All customers from the Jira directory⁡⁬‌⁡⁡⁡⁫؜‍⁯‌⁫⁬‍‍⁠⁪⁬⁫⁯‍⁬⁠⁣⁤',
  'com.atlassian.migrations-platform.migration-details.customers-task-card.no-customers.description':
    '⁣⁢You haven’t selected any customers.⁮⁫⁫‌⁡⁭⁪⁮⁮⁫⁡؜⁯‌⁯⁬⁭⁪⁯‌⁣⁤',
  'com.atlassian.migrations-platform.migration-details.customers-task-card.no-customers.title':
    '{customers, plural, one {⁣⁢{customers} customer؜⁬⁠⁬⁫؜⁪⁡‍⁠⁯‌⁮⁬⁫‌⁡⁯⁯⁫⁣⁤} other {⁣⁢{customers} customers؜⁬⁠⁬⁫؜⁪⁡‍⁠⁯‌⁮⁬⁫‌⁡⁯⁯⁫⁣⁤}}',
  'com.atlassian.migrations-platform.migration-details.customers-task-card.no-selection-text':
    '⁣⁢No customers selected⁭‍⁡⁭⁯⁠⁯⁭⁫⁯⁭⁯⁮⁯‍⁮⁬⁡‍⁬؜⁣⁤',
  'com.atlassian.migrations-platform.migration-details.customers-task-card.referenced-project-customers.description':
    '⁣⁢Includes any customer who has created a request or is referenced in a request.‌⁮⁫‌⁮⁭⁮⁡⁠⁬⁬؜⁫⁡‌⁠؜⁣⁤',
  'com.atlassian.migrations-platform.migration-details.customers-task-card.referenced-project-customers.title':
    '⁣⁢Only customers related to the selected projects⁮⁬‍؜⁯⁠⁠⁠⁭‌⁯⁮‌⁫⁫⁯‌⁠⁡⁪⁮⁪‌⁮⁣⁤',
  'com.atlassian.migrations-platform.migration-details.customers-task-card.task-name':
    '⁣⁢Customers⁫⁬⁪⁬⁡‌⁪⁯⁠‍‌⁯‍؜⁮؜⁡⁯⁭⁬⁣⁤',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.app-data-content-plural':
    '{count, plural, one {⁣⁢{count} app⁮⁠⁡⁠⁮⁡⁠⁯⁪⁮‍‍⁫⁭؜‌؜؜⁡⁮⁮⁣⁤} other {⁣⁢{count} apps⁮⁠⁡⁠⁮⁡⁠⁯⁪⁮‍‍⁫⁭؜‌؜؜⁡⁮⁮⁣⁤}}',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.app-data-header':
    '⁣⁢App data⁪⁠؜⁮‌⁪⁫؜⁯؜⁡؜‌⁯⁡⁮⁭‌⁯⁯⁠⁫⁠⁣⁤',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.cloud-migration-users-and-groups-content':
    '⁣⁢All users and groups of the source site will be migrated to the destination site⁫⁭⁮‌⁯⁪‌⁫‍؜⁬⁪⁠⁬⁬⁫؜⁬⁪⁫⁣⁤',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.cloud-plan-content.cloud-plan':
    '⁣⁢{productName} {productEdition} plan⁭⁬⁬⁠⁯⁯⁬⁪‌⁪⁫⁯‌⁫⁯⁮⁬؜⁮⁣⁤',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.configuration-caption':
    '⁣⁢Configuration؜؜⁠⁯⁪؜⁡⁯؜‌؜⁡⁬؜‍⁠⁪⁯‍⁡⁣⁤',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.customers-header':
    '⁣⁢Customers⁪⁫⁡‌؜⁬⁮‍⁬⁫⁫⁪⁡⁡⁫⁯؜⁬⁡⁫⁣⁤',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.destination-cloud-plan-header':
    '{count, plural, one {⁣⁢Cloud plan‍⁬⁭⁮؜⁫⁯⁭⁯⁯⁡⁮⁫⁮⁠⁭⁠⁯⁠⁭‍⁣⁤} other {⁣⁢Cloud plans‍⁬⁭⁮؜⁫⁯⁭⁯⁯⁡⁮⁫⁮⁠⁭⁠⁯⁠⁭‍⁣⁤}}',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.destination-url-header':
    '⁣⁢Destination‍⁬؜؜⁡⁭⁫⁠⁭؜⁯⁭⁫⁬⁯⁬⁠⁡⁠؜؜⁭⁬⁯⁪⁣⁤',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.edit-migration':
    '⁣⁢Edit⁫⁭⁡⁫‌⁪⁫⁠‍⁯⁫؜⁠⁠⁯⁯⁫⁡⁬⁯⁭⁮⁫⁣⁤',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.edit-migration-tooltip':
    '⁣⁢Edit migration⁮‍؜⁡‌⁫⁭⁬⁭⁭⁡‍⁡⁠⁬⁮⁡⁫⁪⁭⁫⁣⁤',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.group-membership-header':
    '⁣⁢Group membership⁪⁬⁡⁫⁫⁪‍؜⁯⁯⁪⁭⁯⁭⁮⁭⁯⁯⁣⁤',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.migration-name-header':
    '⁣⁢Migration name⁭⁭⁫؜⁬⁫⁫⁫‍‍⁯⁮⁯⁡⁡⁯⁡⁡⁯⁬‍⁪؜⁡⁣⁤',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.project-configuration-content.all':
    '⁣⁢{numberOfProjectsString}, {numberOfIssuesString} and {attachmentsBytesSizeString} of attachments.‌⁪⁬⁭⁬⁯⁠⁫⁭⁬⁭⁪⁭⁮⁮⁫⁫⁯⁡⁣⁤',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.project-configuration-content.all-jira-projects':
    '⁣⁢{numberOfJiraProjectsString}, {numberOfIssuesJiraString}, and {attachmentsBytesSizeJiraString} of attachments.⁭⁫؜⁬⁠⁫؜⁯؜‌‍⁠⁪⁪؜؜⁯؜⁯⁮⁮⁬⁣⁤',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.project-configuration-content.all-jsm-projects':
    '⁣⁢{numberOfJSMProjectsString}, {numberOfIssuesJSMString} and {attachmentsBytesSizeJSMString} of attachments.⁠⁮‌⁠⁪⁭⁫‌‌⁠⁡⁫‌⁭⁭⁫⁯⁪⁬⁠⁯⁡⁪⁣⁤',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.project-configuration-content.attachments-only':
    '⁣⁢{numberOfProjectsString}: attachments only ({attachmentsBytesSizeString})‌⁯‍⁡⁭⁬‍‌⁭‌‍⁭⁠⁭⁯⁬؜⁡⁬⁫⁪⁭⁪⁣⁤',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.project-configuration-content.config-only':
    '⁣⁢{numberOfProjectsString}: configuration only؜⁯⁠‌⁫؜⁭⁯⁬⁡⁠⁠‌⁮⁡‌⁠⁣⁤',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.project-configuration-content.issues-count-string':
    '{count, plural, one {⁣⁢{count} issue⁪⁮⁮‍⁫⁮⁠‌⁭⁫⁭⁠⁫⁡⁪⁫⁪⁪⁡⁪⁯⁠⁪⁣⁤} other {⁣⁢{count} issues⁪⁮⁮‍⁫⁮⁠‌⁭⁫⁭⁠⁫⁡⁪⁫⁪⁪⁡⁪⁯⁠⁪⁣⁤}}',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.project-configuration-content.jira-projects-count-string':
    '{count, plural, one {⁣⁢{count} Jira project⁮⁬⁫⁪⁫⁮⁪⁮⁪؜⁭⁠‌⁫⁮⁮⁪⁪‍⁪⁡؜⁡⁡⁣⁤} other {⁣⁢{count} Jira projects⁮⁬⁫⁪⁫⁮⁪⁮⁪؜⁭⁠‌⁫⁮⁮⁪⁪‍⁪⁡؜⁡⁡⁣⁤}}',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.project-configuration-content.jsm-projects-count-string':
    '{count, plural, one {⁣⁢{count} Jira Service Management project⁡⁭⁭⁡‍⁡⁭⁪⁬⁯⁯⁭⁭‍⁪⁡⁠⁪⁯⁯⁬⁪⁭⁣⁤} other {⁣⁢{count} Jira Service Management projects⁡⁭⁭⁡‍⁡⁭⁪⁬⁯⁯⁭⁭‍⁪⁡⁠⁪⁯⁯⁬⁪⁭⁣⁤}}',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.project-configuration-content.projects-count-string':
    '{count, plural, one {⁣⁢{count} project⁭⁡⁪⁯⁫⁪⁭⁮⁠؜⁫⁠⁯⁯⁮‍⁡⁠⁯⁠⁠⁬⁫⁣⁤} other {⁣⁢{count} projects⁭⁡⁪⁯⁫⁪⁭⁮⁠؜⁫⁠⁯⁯⁮‍⁡⁠⁯⁠⁠⁬⁫⁣⁤}}',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.projects-header':
    '⁣⁢Projects⁡⁬⁮⁠⁭⁫‍‍؜⁯‌‌⁪؜⁫‍⁫⁮⁬؜‌‍⁣⁤',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.source-url-header':
    '⁣⁢Source site⁠⁪⁮⁡‌⁬⁯⁫⁮⁠‍⁠⁬؜؜⁯؜⁭⁡⁣⁤',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.users-and-groups-header':
    '⁣⁢Users and groups⁭⁮⁠⁭؜⁡⁯⁬‍⁪⁫⁮⁬⁭‌⁡⁬⁪⁭⁮⁪⁯⁪⁮‌⁣⁤',
  'com.atlassian.migrations-platform.migration-details.jira-migration-tasklist.back-button':
    '⁣⁢Back‌⁬⁠⁠⁫⁬⁭⁯⁪⁪⁪⁡‌‍⁠⁪⁫⁠⁪⁫⁮⁣⁤',
  'com.atlassian.migrations-platform.migration-details.jira-migration-tasklist.check-for-errors-button':
    '⁣⁢Check for errors⁡⁮⁬⁭‍‌⁯‌⁪‌‍⁬⁠⁠‍؜⁬؜‍‌⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.checks-blocking-errors.description':
    '⁣⁢Refresh to try again or contact support if you continue to get this message.‍⁠⁮⁡⁠⁡⁮؜⁡؜⁪⁭⁭‌⁡⁯⁮‍⁡‌⁬‌⁮‍⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.checks-blocking-errors.title':
    '⁣⁢We could not check your migration⁫⁯⁪؜⁯‌⁡⁫‌⁯⁫⁪⁪؜⁯⁪⁮⁫⁠⁠‍⁪⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.checks-errors.description':
    '⁣⁢Fix these errors before running your migration.⁭⁯⁡⁭⁬⁡⁪⁫⁪⁮‌⁭‌⁫؜⁬⁭⁫⁪⁯⁫⁠⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.checks-errors.title':
    '⁣⁢Errors found⁭⁠‍⁠⁯⁡⁯⁬؜⁮⁡⁬⁮⁡⁭⁯⁭؜‍‌⁭⁪⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.checks-execution-errors.description':
    "⁣⁢We couldn't check some of your migration for errors. You can run your migration but it may fail.⁬‍؜⁡‌⁡‍⁮⁬⁬‍⁫⁭⁫‍⁭‌؜‌⁮‍⁬⁮‌⁫⁣⁤",
  'com.atlassian.migrations-platform.migration-details.migration-status.checks-execution-errors.title':
    '⁣⁢We could not check some of your migration‍⁭⁠⁬⁯⁮⁫⁪⁫⁪⁯⁡⁮⁫⁠‍‍؜⁯⁮⁫⁪؜⁡؜⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.checks-header':
    '⁣⁢Checks‌⁡⁬⁫‍⁮‌⁠⁫⁫⁡⁠⁭⁯⁪‍⁯؜⁯⁮⁠⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.checks-running-auto-save.description':
    '⁣⁢We are still checking some of your data. You can see the results of these checks later.⁫⁯⁡⁬⁮‍‍⁯‍⁬؜‍⁫‍⁫⁡⁫‌⁯⁭؜⁯⁫⁪⁠⁯؜⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.checks-running.description':
    '⁣⁢We are still checking some of your data. You can see the results of these checks later. Save your migration or go back to view the checks now.‍⁠⁡⁭؜‍⁬⁪⁫⁮⁭⁡⁠⁠‌‌⁠⁭⁭⁯⁠⁠‌⁡؜⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.checks-running.title':
    '⁣⁢Checking your migration‌⁭‌‍⁯‍⁠⁬⁡⁠⁫⁫⁡⁬⁭⁭‍⁭⁪⁫⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.checks-success.description':
    '⁣⁢No errors or warnings were found.‌⁬⁯‌⁯⁬⁠⁪⁭‍‌⁮⁠⁮⁠‌⁪‍⁫؜‍⁭‍⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.checks-success.title':
    '⁣⁢Your migration is ready to run⁮‍⁬⁯⁭⁮⁬⁠⁭⁡⁭⁭⁬⁬‍‌⁠⁯‍؜⁡⁬⁭⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.checks-warning.description':
    '⁣⁢Review these warnings before running your migration.⁮⁡⁯⁪؜؜⁬⁠⁪⁭⁯⁠‌‌؜⁫؜⁫‌⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.checks-warnings.title':
    '⁣⁢Warnings found⁫⁪⁡⁯‍⁬⁮⁠؜⁭⁠‍⁡⁠‍⁡⁭⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.container-access-jira-header':
    '⁣⁢Project access؜⁫⁮⁠⁪⁮⁠⁯⁮⁭⁭⁭⁮⁬⁡⁠⁬⁮⁭⁠⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.creation-header':
    '⁣⁢Migration created‌‌‍⁫⁫⁫‌⁪⁪⁬⁯⁫⁠⁮⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.creation-header-info':
    '⁣⁢Migration details will be available on the dashboard for 14 days from the day the migration was created.⁯⁬⁯⁫⁪‍⁯‍⁯‍‍⁭‍؜‍‌⁬⁡‌⁭⁮⁡⁭⁡⁫⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.current-checks-status-blocking-execution-error.title':
    '⁣⁢View warnings؜⁠⁪‍‍⁬⁫⁭⁪؜⁬⁠⁡⁫⁮⁭؜⁯⁠‍⁯⁡⁮⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.current-checks-status-error.title':
    '⁣⁢View errors and warnings⁭؜⁪⁯⁡‌⁪⁠⁡⁡‌⁯⁠؜⁭‌⁮‍⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.current-checks-status-execution-error.title':
    '⁣⁢View warnings⁪‌⁯⁬⁠‍⁫⁮؜‌‍‍⁪‍⁭⁪⁫⁯‍⁡⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.current-checks-status-running.title':
    '⁣⁢Running⁫⁮؜‍⁭⁮⁬⁫⁪‍‌⁫⁮⁪⁬⁮⁪؜⁬؜؜⁪⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.current-checks-status-success.title':
    '⁣⁢No warnings or errors‍⁡⁭⁮⁡⁡‌⁡⁪⁯⁮⁬⁭‍⁡⁡⁡⁮⁡⁭⁡⁠⁪⁮⁫⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.current-checks-status-warning.title':
    '⁣⁢View warnings⁭⁡‍⁬⁪⁬⁯⁭⁮⁯⁪‍⁯⁪⁮⁬؜⁫⁪⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.estimated-time-to-migrate-header':
    '⁣⁢Estimated time to migrate⁯⁯‌‍⁫؜⁮‌‍⁭⁠⁭⁪⁯؜⁪⁡⁫⁬⁬⁡⁡⁯⁮⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.last-checked-header':
    '⁣⁢Last updated⁠⁬⁬⁯⁭⁮⁯⁯؜‌⁭⁭⁯⁪⁡‍⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.migration-complete-default-cloud-destination.description':
    '⁣⁢It may take some time for migrated data to appear in your cloud destination.‌⁭؜⁪⁫⁡‍‌⁡⁮؜‌⁯‌⁫⁪⁫⁮؜‍⁫⁡⁯⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.migration-complete-site-cloud-destination.description':
    '⁣⁢It may take some time for migrated data to appear in your destination site.⁡⁭⁫⁪⁪⁪⁫⁠⁠⁮‍⁮⁪⁡‍⁬؜⁬⁭⁪⁮⁠⁬⁬⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.migration-complete.title':
    '⁣⁢Migration complete⁠⁪‌؜‌⁫⁡‌‍⁠؜⁬⁭؜‌⁫⁯⁡⁬⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.migration-failed.description':
    '⁣⁢We could not complete the migration. Review error log for more details and try running a new migration.⁯⁯⁯⁪⁪‌؜⁪‍⁯⁡⁬⁠؜⁡⁮‌⁡⁡⁬⁬⁯⁪⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.migration-failed.description.without.reports':
    '⁣⁢We could not complete the migration.⁮⁭⁯⁯؜⁬⁭⁯⁯⁮⁭⁯⁪⁬‌⁭‍⁠⁭⁪⁫⁯⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.migration-failed.title':
    '⁣⁢Migration failed؜⁫⁬⁫⁪⁪⁮‌⁪⁬⁫⁬⁡⁪‌⁬؜⁫‍⁮⁬⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.migration-incomplete.cloud.description':
    '⁣⁢We could not migrate some data.⁠⁫⁭⁠⁯⁮‌‌⁡⁠⁫⁡⁪⁠⁯⁡⁡؜⁭⁠⁭⁫‍⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.migration-incomplete.description':
    '⁣⁢We could not migrate some data. Review the error log for more details.⁭‌‌⁪⁭⁯⁬⁮⁬⁮‌⁮⁠‌⁪⁭⁭⁪⁡‍⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.migration-incomplete.title':
    '⁣⁢Migration incomplete⁫⁡⁠⁫‍⁫؜⁪⁪⁭⁠⁪‌⁬⁭‍⁪‍⁫‌⁭⁫⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.migration-running.description':
    '⁣⁢The migration is currently in progress.‍⁠‌؜⁫‌⁠؜؜⁪⁮‌⁡⁯⁡⁭⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.migration-running.title':
    '⁣⁢Migration running⁫‍‌⁬⁠⁪⁭⁬‍؜⁯‌⁯‍⁪⁪؜⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.migration-stopped.description':
    "⁣⁢We've already migrated the data marked as complete. If you want to re-migrate them later, you'll need to delete them from your migration destination.⁪⁪⁡⁡⁮⁡⁪⁪⁯‍⁭‌⁬‍⁡⁭⁬⁡⁫⁪⁣⁤",
  'com.atlassian.migrations-platform.migration-details.migration-status.migration-stopped.title':
    '⁣⁢Migration stopped⁭؜؜⁮⁮⁬⁮‌⁯⁬⁠⁠⁫⁫⁫‌؜⁭⁪⁠⁮⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.migration-stopping.description':
    '⁣⁢The migration is currently being stopped.‍‌؜⁫⁠؜⁬؜⁮⁭⁡‌⁫⁯⁫⁮⁭⁠⁮⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.migration-stopping.title':
    '⁣⁢Stopping migration⁬⁮⁪⁪⁪⁭⁡⁭⁪⁯⁯‍⁡⁫‌⁭⁡‍⁠‌⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.migration-validating.description':
    '⁣⁢We are still checking some of your data.؜؜⁠⁫⁭⁬⁭⁡⁡؜⁮⁮⁪⁫‌⁪⁡⁭⁮⁬⁡⁫⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.migration-validating.title':
    '⁣⁢Checking your migration⁡⁬‍⁯‌‍⁡⁮‌⁮⁡⁠⁭⁬⁬⁡⁫؜⁫⁭⁣⁤',
  'com.atlassian.migrations-platform.migration-details.migration-status.status-message.refresh':
    '⁣⁢Refresh⁮⁮⁡‍⁭‌⁬⁫⁪⁬⁭⁮⁠⁭⁪⁠⁠‌⁫⁬‍⁠⁣⁤',
  'com.atlassian.migrations-platform.migration-details.select-all-customers-button.text':
    '⁣⁢Select all customers⁮‌⁭‌⁫⁫⁭⁮⁡⁯⁭⁠⁯⁭‍⁪⁠‌⁮‍⁡⁯‍⁣⁤',
  'com.atlassian.migrations-platform.migration-details.skip-all-customers-button.text':
    '⁣⁢Skip all customers؜‌⁭⁪⁠⁠⁫⁪‍‌⁡⁬؜‌⁬⁪‍⁫⁭⁭‍⁣⁤',
  'com.atlassian.migrations-platform.migration-details.status.anonymous-access-content.containers':
    '⁣⁢Data will be available to the public‍⁭؜⁡⁯‍‍⁡⁭⁮؜؜‍⁠؜⁮‌⁫⁭⁭⁯⁭⁫⁣⁤',
  'com.atlassian.migrations-platform.migration-details.status.anonymous-access-content.projects':
    '⁣⁢Projects and data will be available to the public‍⁬؜⁮‌⁬⁫⁠⁠؜⁯⁮⁮⁪⁬‌⁮⁬⁭⁣⁤',
  'com.atlassian.migrations-platform.migration-details.status.estimated-time-content.estimated-time-at-16-mbps':
    '⁣⁢(estimated time at 16 Mbps)⁡⁬⁫⁠‍⁠⁪⁫‌⁮؜‌؜⁡⁮⁡؜⁠⁮⁬‍⁣⁤',
  'com.atlassian.migrations-platform.migration-details.status.estimated-time-content.five-to-ten-minutes':
    '⁣⁢5 - 10 min‍⁪⁭⁬⁫⁠⁯؜؜⁮⁡⁠⁭⁠⁠‌⁡⁠‌⁡⁭⁬⁬‍⁣⁤',
  'com.atlassian.migrations-platform.migration-details.status.estimated-time-content.five-to-twelve-hours':
    '⁣⁢5 - 12 h⁠؜‍⁬⁪⁠⁬⁯⁡؜⁭⁫⁮⁡⁯⁪⁯؜⁫‌⁮⁯⁣⁤',
  'com.atlassian.migrations-platform.migration-details.status.estimated-time-content.half-day-to-a-day':
    '⁣⁢12 h - 1 d⁮؜⁠⁫؜⁡؜⁪⁭؜⁫‍‍⁠⁫‌⁫؜؜⁭⁫‌⁮‍⁪⁣⁤',
  'com.atlassian.migrations-platform.migration-details.status.estimated-time-content.half-hour-to-an-hour':
    '⁣⁢30 min - 1 h‌؜‍⁭⁯‌⁡⁡⁫⁪⁫⁮⁠‍⁭⁫⁯⁫⁣⁤',
  'com.atlassian.migrations-platform.migration-details.status.estimated-time-content.less-than-a-minute':
    '⁣⁢0 min⁠⁫⁫⁡؜⁪⁭⁯⁭⁡⁡⁯⁭⁭⁡‍؜⁫؜⁠⁮⁬⁫‍⁣⁤',
  'com.atlassian.migrations-platform.migration-details.status.estimated-time-content.more-than-a-week':
    '⁣⁢~ 1 w⁠‍‌⁯⁡⁯⁮⁮⁮⁡⁬⁮⁠⁯⁠⁮؜⁭؜⁫⁣⁤',
  'com.atlassian.migrations-platform.migration-details.status.estimated-time-content.not-available':
    '⁣⁢No estimate available⁡⁡⁬⁬‌؜⁬⁫‍؜‍⁬؜⁮⁡⁠⁡⁬⁯‍⁯⁬⁠⁮⁪⁯⁣⁤',
  'com.atlassian.migrations-platform.migration-details.status.estimated-time-content.one-to-five-minutes':
    '⁣⁢1 - 5 min⁫⁭⁠؜⁯⁬⁪⁪⁬‌⁮⁫⁠⁪⁬؜؜⁫⁬⁣⁤',
  'com.atlassian.migrations-platform.migration-details.status.estimated-time-content.one-to-two-days':
    '⁣⁢1 - 2 d⁭⁯⁬‌‌‌⁫؜‌⁡⁮⁯⁫⁠‌⁬؜؜⁫⁬⁣⁤',
  'com.atlassian.migrations-platform.migration-details.status.estimated-time-content.one-to-two-hours':
    '⁣⁢1 - 2 h⁬⁮⁪‍⁫⁪⁬⁠⁭؜⁪‌⁮⁬⁫⁪⁮⁯⁫⁬⁠؜⁪⁯⁬⁣⁤',
  'com.atlassian.migrations-platform.migration-details.status.estimated-time-content.ten-to-thirty-minutes':
    '⁣⁢10 - 30 min؜⁪⁯؜⁬⁯⁬⁮⁯‍⁫⁮⁯⁬‌⁫‌⁮؜⁫⁫⁪⁣⁤',
  'com.atlassian.migrations-platform.migration-details.status.estimated-time-content.two-to-five-days':
    '⁣⁢2 - 5 d⁠⁡⁫⁪⁬⁯⁯⁠⁪‌⁠⁡‍⁠⁠⁭‍⁭⁪⁬⁡⁭؜⁫⁣⁤',
  'com.atlassian.migrations-platform.migration-details.status.estimated-time-content.two-to-five-hours':
    '⁣⁢2 - 5 h⁭⁠⁡⁡⁠⁮⁮⁡⁯‍⁫⁪⁫⁫‌؜⁠‍‍⁯⁣⁤',
  'com.atlassian.migrations-platform.migration-details.task-card.edit-button':
    '⁣⁢Edit⁫‍⁮⁫⁬⁠⁫⁯‌⁭⁡‍⁫⁯⁫؜⁯⁠⁮⁯⁮⁠⁬؜⁪‍⁠⁣⁤',
  'com.atlassian.migrations-platform.migration-details.task-card.select-button':
    '⁣⁢Select⁫‍؜‌⁮؜⁬⁪⁡‌⁫‍؜‌⁫‍‍‌‍⁬⁫⁠⁫⁪⁣⁤',
  'com.atlassian.migrations-platform.migration-details.task-card.skip-button':
    '⁣⁢Skip {lowerCaseTaskName}⁠⁫⁫؜⁬‍؜‌⁬⁪⁪⁬⁠⁫⁭‌⁪⁬⁯؜⁠⁪⁠⁣⁤',
  'com.atlassian.migrations-platform.migration-details.task-card.status-indicator-error-icon-label':
    '⁣⁢Error⁫⁪⁫⁬⁭⁬⁭⁪⁬‍⁪⁮؜⁪‌؜؜⁫⁫⁣⁤',
  'com.atlassian.migrations-platform.migration-details.task-card.status-indicator-not-selected-icon-label':
    '⁣⁢Not completed‌⁡⁭⁪⁮⁠‍⁬‌⁮⁠⁡⁭⁫‍⁪؜؜⁬⁣⁤',
  'com.atlassian.migrations-platform.migration-details.task-card.status-indicator-selected-icon-label':
    '⁣⁢Completed⁯‌⁫⁬⁬⁡⁡⁫⁭⁯⁠⁯⁪؜‌؜⁡⁯⁫‍⁣⁤',
  'com.atlassian.migrations-platform.migration-details.task-list-errors.attachments-only-error-description':
    '⁣⁢Since you are migrating attachments only for selected projects, you can’t migrate some of the items below. Either skip those items or change your Attachments only selection.⁯⁭؜⁭⁬⁫⁯؜⁠⁪⁭⁯⁠⁮⁬⁪⁡⁡⁡⁭⁯⁮؜‌‌⁪⁠⁣⁤',
  'com.atlassian.migrations-platform.migration-details.task-list-errors.config-only-error-description':
    '⁣⁢Since you are migrating configuration only for selected projects, you can’t migrate some of the items below. Either skip those items or change your Configuration only selection.⁬⁪⁫⁬⁫⁮⁪‌⁪‍⁠⁫⁠⁡‍⁬‍‍⁠⁣⁤',
  'com.atlassian.migrations-platform.migration-details.task-list-errors.invalid-selection-error-title':
    '⁣⁢Invalid selection⁯⁪⁯⁬⁡⁬⁭⁮‍‌⁠⁫‍⁯⁯‍‌‌‍⁬⁮⁫⁣⁤',
  'com.atlassian.migrations-platform.migration-details.task-list-errors.skip-projects-but-referenced-users-groups-error-description':
    '⁣⁢Since you haven’t selected any projects, you can’t migrate users and groups related to those projects. Either add projects to your migration or select all users and groups.⁯⁡⁠⁯⁡⁡؜⁮‍‌⁭⁪⁡‌⁮‌⁡⁬⁯⁣⁤',
  'com.atlassian.migrations-platform.migration-details.task-list-errors.skip-projects-but-referenced-users-groups-error-title':
    '⁣⁢Invalid users and groups selection⁬⁯⁮؜⁬؜⁫؜⁬⁪⁮⁡؜‍⁡⁬⁫⁡‌⁯⁯⁮⁣⁤',
  'com.atlassian.migrations-platform.migration-details.task-list-errors.skip-projects-referenced-customers-error-description':
    '⁣⁢Since you haven’t selected any projects, you can’t migrate customers related to those projects. You must add projects to your migration or select all or no customers.⁠⁮⁡⁯⁬⁭⁡⁫‌⁠⁫⁭⁠‌⁯⁯⁯⁪⁮⁬⁣⁤',
  'com.atlassian.migrations-platform.migration-details.task-list-errors.skip-projects-referenced-customers-error-title':
    '⁣⁢Invalid customer selection⁠⁠⁯⁪⁡⁫؜⁫⁯؜⁭⁭؜⁯⁫⁭؜⁮‍⁠⁠⁯⁮؜⁫⁯⁣⁤',
  'com.atlassian.migrations-platform.migration-details.task-list-errors.skip-projects-referenced-users-groups-customers-error-description':
    '⁣⁢Since you haven’t selected any projects, you can’t migrate related users and groups or customers. Either add projects to your migration or change your selections.⁡⁮⁮⁯⁭⁬؜‍⁡⁬؜‌⁪؜⁡⁯؜⁡‍⁫⁡‌‌⁡⁬‍⁣⁤',
  'com.atlassian.migrations-platform.migration-details.task-list-errors.skip-projects-referenced-users-groups-customers-error-title':
    '⁣⁢Invalid selection‌⁫⁭‌‍‍‍‍⁯⁠⁫⁡⁮⁯⁭‌⁭‌⁮⁫⁣⁤',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.all-users-and-groups':
    '⁣⁢All users and groups from the Jira directory‍⁯⁠‌⁡⁯⁮؜⁫⁠⁯‍⁪⁠⁡⁯⁮⁫⁮⁬⁫⁬‍⁣⁤',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.attachments-only-disabled-description':
    '⁣⁢Since only project attachments are selected, no users, groups, or group membership can be migrated.‍‌⁪⁡⁠؜؜⁭⁡⁫⁮⁠⁯؜⁪⁪‍⁮⁯⁬⁭⁣⁤',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.include-role-actors':
    '⁣⁢All users and groups assigned to required roles.⁮⁠⁠⁠⁭؜⁪⁮⁯‌⁬؜⁮⁯⁮؜⁡⁠⁮⁪⁫⁣⁤',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.include-users-in-groups':
    '⁣⁢Any user that is a member of a group in this migration.⁠⁯⁠⁭⁯‍⁯⁡⁫⁫⁪⁭⁭⁪⁭؜؜⁡؜⁮⁠⁭⁡⁭⁣⁤',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.migrate-users-groups-separately-description':
    '⁣⁢Users will not be given project permissions and will not be added to your license.‌‌⁯⁮⁭⁪⁡⁯⁭⁫⁠⁮⁮⁠‌⁮‌⁬⁯‌⁯⁣⁤',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.migrate-users-groups-separately-title':
    '⁣⁢Migrate users and groups separately⁬⁮؜⁠‌‍‌⁪؜‌‍⁯‌⁯⁮⁪⁠⁭‌⁮⁠⁣⁤',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.no-selection-text':
    '⁣⁢No users, groups, or group membership selected⁬‌⁫‌⁫⁪⁡‍⁠⁡⁮⁡‍؜⁮⁯⁣⁤',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.preserver-group-membership-description':
    '⁣⁢Users will get product access and will be added to your cloud license.‌⁡⁮⁪‌⁭⁯؜⁭⁯⁠⁬⁭‌⁪⁮⁯⁠⁪⁫⁮⁮⁯⁣⁤',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.preserver-group-membership-title':
    '⁣⁢Preserve group memberships‍‌⁪⁯⁪⁭⁭⁠⁡⁬⁭⁭؜⁫⁭⁠⁭؜⁠⁭⁫⁮‌⁠‌⁣⁤',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.referenced-users-and-groups-with-options':
    '⁣⁢Users and groups referenced in projects.⁯‍⁭‍⁯⁬⁡⁭⁠⁭⁬؜⁮⁮‌⁫‍‍؜⁪‍⁫⁣⁤',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.refrenced-users-and-groups-minimum':
    '⁣⁢Users and groups referenced in projects.⁮‌‍⁭⁭⁪⁡⁬⁭⁡⁮⁮⁡⁬‌⁬‍؜⁡⁠⁡⁮⁠⁮⁭⁣⁤',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.refrenced-users-and-groups-title':
    '⁣⁢Only users and groups related to selected projects⁬‌⁫⁮؜‌⁭⁮⁠⁡⁬⁬⁠⁯‌⁫‍⁡⁪⁯⁭⁣⁤',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.select-all-users-and-groups-button-text':
    '⁣⁢Select all users and groups؜⁫⁡⁠‌⁯⁯⁭⁠؜⁮⁭⁮؜‌⁮؜⁡⁭‌؜⁫⁬⁭⁣⁤',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.skip-all-users-and-groups-button-text':
    '⁣⁢Skip all users and groups⁪⁯⁯⁭⁭⁬⁭⁫⁭⁡⁠⁭‍⁯⁡⁭⁡⁪⁭⁠‍⁡⁡⁬⁣⁤',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.task-name':
    '⁣⁢Users and groups⁪‌‍⁮؜؜⁮⁯⁫⁭‌‍⁠⁠⁮‌‌⁪⁭⁣⁤',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.users-and-groups-counts':
    '⁣⁢Currently, {usersCount} users and {groupsCount} groups.‌⁠⁯⁪‍⁡⁭‍⁫⁪⁪⁬⁮‌⁬⁭‌⁪⁭‌⁣⁤',
};
