/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// French
export default {
  'com.atlassian.migrations-platform.migration-details.advanced-roadmaps-task-card.attachments-only-disabled-text':
    "Étant donné que vous avez sélectionné l'option Pièces jointes de projet uniquement, vous ne pouvez migrer aucun plan.",
  'com.atlassian.migrations-platform.migration-details.advanced-roadmaps-task-card.config-only-disabled-text':
    "Étant donné que vous avez sélectionné l'option Configuration du projet uniquement, vous ne pouvez migrer aucun plan.",
  'com.atlassian.migrations-platform.migration-details.advanced-roadmaps-task-card.fix-error-button-text':
    'Ignorer les plans',
  'com.atlassian.migrations-platform.migration-details.advanced-roadmaps-task-card.no-selection-text':
    'Aucun plan sélectionné',
  'com.atlassian.migrations-platform.migration-details.advanced-roadmaps-task-card.not-migrating-text':
    "Vous n'avez sélectionné aucun plan.",
  'com.atlassian.migrations-platform.migration-details.advanced-roadmaps-task-card.plans-count-description':
    'Inclut toutes les sources de ticket et entités associées',
  'com.atlassian.migrations-platform.migration-details.advanced-roadmaps-task-card.plans-count-title':
    '{count, plural, one {{count} plan} other {{count} plans}}',
  'com.atlassian.migrations-platform.migration-details.advanced-roadmaps-task-card.skip-button-text':
    'Ignorer les plans',
  'com.atlassian.migrations-platform.migration-details.advanced-roadmaps-task-card.task-name':
    'Plans Advanced Roadmaps',
  'com.atlassian.migrations-platform.migration-details.app-migrations-task-card.apps-count-description':
    "Toutes les apps marquées comme « Nécessaires dans le cloud » et disposant d'un parcours de migration.",
  'com.atlassian.migrations-platform.migration-details.app-migrations-task-card.apps-count-title':
    '{count, plural, one {{count} app} other {{count} apps}}',
  'com.atlassian.migrations-platform.migration-details.app-migrations-task-card.no-selection-text':
    'Aucune app sélectionnée',
  'com.atlassian.migrations-platform.migration-details.app-migrations-task-card.not-selected':
    'Aucune app à migrer',
  'com.atlassian.migrations-platform.migration-details.app-migrations-task-card.task-name':
    'Apps',
  'com.atlassian.migrations-platform.migration-details.configuration.group-membership-content.migrate-separately':
    "Les utilisateurs et les groupes seront migrés séparément. Les utilisateurs ne recevront pas d'autorisations de projet et ne seront pas ajoutés à votre licence.",
  'com.atlassian.migrations-platform.migration-details.configuration.group-membership-content.preserve':
    'Les adhésions aux groupes seront conservées. Les utilisateurs auront accès au produit et seront ajoutés à votre licence Cloud.',
  'com.atlassian.migrations-platform.migration-details.configuration.users-and-groups-content.all-users-and-groups':
    "Vous avez choisi de migrer tous les utilisateurs et groupes à partir de l'annuaire Jira",
  'com.atlassian.migrations-platform.migration-details.configuration.users-and-groups-content.include-role-actors':
    'Tous les utilisateurs et groupes assignés à des rôles',
  'com.atlassian.migrations-platform.migration-details.configuration.users-and-groups-content.include-users-in-groups':
    "Tout utilisateur membre d'un groupe associé",
  'com.atlassian.migrations-platform.migration-details.configuration.users-and-groups-content.referenced-users-and-groups':
    'Utilisateurs et groupes associés aux projets sélectionnés.',
  'com.atlassian.migrations-platform.migration-details.configuration.users-and-groups-content.referenced-users-and-groups-options':
    'Utilisateurs et groupes associés aux projets sélectionnés. Plus :',
  'com.atlassian.migrations-platform.migration-details.customers-task-card.all-customers.title':
    "Tous les clients à partir de l'annuaire Jira",
  'com.atlassian.migrations-platform.migration-details.customers-task-card.no-customers.description':
    "Vous n'avez sélectionné aucun client.",
  'com.atlassian.migrations-platform.migration-details.customers-task-card.no-selection-text':
    'Aucun client sélectionné',
  'com.atlassian.migrations-platform.migration-details.customers-task-card.referenced-project-customers.description':
    'Inclut tout client qui a créé une demande ou qui est référencé dans une demande.',
  'com.atlassian.migrations-platform.migration-details.customers-task-card.referenced-project-customers.title':
    'Uniquement les clients liés aux projets sélectionnés',
  'com.atlassian.migrations-platform.migration-details.customers-task-card.task-name':
    'Clients',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.cloud-plan-content.cloud-plan':
    'Offre {productName} {productEdition}',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.configuration-caption':
    'Configuration',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.destination-cloud-plan-header':
    '{count, plural, one {Offre Cloud} other {Offres Cloud}}',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.destination-url-header':
    'Destination',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.group-membership-header':
    'Adhésions aux groupes',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.migration-name-header':
    'Nom de la migration',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.project-configuration-content.all':
    '{numberOfProjectsString}, {numberOfIssuesString} et {attachmentsBytesSizeString} de pièces jointes.',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.project-configuration-content.attachments-only':
    '{numberOfProjectsString} : pièces jointes uniquement ({attachmentsBytesSizeString})',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.project-configuration-content.config-only':
    '{numberOfProjectsString} : configuration uniquement',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.project-configuration-content.issues-count-string':
    '{count, plural, one {{count} ticket} other {{count} tickets}}',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.project-configuration-content.projects-count-string':
    '{count, plural, one {{count} projet} other {{count} projets}}',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.projects-header':
    'Projets',
  'com.atlassian.migrations-platform.migration-details.jira-migration-configuration.users-and-groups-header':
    'Utilisateurs et groupes',
  'com.atlassian.migrations-platform.migration-details.jira-migration-tasklist.back-button':
    'Retour',
  'com.atlassian.migrations-platform.migration-details.jira-migration-tasklist.check-for-errors-button':
    'Rechercher des erreurs',
  'com.atlassian.migrations-platform.migration-details.migration-status.current-checks-status-blocking-execution-error.title':
    'Afficher les avertissements',
  'com.atlassian.migrations-platform.migration-details.migration-status.current-checks-status-error.title':
    'Afficher les erreurs et les avertissements',
  'com.atlassian.migrations-platform.migration-details.migration-status.current-checks-status-execution-error.title':
    'Afficher les avertissements',
  'com.atlassian.migrations-platform.migration-details.migration-status.current-checks-status-running.title':
    "En cours d'exécution",
  'com.atlassian.migrations-platform.migration-details.migration-status.current-checks-status-success.title':
    'Aucun avertissement et aucune erreur',
  'com.atlassian.migrations-platform.migration-details.migration-status.current-checks-status-warning.title':
    'Afficher les avertissements',
  'com.atlassian.migrations-platform.migration-details.migration-status.status-message.refresh':
    'Actualiser',
  'com.atlassian.migrations-platform.migration-details.select-all-customers-button.text':
    'Sélectionner tous les clients',
  'com.atlassian.migrations-platform.migration-details.skip-all-customers-button.text':
    'Ignorer tous les clients',
  'com.atlassian.migrations-platform.migration-details.status.anonymous-access-content.containers':
    'Les données seront disponibles au public',
  'com.atlassian.migrations-platform.migration-details.status.anonymous-access-content.projects':
    'Les projets et les données seront disponibles au public',
  'com.atlassian.migrations-platform.migration-details.task-card.edit-button':
    'Modifier',
  'com.atlassian.migrations-platform.migration-details.task-card.select-button':
    'Sélectionner',
  'com.atlassian.migrations-platform.migration-details.task-card.skip-button':
    'Ignorer {lowerCaseTaskName}',
  'com.atlassian.migrations-platform.migration-details.task-card.status-indicator-not-selected-icon-label':
    'Non terminé',
  'com.atlassian.migrations-platform.migration-details.task-card.status-indicator-selected-icon-label':
    'Terminé',
  'com.atlassian.migrations-platform.migration-details.task-list-errors.attachments-only-error-description':
    'Étant donné que vous migrez les pièces jointes uniquement pour les projets sélectionnés, vous ne pouvez pas migrer certains des éléments ci-dessous. Ignorez ces éléments ou sélectionnez une autre option que Pièces jointes uniquement.',
  'com.atlassian.migrations-platform.migration-details.task-list-errors.config-only-error-description':
    'Étant donné que vous migrez la configuration uniquement pour les projets sélectionnés, vous ne pouvez pas migrer certains des éléments ci-dessous. Ignorez ces éléments ou sélectionnez une autre option que Configuration uniquement.',
  'com.atlassian.migrations-platform.migration-details.task-list-errors.invalid-selection-error-title':
    'Sélection non valide',
  'com.atlassian.migrations-platform.migration-details.task-list-errors.skip-projects-but-referenced-users-groups-error-description':
    "Puisque vous n'avez sélectionné aucun projet, vous ne pouvez pas migrer les utilisateurs et groupes associés. Ajoutez des projets à votre migration ou sélectionnez tous les utilisateurs et groupes.",
  'com.atlassian.migrations-platform.migration-details.task-list-errors.skip-projects-but-referenced-users-groups-error-title':
    "Sélection d'utilisateurs et de groupes non valide",
  'com.atlassian.migrations-platform.migration-details.task-list-errors.skip-projects-referenced-customers-error-description':
    "Puisque vous n'avez sélectionné aucun projet, vous ne pouvez pas migrer les clients associés à ces projets. Vous devez ajouter des projets à votre migration ou sélectionner tous les clients ou aucun client.",
  'com.atlassian.migrations-platform.migration-details.task-list-errors.skip-projects-referenced-customers-error-title':
    'Sélection de client non valide',
  'com.atlassian.migrations-platform.migration-details.task-list-errors.skip-projects-referenced-users-groups-customers-error-description':
    "Puisque vous n'avez sélectionné aucun projet, vous ne pouvez pas migrer les utilisateurs et groupes ou clients associés. Ajoutez des projets à votre migration ou modifiez vos sélections.",
  'com.atlassian.migrations-platform.migration-details.task-list-errors.skip-projects-referenced-users-groups-customers-error-title':
    'Sélection non valide',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.all-users-and-groups':
    "Tous les utilisateurs et groupes à partir de l'annuaire Jira",
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.attachments-only-disabled-description':
    "Étant donné que vous avez sélectionné l'option Pièces jointes de projet uniquement, vous ne pouvez migrer aucun utilisateur, aucun groupe ou aucune adhésion de groupe.",
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.include-role-actors':
    'Tous les utilisateurs et groupes assignés aux rôles requis.',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.include-users-in-groups':
    "Tout utilisateur membre d'un groupe dans cette migration.",
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.migrate-users-groups-separately-description':
    "Les utilisateurs ne recevront pas d'autorisations de projet et ne seront pas ajoutés à votre licence.",
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.migrate-users-groups-separately-title':
    'Migrer les utilisateurs et les groupes séparément',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.no-selection-text':
    'Aucun utilisateur, aucun groupe ou aucune adhésion au groupe sélectionné(e)',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.preserver-group-membership-description':
    'Les utilisateurs auront accès au produit et seront ajoutés à votre licence Cloud.',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.preserver-group-membership-title':
    'Conserver les adhésions au groupe',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.referenced-users-and-groups-with-options':
    'Utilisateurs et groupes référencés dans les projets.',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.refrenced-users-and-groups-minimum':
    'Utilisateurs et groupes référencés dans les projets.',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.refrenced-users-and-groups-title':
    'Seuls les utilisateurs et les groupes associés aux projets sélectionnés',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.select-all-users-and-groups-button-text':
    'Sélectionner tous les utilisateurs et groupes',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.skip-all-users-and-groups-button-text':
    'Ignorer tous les utilisateurs et groupes',
  'com.atlassian.migrations-platform.migration-details.users-and-groups-task-card.task-name':
    'Utilisateurs et groupes',
};
