/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Danish
export default {
  'growth-experimental.project-pages.learn-more.banner':
    'Projektsider leveres af Confluence.',
  'growth-experimental.project-pages.learn-more.text': 'Læs mere',
  'project-pages.activating.description':
    'Det tilknyttede Confluence-område er ikke helt klar endnu. {contactSupport}, hvis problemet ikke løses ved at opdatere siden.',
  'project-pages.activating.heading': 'Confluence indlæses stadig',
  'project-pages.button.connect-different-space-or-page.label':
    'Opdater område eller sideikon',
  'project-pages.button.connect-different-space-or-page.tooltip':
    'Tilknyt et andet område eller en anden side',
  'project-pages.button.connect-space-or-page.tooltip':
    'Opret forbindelse til Confluence',
  'project-pages.button.go-to-connected-page.tooltip': 'Åbn side i Confluence',
  'project-pages.button.go-to-connected-space.tooltip':
    'Åbn område i Confluence',
  'project-pages.connect-space-dialog.connection-error':
    'Tilknytningen mislykkedes.',
  'project-pages.connect-space-dialog.connection-retry': 'Prøv igen',
  'project-pages.connect-space-dialog.content.create-space-link.link-text':
    'Opret nyt Confluence-område',
  'project-pages.connect-space-dialog.content.space-or-page-selector.description':
    'Vælg et område eller en side, som skal knyttes til dit projekt.',
  'project-pages.connect-space-dialog.content.space-or-page-selector.placeholder':
    'Søg i Confluence',
  'project-pages.connect-space-dialog.content.space-selector.description':
    'Vælg et område, som skal knyttes til dette projekt',
  'project-pages.connect-space-dialog.content.space-selector.disconnected-templates-description':
    'Dette projekt skal knyttes til et område, før du kan oprette en side. Vælg et område, som skal knyttes til dette projekt.',
  'project-pages.connect-space-dialog.content.space-selector.placeholder':
    'Vælg et område',
  'project-pages.connect-space-dialog.error-icon': 'Fejl:',
  'project-pages.connect-space-dialog.footer.cancel': 'Annuller',
  'project-pages.connect-space-dialog.footer.connect-space': 'Forbind',
  'project-pages.connect-space-dialog.header.title':
    'Tilknyt et Confluence-område',
  'project-pages.connect-space-or-page-dialog.header.title':
    'Knyt projekt til Confluence',
  'project-pages.connect-space.button': 'Tilknyt et område',
  'project-pages.connect-space.description':
    'Områder er ligesom mapper – du kan bruge dem til at oprette, organisere og samarbejde om al indholdet, der vedrører projektet.',
  'project-pages.connect-space.heading':
    'Knyt dette projekt til et Confluence-område',
  'project-pages.create-space-dialog.connection-error':
    'Tilknytningen mislykkedes.',
  'project-pages.create-space-dialog.connection-retry': 'Prøv igen',
  'project-pages.create-space-dialog.content.empty-name':
    'Giv dit område et navn.',
  'project-pages.create-space-dialog.content.invalid-name':
    'Områdenavne skal have mindst ét bogstav eller tal.',
  'project-pages.create-space-dialog.content.placeholder':
    'Indtast et områdenavn',
  'project-pages.create-space-dialog.creation-error':
    'Det lykkedes ikke at oprette området.',
  'project-pages.create-space-dialog.error-icon': 'Fejl:',
  'project-pages.create-space-dialog.footer.cancel': 'Annuller',
  'project-pages.create-space-dialog.footer.create-space': 'Opret',
  'project-pages.create-space-dialog.header.title':
    'Opret nyt Confluence-område',
  'project-pages.cross-join.access-revoked.templates.subtitle':
    'Du kan ikke bruge projektsider, fordi administratoren ikke har givet dig adgang til Confluence. Kontakt administratoren for dit websted for at anmode om adgang.',
  'project-pages.cross-join.access-revoked.templates.title':
    'Du har ikke tilladelse til at bruge projektsider',
  'project-pages.cross-join.avatar.view-profile': 'Se profil',
  'project-pages.cross-join.denied-request.templates.subtitle':
    'Du kan ikke bruge projektsider, fordi administratoren for webstedet har afvist din anmodning om at få adgang til Confluence.',
  'project-pages.cross-join.denied-request.templates.title':
    'Din administrator har afvist at give dig adgang',
  'project-pages.cross-join.errors.unknown-error.description':
    '{contactSupport}, hvis det ikke hjælper at opdatere.',
  'project-pages.cross-join.errors.unknown-error.title':
    'Vi kan ikke vise projektsider lige nu',
  'project-pages.cross-join.join-product.button': 'Tilmeld dig Confluence',
  'project-pages.cross-join.join-product.connected.description':
    'Dit team bruger allerede Confluence til at samarbejde på projektsider. Webstedsadministratoren har allerede givet dig adgang til at samarbejde med dem.',
  'project-pages.cross-join.join-product.connected.title':
    'Tilmeld dig Confluence for at få adgang til dit teams projektsider',
  'project-pages.cross-join.join-product.not-connected.description':
    'Projektsider hjælper med at indsamle dit teams viden og holde indhold samlet på ét sted. Din webstedsadministrator har allerede givet dig adgang.',
  'project-pages.cross-join.join-product.not-connected.title':
    'Tilmeld dig Confluence for at begynde at bruge projektsider',
  'project-pages.cross-join.join-product.templates.subtitle':
    'GIVER DIG ADGANG TIL CONFLUENCE',
  'project-pages.cross-join.join-product.templates.tooltip':
    'Opret denne side i Confluence',
  'project-pages.cross-join.pending-request.templates.subtitle':
    'Webstedsadministratoren har modtaget din anmodning om adgang til Confluence. Hvis din anmodning bliver godkendt, begynder projektsider at fungere, og vi sender dig en e-mail med bekræftelse.',
  'project-pages.cross-join.pending-request.templates.title':
    'Du har anmodet om adgang til Confluence',
  'project-pages.cross-join.request-access.button': 'Anmod om adgang',
  'project-pages.cross-join.request-access.connected.description':
    'Dit team bruger allerede Confluence til at samarbejde på projektsider. Anmod om adgang for at samarbejde med dem.',
  'project-pages.cross-join.request-access.not-connected.description':
    'Brug projektsider til at indsamle dit teams viden og holde indhold samlet på ét sted. Anmod om adgang til Confluence for at komme i gang.',
  'project-pages.cross-join.request-access.templates.subtitle':
    'ANMODER OM ADGANG TIL CONFLUENCE',
  'project-pages.cross-join.request-access.templates.tooltip':
    'Anmoder om adgang til Confluence',
  'project-pages.cross-join.request-access.title':
    'Projektsider kræver adgang til Confluence',
  'project-pages.default-contextual-heading':
    'Projektsider er drevet af Confluence',
  'project-pages.default-contextual-message':
    'Opret, del og samarbejd om alle dine projektdokumenter på ét sted med Confluence-sider.',
  'project-pages.default-reactivate-CTA': 'Genaktiver Confluence',
  'project-pages.default-trial-CTA': 'Prøv Confluence gratis i 30 dage',
  'project-pages.draft-saved-flag.action': 'Åbn udkast',
  'project-pages.draft-saved-flag.description':
    'Dit udkast er kun synligt for dig, indtil du udgiver det.',
  'project-pages.draft-saved-flag.title': 'Udkastet blev gemt',
  'project-pages.embedded-pages.create-page-error.close-button': 'Luk',
  'project-pages.embedded-pages.create-page-error.description':
    'Der opstod et problem, og vi kunne ikke oprette en side til dig.',
  'project-pages.embedded-pages.create-page-error.title':
    'Vi kunne ikke oprette en side',
  'project-pages.embedded-pages.create-page-error.try-again-button':
    'Prøv igen',
  'project-pages.embedded-pages.modal.close.button.hint': 'Luk',
  'project-pages.embedded-pages.modal.title.button': 'Åbn i Confluence',
  'project-pages.embedded-pages.modal.title.button.hint': 'Åbn i en ny fane',
  'project-pages.generic-error.button.reload': 'Genindlæs siden',
  'project-pages.generic-error.description':
    'Noget gik galt. Prøv igen senere.',
  'project-pages.generic-error.heading': 'Uh, det var akavet ...',
  'project-pages.generic-success-flag.description.page':
    'Tilknytningen til {connectedSpaceOrPageName}-siden blev oprettet.',
  'project-pages.generic-success-flag.description.space':
    'Tilknytningen til {connectedSpaceOrPageName}-området blev oprettet.',
  'project-pages.generic-success-flag.heading.page': 'Siden blev tilknyttet',
  'project-pages.generic-success-flag.heading.space': 'Område blev tilknyttet',
  'project-pages.granular-pages.connect-space-dialog.content.create-space-link.link-text':
    'Eller opret et nyt område',
  'project-pages.granular-pages.connect-space.button':
    'Opret forbindelse til Confluence',
  'project-pages.granular-pages.connect-space.heading':
    'Knyt dette projekt til et Confluence-område eller en Confluence-side',
  'project-pages.improvement.contact-support': 'Kontakt support',
  'project-pages.improvement.errors.access-error.description':
    'Prøv at kontakte sideadministratoren for at få adgang.',
  'project-pages.improvement.errors.access-error.title':
    'Du har ikke tilladelse til at få vist projektsider',
  'project-pages.improvement.errors.page-tree-unknown-error.description':
    'Noget gik galt under forsøget på at vise sider fra dit tilknyttede Confluence-område. {contactSupport}, hvis problemet ikke løses ved at opdatere siden.',
  'project-pages.improvement.errors.page-tree-unknown-error.title':
    'Vi har problemer med at vise projektsider',
  'project-pages.improvement.errors.space-not-found.button':
    'Tilknyt et andet område',
  'project-pages.improvement.errors.space-not-found.description':
    'Confluence-området, der var knyttet til projektsider, er slettet eller flyttet.',
  'project-pages.improvement.errors.space-not-found.title':
    'Området blev ikke fundet',
  'project-pages.improvement.errors.unknown-error.description':
    '{contactSupport}, hvis problemet ikke løses ved at opdatere siden.',
  'project-pages.improvement.errors.unknown-error.title':
    'Vi kan ikke vise projektsider lige nu',
  'project-pages.improvement.heading-info':
    'Registrer dit teams viden, og forbedr den måde, hvorpå I får arbejdet fra hånden.',
  'project-pages.improvement.learn-more-button': 'Læs mere',
  'project-pages.improvement.powered-by': 'Drevet af',
  'project-pages.improvement.powered-by.tooltip':
    'Åbn Confluence på en ny fane',
  'project-pages.improvement.preview-teaser':
    'Lås op for skabeloner, projektsider m.m.',
  'project-pages.improvement.templates.blank-page.description':
    'Start en side fra bunden.',
  'project-pages.improvement.templates.blank-page.name': 'Tom side',
  'project-pages.improvement.templates.decision.description':
    'Registrer vigtige projektbeslutninger, og drøft dem med dit hold.',
  'project-pages.improvement.templates.decision.name': 'Beslutning',
  'project-pages.improvement.templates.meeting-notes.description':
    'Planlæg dine møder, og del notater og handlinger med dit team.',
  'project-pages.improvement.templates.meeting-notes.name': 'Mødenotater',
  'project-pages.improvement.templates.post-expand.more': 'Flere skabeloner',
  'project-pages.improvement.templates.post-expand.more.tooltip':
    'Vis alle skabeloner i Confluence',
  'project-pages.improvement.templates.post-expand.subtitle':
    'Populære skabeloner',
  'project-pages.improvement.templates.post-expand.title': 'Opret en side',
  'project-pages.improvement.templates.pre-expand.more': 'Se flere skabeloner',
  'project-pages.improvement.templates.pre-expand.subtitle':
    'Populære hos teams som dit',
  'project-pages.improvement.templates.pre-expand.title':
    'Forhåndsvisning af skabeloner',
  'project-pages.improvement.templates.product-requirements.description':
    'Definér, spor og undersøg kravene til dit produkt eller funktion.',
  'project-pages.improvement.templates.product-requirements.name':
    'Produktkrav',
  'project-pages.improvement.templates.retrospective.description':
    'Hvad gik godt? Hvad kunne være gået bedre? Crowdsource forbedringer med dit team.',
  'project-pages.improvement.templates.retrospective.name': 'Retrospektiv',
  'project-pages.improvement.templates.template.disabled-tooltip':
    'Tilknyt først et Confluence-område',
  'project-pages.improvement.templates.template.tooltip':
    'Opret denne side i Confluence',
  'project-pages.improvement.title': 'Projektsider',
  'project-pages.improvement.transient-states.empty-state.create-page-button':
    'Opret din første side',
  'project-pages.improvement.transient-states.empty-state.description':
    'Opret mødenoter, produktkrav, beslutninger eller andet indhold for at se området blive fyldt ud.',
  'project-pages.improvement.transient-states.empty-state.title':
    'Der er ikke andet end potentiale her',
  'project-pages.improvement.tree-empty-state.contributors': 'Bidragydere',
  'project-pages.improvement.tree-empty-state.last-modified': 'Sidst ændret',
  'project-pages.improvement.tree-empty-state.page-name': 'Navn',
  'project-pages.improvement.try-button': 'Prøv denne skabelon i Confluence',
  'project-pages.improvement.try-button.tooltip':
    'Starter en Confluence-prøveversion',
  'project-pages.improvement.try-lozenge': 'Prøv',
  'project-pages.menu.connect-different-space': 'Knyt til et andet område',
  'project-pages.menu.connect-space': 'Tilknyt et område',
  'project-pages.more-menu-button.label': 'Mere',
  'project-pages.page-deleted-flag.title': 'Siden blev slettet.',
  'project-pages.page-published-flag.title': 'Din side er blevet udgivet.',
  'project-pages.unknown-error.description':
    '{contactSupport}, hvis problemet ikke løses ved at opdatere siden.',
  'project-pages.unknown-error.heading':
    'Vi kan ikke vise projektsider lige nu',
};
