/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// English (Instrumented)
export default {
  'growth-experimental.project-pages.learn-more.banner':
    '⁣⁢Project pages is powered by Confluence.⁪⁡؜⁫⁭⁪‍‍⁮⁬⁬⁬‍⁪⁮⁯‌⁭⁠⁯⁯‌⁣⁤',
  'growth-experimental.project-pages.learn-more.text':
    '⁣⁢Learn more‍⁮‌⁫⁡⁯⁭⁬⁠⁯؜⁡⁯⁠⁪⁮⁯⁬⁭‌⁠‌⁯⁡⁣⁤',
  'project-pages.activating.description':
    '⁣⁢The connected Confuence space isn’t quite ready yet. {contactSupport} if refreshing doesn’t fix things.⁭⁬⁬⁪⁮⁠⁯‍‍؜؜⁪⁪‍‍‌⁬‍؜⁯⁣⁤',
  'project-pages.activating.heading':
    '⁣⁢Confluence is still loading⁡⁫⁯⁫‌‌⁪؜⁬⁬⁭؜؜؜⁠⁯⁪⁮⁮⁭⁭⁮⁬‌⁣⁤',
  'project-pages.button.connect-different-space-or-page.label':
    '⁣⁢Update space or page icon⁫⁮؜‌⁫⁭⁮⁭⁪⁪⁮⁮⁮⁭؜⁪⁮⁠⁡⁬⁠⁣⁤',
  'project-pages.button.connect-different-space-or-page.tooltip':
    '⁣⁢Connect different space or page⁬⁮⁫⁭‍⁠⁫⁬⁠⁭⁯⁬⁮⁪‌⁭⁭⁪‍؜⁬؜⁪⁠؜⁣⁤',
  'project-pages.button.connect-space-or-page.tooltip':
    '⁣⁢Connect to Confluence⁯⁠⁯⁡⁫⁪‌⁠⁪⁮⁫⁪⁬⁫⁡⁬‌⁬⁭‌⁭⁭⁬⁣⁤',
  'project-pages.button.go-to-connected-page.tooltip':
    '⁣⁢Open page in Confluence؜؜‌‌⁪⁪⁡⁮⁫⁪‍⁭⁯⁠؜⁫⁯⁫؜⁫⁮⁪⁬‍⁯⁯⁣⁤',
  'project-pages.button.go-to-connected-space.tooltip':
    '⁣⁢Open space in Confluence⁡‍‌⁪⁠‌‌⁠‌⁬‌⁡⁪⁮⁫‌⁪⁪‌⁣⁤',
  'project-pages.connect-space-dialog.connection-error':
    '⁣⁢Connection failed.⁠‌‌؜؜⁡⁯⁯؜⁫⁫⁪⁮⁯‍⁡⁭‌⁫⁯⁬⁣⁤',
  'project-pages.connect-space-dialog.connection-retry':
    '⁣⁢Retry⁬⁡⁮‌‌‌‍⁫⁭⁮⁯⁭⁪⁠⁪⁪⁬⁡⁠؜؜⁣⁤',
  'project-pages.connect-space-dialog.content.create-space-link.link-text':
    '⁣⁢Create new Confluence space⁪‌‍⁬⁮؜⁪⁬‍⁡‍‍⁯⁯⁭⁡⁬⁪⁫‍‌⁠⁣⁤',
  'project-pages.connect-space-dialog.content.space-or-page-selector.description':
    '⁣⁢Choose a space or page to connect to your project.⁮⁠‍⁯⁡؜⁬⁬⁮‍⁡⁭⁫‍⁫⁬⁣⁤',
  'project-pages.connect-space-dialog.content.space-or-page-selector.placeholder':
    '⁣⁢Search Confluence‌⁪⁠⁭⁬⁠‌⁫⁠⁪⁬⁬⁭⁪⁬⁠⁡‍⁬⁭⁪⁫⁣⁤',
  'project-pages.connect-space-dialog.content.space-selector.description':
    '⁣⁢Choose a space to connect to this project⁯⁫⁮‌⁯⁬⁭⁫‌⁡⁯⁡‌⁡⁬⁮⁡‍⁯⁡‌⁫⁣⁤',
  'project-pages.connect-space-dialog.content.space-selector.disconnected-templates-description':
    '⁣⁢This project needs to be connected to a space before you can create a page. Choose a space to connect to this project.‍؜؜⁠⁪⁭⁪⁭⁡‍؜⁬؜⁪‌⁪⁫⁪⁣⁤',
  'project-pages.connect-space-dialog.content.space-selector.placeholder':
    '⁣⁢Select a space⁡؜؜⁠‌⁯⁡⁮⁪⁬⁭‍⁪⁯⁡⁪⁮⁬⁪⁡⁪⁬⁣⁤',
  'project-pages.connect-space-dialog.error-icon':
    '⁣⁢Error:⁭⁪⁬⁮⁪⁡⁭⁮⁡؜⁬⁡⁡⁫⁭‍⁫⁡⁬⁮⁯⁮⁫⁣⁤',
  'project-pages.connect-space-dialog.footer.cancel':
    '⁣⁢Cancel⁬⁭⁮⁫⁮؜⁭⁬⁪⁯؜⁬‍⁡⁡⁫⁬؜⁣⁤',
  'project-pages.connect-space-dialog.footer.connect-space':
    '⁣⁢Connect‌⁮⁪⁬‍⁯⁭‌⁫⁬⁮⁡؜⁯⁬؜‌⁯‍⁭؜⁫⁠⁫⁮⁣⁤',
  'project-pages.connect-space-dialog.header.title':
    '⁣⁢Connect a Confluence space⁠⁬⁭؜⁠‍⁮؜⁭⁯⁭‍⁯؜⁬⁪⁬⁡‍‍⁯⁣⁤',
  'project-pages.connect-space-or-page-dialog.header.title':
    '⁣⁢Connect project to Confluence؜؜⁬⁠‌⁭⁭‍‍⁠‍⁬⁭⁭⁠⁮⁪⁡⁡⁪‍⁣⁤',
  'project-pages.connect-space.button':
    '⁣⁢Connect a space⁫⁮⁪؜‌؜⁮⁠‍⁡⁠⁭⁡⁡⁮‍⁫⁭⁡⁡⁡⁣⁤',
  'project-pages.connect-space.description':
    '⁣⁢Spaces are like folders - you can use them to create, organize, and collaborate on all the content related to your project.⁫؜⁯‌⁯⁬‍⁫‍⁭⁫⁮⁯⁫⁠⁠⁬⁭⁫⁫⁯⁬؜⁬⁯⁣⁤',
  'project-pages.connect-space.heading':
    '⁣⁢Connect this project to a Confluence space؜؜⁫‍⁬⁮⁫⁠‌⁮⁫‍؜⁫⁯⁭⁬⁮؜⁡⁠⁬⁠؜⁣⁤',
  'project-pages.create-space-dialog.connection-error':
    '⁣⁢Connection failed.⁮⁮⁭⁫⁬⁭⁪‌‌‍⁪⁭⁫⁯⁯؜‍؜‌⁪؜‍‌⁫‌⁣⁤',
  'project-pages.create-space-dialog.connection-retry':
    '⁣⁢Retry⁪⁪‍؜⁬⁬⁬⁠⁪⁯⁫⁪‌‍⁡⁠⁠‌⁫⁣⁤',
  'project-pages.create-space-dialog.content.empty-name':
    '⁣⁢Please give your space a name.⁭‌⁬⁯⁯⁠⁮⁡⁮⁮⁯‌⁪⁭⁪⁮؜⁫⁫؜⁪⁭⁠⁣⁤',
  'project-pages.create-space-dialog.content.invalid-name':
    '⁣⁢Space names require at least one letter or number.⁭⁮⁫⁪⁬‍⁬⁡⁮⁬⁭؜⁬⁡؜‌؜⁬⁫⁠⁣⁤',
  'project-pages.create-space-dialog.content.placeholder':
    '⁣⁢Enter a space name⁡⁯⁪‌⁫⁭⁠⁯؜؜⁫⁯⁭⁯⁬⁮⁪‌‌⁬⁬⁮؜⁭⁣⁤',
  'project-pages.create-space-dialog.creation-error':
    '⁣⁢Space creation failed.⁪؜⁡⁭⁡⁭⁬⁠⁮⁭⁠‍؜⁬⁪⁮⁯⁭⁬‍؜⁯‌⁫⁮؜⁣⁤',
  'project-pages.create-space-dialog.error-icon':
    '⁣⁢Error:⁫؜⁬⁮⁡‍⁮⁮⁫‌‍⁯⁭⁫⁮⁡⁡⁯؜‍‍؜؜⁡⁪⁡⁣⁤',
  'project-pages.create-space-dialog.footer.cancel':
    '⁣⁢Cancel⁮⁭‍‍‌⁭⁬⁯‍‍⁪⁪⁬⁯⁪⁬⁬؜⁬⁪⁯⁫⁣⁤',
  'project-pages.create-space-dialog.footer.create-space':
    '⁣⁢Create⁫‌⁡⁪⁯⁭‌⁡⁫؜⁫⁮⁠‍⁯⁣⁤',
  'project-pages.create-space-dialog.header.title':
    '⁣⁢Create new Confluence space⁮⁡؜⁭⁠⁪؜⁮⁪⁫؜؜‌⁪⁯⁪⁪⁮⁣⁤',
  'project-pages.cross-join.access-revoked.templates.subtitle':
    '⁣⁢You cannot use project pages because the admin has denied you access to Confluence. Contact your site admin to request access.⁡؜⁪⁫⁫⁪⁬‍⁪⁡⁫⁬⁡⁭⁪⁠‍‍⁪⁠؜⁠؜‍⁣⁤',
  'project-pages.cross-join.access-revoked.templates.title':
    "⁣⁢You don't have permissions to use project pages⁯‍⁮⁮⁭؜⁮⁮⁯‌⁪‍‍⁯⁯⁪⁯⁮‍⁯‍⁣⁤",
  'project-pages.cross-join.avatar.view-profile':
    '⁣⁢View profile⁫⁫⁮⁠⁬⁡⁡⁯⁯⁯⁡‍⁠⁭⁡⁬⁡‍⁮⁡⁮⁪⁣⁤',
  'project-pages.cross-join.denied-request.templates.subtitle':
    "⁣⁢You can't use project pages because the site admin denied your request to join Confluence.‍؜⁯⁮⁯؜؜‌⁬⁯⁬⁯؜‍⁪⁬⁪؜‍‍⁣⁤",
  'project-pages.cross-join.denied-request.templates.title':
    '⁣⁢Your admin has denied you access⁠⁯⁠⁠⁮⁠⁬⁮⁬⁬‍⁯⁮⁮⁮⁪؜⁬؜⁭‌⁠‌⁭⁣⁤',
  'project-pages.cross-join.errors.unknown-error.description':
    "⁣⁢{contactSupport} if refreshing doesn't fix things.⁬⁠⁮⁮⁭‌⁯⁠⁫⁫⁡⁭؜؜⁮⁭⁮⁪⁠⁣⁤",
  'project-pages.cross-join.errors.unknown-error.title':
    "⁣⁢We can't display project pages right now⁪⁡⁡⁠؜⁫⁮‌‌⁭⁮⁫⁬⁬⁮؜⁯⁪⁣⁤",
  'project-pages.cross-join.join-product.button':
    '⁣⁢Join Confluence⁪⁬⁠‌؜⁪⁮⁭⁡⁪⁫⁬⁡؜⁡‍⁫⁬⁪⁣⁤',
  'project-pages.cross-join.join-product.connected.description':
    '⁣⁢Your team are already using Confluence to collaborate on project pages. Your site admin has already approved access for you to join them.⁯⁮⁠؜⁫⁮⁯⁯⁫⁪‌‌‌⁮⁮‌⁮⁣⁤',
  'project-pages.cross-join.join-product.connected.title':
    "⁣⁢Join Confluence to access your team's project pages⁫⁮⁠⁭⁯؜⁪‌⁪⁪⁭⁭⁮⁪⁭⁠⁡⁬‍⁣⁤",
  'project-pages.cross-join.join-product.not-connected.description':
    "⁣⁢Project pages help capture your team's knowledge and keep content in a single place. Your site admin has already approved access for you.‌⁫⁠؜‌⁯⁭⁭‍⁭⁮⁯⁬⁠‍⁮‌‌⁭؜⁬‌⁣⁤",
  'project-pages.cross-join.join-product.not-connected.title':
    '⁣⁢Join Confluence to start using project pages‍؜⁠؜⁭⁯⁪⁮⁭⁡‌؜‌⁠⁯⁪⁮⁫⁠⁠⁬⁫⁣⁤',
  'project-pages.cross-join.join-product.templates.subtitle':
    '⁣⁢GIVES YOU ACCESS TO CONFLUENCE⁯⁡‌⁠‍⁭؜؜⁭⁭‌⁡‌⁡⁮؜⁠‌؜⁬‌‍⁫⁣⁤',
  'project-pages.cross-join.join-product.templates.tooltip':
    '⁣⁢Create this page in Confluence؜⁬⁭؜⁪⁭⁬⁫⁭⁫⁬⁫‌⁪‌‌⁡‍⁭⁪⁪⁡⁪⁣⁤',
  'project-pages.cross-join.pending-request.templates.subtitle':
    "⁣⁢The site admin has received your request to join Confluence. If you're approved to join, project pages will start working and we'll send you a confirmation email.⁭⁭‍⁡‌⁭⁠؜‌⁭⁯⁪⁫⁡‌؜⁬⁪⁬⁡⁫⁪⁪⁣⁤",
  'project-pages.cross-join.pending-request.templates.title':
    "⁣⁢You've requested access to Confluence⁬⁭⁪⁡⁠⁭‍‍⁪⁯⁪‌⁮⁫⁭⁮⁫⁭⁪⁠‌؜⁣⁤",
  'project-pages.cross-join.request-access.button':
    '⁣⁢Request access⁠⁬⁯؜‌⁡⁫⁮⁮⁫⁡⁭؜⁫⁠⁠⁬‌⁮⁬⁣⁤',
  'project-pages.cross-join.request-access.connected.description':
    '⁣⁢Your team are already using Confluence to collaborate on project pages. Request access to join them.⁪⁯⁮‌⁮⁡⁭؜⁪⁭⁫‌⁪⁫⁯⁫‍⁡⁯⁪⁯⁪⁮⁯⁣⁤',
  'project-pages.cross-join.request-access.not-connected.description':
    "⁣⁢Use project pages to capture your team's knowledge and keep content in a single place. Request access to Confluence to get started.⁪‌‌⁮⁪⁡⁮⁭⁡⁫؜⁫‌⁮⁬‍⁭⁠⁭⁣⁤",
  'project-pages.cross-join.request-access.templates.subtitle':
    '⁣⁢REQUESTS ACCESS TO CONFLUENCE‌‌⁮⁯⁡⁪⁯‌⁪⁬⁠⁭‌‍⁬‌⁫⁯⁠⁬⁣⁤',
  'project-pages.cross-join.request-access.templates.tooltip':
    '⁣⁢Requests access to Confluence⁭‌⁪⁯⁮⁡‌⁪⁫⁫⁭⁫⁠⁠‍⁪⁬⁠‌⁯⁫⁠⁣⁤',
  'project-pages.cross-join.request-access.title':
    '⁣⁢Project pages require access to Confluence‌⁮⁫‍‍⁫⁮⁫⁮‌⁬⁭⁯؜‌⁡⁯⁮؜⁪‍⁭⁣⁤',
  'project-pages.default-contextual-heading':
    '⁣⁢Project pages are powered by Confluence⁡؜⁪؜⁪⁭‌⁯‌⁮‍⁠⁡‍⁬‌⁯⁯⁯⁠⁡⁡⁠⁭؜⁯⁣⁤',
  'project-pages.default-contextual-message':
    '⁣⁢Create, share, and collaborate on all your project docs in one place, with Confluence pages.⁪⁭⁪⁠⁪؜⁪⁡؜⁭⁮⁮⁫⁠⁮⁪‍⁣⁤',
  'project-pages.default-reactivate-CTA':
    '⁣⁢Reactivate Confluence⁬؜⁯⁫⁪⁬⁠‌؜‌؜⁫⁮‍⁬⁪‍⁠⁭⁠‌⁠‍⁬⁭‌⁮⁣⁤',
  'project-pages.default-trial-CTA':
    '⁣⁢Try Confluence free for 30 days⁬‌⁫⁠⁫‍‌⁡؜⁬⁮⁮⁫⁭⁫⁭⁮⁯⁯‍⁮⁣⁤',
  'project-pages.draft-saved-flag.action':
    '⁣⁢Open draft‌⁯⁡⁫⁯⁬‍⁭‌⁡⁫⁮⁯⁯⁡⁡⁯⁭؜⁫؜⁫‌⁣⁤',
  'project-pages.draft-saved-flag.description':
    '⁣⁢Your draft is only visible to you until you publish it.⁠⁬‍⁮⁬⁠؜⁭‍‍‍‍‍‌⁯⁮⁠‍⁠⁭⁯⁭⁯؜⁮⁣⁤',
  'project-pages.draft-saved-flag.title':
    '⁣⁢Draft saved⁮⁠⁮⁡؜‌؜⁡⁡⁯⁮⁪؜⁡‍⁯⁪⁬⁪⁯؜⁣⁤',
  'project-pages.embedded-pages.create-page-error.close-button':
    '⁣⁢Close⁯‌⁭⁭⁯؜⁬⁡⁭⁡؜⁭⁬⁭⁯⁬⁪⁮‍‍⁪⁫⁡⁫⁫⁣⁤',
  'project-pages.embedded-pages.create-page-error.description':
    '⁣⁢There was a problem and we couldn’t create a page for you.⁯‌⁮‍⁯⁠⁭⁡⁮‌⁡⁯؜⁯⁡⁮⁪⁫⁠⁣⁤',
  'project-pages.embedded-pages.create-page-error.title':
    '⁣⁢We couldn’t create a page⁫⁭⁪⁫⁮⁪⁫؜⁠⁪‍⁭⁪‍⁠⁬⁫⁮⁫⁭⁪⁯⁭⁭⁣⁤',
  'project-pages.embedded-pages.create-page-error.try-again-button':
    '⁣⁢Try again⁬؜⁬‌⁪‌⁫⁬⁭⁭⁪⁮⁭⁯⁭⁯⁪⁮⁮⁡؜⁪‌⁮⁣⁤',
  'project-pages.embedded-pages.modal.close.button.hint':
    '⁣⁢Close‌‍⁪⁮⁬‌⁠⁮‍⁡؜⁠⁪⁡⁡‍⁫⁪⁫‌⁪⁠؜⁪⁣⁤',
  'project-pages.embedded-pages.modal.title.button':
    '⁣⁢Open in Confluence⁠⁫⁪⁬⁬⁮⁡⁡⁬⁡⁫⁬؜‍⁠؜⁡‍⁬⁮⁮⁣⁤',
  'project-pages.embedded-pages.modal.title.button.hint':
    '⁣⁢Open in a new tab⁬؜؜⁮⁠⁫‍⁭⁡⁯⁪؜⁬⁯⁭⁫⁭⁯⁬⁪⁡⁣⁤',
  'project-pages.generic-error.button.reload':
    '⁣⁢Reload page⁬⁭⁭⁫؜⁡⁠⁯⁡⁭‌‌⁫⁪⁡⁭‍⁡⁪⁭⁠⁣⁤',
  'project-pages.generic-error.description':
    '⁣⁢Something went wrong. Please try again later.⁡‍⁫‍‍⁬‍‌⁯⁡⁠⁡؜⁬⁭⁮⁫⁯⁠‍⁣⁤',
  'project-pages.generic-error.heading':
    '⁣⁢Well, this is awkward...؜⁪⁮⁪⁡⁮⁯⁠‌⁠⁮؜‌⁯⁡‍‌⁫⁫⁡⁪؜⁬⁪؜⁣⁤',
  'project-pages.generic-success-flag.description.page':
    '⁣⁢Successfully connected with {connectedSpaceOrPageName} page.‍⁪⁮‍⁪‌‌⁪‍⁮‍⁭‌؜⁫⁬؜⁠⁬؜⁠⁮‍⁮⁣⁤',
  'project-pages.generic-success-flag.description.space':
    '⁣⁢Successfully connected with {connectedSpaceOrPageName} space.‌⁪⁫‍⁪⁪⁡⁬⁡⁮‍⁭⁮‍⁫⁬⁠؜⁡⁠‍⁣⁤',
  'project-pages.generic-success-flag.heading.page':
    '⁣⁢Page connected⁯⁪⁭‌⁠⁯⁡⁭‍⁠؜⁡⁡⁫‌⁫‌⁬⁡‍⁣⁤',
  'project-pages.generic-success-flag.heading.space':
    '⁣⁢Space connected⁬⁫⁠⁪؜⁡⁬⁯⁯⁭⁯‌⁯‌⁮⁪؜⁭‌⁡⁣⁤',
  'project-pages.granular-pages.connect-space-dialog.content.create-space-link.link-text':
    '⁣⁢Or create a new space؜⁬؜⁬⁬⁯⁯‍⁭‌؜⁠⁠‍⁬⁡⁠‍⁫⁮‌‍⁣⁤',
  'project-pages.granular-pages.connect-space.button':
    '⁣⁢Connect to Confluence‍⁪⁠⁮⁭⁮⁭⁭‍⁠‍؜⁭‍⁫‍‌⁮⁠؜⁣⁤',
  'project-pages.granular-pages.connect-space.heading':
    '⁣⁢Connect this project to a Confluence space or page⁭؜⁬⁬⁬‌⁡⁫⁬‌⁭⁮⁮⁠⁮⁬⁣⁤',
  'project-pages.improvement.contact-support':
    '⁣⁢Contact support‌⁮⁬⁬‌‌⁯⁠⁯⁠⁪‌‍⁪⁭⁫‍⁯⁪⁯⁬⁫⁣⁤',
  'project-pages.improvement.errors.access-error.description':
    '⁣⁢Try contacting the site admin to ask for access.؜⁪‍⁠⁬⁫⁠⁯؜⁫⁬⁡⁯⁡⁠⁡⁡⁭⁭⁭⁪⁯⁣⁤',
  'project-pages.improvement.errors.access-error.title':
    '⁣⁢You don’t have permission to view project pages؜⁬⁮‍⁯⁡⁪⁪‍‌⁯⁠⁡⁡⁮⁡⁬⁫⁮⁫⁬⁣⁤',
  'project-pages.improvement.errors.page-tree-unknown-error.description':
    '⁣⁢Something went wrong while trying to display pages from your connected Confluence space. {contactSupport} if refreshing doesn’t fix things.⁡⁯⁭؜؜⁡⁮‍⁫⁫⁠⁪⁡⁬⁮⁭⁪⁡‍‌⁡⁯⁭⁭⁠⁡⁣⁤',
  'project-pages.improvement.errors.page-tree-unknown-error.title':
    '⁣⁢We’re having trouble displaying project pages؜‌⁬‌⁠؜⁠؜⁡؜⁡‍⁠⁠⁯⁫⁯⁭⁪⁭⁯‍⁣⁤',
  'project-pages.improvement.errors.space-not-found.button':
    '⁣⁢Connect a different space⁮‌⁪⁠؜⁯‍⁠⁠⁬⁮⁬؜⁡⁪⁯‍⁡⁫‍⁮⁬⁪⁡‍⁭⁪‍⁣⁤',
  'project-pages.improvement.errors.space-not-found.description':
    '⁣⁢The Confluence space that was connected to project pages has been deleted or moved.⁫⁮‌⁪؜⁠‌⁡⁬⁠⁬⁭⁫⁫⁬⁠⁮⁮‍‍؜⁪⁫⁠؜⁠⁣⁤',
  'project-pages.improvement.errors.space-not-found.title':
    '⁣⁢Space not found⁡⁠⁬⁮‌⁫⁪⁭⁭⁮‌‍‍⁬‍؜⁭⁫⁬⁠⁡⁫⁡⁣⁤',
  'project-pages.improvement.errors.unknown-error.description':
    '⁣⁢{contactSupport} if refreshing doesn’t fix things.‍⁠‌؜⁯⁬⁪‌‌⁠⁠؜⁯‍⁠⁪⁭⁡⁬⁬⁯⁯؜⁣⁤',
  'project-pages.improvement.errors.unknown-error.title':
    '⁣⁢We can’t display project pages right now⁬⁯⁠⁯⁪⁭؜؜⁫⁡⁡⁯⁪؜؜⁭⁫⁫⁬‍؜⁫⁭⁣⁤',
  'project-pages.improvement.heading-info':
    "⁣⁢Capture your team's knowledge and improve the way you get work done.⁮⁯⁯‌⁪⁪⁯⁡⁪⁯⁪⁮‌⁡⁯⁯‌⁭⁠؜⁣⁤",
  'project-pages.improvement.learn-more-button':
    '⁣⁢Learn more⁫⁭⁬⁫؜⁫؜⁬⁮⁬⁡⁯‌⁯⁪‌⁯‍⁣⁤',
  'project-pages.improvement.powered-by': '⁣⁢Powered by⁮⁭⁫؜⁭‍⁭‍⁬⁭⁠⁪⁫⁪‍⁬⁠⁡⁪‍⁭⁣⁤',
  'project-pages.improvement.powered-by.tooltip':
    '⁣⁢Open Confluence in a new tab‍⁡⁠⁯⁠⁬⁬‌‍‍⁡⁪‍⁬⁫⁠⁯‍‌⁫؜⁡⁬⁣⁤',
  'project-pages.improvement.preview-teaser':
    '⁣⁢Unlock templates, project pages, and more.⁬‍⁡؜⁪‍⁭⁡‌⁪⁪‌⁪⁠⁮⁠‍⁭؜⁡⁮⁠⁪⁡⁪‍⁣⁤',
  'project-pages.improvement.templates.blank-page.description':
    '⁣⁢Start a page from scratch.⁬‌⁡؜⁫⁠⁪⁬؜⁭⁫⁬⁮‍⁠⁮⁭‍‌⁯⁬⁠⁣⁤',
  'project-pages.improvement.templates.blank-page.name':
    '⁣⁢Blank page‌⁬⁭⁠⁭⁯⁫⁯⁮؜⁡⁪⁭⁬⁮‌⁯⁡⁡‌⁮⁯⁮⁫⁠‍‌⁣⁤',
  'project-pages.improvement.templates.decision.description':
    '⁣⁢Record important project decisions and communicate them with your team.‍⁫‌⁬؜⁯⁭⁯؜؜⁠⁭⁠⁭⁠⁮⁪⁫⁮⁮⁠؜⁭⁣⁤',
  'project-pages.improvement.templates.decision.name':
    '⁣⁢Decision⁠⁮⁡‍⁫‍‍‌⁯‌⁡⁬⁭⁪⁡⁡⁭؜⁬⁪⁮⁣⁤',
  'project-pages.improvement.templates.meeting-notes.description':
    '⁣⁢Set meeting agendas, take notes, and share action items with your team.⁠⁬⁭⁬‌⁫⁬⁭⁬⁪⁯⁭؜⁬‍‍⁭؜⁫‌⁪⁡⁣⁤',
  'project-pages.improvement.templates.meeting-notes.name':
    '⁣⁢Meeting notes⁪⁠⁬⁡⁡‌⁮⁯⁪⁭⁠⁡‌⁪⁭⁮⁬⁯⁡‌‍⁣⁤',
  'project-pages.improvement.templates.post-expand.more':
    '⁣⁢More templates⁯⁪⁫؜⁬⁭⁬‍⁬⁠‌⁪⁠⁯⁭⁡‍⁮⁭⁮‌؜⁣⁤',
  'project-pages.improvement.templates.post-expand.more.tooltip':
    '⁣⁢View all templates in Confluence‌‌⁡⁠‍‌⁭⁡‍⁭⁯‌⁮‍⁭⁪⁪‌‌‍⁫⁣⁤',
  'project-pages.improvement.templates.post-expand.subtitle':
    '⁣⁢Popular templates⁠⁮⁠⁬⁡⁪⁪⁫⁠؜؜⁬؜⁭‍⁡⁠⁪⁡⁣⁤',
  'project-pages.improvement.templates.post-expand.title':
    '⁣⁢Create a page‍⁡⁫⁡⁠‍⁭⁡⁭⁬⁫⁡⁡⁬⁬⁬‌‍‍⁫⁣⁤',
  'project-pages.improvement.templates.pre-expand.more':
    '⁣⁢Explore more templates⁬‍⁡⁯⁯⁪؜⁮⁡⁡‌⁫؜؜‌⁠‍‍⁫⁠⁣⁤',
  'project-pages.improvement.templates.pre-expand.subtitle':
    '⁣⁢Popular with teams like yours⁮⁬⁫⁠⁯⁪⁭⁡⁫⁠⁡⁭⁫⁠⁫⁮⁮⁡⁣⁤',
  'project-pages.improvement.templates.pre-expand.title':
    '⁣⁢Preview templates⁫⁫⁪⁬‌⁪⁪‌⁮⁪⁮⁭⁮⁯⁬⁪⁡⁡‌⁭⁭؜⁮⁠⁬⁭⁣⁤',
  'project-pages.improvement.templates.product-requirements.description':
    '⁣⁢Define, track and scope requirements for your product or feature.⁮⁯‌⁮⁠؜‌؜⁠⁫؜⁠⁯⁭‍؜؜⁬⁯⁭⁭⁭⁣⁤',
  'project-pages.improvement.templates.product-requirements.name':
    '⁣⁢Product requirements⁮⁭⁯؜⁬⁪⁬⁯⁫‌⁮⁬⁪⁬‌⁪⁡⁡؜⁡‍‍‍⁬‍⁣⁤',
  'project-pages.improvement.templates.retrospective.description':
    '⁣⁢What went well? What could have gone better? Crowdsource improvements with your team.‌⁭⁬⁯‌‍⁬⁪⁪‍⁮⁭⁠⁡⁡⁮‍⁫⁮⁭⁬⁪⁠⁮⁣⁤',
  'project-pages.improvement.templates.retrospective.name':
    '⁣⁢Retrospective؜⁡‌⁫⁯‍؜⁯؜‍⁠⁯⁠⁯⁮⁯‌⁫⁫⁪⁯‍⁣⁤',
  'project-pages.improvement.templates.template.disabled-tooltip':
    '⁣⁢Connect a Confluence space first⁭؜⁬⁬⁭⁭⁮‌؜⁫⁯‍⁡⁭⁡⁠⁬⁡‍‍⁭⁣⁤',
  'project-pages.improvement.templates.template.tooltip':
    '⁣⁢Create this page in Confluence⁮⁯⁭؜‍‌⁭؜⁠‌⁮⁮؜⁠⁬‌⁫⁫‍⁣⁤',
  'project-pages.improvement.title':
    '⁣⁢Project pages⁫⁬⁡⁮⁪⁯⁭⁫‌⁫⁠⁫⁪⁯⁫⁬⁪‌⁫‌‍؜⁠⁬⁠⁭⁡‍⁣⁤',
  'project-pages.improvement.transient-states.empty-state.create-page-button':
    '⁣⁢Create your first page‍⁪؜؜‍⁭⁯⁫⁬‍‍⁫⁬⁭؜⁠⁡⁡⁡⁮؜⁣⁤',
  'project-pages.improvement.transient-states.empty-state.description':
    '⁣⁢Create some meeting notes, product requirements, decisions, or other content to see this space fill up.‌⁪؜⁡⁯⁡⁯⁭⁡⁯⁡⁯⁠⁠⁠‌⁬⁠⁮‍⁬⁫⁣⁤',
  'project-pages.improvement.transient-states.empty-state.title':
    '⁣⁢There’s nothing here but potential⁪⁭⁬⁬⁬⁫⁫⁭‌⁭؜⁡⁬؜⁬⁬⁫‌⁬⁪‍⁫⁣⁤',
  'project-pages.improvement.tree-empty-state.contributors':
    '⁣⁢Contributors‍⁪⁡⁭؜‌⁫⁪؜⁫⁫⁯⁡⁬؜⁬⁡⁭‌⁭‍⁣⁤',
  'project-pages.improvement.tree-empty-state.last-modified':
    '⁣⁢Last modified⁮‍⁬⁭⁠⁭⁭⁡‌‍⁮⁪؜⁪⁠⁬⁯⁡⁭؜⁯⁣⁤',
  'project-pages.improvement.tree-empty-state.page-name':
    '⁣⁢Name⁡‍⁮⁫⁯⁯⁪؜⁪‌؜⁡⁭⁫⁠‌⁬⁬⁫⁯‍⁣⁤',
  'project-pages.improvement.try-button':
    '⁣⁢Try this template in Confluence⁫⁠‍⁪⁯⁯⁯⁠؜⁯⁠‌⁠⁠⁫⁯‍؜⁪‍⁯‌⁫⁣⁤',
  'project-pages.improvement.try-button.tooltip':
    '⁣⁢Starts a Confluence trial‍⁬⁮⁫⁪‍؜‍‍⁮؜⁯⁫⁫⁪⁬⁡⁮‌⁫‍⁮⁫⁣⁤',
  'project-pages.improvement.try-lozenge': '⁣⁢try⁪‌⁯؜⁬⁫؜⁮⁡⁯⁫⁡⁡⁪⁡‌⁡؜⁮⁮⁭‍⁡⁣⁤',
  'project-pages.menu.connect-different-space':
    '⁣⁢Connect to a different space⁯‍⁪⁭⁪‌⁮⁫⁮⁮⁫⁯‌⁯؜⁯⁬⁭⁣⁤',
  'project-pages.menu.connect-space':
    '⁣⁢Connect a space؜⁮⁫⁠⁮⁮⁭⁠⁡⁠⁫؜؜⁫‍⁬⁫؜؜‌⁠⁭؜⁣⁤',
  'project-pages.more-menu-button.label': '⁣⁢More⁫⁮‍⁫؜⁡‌⁫⁮⁡⁯⁠⁫⁠⁬⁫⁪⁭⁯⁭⁣⁤',
  'project-pages.page-deleted-flag.title':
    '⁣⁢Page deleted.⁮‍⁪‌؜⁮⁮⁮⁠⁬‍؜⁪⁠‌⁭⁮‌⁯⁯⁫‌⁡⁯⁣⁤',
  'project-pages.page-published-flag.title':
    '⁣⁢Your page has been published.‌⁯⁠؜⁯⁠⁡⁮‌⁭⁠‌‌؜⁯؜⁫⁡⁠⁭⁭؜⁬؜⁣⁤',
  'project-pages.unknown-error.description':
    '⁣⁢{contactSupport} if refreshing doesn’t fix things.⁡⁭⁡⁯؜⁡⁭؜⁪⁪⁮⁠⁪⁡⁭⁬⁭⁬⁭⁠⁣⁤',
  'project-pages.unknown-error.heading':
    '⁣⁢We can’t display project pages right now⁪⁫⁪‌⁡⁮‌⁠⁪⁬⁬⁯‌⁫⁬⁬⁬؜⁯⁡؜⁭⁣⁤',
};
