/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Vietnamese
export default {
  'growth-experimental.project-pages.learn-more.banner':
    'Các trang dự án được Confluence hỗ trợ.',
  'growth-experimental.project-pages.learn-more.text': 'Tìm hiểu thêm',
  'project-pages.activating.description':
    'Vùng Confuence đã kết nối vẫn chưa sẵn sàng. {contactSupport} nếu thao tác làm mới không khắc phục được mọi thứ.',
  'project-pages.activating.heading': 'Confluence vẫn đang tải',
  'project-pages.button.connect-different-space-or-page.label':
    'Biểu tượng cập nhật vùng hoặc trang',
  'project-pages.button.connect-different-space-or-page.tooltip':
    'Kết nối không gian hoặc trang khác',
  'project-pages.button.connect-space-or-page.tooltip':
    'Kết nối với Confluence',
  'project-pages.button.go-to-connected-page.tooltip':
    'Mở trang trong Confluence',
  'project-pages.button.go-to-connected-space.tooltip':
    'Mở không gian trong Confluence',
  'project-pages.connect-space-dialog.connection-error': 'Không thể kết nối.',
  'project-pages.connect-space-dialog.connection-retry': 'Thử lại',
  'project-pages.connect-space-dialog.content.create-space-link.link-text':
    'Tạo vùng Confluence mới',
  'project-pages.connect-space-dialog.content.space-or-page-selector.description':
    'Chọn không gian hoặc trang cần kết nối với dự án của bạn.',
  'project-pages.connect-space-dialog.content.space-or-page-selector.placeholder':
    'Tìm kiếm Confluence',
  'project-pages.connect-space-dialog.content.space-selector.description':
    'Chọn vùng cần kết nối với dự án này',
  'project-pages.connect-space-dialog.content.space-selector.disconnected-templates-description':
    'Dự án này cần phải được kết nối với vùng trước khi bạn có thể tạo trang. Chọn vùng cần kết nối với dự án này.',
  'project-pages.connect-space-dialog.content.space-selector.placeholder':
    'Chọn vùng',
  'project-pages.connect-space-dialog.error-icon': 'Lỗi:',
  'project-pages.connect-space-dialog.footer.cancel': 'Hủy',
  'project-pages.connect-space-dialog.footer.connect-space': 'Kết nối',
  'project-pages.connect-space-dialog.header.title': 'Kết nối vùng Confluence',
  'project-pages.connect-space-or-page-dialog.header.title':
    'Kết nối dự án với Confluence',
  'project-pages.connect-space.button': 'Kết nối vùng',
  'project-pages.connect-space.description':
    'Vùng giống như thư mục - bạn có thể sử dụng chúng để tạo, sắp xếp và cộng tác cho tất cả nội dung liên quan đến dự án của bạn.',
  'project-pages.connect-space.heading':
    'Kết nối dự án này với vùng Confluence',
  'project-pages.create-space-dialog.connection-error': 'Không thể kết nối.',
  'project-pages.create-space-dialog.connection-retry': 'Thử lại',
  'project-pages.create-space-dialog.content.empty-name':
    'Vui lòng đặt tên cho vùng của bạn.',
  'project-pages.create-space-dialog.content.invalid-name':
    'Tên vùng cần chứa tối thiểu một chữ cái hoặc chữ số.',
  'project-pages.create-space-dialog.content.placeholder': 'Nhập tên vùng',
  'project-pages.create-space-dialog.creation-error': 'Không thể tạo vùng.',
  'project-pages.create-space-dialog.error-icon': 'Lỗi:',
  'project-pages.create-space-dialog.footer.cancel': 'Hủy',
  'project-pages.create-space-dialog.footer.create-space': 'Tạo',
  'project-pages.create-space-dialog.header.title': 'Tạo vùng Confluence mới',
  'project-pages.cross-join.access-revoked.templates.subtitle':
    'Bạn không thể sử dụng các trang dự án vì quản trị viên đã từ chối yêu cầu truy cập vào Confluence của bạn. Hãy liên hệ với quản trị viên trang web của bạn để yêu cầu cấp quyền truy cập.',
  'project-pages.cross-join.access-revoked.templates.title':
    'Bạn không có quyền sử dụng các trang dự án',
  'project-pages.cross-join.avatar.view-profile': 'Xem hồ sơ',
  'project-pages.cross-join.denied-request.templates.subtitle':
    'Bạn không thể sử dụng các trang dự án vì quản trị viên trang web đã từ chối yêu cầu tham gia Confluence của bạn.',
  'project-pages.cross-join.denied-request.templates.title':
    'Quản trị viên của bạn đã từ chối yêu cầu truy cập của bạn',
  'project-pages.cross-join.errors.unknown-error.description':
    '{contactSupport} nếu thao tác làm mới không khắc phục được vấn đề.',
  'project-pages.cross-join.errors.unknown-error.title':
    'Chúng tôi không thể hiển thị các trang dự án ngay bây giờ',
  'project-pages.cross-join.join-product.button': 'Tham gia Confluence',
  'project-pages.cross-join.join-product.connected.description':
    'Nhóm của bạn đang sử dụng Confluence để cộng tác trên các trang dự án. Quản trị viên trang web của bạn đã chấp thuận cấp quyền truy cập để bạn tham gia.',
  'project-pages.cross-join.join-product.connected.title':
    'Tham gia Confluence để truy cập các trang dự án của nhóm bạn',
  'project-pages.cross-join.join-product.not-connected.description':
    'Các trang dự án giúp ghi lại kiến thức của nhóm bạn và lưu trữ nội dung ở một nơi duy nhất. Quản trị viên trang web của bạn đã chấp thuận cấp quyền truy cập cho bạn.',
  'project-pages.cross-join.join-product.not-connected.title':
    'Tham gia Confluence để bắt đầu sử dụng các trang dự án',
  'project-pages.cross-join.join-product.templates.subtitle':
    'CẤP CHO BẠN QUYỀN TRUY CẬP VÀO CONFLUENCE',
  'project-pages.cross-join.join-product.templates.tooltip':
    'Tạo trang này trong Confluence',
  'project-pages.cross-join.pending-request.templates.subtitle':
    'Quản trị viên trang web đã nhận được yêu cầu tham gia Confluence của bạn. Nếu bạn được chấp thuận tham gia, các trang dự án sẽ bắt đầu hoạt động và chúng tôi sẽ gửi cho bạn email xác nhận.',
  'project-pages.cross-join.pending-request.templates.title':
    'Bạn đã yêu cầu cấp quyền truy cập vào Confluence',
  'project-pages.cross-join.request-access.button':
    'Yêu cầu cấp quyền truy cập',
  'project-pages.cross-join.request-access.connected.description':
    'Nhóm của bạn đang sử dụng Confluence để cộng tác trên các trang dự án. Yêu cầu cấp quyền truy cập để tham gia cùng họ.',
  'project-pages.cross-join.request-access.not-connected.description':
    'Sử dụng các trang dự án để ghi lại kiến thức của nhóm bạn và lưu trữ nội dung ở một nơi duy nhất. Yêu cầu cấp quyền truy cập vào Confluence để bắt đầu.',
  'project-pages.cross-join.request-access.templates.subtitle':
    'YÊU CẦU CẤP QUYỀN TRUY CẬP VÀO CONFLUENCE',
  'project-pages.cross-join.request-access.templates.tooltip':
    'Yêu cầu cấp quyền truy cập vào Confluence',
  'project-pages.cross-join.request-access.title':
    'Cần có quyền truy cập vào Confluence để sử dụng các trang dự án',
  'project-pages.default-contextual-heading':
    'Các trang dự án được hỗ trợ bởi Confluence',
  'project-pages.default-contextual-message':
    'Tạo, chia sẻ và cộng tác trên tất cả các tài liệu của dự án ở một nơi tập trung duy nhất, với trang Confluence.',
  'project-pages.default-reactivate-CTA': 'Hủy kích hoạt Confluence',
  'project-pages.default-trial-CTA':
    'Dùng thử Confluence miễn phí trong 30 ngày',
  'project-pages.draft-saved-flag.action': 'Mở bản nháp',
  'project-pages.draft-saved-flag.description':
    'Bản nháp chưa đăng sẽ chỉ hiển thị với bạn.',
  'project-pages.draft-saved-flag.title': 'Đã lưu bản nháp',
  'project-pages.embedded-pages.create-page-error.close-button': 'Đóng',
  'project-pages.embedded-pages.create-page-error.description':
    'Đã xảy ra sự cố và chúng tôi không thể tạo trang cho bạn.',
  'project-pages.embedded-pages.create-page-error.title':
    'Chúng tôi không thể tạo trang',
  'project-pages.embedded-pages.create-page-error.try-again-button': 'Thử lại',
  'project-pages.embedded-pages.modal.close.button.hint': 'Đóng',
  'project-pages.embedded-pages.modal.title.button': 'Mở trong Confluence',
  'project-pages.embedded-pages.modal.title.button.hint': 'Mở trong tab mới',
  'project-pages.generic-error.button.reload': 'Tải lại trang',
  'project-pages.generic-error.description':
    'Đã xảy ra lỗi. Vui lòng thử lại sau.',
  'project-pages.generic-error.heading': 'Chà, thật là lạ...',
  'project-pages.generic-success-flag.description.page':
    'Đã kết nối thành công với trang {connectedSpaceOrPageName}.',
  'project-pages.generic-success-flag.description.space':
    'Đã kết nối thành công với vùng {connectedSpaceOrPageName}.',
  'project-pages.generic-success-flag.heading.page': 'Trang đã kết nối',
  'project-pages.generic-success-flag.heading.space': 'Đã kết nối vùng',
  'project-pages.granular-pages.connect-space-dialog.content.create-space-link.link-text':
    'Hoặc tạo một không gian mới',
  'project-pages.granular-pages.connect-space.button': 'Kết nối với Confluence',
  'project-pages.granular-pages.connect-space.heading':
    'Kết nối dự án này với vùng hoặc trang Confluence',
  'project-pages.improvement.contact-support': 'Liên hệ với bộ phận hỗ trợ',
  'project-pages.improvement.errors.access-error.description':
    'Hãy thử liên hệ với quản trị viên trang web để có quyền truy cập.',
  'project-pages.improvement.errors.access-error.title':
    'Bạn không có quyền xem các trang dự án',
  'project-pages.improvement.errors.page-tree-unknown-error.description':
    'Đã xảy ra lỗi khi cố gắng hiển thị các trang từ vùng Confluence đã kết nối của bạn. {contactSupport} nếu thao tác làm mới không khắc phục được mọi thứ.',
  'project-pages.improvement.errors.page-tree-unknown-error.title':
    'Chúng tôi đã gặp sự cố khi hiển thị các trang dự án',
  'project-pages.improvement.errors.space-not-found.button':
    'Kết nối với một vùng khác',
  'project-pages.improvement.errors.space-not-found.description':
    'Vùng Confluence được kết nối với các trang dự án đã bị xóa hoặc di chuyển.',
  'project-pages.improvement.errors.space-not-found.title':
    'Không tìm thấy vùng nào',
  'project-pages.improvement.errors.unknown-error.description':
    '{contactSupport} nếu thao tác làm mới không khắc phục được mọi thứ.',
  'project-pages.improvement.errors.unknown-error.title':
    'Chúng tôi không thể hiển thị các trang dự án ngay bây giờ',
  'project-pages.improvement.heading-info':
    'Thấu hiểu được nhóm của bạn và cải thiện cách bạn hoàn thành công việc.',
  'project-pages.improvement.learn-more-button': 'Tìm hiểu thêm',
  'project-pages.improvement.powered-by': 'Được hỗ trợ bởi',
  'project-pages.improvement.powered-by.tooltip': 'Mở Confluence trong tab mới',
  'project-pages.improvement.preview-teaser':
    'Mở khóa biểu mẫu, các trang dự án và nhiều lựa chọn khác.',
  'project-pages.improvement.templates.blank-page.description':
    'Bắt đầu một trang ngay từ đầu.',
  'project-pages.improvement.templates.blank-page.name': 'Trang trống',
  'project-pages.improvement.templates.decision.description':
    'Ghi lại các quyết định quan trọng về dự án và trao đổi chúng với nhóm của bạn.',
  'project-pages.improvement.templates.decision.name': 'Quyết định',
  'project-pages.improvement.templates.meeting-notes.description':
    'Đặt chương trình họp, ghi chú và chia sẻ các mục hành động với nhóm.',
  'project-pages.improvement.templates.meeting-notes.name': 'Biên bản cuộc họp',
  'project-pages.improvement.templates.post-expand.more': 'Các mẫu khác',
  'project-pages.improvement.templates.post-expand.more.tooltip':
    'Xem tất cả các mẫu trong Confluence',
  'project-pages.improvement.templates.post-expand.subtitle':
    'Các mẫu phổ biến',
  'project-pages.improvement.templates.post-expand.title': 'Tạo trang',
  'project-pages.improvement.templates.pre-expand.more':
    'Khám phá các mẫu khác',
  'project-pages.improvement.templates.pre-expand.subtitle':
    'Quen thuộc với các nhóm như nhóm của bạn',
  'project-pages.improvement.templates.pre-expand.title': 'Xem trước mẫu',
  'project-pages.improvement.templates.product-requirements.description':
    'Xác định, theo dõi và xem xét các yêu cầu đối với sản phẩm hoặc tính năng của bạn.',
  'project-pages.improvement.templates.product-requirements.name':
    'Yêu cầu sản phẩm',
  'project-pages.improvement.templates.retrospective.description':
    'Phần nào đã tốt rồi? Phần nào còn có thể cải thiện? Cải thiện nguồn lực cộng đồng với nhóm của bạn.',
  'project-pages.improvement.templates.retrospective.name': 'Xem lại',
  'project-pages.improvement.templates.template.disabled-tooltip':
    'Trước tiên, hãy kết nối với một vùng Confluence',
  'project-pages.improvement.templates.template.tooltip':
    'Tạo trang này trong Confluence',
  'project-pages.improvement.title': 'Các trang dự án',
  'project-pages.improvement.transient-states.empty-state.create-page-button':
    'Tạo trang đầu tiên',
  'project-pages.improvement.transient-states.empty-state.description':
    'Tạo vài ghi chú cuộc họp, yêu cầu sản phẩm, quyết định hoặc nội dung khác để thấy vùng này lấp đầy.',
  'project-pages.improvement.transient-states.empty-state.title':
    'Không có gì ở đây ngoài tiềm năng',
  'project-pages.improvement.tree-empty-state.contributors': 'Người đóng góp',
  'project-pages.improvement.tree-empty-state.last-modified':
    'Sửa đổi gần đây nhất',
  'project-pages.improvement.tree-empty-state.page-name': 'Tên',
  'project-pages.improvement.try-button': 'Thử biểu mẫu này trong Confluence',
  'project-pages.improvement.try-button.tooltip': 'Bắt đầu dùng thử Confluence',
  'project-pages.improvement.try-lozenge': 'Thử',
  'project-pages.menu.connect-different-space': 'Kết nối với một vùng khác',
  'project-pages.menu.connect-space': 'Kết nối vùng',
  'project-pages.more-menu-button.label': 'Khác',
  'project-pages.page-deleted-flag.title': 'Đã xóa trang.',
  'project-pages.page-published-flag.title': 'Đã đăng trang của bạn.',
  'project-pages.unknown-error.description':
    '{contactSupport} nếu thao tác làm mới không khắc phục được mọi thứ.',
  'project-pages.unknown-error.heading':
    'Chúng tôi không thể hiển thị các trang dự án ngay bây giờ',
};
