/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Danish
export default {
  'people-and-teams.people-teams.member-picker.error.msg.exceed.limited.number.error2':
    '{maxNumber, plural, one {Du har indtastet mere end {maxNumber} person.} other {Du har indtastet mere end {maxNumber} personer.}}',
  'people-and-teams.people-teams.member-picker.msg.exceed.limited.number.info':
    '{maxNumber, plural, one {Du kan invitere op til én person ad gangen.} other {Du kan invitere op til {maxNumber} personer ad gangen.}}',
  'people-and-teams.people-teams.member-picker.no-option': 'Ingen resultater.',
  'people-and-teams.people-teams.member-picker.placeholder':
    'Navn eller @omtale',
  'people-and-teams.people-teams.team-create-dialog.button.cancel': 'Annuller',
  'people-and-teams.people-teams.team-create-dialog.button.submit':
    'Opret team',
  'people-and-teams.people-teams.team-create-dialog.flag-error.desc':
    'Vi kunne ikke gemme dit team. Prøv igen.',
  'people-and-teams.people-teams.team-create-dialog.flag-error.title':
    'Der gik desværre noget galt',
  'people-and-teams.people-teams.team-create-dialog.flag-success.action':
    'Se dit team',
  'people-and-teams.people-teams.team-create-dialog.flag-success.desc':
    'Omtal dit nye team for at begynde at samarbejde med det samme, eller rediger teamet under teamets profil.',
  'people-and-teams.people-teams.team-create-dialog.flag-success.title':
    'Du har oprettet "{teamName}"',
  'people-and-teams.people-teams.team-create-dialog.invite-members.failed.desc':
    'Vi oprettede teamet, men du skal tilføje teammedlemmerne igen.',
  'people-and-teams.people-teams.team-create-dialog.invite-members.failed.title':
    'Der gik noget galt med dine invitationer',
  'people-and-teams.people-teams.team-create-dialog.learn-more':
    'Få mere at vide',
  'people-and-teams.people-teams.team-create-dialog.modal.fields.invite-emails.label':
    'Inviter folk til dit team',
  'people-and-teams.people-teams.team-create-dialog.modal.team-name-field.placeholder':
    'Hvad hedder dit team?',
  'people-and-teams.people-teams.team-create-dialog.pretext.with.mention':
    'Få alle til at arbejde ét sted ved at føje dem til et team. Hold jer opdateret med @omtaler, samarbejd med hinanden, og hold nemt styr på det hele fra teamets profilside. {learnMoreLink}',
  'people-and-teams.people-teams.team-create-dialog.team-name-field.label':
    'Teamnavn',
  'people-and-teams.people-teams.team-create-dialog.title': 'Opret et nyt team',
};
