/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Turkish
export default {
  'people-and-teams.people-teams.member-picker.error.msg.exceed.limited.number.error2':
    '{maxNumber, plural, one {{maxNumber} kişiden fazla girdiniz.} other {{maxNumber} kişiden fazla girdiniz.}}',
  'people-and-teams.people-teams.member-picker.msg.exceed.limited.number.info':
    '{maxNumber, plural, one {Tek seferde en fazla 1 kişi davet edebilirsiniz.} other {Tek seferde en fazla {maxNumber} kişi davet edebilirsiniz.}}',
  'people-and-teams.people-teams.member-picker.no-option': 'Eşleşme yok.',
  'people-and-teams.people-teams.member-picker.placeholder':
    'Ad veya @bahsetme etiketi',
  'people-and-teams.people-teams.team-create-dialog.button.cancel': 'İptal',
  'people-and-teams.people-teams.team-create-dialog.button.submit':
    'Takım oluştur',
  'people-and-teams.people-teams.team-create-dialog.flag-error.desc':
    'Takımınızı kaydedemedik. Lütfen yeniden deneyin.',
  'people-and-teams.people-teams.team-create-dialog.flag-error.title':
    'Üzgünüz, bir hata oluştu',
  'people-and-teams.people-teams.team-create-dialog.flag-success.action':
    'Takımınızı görüntüleyin',
  'people-and-teams.people-teams.team-create-dialog.flag-success.desc':
    'Hemen iş birliği yapmaya başlamak için takımınızdan bahsedin veya takım profilinden takımınızı düzenleyin.',
  'people-and-teams.people-teams.team-create-dialog.flag-success.title':
    '"{teamName}" adlı takımı oluşturdunuz',
  'people-and-teams.people-teams.team-create-dialog.invite-members.failed.desc':
    'Takımı oluşturduk, ancak takım üyelerini yeniden eklemeniz gerekecek.',
  'people-and-teams.people-teams.team-create-dialog.invite-members.failed.title':
    'Davetlerinizle ilgili bir hata oluştu',
  'people-and-teams.people-teams.team-create-dialog.learn-more':
    'Daha fazla bilgi',
  'people-and-teams.people-teams.team-create-dialog.modal.fields.invite-emails.label':
    'Kişileri takımınıza davet edin',
  'people-and-teams.people-teams.team-create-dialog.modal.team-name-field.placeholder':
    'Takımınızın adı nedir?',
  'people-and-teams.people-teams.team-create-dialog.pretext.with.mention':
    'İnsanları bir takıma ekleyerek aynı yerde çalışmalarını sağlayın. @Bahsetmeler kullanarak bağlantıda kalın, çalışmalarınızda iş birliği yapın ve takımın profil sayfasından her şeyi verimli bir şekilde yönetin. {learnMoreLink}',
  'people-and-teams.people-teams.team-create-dialog.team-name-field.label':
    'Takım adı',
  'people-and-teams.people-teams.team-create-dialog.title':
    'Yeni bir takım oluşturun',
};
