/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// undefined
export default {
  'people-and-teams.people-teams.member-picker.error.msg.exceed.limited.number.error2':
    '{maxNumber, plural, other {您已輸入超過 {maxNumber} 位人員。}}',
  'people-and-teams.people-teams.member-picker.msg.exceed.limited.number.info':
    '{maxNumber, plural, other {一次最多可以邀請 {maxNumber} 個人。}}',
  'people-and-teams.people-teams.member-picker.no-option': '沒有相符項目。',
  'people-and-teams.people-teams.member-picker.placeholder': '其名稱或 @提及',
  'people-and-teams.people-teams.team-create-dialog.button.cancel': '取消',
  'people-and-teams.people-teams.team-create-dialog.button.submit':
    '開始建立團隊',
  'people-and-teams.people-teams.team-create-dialog.flag-error.desc':
    '我們無法拯救您的團隊。請再試一次。',
  'people-and-teams.people-teams.team-create-dialog.flag-error.title':
    '抱歉，發生問題',
  'people-and-teams.people-teams.team-create-dialog.flag-success.action':
    '檢視您的團隊',
  'people-and-teams.people-teams.team-create-dialog.flag-success.desc':
    '提及您的新團隊以立即開始協作，或在團隊設定檔中編輯團隊。',
  'people-and-teams.people-teams.team-create-dialog.flag-success.title':
    '您已建立「{teamName}」',
  'people-and-teams.people-teams.team-create-dialog.invite-members.failed.desc':
    '我們已建立團隊，但您必須再次新增團隊成員。',
  'people-and-teams.people-teams.team-create-dialog.invite-members.failed.title':
    '您的邀請發生錯誤',
  'people-and-teams.people-teams.team-create-dialog.learn-more': '深入了解',
  'people-and-teams.people-teams.team-create-dialog.modal.fields.invite-emails.label':
    '邀請其他人加入您的團隊',
  'people-and-teams.people-teams.team-create-dialog.modal.team-name-field.placeholder':
    '您的團隊名稱是？',
  'people-and-teams.people-teams.team-create-dialog.pretext.with.mention':
    '加入團隊成員，讓所有人一起工作。透過 @提及功能保持聯繫、互相合作，並有效管理團隊設定檔頁面的每一個項目。{learnMoreLink}',
  'people-and-teams.people-teams.team-create-dialog.team-name-field.label':
    '團隊名稱',
  'people-and-teams.people-teams.team-create-dialog.title': '開始建立新團隊',
};
