/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// English (Instrumented)
export default {
  'form-builder.Choice.LabelPlaceholder':
    '⁣⁢Choice label⁬؜⁠؜⁪‍؜⁡‍⁫⁯‍⁡⁫⁫‍‍؜⁮⁠⁡⁡‌⁠⁣⁤',
  'form-builder.Choice.NoChoicesToDisplay':
    '⁣⁢No choices are available for the linked field.⁬‌⁭⁫‌؜‍‍؜⁯⁠⁪⁡‌⁮⁠⁡⁣⁤',
  'form-builder.Choice.NoOptionsMsg': '⁣⁢No options‍‌⁬‍⁬⁠⁮⁠‍⁫⁭⁭‌⁯⁮⁪⁯⁬⁬؜⁣⁤',
  'form-builder.Choice.NoneLabel': '⁣⁢None⁬⁠؜⁪⁯⁫⁠؜‍‌⁯؜⁠؜⁫⁭‍‌‍⁪⁣⁤',
  'form-builder.DefaultAnswerField.DatePlaceholder':
    '⁣⁢Enter default date⁯‍⁭⁮⁮‌⁠‌⁫؜⁭‍⁮⁡⁯‌؜⁠؜⁭⁮⁣⁤',
  'form-builder.DefaultAnswerField.TimePlaceholder':
    '⁣⁢Enter default time⁫⁡‍⁮⁮‌⁠⁫⁪⁭⁭⁠‍⁭‌⁫⁡‌⁠⁠⁠⁣⁤',
  'form-builder.EmptyBuilderPlaceholder':
    '⁣⁢To help you start building a form you can use the form templates in the right sidebar.⁡؜⁠⁮؜⁡⁮⁭‍⁬⁪⁭⁬⁮⁯⁡‌⁫⁪⁬⁪‌⁫؜⁣⁤',
  'form-builder.HtmlQuestionsNoLongerSupporter':
    '⁣⁢HTML questions are no longer supported.؜⁠⁪‍‌⁭‌⁬⁮⁪‌⁡‍⁭⁪⁬⁮⁡⁮⁫⁠⁣⁤',
  'form-builder.HtmlSidebar.Heading':
    '⁣⁢HTML Content⁫⁡؜‍⁮⁡‍‍⁫⁠⁡‍؜؜⁭⁫⁫‍⁬⁫⁫⁭⁫⁫⁣⁤',
  'form-builder.MediaSidebar.Accessible':
    '⁣⁢Accessible:⁡‍⁠⁠⁭‌‌‌‌⁯⁠⁬‌⁪⁡⁪‌⁡‌‌⁬⁣⁤',
  'form-builder.MediaSidebar.AccessibleDesc':
    '⁣⁢Please ensure that the image is accessible to everyone that will fill out your form. e.g. it is not saved on a Confluence page only you can access. A simple way to check this is to try loading the image URL in your browser incognito mode.⁪⁬⁮⁯‌⁮⁯⁭؜‌؜؜⁬؜⁡⁫⁯⁫‌⁣⁤',
  'form-builder.MediaSidebar.ClickingAnImage':
    '⁣⁢Clicking an image:⁯‌‍⁪‍‌⁯⁬⁪⁪⁫⁪⁠⁠؜⁫؜⁪⁬⁠⁠⁠‌⁯⁬⁣⁤',
  'form-builder.MediaSidebar.ClickingAnImageDesc':
    '⁣⁢When viewing a form, clicking on an image will display it full screen. This does not affect the contents of the form, as the image can simply be closed; however, it may seem like strange behaviour to a user.⁬⁮⁠⁭⁪⁭‍⁬⁬⁫؜⁫⁯⁯؜⁫‍⁫؜‌⁡⁬⁭⁣⁤',
  'form-builder.MediaSidebar.CopyImageLocation':
    '⁣⁢copy image location.‍؜⁭⁯⁪⁬‌⁯⁪⁫؜⁭‍⁬⁡⁯⁫⁬⁬⁫⁭⁠⁡⁫‍⁣⁤',
  'form-builder.MediaSidebar.EarlyAccessFeature':
    '⁣⁢Early Access Feature⁯⁭‌‍⁯⁫⁬⁭⁠⁪‍‍⁬⁭⁬⁠⁭؜⁠⁪⁪؜؜⁣⁤',
  'form-builder.MediaSidebar.ExcludedFromPdf':
    '⁣⁢Excluded from PDFs:⁬⁮؜⁡⁡⁪⁯‌⁯⁬⁮⁡⁠⁫⁠⁯⁪؜⁡‍⁫⁣⁤',
  'form-builder.MediaSidebar.ExcludedFromPdfDesc':
    '⁣⁢Images are not included in any PDFs generated from the form.⁬⁡⁭؜⁡⁮⁪⁬⁯⁬‍⁠⁪⁪⁬⁪⁪⁬‌‍⁬⁪؜⁬⁣⁤',
  'form-builder.MediaSidebar.Heading': '⁣⁢Image؜⁭⁭؜⁠⁮؜⁫⁬⁬‌⁬⁭‌⁯⁬‌⁮⁪⁯⁡⁣⁤',
  'form-builder.MediaSidebar.ImageHosting':
    '⁣⁢Image Hosting:⁬‍‌⁯⁡⁭⁭؜⁫⁠؜⁠⁡⁭؜؜⁮‌⁯⁬‌⁮⁡⁮⁮⁣⁤',
  'form-builder.MediaSidebar.ImageHostingDesc':
    '⁣⁢It is not possible to upload an image directly into the form, the image must already exist on another page/site.⁬⁭‍⁭⁪⁯⁠⁪⁫⁯⁫‍⁡⁬⁮⁭⁡؜⁡⁡⁣⁤',
  'form-builder.MediaSidebar.ImageUrl': '⁣⁢Image URL⁫⁫⁡⁪⁫⁠⁪⁪⁫⁮⁫‌‌⁡؜⁡⁡⁮⁬‌⁫⁮⁮⁠⁣⁤',
  'form-builder.MediaSidebar.ImageUrlErrorMessage':
    '⁣⁢Image URL must start with http:// or https://⁬⁮⁠⁮⁫⁫⁮⁠⁭⁭⁯⁠‍⁫⁪؜⁭؜⁪⁡⁯⁡⁠⁬‌⁣⁤',
  'form-builder.MediaSidebar.ImageUrlPlaceholder':
    '⁣⁢Enter a URL for the image to be displayed؜؜⁪‌⁪‍؜؜⁬⁮⁪⁡⁫⁭‌⁯⁠⁮⁭⁡⁪⁡⁣⁤',
  'form-builder.MediaSidebar.IsInEarlyAccess':
    '⁣⁢Support for images within forms is in Early Access. It has the following limitations:‌⁬‌⁮⁡⁯⁯⁮⁫؜‍‍⁮⁯⁪⁫⁡⁮⁬⁣⁤',
  'form-builder.MediaSidebar.OnTheImage':
    '⁣⁢on the image in your browser and select⁠‍‍⁡⁭⁯⁪⁮⁡؜⁭⁫⁪⁪⁫؜⁬⁡⁠⁠⁮⁣⁤',
  'form-builder.MediaSidebar.PasteLocation':
    '⁣⁢Paste this location into the field above.⁡⁯⁡⁠⁭⁬‍⁮⁯⁯⁬⁫⁯‌‍‌؜⁫⁬‍⁠⁬⁣⁤',
  'form-builder.MediaSidebar.RightClick':
    '⁣⁢right-click؜⁫‌⁪⁭⁯⁯؜‌⁠⁠⁭⁭⁯؜⁡⁭‍⁭⁬⁠⁬⁮⁣⁤',
  'form-builder.MediaSidebar.SubHeading':
    '⁣⁢Add an image to your forms.⁬⁬‍⁠؜⁪⁡‌⁫؜⁭⁬⁭⁯⁡⁡‌⁬⁮⁡⁡⁣⁤',
  'form-builder.MediaSidebar.ToObtainUrl':
    '⁣⁢To obtain the URL for an image⁬⁬⁬⁮‍‌⁮⁯⁮⁯⁯⁯‌⁮⁪⁬؜؜⁯‍⁪⁮⁪؜‌⁣⁤',
  'form-builder.QuestionSidebar.AddChoice':
    '⁣⁢Add choice⁯‌⁬⁮⁪‍⁪⁡⁪⁮‍⁠‍‍‌‌؜⁫⁭⁫⁫⁠⁣⁤',
  'form-builder.QuestionSidebar.AddOther':
    "⁣⁢Add 'Other...'؜⁭‍؜⁮⁯⁬⁫⁭‌⁮⁡‍⁠⁫⁭‍‌⁮؜⁡⁣⁤",
  'form-builder.QuestionSidebar.ChoiceOr': '⁣⁢or⁭⁡⁫⁠⁫‌⁡⁪⁮⁯؜⁯⁭⁡⁯‍⁭⁠⁡⁭⁣⁤',
  'form-builder.QuestionSidebar.Choices': '⁣⁢Choices⁡⁭⁪‍⁪⁬⁭⁫؜⁪⁬؜؜⁪⁪⁡⁠⁠⁭⁣⁤',
  'form-builder.QuestionSidebar.ConnectionConflictPopup.CannotLinkJiraFieldAndDataConnection':
    '⁣⁢A question cannot be linked to both a Jira field and a data connection.‌⁡⁭⁪⁪؜⁭⁡⁮‌⁮‌⁡⁭‍⁯‌‍‌⁭⁠⁯⁡⁣⁤',
  'form-builder.QuestionSidebar.ConnectionConflictPopup.Close':
    '⁣⁢Close⁮‍⁪‍⁭‍⁠⁠‌⁡⁭⁭⁠⁡‍⁭⁣⁤',
  'form-builder.QuestionSidebar.ConnectionConflictPopup.ExistingDataConnection':
    '⁣⁢Existing data connection:⁯⁭⁬⁠‌⁭⁠‌⁫⁫⁠⁫‍⁠⁯⁮⁪⁯⁫⁡⁮⁡‌⁫⁪‍⁣⁤',
  'form-builder.QuestionSidebar.ConnectionConflictPopup.ExistingJiraField':
    '⁣⁢Existing linked Jira field:⁠⁡⁯⁬⁬⁪⁮⁫‌⁬‌؜؜⁡⁫⁯‍⁫⁣⁤',
  'form-builder.QuestionSidebar.ConnectionConflictPopup.Heading':
    '⁣⁢Cannot link simultaneously؜⁯⁭⁡⁮⁠؜⁯⁫⁪⁭‌‌؜⁪⁡⁠‌؜‍‌؜⁠⁣⁤',
  'form-builder.QuestionSidebar.ConnectionConflictPopup.NewDataConnection':
    '⁣⁢New data connection:‌‌⁯⁮؜⁪⁭⁠⁡‍‍⁭‍⁭⁡⁯‍⁡⁯⁮⁣⁤',
  'form-builder.QuestionSidebar.ConnectionConflictPopup.NewJiraField':
    '⁣⁢New linked Jira field:⁫؜⁭‍⁯؜⁡⁭‍؜⁠‌⁮‌⁠⁮⁯؜⁭⁣⁤',
  'form-builder.QuestionSidebar.ConnectionConflictPopup.RemoveDataConnection':
    '⁣⁢If you wish to link to this Jira field, remove the data connection first.⁪‌⁬⁬‍‍⁮⁪؜⁫⁡⁪⁫⁠⁪⁡⁠⁡⁠⁪⁭⁪⁬؜⁪‍⁣⁤',
  'form-builder.QuestionSidebar.ConnectionConflictPopup.RemoveJiraField':
    '⁣⁢If you wish to link to this data connection, remove the Jira field link first.‌⁯‍⁭‌⁪⁠⁡⁮⁬‌⁡⁯⁮⁫⁫⁬⁪‍⁭⁭‌‌⁪⁣⁤',
  'form-builder.QuestionSidebar.DataConnection':
    '⁣⁢Data Connection‍⁯⁬⁬⁠⁮‌⁪⁫؜‌⁭؜؜⁪⁭⁫⁭⁡⁠؜‌⁣⁤',
  'form-builder.QuestionSidebar.DataConnectionPlaceholder':
    '⁣⁢Select a connection⁭‍⁫⁡⁬⁯؜⁠⁮؜‌‍⁬⁡⁮⁯‍⁪⁭⁠‍⁣⁤',
  'form-builder.QuestionSidebar.DefaultAnswer':
    '⁣⁢Default answer⁠⁮⁡⁮‌⁬⁬⁬⁪⁪⁪⁠⁮⁭⁯⁡⁡⁣⁤',
  'form-builder.QuestionSidebar.DefaultAnswerPlaceholder':
    '⁣⁢Pre-fill answer with a default‌‍⁭⁯⁭⁮‍⁭⁭⁭⁠⁪⁠‌⁡؜‍⁠‌⁠؜⁡⁣⁤',
  'form-builder.QuestionSidebar.DefaultUserSearchType':
    '⁣⁢Default Jira user search (Restricted)⁯⁪⁠؜⁪⁮‍⁡⁫؜؜⁫⁠⁡‌⁪⁪⁭⁮⁭⁮⁭‍⁬؜⁣⁤',
  'form-builder.QuestionSidebar.DefaultUserSearchTypeText1':
    '⁣⁢Only users with permission to access Jira can lookup other Jira users.⁭⁮⁫⁯⁯⁠؜⁮؜؜⁡⁭‍⁭‍⁯⁫⁫؜⁮‌⁭⁣⁤',
  'form-builder.QuestionSidebar.DefaultUserSearchTypeText2':
    '⁣⁢This search will NOT work for customers and anonymous users in the Jira Service Management portal.⁡⁫⁡‍⁮⁠‌‍⁪⁫؜⁯‍⁠⁫⁡؜⁬⁮⁪⁠⁣⁤',
  'form-builder.QuestionSidebar.Description':
    '⁣⁢Description⁯⁭‍⁯⁭⁡⁯؜‍‌⁯؜⁯⁠⁬⁡⁪‌‌‍⁣⁤',
  'form-builder.QuestionSidebar.DescriptionPlaceholder':
    '⁣⁢No description⁠⁬‌⁭‍⁯⁮⁮⁪⁭⁠⁬⁪⁮⁭⁡⁠⁭⁮⁮⁯⁫‍⁣⁤',
  'form-builder.QuestionSidebar.DoNotLink':
    '⁣⁢Do not link‌؜؜‌⁡؜⁡⁡⁪⁮⁪⁮⁯‌⁭⁠⁯⁬⁮⁯⁡‌⁯⁭⁣⁤',
  'form-builder.QuestionSidebar.EditProperties':
    '⁣⁢Edit Properties⁯⁮⁪‍⁯⁭؜⁭⁡⁪⁯⁮؜⁮⁪⁬⁯⁣⁤',
  'form-builder.QuestionSidebar.FieldChoiceChangePopup.Cancel':
    '⁣⁢Cancel⁭⁡⁭⁡⁠⁯⁯‌⁪⁫⁠⁯⁠⁬⁭⁡⁮⁬⁬⁯⁮⁬⁣⁤',
  'form-builder.QuestionSidebar.FieldChoiceChangePopup.Heading':
    '⁣⁢Choices will be replaced⁬⁬‍⁬⁮‌‌‌‍⁮⁠⁫⁭⁯⁭⁬‍⁯⁭⁭⁬⁣⁤',
  'form-builder.QuestionSidebar.FieldChoiceChangePopup.Message':
    '⁣⁢Linking to the {jiraFieldName} Jira field will replace all of your existing choices for the question with the Jira field choices.⁮⁪⁬⁯‍⁠⁪⁮؜⁠⁡‌⁯⁮‍⁠⁭⁠⁫⁮⁬‍⁯⁠⁡‍⁣⁤',
  'form-builder.QuestionSidebar.FieldChoiceChangePopup.ReplaceChoices':
    '⁣⁢Replace choices‌⁯⁪⁮‍؜⁬؜؜⁫‌⁮⁪⁫‌⁬⁮⁭‌⁪⁣⁤',
  'form-builder.QuestionSidebar.FieldTypeChangePopup.Cancel':
    '⁣⁢Cancel⁮⁪‍⁮⁫‌؜⁭⁮‌⁡⁯؜⁬‍⁮⁮‍⁡‌⁣⁤',
  'form-builder.QuestionSidebar.FieldTypeChangePopup.ChangeType':
    '⁣⁢Change type⁠‌‍⁠‍‌⁫‍⁯⁭‍⁪⁭⁭⁫⁭⁪‍⁮⁪‍؜⁠⁪⁣⁤',
  'form-builder.QuestionSidebar.FieldTypeChangePopup.CurrentQuestionType':
    '⁣⁢Current question type:‍⁬⁪⁮⁬⁫⁪⁬⁡⁭⁠⁠⁪⁮⁪⁬‍‍⁭‌⁣⁤',
  'form-builder.QuestionSidebar.FieldTypeChangePopup.Heading':
    '⁣⁢Question type will change‌‍؜⁮⁠⁠⁫⁫⁡⁭‍⁪؜‍⁭⁫‌؜⁪؜‌⁬⁣⁤',
  'form-builder.QuestionSidebar.FieldTypeChangePopup.NewQuestionType':
    '⁣⁢New question type:⁯⁠⁯⁯⁭⁠‌⁪‍‌⁮⁠‍⁪‍⁭‍⁠⁡⁡⁫؜⁠⁣⁤',
  'form-builder.QuestionSidebar.FieldTypeChangePopup.WillChangeQuestionType':
    '⁣⁢Linking to the {jiraFieldName} Jira field will change the question type.‍⁮⁫⁯‍⁮‍⁬⁬⁭⁡⁪⁫⁬‌⁠⁪⁯⁬⁠؜؜‍⁠⁣⁤',
  'form-builder.QuestionSidebar.InsightChoicesLimitMsg':
    '⁣⁢This question will not display more than {insightChoicesLimit} choices. If there are more choices, the person filling out the form will not be able to choose them.⁬⁬⁮⁯⁡⁮⁬⁪‌‌⁭⁡⁡⁮⁬⁡‍⁡⁮⁮⁯⁬⁠⁣⁤',
  'form-builder.QuestionSidebar.InsightChoicesLimitTitle':
    '⁣⁢Linked Insight Choices Limit⁬⁮⁪⁫‍⁠؜⁬⁭‌؜⁯⁯⁬⁬‍⁯⁠⁯⁠⁭⁭⁫⁣⁤',
  'form-builder.QuestionSidebar.Label': '⁣⁢Label‌⁮‍⁮⁪⁪‍⁭⁯⁡⁮⁪‍⁯⁯⁯‌؜⁫⁯⁣⁤',
  'form-builder.QuestionSidebar.LabelPlaceholder':
    '⁣⁢No label‌‌⁫‌‌⁯⁬⁭⁮⁫⁠⁡؜⁫‍⁫⁯‍⁭⁠⁯‌‍⁣⁤',
  'form-builder.QuestionSidebar.LinkedJiraField':
    '⁣⁢Linked Jira Field‍⁯⁭⁯⁫‍؜⁯⁪⁬⁠‌‍⁬⁮⁯⁯⁬‍⁭⁣⁤',
  'form-builder.QuestionSidebar.LinkedJiraFieldPlaceholder':
    '⁣⁢Select a field؜‍⁮‍⁡⁠⁭⁮⁮‌⁪‌⁭⁮⁬‍⁭⁪⁬⁮⁪⁭⁪⁣⁤',
  'form-builder.QuestionSidebar.LoadingFields':
    '⁣⁢Loading fields...‍⁬؜‌⁬⁬⁪⁫⁭⁠⁡⁬⁮⁠؜⁪⁮‌⁭⁡⁯⁫؜⁣⁤',
  'form-builder.QuestionSidebar.NewChoicePlaceholder':
    '⁣⁢New Choice⁮⁪⁫⁡⁬⁠⁫⁪⁡⁡⁭⁫‌⁮⁫⁡⁪‌⁭⁬⁯⁯⁠‍⁣⁤',
  'form-builder.QuestionSidebar.QuestionJiraFieldDropdown.InUse':
    '⁣⁢in use‍؜⁬⁫⁯‍⁡⁡‌⁡⁠⁪‌⁫⁬⁮؜‌⁠⁠⁮⁫‍⁮⁬⁣⁤',
  'form-builder.QuestionSidebar.QuestionJiraFieldDropdown.ReadOnly':
    '⁣⁢read only⁠⁫⁪؜‍⁪⁬⁯⁠؜⁭⁮⁯‌⁭⁭‍⁯؜⁮⁯‌⁣⁤',
  'form-builder.QuestionSidebar.QuestionKey':
    '⁣⁢Question Key⁭⁡⁬⁭⁯⁬⁯؜؜⁭⁠⁫⁯⁠⁪‍⁭‍⁯⁯⁫‍⁬⁬⁣⁤',
  'form-builder.QuestionSidebar.QuestionKeyErrorMsg':
    '⁣⁢This question key is in use on another question on this form⁭‌‌⁮⁭⁫؜⁯‌⁭‍‌⁮⁫‌⁫⁡‌⁣⁤',
  'form-builder.QuestionSidebar.QuestionKeyPlaceholder':
    '⁣⁢No question key‍‌؜⁠⁠⁯⁫⁡⁮⁫⁠⁫⁫⁡⁬⁪⁠‌⁫⁮‍⁣⁤',
  'form-builder.QuestionSidebar.QuestionKeys.Close':
    '⁣⁢Close⁫⁡⁡⁮⁬⁭⁮⁮⁠⁮؜⁮⁡؜⁡⁪⁬⁡⁮⁣⁤',
  'form-builder.QuestionSidebar.QuestionKeys.Heading':
    '⁣⁢Question key in use؜‍؜⁫⁡⁭⁭‌‌؜‍⁮⁬‍⁡⁫⁯⁯⁡⁫‌⁮‌⁡⁡⁯‌⁣⁤',
  'form-builder.QuestionSidebar.QuestionKeys.Message':
    '⁣⁢The question key "{questionKey}" is already in use on this form. Please choose another question key.⁫⁪⁠⁪⁪⁪‍⁪‌⁮⁮⁬⁫⁠⁬⁭⁯⁬⁮⁯‌⁭⁭⁭⁣⁤',
  'form-builder.QuestionSidebar.ReadOnly':
    '⁣⁢Read only؜⁪⁬‍‍⁭⁯⁫⁮⁭⁬⁫⁡⁡⁯⁯⁯‌⁭⁡؜⁬⁬‌⁠⁣⁤',
  'form-builder.QuestionSidebar.RemoveDataConnectionPopup.Cancel':
    '⁣⁢Cancel⁮⁫⁪⁫؜⁡⁮⁭‍⁮⁫⁮⁮⁪‌؜؜‌⁭‍⁮⁯⁣⁤',
  'form-builder.QuestionSidebar.RemoveDataConnectionPopup.Choice':
    '⁣⁢Choice⁯⁭⁮‌⁪⁡⁫‍⁬⁡⁯‍⁭⁬⁯؜⁭⁪⁣⁤',
  'form-builder.QuestionSidebar.RemoveDataConnectionPopup.CurrentQuestionType':
    '⁣⁢Current question type:‌⁯‍⁠‍‍⁭⁪‍؜⁠⁫⁪⁮⁯‌⁡⁮⁮⁠⁡⁪‌⁣⁤',
  'form-builder.QuestionSidebar.RemoveDataConnectionPopup.Heading':
    '⁣⁢Link to data connection will be removed⁡⁭‍⁫؜⁡⁪⁬؜⁬⁮⁭⁭‌⁭؜⁫⁮‍‍⁪⁫⁠⁪⁡⁡⁬⁠⁣⁤',
  'form-builder.QuestionSidebar.RemoveDataConnectionPopup.Message':
    '⁣⁢This question includes choices from a data connection to an outside source. Changing the question type will disconnect the question from {dataConnectionName}.⁬⁪⁪⁭⁡‍⁡‌⁡⁪⁭⁮⁡⁠⁯⁮⁪‌⁪⁯⁭⁣⁤',
  'form-builder.QuestionSidebar.RemoveDataConnectionPopup.NewQuestionType':
    '⁣⁢New question type:‌⁫⁪⁭⁭⁮⁪⁭⁪⁠⁫⁬⁪⁮⁠‌⁫⁮⁪⁭⁭‍⁡⁠⁣⁤',
  'form-builder.QuestionSidebar.RemoveDataConnectionPopup.RemoveDataConnection':
    '⁣⁢Remove data connection‌؜⁪⁯⁠⁡⁮؜⁪⁬⁯⁠؜⁡⁯⁬‍‍؜‍؜⁣⁤',
  'form-builder.QuestionSidebar.RemoveJiraFieldPopup.Cancel':
    '⁣⁢Cancel‍؜⁬؜⁭⁡⁯⁯‌⁭‍⁡⁮⁡⁭⁯؜⁭⁮⁪⁭⁠⁭⁣⁤',
  'form-builder.QuestionSidebar.RemoveJiraFieldPopup.CannotRemainLinked':
    '⁣⁢The {jiraFieldName} Jira field stores data in a different format and so cannot remain linked.⁪⁡⁠⁭‌⁠⁮⁫⁬⁫⁯⁮⁯⁮‍⁮‌⁡‍⁭⁡؜⁮؜⁣⁤',
  'form-builder.QuestionSidebar.RemoveJiraFieldPopup.CurrentQuestionType':
    '⁣⁢Current question type:⁡⁪⁠‌⁪⁯⁫⁭؜‌⁠⁭⁭⁮؜‍⁪⁪⁮⁭⁪⁫‍⁭⁣⁤',
  'form-builder.QuestionSidebar.RemoveJiraFieldPopup.Heading':
    '⁣⁢Link to Jira field will be removed‌⁠⁡⁭⁫⁭⁪⁪⁫⁮‍‍؜⁬⁡⁪⁠⁫⁪⁯⁬؜⁫⁭⁣⁤',
  'form-builder.QuestionSidebar.RemoveJiraFieldPopup.NewQuestionType':
    '⁣⁢New question type:⁯⁡⁪⁫⁯⁬⁪‌⁯⁭⁡⁬⁫⁠‍⁮⁮⁪⁯؜⁭⁣⁤',
  'form-builder.QuestionSidebar.RemoveJiraFieldPopup.RemoveJiraField':
    '⁣⁢Remove Jira field⁭⁯‍⁭⁠⁯⁭⁯⁫‍‍؜⁯⁡⁪⁯‍⁪⁬؜⁣⁤',
  'form-builder.QuestionSidebar.RemoveJiraFieldPopup.WillRemoveLink':
    '⁣⁢Changing the question type will remove the link to a Jira field.⁯؜⁬⁫⁡⁪⁬⁪⁭⁡⁫⁯⁪⁮⁠⁪⁮⁡⁠⁮⁣⁤',
  'form-builder.QuestionSidebar.SearchTypesExplainedTitle':
    '⁣⁢Search Types Explained‌⁪‍⁬⁭⁡⁪⁮⁫‍⁬⁮⁭⁡‍‍؜⁡⁠⁣⁤',
  'form-builder.QuestionSidebar.Section': '⁣⁢Section⁬⁡⁫‍؜⁭‍‍⁬⁡⁮⁮⁯⁠؜⁠؜⁫⁯⁯⁮؜⁣⁤',
  'form-builder.QuestionSidebar.ShowAllChoices':
    '⁣⁢Show all {choicesLength} choices⁪⁭⁬‍؜⁡⁬⁪‍⁭؜‌⁮⁬‌⁯⁯‌⁫⁠⁬‍‌⁣⁤',
  'form-builder.QuestionSidebar.ShowFirstChoices':
    '⁣⁢Show first {choicesLength} choices⁬⁠⁯⁫⁡⁪⁬؜⁫⁭⁪‌‌⁬⁡؜⁮⁯⁭⁯⁮⁫⁮⁣⁤',
  'form-builder.QuestionSidebar.SubTitle':
    '⁣⁢Questions provide a place for answers to be filled in.‍⁠⁠⁯⁡؜⁠⁬؜؜‍⁠⁮⁫‍⁪⁭‌؜؜⁡‍⁪‍‌‍⁣⁤',
  'form-builder.QuestionSidebar.Title': '⁣⁢Question؜⁪⁭⁠⁡⁭؜⁪⁠⁬‌⁫⁮⁮⁮⁯⁪‍⁠⁡⁡⁯⁣⁤',
  'form-builder.QuestionSidebar.Type': '⁣⁢Type‌⁠⁫⁮⁭⁭؜⁫⁬⁮‍⁠⁫‍⁫‌⁣⁤',
  'form-builder.QuestionSidebar.UnknownDataConnection':
    '⁣⁢Unknown data connection: {dataConnectionId}⁯⁮⁮⁯⁬⁬⁯⁮⁪⁪‌⁭⁬⁪؜‌‍‌؜⁮‍⁠⁫⁡⁠⁣⁤',
  'form-builder.QuestionSidebar.UnknownJirafield':
    '⁣⁢Unknown Jira field: {jiraFieldKey}⁯⁡⁭⁬⁭⁪؜⁬⁬⁯⁬⁡⁭⁡‌؜⁠‍⁯⁪⁡؜⁡⁮⁯⁭‍⁣⁤',
  'form-builder.QuestionSidebar.UnknownSearchType':
    '⁣⁢Unknown search type: {searchTypeKey}⁯⁫؜⁮‌‍⁮⁡⁠⁯⁬⁯⁫⁮⁭‌⁬؜⁠⁣⁤',
  'form-builder.QuestionSidebar.UserSearchType':
    '⁣⁢User Search Type⁫⁪⁯؜⁠⁮‌⁮‌‍‍‍⁯⁫⁭؜⁡؜⁯⁡‍‌؜⁯⁣⁤',
  'form-builder.QuestionSidebar.UsersWithBrowseProjectsSearchText':
    '⁣⁢Both Jira and Portal users can lookup Jira users who have the Browse project permission for this project.‍؜⁫⁫‌‌⁫⁠⁮⁭⁯‍⁭⁭⁯⁡‍؜‍⁠‌⁪⁣⁤',
  'form-builder.QuestionSidebar.UsersWithBrowseProjectsSearchType':
    '⁣⁢Users with Browse Project permission‌⁭⁬⁮⁫⁡؜⁭؜⁠⁮‌⁯‌⁯‍⁮⁯⁣⁤',
  'form-builder.QuestionSidebar.Validation':
    '⁣⁢Validation⁫⁡⁪⁬‌⁡⁠⁡⁯⁯⁬‍⁪⁮⁠⁡⁬⁯‌⁮⁠‌⁣⁤',
  'form-builder.QuestionSidebar.ValidationCharacters':
    '⁣⁢Characters⁠؜⁭⁮⁮⁯؜⁠⁯⁯⁠⁭⁫⁫‌⁮⁪⁠⁡⁪⁬⁪⁮⁣⁤',
  'form-builder.QuestionSidebar.ValidationMatchRegex':
    '⁣⁢Must match regex pattern⁪؜⁫⁮⁠⁬‌⁠⁭⁭⁫‍⁫⁬⁮⁭⁭‌⁮⁣⁤',
  'form-builder.QuestionSidebar.ValidationMaxChoices':
    '⁣⁢Maximum number of choices⁡؜⁭⁪‍⁫⁯⁪؜⁭⁮‍⁭⁭⁠‌⁡⁮⁮⁪⁪⁯‌⁣⁤',
  'form-builder.QuestionSidebar.ValidationMaxDate':
    '⁣⁢Latest date‌⁡⁭⁮⁭⁭⁯‍⁫⁮⁭⁯⁠⁫⁡⁬⁭؜⁫⁫⁯⁫⁪⁭⁫⁣⁤',
  'form-builder.QuestionSidebar.ValidationMaxDateAndTime':
    '⁣⁢Latest date & time⁭⁪⁠⁮⁠⁬⁡⁮⁡⁫‌‌‌⁠⁡⁭⁬⁡⁡‌؜⁣⁤',
  'form-builder.QuestionSidebar.ValidationMaxDatePlaceholder':
    '⁣⁢No maximum date؜⁬⁡‍‍⁫؜⁭⁮‍؜‍⁫⁯⁯‍⁪⁪⁬⁬‌⁬⁡⁣⁤',
  'form-builder.QuestionSidebar.ValidationMaxTime':
    '⁣⁢Latest time⁡⁫‌⁠‍⁬⁭⁠⁯⁫⁫⁭‌⁠‍⁬‍⁫⁡⁪⁯⁬⁣⁤',
  'form-builder.QuestionSidebar.ValidationMaxTimePlaceholder':
    '⁣⁢No maximum time⁯⁮⁫⁭⁡⁫⁯⁫⁠‌؜؜⁮⁪⁯⁯‌⁬⁠⁭؜⁣⁤',
  'form-builder.QuestionSidebar.ValidationMaximum':
    '⁣⁢Maximum⁮⁡⁮⁮⁫⁡؜⁬⁡⁫⁪⁭⁠⁯‌‍⁪⁡⁫⁡⁯⁡⁣⁤',
  'form-builder.QuestionSidebar.ValidationMaximumPlaceholder':
    '⁣⁢No max⁠⁮‍‌⁪⁫‌⁬‍⁬⁡⁬⁫؜⁡‌⁯⁪⁯⁪‌⁮⁫⁠⁡⁣⁤',
  'form-builder.QuestionSidebar.ValidationMinChoices':
    '⁣⁢Minimum number of choices‌؜⁫⁭⁯⁡⁪⁡؜⁮⁬⁪⁫؜⁮⁫⁠⁡؜⁭⁠‌⁡⁪⁣⁤',
  'form-builder.QuestionSidebar.ValidationMinDate':
    '⁣⁢Earliest date⁫⁭⁡؜⁡⁪⁮‍‍؜⁡⁭⁠⁯؜⁭⁪⁫⁭⁠⁣⁤',
  'form-builder.QuestionSidebar.ValidationMinDateAndTime':
    '⁣⁢Earliest date & time⁡⁯⁬⁫؜⁮⁫⁡⁬⁬⁠⁫⁡⁡⁭⁭⁫⁪⁬⁣⁤',
  'form-builder.QuestionSidebar.ValidationMinDatePlaceholder':
    '⁣⁢No minimum date⁭⁠⁪⁫؜⁮⁮‍⁡⁡⁫⁡⁭⁡⁪‍؜؜⁫؜⁪⁯⁠⁫⁫⁪؜⁣⁤',
  'form-builder.QuestionSidebar.ValidationMinTime':
    '⁣⁢Earliest time⁫⁬⁡⁪⁯⁬⁡‍⁭⁪⁪⁮⁭‍⁪⁮⁬‌⁠⁯⁡⁡⁣⁤',
  'form-builder.QuestionSidebar.ValidationMinTimePlaceholder':
    '⁣⁢No minimum time⁠⁯⁬‍⁪⁪‌‍⁪⁬⁫⁭⁪‌⁪⁯⁡؜‌⁬؜⁣⁤',
  'form-builder.QuestionSidebar.ValidationMinimum':
    '⁣⁢Minimum⁠‌⁡‍‌⁫⁠‌‌⁭⁬؜⁮‌⁬⁮⁭⁠⁪؜⁪⁣⁤',
  'form-builder.QuestionSidebar.ValidationMinimumPlaceholder':
    '⁣⁢No min⁠‌⁡⁠⁫⁯؜⁡⁬‌⁪⁯⁠⁡⁮‍⁣⁤',
  'form-builder.QuestionSidebar.ValidationNumChoicesLoading':
    '⁣⁢Loading...⁠⁡⁪⁪‌⁠⁪⁡‌⁪⁯⁯⁭؜⁡⁬‍⁮⁭⁪‌⁣⁤',
  'form-builder.QuestionSidebar.ValidationNumChoicesNone':
    '⁣⁢None‌⁮⁭‍‍‌⁬⁮⁫⁠⁯⁭؜⁡⁫⁬⁬⁫⁯‌⁮⁫⁫⁮⁣⁤',
  'form-builder.QuestionSidebar.ValidationNumChoicesOptions':
    '⁣⁢Options⁪⁪‌‍⁯؜⁠‍؜⁯⁫؜⁭⁠؜‍⁪⁡⁬⁯‍⁪‌⁭؜‍⁫⁣⁤',
  'form-builder.QuestionSidebar.ValidationNumber':
    '⁣⁢Number‍⁡⁬⁮⁯⁪⁯‌⁬⁯⁫⁫⁯⁠⁡⁪⁯⁪⁡‍⁫؜⁬⁣⁤',
  'form-builder.QuestionSidebar.ValidationRegexExample':
    '⁣⁢examples؜⁮⁡⁡⁬⁠⁯⁠⁪⁫‌⁫⁮⁫⁬‌⁮⁯⁭⁫؜⁬‌⁭⁫⁫⁣⁤',
  'form-builder.QuestionSidebar.ValidationRegexMessage':
    '⁣⁢Regex: Message if input is invalid⁯⁮‍⁡⁬⁬⁭⁡⁠⁫‍⁪⁭‌⁡؜⁫؜⁭⁬⁬⁡‌⁮⁣⁤',
  'form-builder.QuestionSidebar.ValidationRegexPattern':
    '⁣⁢Regex: Pattern⁭⁫‌‍⁯‌⁫⁫⁪⁠⁠‌⁪؜⁫⁡‍‌⁮⁭‌⁡؜⁣⁤',
  'form-builder.QuestionSidebar.ValidationRegexPlaceholder':
    '⁣⁢e.g. \\d+؜‍⁬‌⁠⁯⁮‍‌‌‍⁯⁮⁪⁮⁮⁪⁬⁫⁪⁯⁡⁭⁡⁭‍⁣⁤',
  'form-builder.QuestionSidebar.ValidationRequiredChoice':
    '⁣⁢Required choice‍⁭⁮؜‍⁯‍⁡⁬⁮⁪؜⁫⁬؜⁠⁠⁣⁤',
  'form-builder.QuestionSidebar.ValidationRequiredChoicePlaceholder':
    '⁣⁢Select a required choice‌؜‌⁯⁮⁭⁠⁪‌⁭‌⁮⁮⁮⁡⁮⁫‍؜⁬⁭‌⁪⁡⁬‍⁪⁣⁤',
  'form-builder.QuestionSidebar.ValidationResponseRequired':
    '⁣⁢Response required⁡؜⁡؜⁠⁡؜⁮؜⁮⁬؜⁫‍‍‌⁬⁬⁪⁪؜‍⁣⁤',
  'form-builder.QuestionSidebar.ValidationWholeNumber':
    '⁣⁢Whole numbers only⁭؜⁮⁡⁡⁠⁮‌؜⁮‌⁮⁠⁭⁭⁠⁠؜⁪؜؜⁪‌⁣⁤',
  'form-builder.QuestionSidebar.ValidationWords':
    '⁣⁢Words⁡؜؜⁫؜‍⁯⁡⁭⁪⁠⁫⁪⁫⁬⁮⁫⁠؜⁯⁪⁣⁤',
  'form-builder.QuestionTypeDropdown.ChooseAQuestionType':
    '⁣⁢Choose a question type⁮⁡⁡⁬⁡⁯⁪⁡⁡‌⁫⁡‍⁪⁡؜⁠⁪⁭⁮⁠⁠⁭⁠⁣⁤',
  'form-builder.SectionSidebar.Heading': '⁣⁢Section؜⁭⁫⁡⁯⁡⁡⁯⁬‌⁮⁮⁮⁯؜⁫⁬‍⁮⁭⁣⁤',
  'form-builder.SectionSidebar.IsAnyOf': '⁣⁢Is any of:‍⁫‍⁯⁡‌⁬⁪؜⁫⁡⁪⁠⁪⁮‍⁯‌⁠⁪⁬⁯⁣⁤',
  'form-builder.SectionSidebar.Name': '⁣⁢Name‍⁬⁬؜⁡⁮⁠⁠⁫⁮⁮⁡⁬⁬⁬⁭⁮⁬؜⁣⁤',
  'form-builder.SectionSidebar.NamePlaceholder':
    '⁣⁢Unnamed⁡‌⁬⁪⁪⁫؜‍⁯⁡‌؜⁮⁪⁭⁠⁪⁠⁮⁭⁭‍⁭⁣⁤',
  'form-builder.SectionSidebar.Question': '⁣⁢Question:⁪⁡⁯‌⁯‍‌⁪⁡⁫⁪؜⁮⁡⁮⁭⁠⁬‍⁮⁣⁤',
  'form-builder.SectionSidebar.ShowSection':
    '⁣⁢Show section‌‍⁡؜‌⁬‍⁬‍⁠⁯⁮⁫‌؜⁭⁫؜⁭‍⁣⁤',
  'form-builder.SectionSidebar.ShowSectionAlways':
    '⁣⁢Always‍؜؜⁯⁭⁬⁮⁮⁯⁫⁫⁭؜⁡‌⁡؜⁬⁪⁫‌⁮⁮⁬⁠⁣⁤',
  'form-builder.SectionSidebar.ShowSectionConditionally':
    '⁣⁢Conditionally‍⁫⁬⁠⁡⁬⁪؜⁯⁠⁯⁮⁪⁡⁬‌⁬⁪⁡⁣⁤',
  'form-builder.SectionSidebar.SubHeading':
    '⁣⁢Sections group questions for conditional logic.؜⁫⁯⁮؜⁡⁠⁭⁯⁫⁠⁬⁯‍‌⁠⁡⁯⁮⁡⁮⁪⁪⁡⁪⁣⁤',
  'form-builder.SectionSidebar.When': '⁣⁢When⁡⁬⁬⁭‌‍؜⁭⁭⁯⁭‌⁭؜؜⁬⁬‌‌⁭⁬⁡؜⁠⁣⁤',
  'form-builder.TemplatesSidebar.InsertTemplate':
    '⁣⁢Insert Template‍⁮⁡⁪⁫⁬‍‌⁡‍⁡‌⁡⁠‍⁡⁭⁪⁭⁭⁭⁮⁣⁤',
  'form-builder.TemplatesSidebar.Language':
    '⁣⁢Language⁬⁯⁬⁮‍⁯‌‍⁬‍‍‍‌⁪⁯؜‍⁪؜؜‍⁭⁠⁯⁣⁤',
  'form-builder.TemplatesSidebar.LoadingTemplatePreview':
    '⁣⁢Loading template preview⁬‌⁫⁫⁮⁡⁠‍⁠‍‍⁯⁫⁮⁪⁮⁬؜؜‌⁪⁣⁤',
  'form-builder.TemplatesSidebar.New': '⁣⁢New !⁬⁮⁯⁮⁬⁬⁫⁬‍⁮⁬⁬⁭‍⁮⁬‌⁮⁯⁯⁬‌⁯‍⁫؜⁭⁠⁣⁤',
  'form-builder.TemplatesSidebar.Process': '⁣⁢Process⁮⁮‌⁮⁪⁭⁡⁭⁬⁫‍⁪⁡⁬؜⁫⁮؜⁫⁫⁭⁯⁣⁤',
  'form-builder.TemplatesSidebar.SearchTemplates':
    '⁣⁢Search Templates⁫⁮⁬؜⁯⁡⁬‍⁡‌⁮⁯⁬⁯‍⁡‍⁬⁮‍⁣⁤',
  'form-builder.TemplatesSidebar.Team': '⁣⁢Team‌⁪‌⁮⁫؜‍⁡⁠⁫⁭‍⁪⁠⁮⁫⁪⁡؜⁡⁮‍⁣⁤',
  'form-builder.TemplatesSidebar.TemplatePreview':
    '⁣⁢Template Preview⁬⁬⁭⁠⁫‍⁫⁭⁡⁪⁠⁠⁮⁬‌⁭⁡⁪؜⁮⁪⁠‍⁣⁤',
  'form-builder.TemplatesSidebar.Templates': '⁣⁢Templates؜⁮⁭؜‍⁫⁪⁮⁡⁭⁯⁪⁠⁬⁯‌⁭‍⁬⁣⁤',
  'form-builder.UserSearchType.UsersWithBrowseProjectPermission':
    '⁣⁢Users with Browse Project permission⁡⁠⁭⁡⁯⁠⁪⁠⁭⁯؜⁠‌⁮⁮⁪⁠⁭⁭⁮⁫⁪⁪‍⁪⁣⁤',
  'proforma-form-builder.EditorFormNamePlaceholder':
    '⁣⁢Give your form a name⁪⁪‍⁬⁠⁮⁡⁯⁠⁮⁬؜⁪⁭⁡⁡‍⁮⁮؜⁣⁤',
  'proforma-form-builder.Sidebar.InsertQuestionButtonLabel':
    '⁣⁢Questions⁠⁬‍⁭⁫‍⁮؜⁪⁬⁬‍⁮⁪⁬⁠⁭؜⁠؜⁡⁠⁯⁣⁤',
  'proforma-form-builder.Sidebar.InsertTemplateButtonLabel':
    '⁣⁢Template‌⁫⁬‌؜⁠⁡⁮⁭⁫؜؜⁮‍⁪‌⁪⁪⁡⁪⁬⁣⁤',
  'ui-form-builder.FormBuilder.DragHandleQuestionTooltip':
    '⁣⁢Reorder Question⁮؜⁠؜⁯⁭⁭⁫⁡⁭⁪⁡⁭⁬⁯⁮⁫⁪‍⁣⁤',
  'ui-form-builder.FormBuilder.DragHandleSectionTooltip':
    '⁣⁢Reorder Section‌⁫⁫⁬⁭‌⁪⁠⁡⁮⁮⁪⁪⁬⁫⁬؜⁪⁮⁡⁣⁤',
  'ui-form-builder.FormBuilder.SectionEnd':
    '⁣⁢Section end⁭⁪⁯⁭⁠⁬⁡⁫⁭‍⁭⁫⁯‍⁠⁡⁡⁬⁮⁫‌⁣⁤',
  'ui-form-builder.FormBuilder.SectionStart':
    '⁣⁢Section start⁮⁪؜⁪‌⁭⁫⁯⁯⁫؜⁭‌⁠⁪⁮⁪‍⁪⁫‌⁭⁡⁬⁣⁤',
};
