import {
  categoryMessages,
  extraMessages,
  featureNameMessages,
  freeEditionMessages,
  premiumEditionMessages,
  standardEditionMessages,
} from '../messages';
import { Features } from '../types';

export const features: Features = {
  confluence: [
    {
      key: 'userLimits',
      name: featureNameMessages.userLimit,
      free: freeEditionMessages.userLimit,
      standard: {
        title: standardEditionMessages.userLimitTitle,
        subTitle: standardEditionMessages.userLimitSubtitle,
      },
      premium: {
        title: premiumEditionMessages.userLimitTitle,
        subTitle: premiumEditionMessages.userLimitSubtitle,
      },
    },
    {
      key: 'storageConfluence',
      name: featureNameMessages.storage,
      free: freeEditionMessages.storage,
      standard: standardEditionMessages.storage,
      premium: premiumEditionMessages.storage,
    },
    {
      key: 'supportConfluence',
      name: featureNameMessages.support,
      free: freeEditionMessages.support,
      standard: standardEditionMessages.support,
      premium: premiumEditionMessages.support,
    },
    {
      key: 'pagePermissions',
      name: featureNameMessages.pagePermissions,
      free: false,
      standard: true,
      premium: true,
    },
    {
      key: 'spacePermissions',
      name: featureNameMessages.spacePermissions,
      free: false,
      standard: true,
      premium: true,
    },
    {
      key: 'advancedPermissionsConfluence',
      name: featureNameMessages.advancedPermissions,
      free: false,
      standard: true,
      premium: true,
    },
    {
      key: 'anonymousAccessConfluence',
      name: featureNameMessages.anonymousAccess,
      free: false,
      standard: true,
      premium: true,
    },
    {
      key: 'pageInsights',
      name: featureNameMessages.pageInsights,
      free: false,
      standard: true,
      premium: true,
    },
    {
      key: 'auditLogs',
      name: featureNameMessages.auditLogs,
      free: false,
      standard: true,
      premium: true,
    },
    {
      key: 'pageArchiving',
      name: featureNameMessages.pageArchiving,
      free: false,
      standard: true,
      premium: true,
    },
    {
      key: 'unlimitedSpacesAndPages',
      name: featureNameMessages.unlimitedSpacesAndPages,
      free: true,
      standard: true,
      premium: true,
    },
    {
      key: 'macros',
      name: featureNameMessages.macros,
      free: true,
      standard: true,
      premium: true,
    },
    {
      key: 'structuredPageTree',
      name: featureNameMessages.structuredPageTree,
      free: true,
      standard: true,
      premium: true,
    },
    {
      key: 'pageVersioning',
      name: featureNameMessages.pageVersioning,
      free: true,
      standard: true,
      premium: true,
    },
    {
      key: 'bestPracticesTemplates',
      name: featureNameMessages.bestPracticesTemplates,
      free: true,
      standard: true,
      premium: true,
    },
    {
      key: 'appsAndIntegrationsConfluence',
      name: featureNameMessages.appsAndIntegrations,
      free: true,
      standard: true,
      premium: true,
    },
    {
      key: 'externalCollaboration',
      name: featureNameMessages.externalCollaboration,
      lozenge: extraMessages.comingSoon,
      free: false,
      standard: false,
      premium: true,
    },
    {
      key: 'analytics',
      name: featureNameMessages.analytics,
      free: false,
      standard: false,
      premium: true,
    },
    {
      key: 'bulkArchivePages',
      name: featureNameMessages.bulkArchivePages,
      free: false,
      standard: false,
      premium: true,
    },
    {
      key: 'teamCalendars',
      name: featureNameMessages.teamCalendars,
      lozenge: extraMessages.comingSoon,
      free: false,
      standard: false,
      premium: true,
    },
    {
      key: 'inspectPermissions',
      name: featureNameMessages.inspectPermissions,
      free: false,
      standard: false,
      premium: true,
    },
    {
      key: 'copySpacePermissions',
      name: featureNameMessages.copySpacePermissions,
      free: false,
      standard: false,
      premium: true,
    },
    {
      key: 'adminKey',
      name: featureNameMessages.adminKey,
      free: false,
      standard: false,
      premium: true,
    },
    {
      key: 'adminInsightsConfluence',
      name: featureNameMessages.adminInsights,
      free: false,
      standard: false,
      premium: true,
    },
    {
      key: 'ipAllowlisting',
      name: featureNameMessages.ipAllowlisting,
      free: false,
      standard: false,
      premium: true,
    },
    {
      key: 'sandboxConfluence',
      name: featureNameMessages.sandbox,
      lozenge: extraMessages.beta,
      free: false,
      standard: false,
      premium: true,
    },
    {
      key: 'releaseTracksConfluence',
      name: featureNameMessages.releaseTracks,
      lozenge: extraMessages.beta,
      free: false,
      standard: false,
      premium: true,
    },
    {
      key: 'uptimeSla',
      name: featureNameMessages.uptimeSla,
      free: false,
      standard: false,
      premium: premiumEditionMessages.uptimeSla,
    },
  ],
  'jira-software': [
    {
      key: 'siteEssentials',
      name: categoryMessages.siteEssentials,
    },
    {
      key: 'userLimitsJsw',
      name: featureNameMessages.userLimit,
      free: freeEditionMessages.userLimit,
      standard: standardEditionMessages.userLimitTitle,
      premium: premiumEditionMessages.userLimitTitle,
    },
    {
      key: 'storageJsw',
      name: featureNameMessages.storage,
      free: freeEditionMessages.storage,
      standard: standardEditionMessages.storage,
      premium: premiumEditionMessages.storage,
    },
    {
      key: 'supportJsw',
      name: featureNameMessages.support,
      free: freeEditionMessages.support,
      standard: standardEditionMessages.support,
      premium: premiumEditionMessages.support,
    },
    {
      key: 'advanceFeatures',
      name: categoryMessages.advanceFeatures,
    },
    {
      key: 'automation',
      name: featureNameMessages.automation,
      free: freeEditionMessages.freeAutomation,
      standard: standardEditionMessages.standardAutomation,
      premium: premiumEditionMessages.premiumAutomation,
    },
    {
      key: 'capacityPlanning',
      name: featureNameMessages.capacityPlanning,
      free: false,
      standard: false,
      premium: true,
    },
    {
      key: 'dependencyManagement',
      name: featureNameMessages.dependencyManagement,
      free: freeEditionMessages.basicFeature,
      standard: standardEditionMessages.basicFeature,
      premium: premiumEditionMessages.advancedFeature,
    },
    {
      key: 'projectArchiving',
      name: featureNameMessages.projectArchiving,
      free: false,
      standard: false,
      premium: true,
    },
    {
      key: 'roadmaps',
      name: featureNameMessages.roadmaps,
      free: freeEditionMessages.basicFeature,
      standard: standardEditionMessages.basicFeature,
      premium: premiumEditionMessages.advancedFeature,
    },
    {
      key: 'adminControls',
      name: categoryMessages.adminControls,
    },
    {
      key: 'adminInsightsJsw',
      name: featureNameMessages.adminInsights,
      free: false,
      standard: false,
      premium: true,
    },
    {
      key: 'advancedUserPermissionsJsw',
      name: featureNameMessages.advancedPermissions,
      free: false,
      standard: true,
      premium: true,
    },
    {
      key: 'projectRoles',
      name: featureNameMessages.projectRoles,
      free: false,
      standard: true,
      premium: true,
    },
    {
      key: 'releaseTracksJsw',
      name: featureNameMessages.releaseTracks,
      free: false,
      standard: false,
      premium: true,
    },
    {
      key: 'sandboxJsw',
      name: featureNameMessages.sandbox,
      free: false,
      standard: false,
      premium: true,
    },
    {
      key: 'securityCompliance',
      name: categoryMessages.securityCompliance,
    },
    {
      key: 'anonymousAccessJsw',
      name: featureNameMessages.anonymousAccess,
      free: false,
      standard: true,
      premium: true,
    },
    {
      key: 'auditLogs',
      name: featureNameMessages.auditLogs,
      free: false,
      standard: true,
      premium: true,
    },
    {
      key: 'dataResidency',
      name: featureNameMessages.dataResidency,
      free: false,
      standard: true,
      premium: true,
    },
    {
      key: 'ipAllowlisting',
      name: featureNameMessages.ipAllowlisting,
      free: false,
      standard: false,
      premium: true,
    },
    {
      key: 'uptimeSlaJsw',
      name: featureNameMessages.uptimeSla,
      free: false,
      standard: false,
      premium: premiumEditionMessages.uptimeSla,
    },
    {
      key: 'coreFeatures',
      name: categoryMessages.coreFeatures,
    },
    {
      key: 'agileReporting',
      name: featureNameMessages.agileReporting,
      free: true,
      standard: true,
      premium: true,
    },
    {
      key: 'appsAndIntegrationsJsw',
      name: featureNameMessages.appsAndIntegrations,
      free: true,
      standard: true,
      premium: true,
    },
    {
      key: 'backlog',
      name: featureNameMessages.backlog,
      free: true,
      standard: true,
      premium: true,
    },
    {
      key: 'businessContinuity',
      name: featureNameMessages.businessContinuityDisasterRecovery,
      free: true,
      standard: true,
      premium: true,
    },
    {
      key: 'customizableWorkflows',
      name: featureNameMessages.customizableWorkflows,
      free: true,
      standard: true,
      premium: true,
    },
    {
      key: 'domainVerification',
      name: featureNameMessages.domainVerificationAccountCapture,
      free: true,
      standard: true,
      premium: true,
    },
    {
      key: 'encryptionInTransit',
      name: featureNameMessages.encryption,
      free: true,
      standard: true,
      premium: true,
    },
    {
      key: 'mobileDeviceManagement',
      name: featureNameMessages.mobileDeviceManagement,
      free: true,
      standard: true,
      premium: true,
    },
    {
      key: 'passwordPolicies',
      name: featureNameMessages.passwordPolicies,
      free: true,
      standard: true,
      premium: true,
    },
    {
      key: 'scrumAndKanbanBoards',
      name: featureNameMessages.scrumAndKanbanBoards,
      free: true,
      standard: true,
      premium: true,
    },
    {
      key: 'sessionDurationManagement',
      name: featureNameMessages.sessionDurationManagement,
      free: true,
      standard: true,
      premium: true,
    },
  ],
  'jira-servicedesk': [
    {
      key: 'agentLimit',
      name: featureNameMessages.agentLimit,
      free: freeEditionMessages.agentLimit,
      standard: {
        title: standardEditionMessages.agentLimitTitle,
        subTitle: standardEditionMessages.agentLimitSubtitle,
      },
      premium: {
        title: premiumEditionMessages.agentLimitTitle,
        subTitle: premiumEditionMessages.agentLimitSubtitle,
      },
    },
    {
      key: 'storageJsm',
      name: featureNameMessages.storage,
      free: freeEditionMessages.storage,
      standard: standardEditionMessages.storage,
      premium: premiumEditionMessages.storage,
    },
    {
      key: 'supportJsm',
      name: featureNameMessages.support,
      free: freeEditionMessages.support,
      standard: standardEditionMessages.support,
      premium: premiumEditionMessages.support,
    },
    {
      key: 'majorIncidentsPerMonth',
      name: featureNameMessages.majorIncidentsPerMonth,
      free: freeEditionMessages.majorIncidentsPerMonth,
      standard: standardEditionMessages.majorIncidentsPerMonth,
      premium: premiumEditionMessages.majorIncidentsPerMonth,
    },
    {
      key: 'postMortems',
      name: featureNameMessages.postMortems,
      free: freeEditionMessages.postMortems,
      standard: standardEditionMessages.postMortems,
      premium: premiumEditionMessages.postMortems,
    },
    {
      key: 'incidentCreation',
      name: featureNameMessages.incidentCreation,
      free: freeEditionMessages.incidentCreation,
      standard: standardEditionMessages.incidentCreation,
      premium: premiumEditionMessages.incidentCreation,
    },
    {
      key: 'alertsNotificationsPerMonth',
      name: featureNameMessages.monthlyAlertsAndNotifications,
      free: freeEditionMessages.monthlyAlertsAndNotifications,
      standard: standardEditionMessages.monthlyAlertsAndNotifications,
      premium: premiumEditionMessages.monthlyAlertsAndNotifications,
    },
    {
      key: 'itServiceManagement',
      name: featureNameMessages.itServiceManagement,
      free: true,
      standard: true,
      premium: true,
    },
    {
      key: 'serviceStatusPages',
      name: featureNameMessages.serviceStatusPages,
      free: false,
      standard: true,
      premium: true,
    },
    {
      key: 'serviceDependency',
      name: featureNameMessages.serviceDependency,
      free: false,
      standard: true,
      premium: true,
    },
    {
      key: 'auditLogs',
      name: featureNameMessages.auditLogs,
      free: false,
      standard: true,
      premium: true,
    },
    {
      key: 'anonymousAccessJsm',
      name: featureNameMessages.anonymousAccess,
      free: false,
      standard: true,
      premium: true,
    },
    {
      key: 'slaManagement',
      name: featureNameMessages.slaManagement,
      free: true,
      standard: true,
      premium: true,
    },
    {
      key: 'automationAndWorkflows',
      name: featureNameMessages.automationAndWorkflows,
      free: true,
      standard: true,
      premium: true,
    },
    {
      key: 'reportingAndAnalytics',
      name: featureNameMessages.reportingAndAnalytics,
      free: true,
      standard: true,
      premium: true,
    },
    {
      key: 'appsAndIntegrationsJsm',
      name: featureNameMessages.appsAndIntegrations,
      free: true,
      standard: true,
      premium: true,
    },
    {
      key: 'monitoringAndChatOpsIntegrations',
      name: featureNameMessages.monitoringAndChatOpsIntegrations,
      free: true,
      standard: true,
      premium: true,
    },
    {
      key: 'incidentCommandCenter',
      name: featureNameMessages.incidentCommandCenter,
      free: false,
      standard: false,
      premium: true,
    },
    {
      key: 'incidentInvestigation',
      name: featureNameMessages.incidentInvestigation,
      free: false,
      standard: false,
      premium: true,
    },
    {
      key: 'majorIncidentAnalytics',
      name: featureNameMessages.majorIncidentAnalytics,
      free: false,
      standard: false,
      premium: true,
    },
    {
      key: 'automationMultiProject',
      name: featureNameMessages.globalAutomation,
      free: false,
      standard: false,
      premium: true,
    },
    {
      key: 'serviceSubscriptions',
      name: featureNameMessages.serviceSubscriptions,
      free: false,
      standard: false,
      premium: true,
    },
    {
      key: 'externalServices',
      name: featureNameMessages.externalServices,
      free: false,
      standard: false,
      premium: true,
    },
    {
      key: 'serviceHealthAnalysis',
      name: featureNameMessages.serviceHealthAnalysis,
      free: false,
      standard: false,
      premium: true,
    },
    {
      key: 'adminInsightsJsm',
      name: featureNameMessages.adminInsights,
      free: false,
      standard: false,
      premium: true,
    },
    {
      key: 'ipAllowlisting',
      name: featureNameMessages.ipAllowlisting,
      free: false,
      standard: false,
      premium: true,
    },
    {
      key: 'releaseTracksJsm',
      name: featureNameMessages.releaseTracks,
      lozenge: extraMessages.beta,
      free: false,
      standard: false,
      premium: true,
    },
    {
      key: 'sandboxJsm',
      name: featureNameMessages.sandbox,
      lozenge: extraMessages.beta,
      free: false,
      standard: false,
      premium: true,
    },
    {
      key: 'uptimeSla',
      name: featureNameMessages.uptimeSla,
      free: false,
      standard: false,
      premium: premiumEditionMessages.uptimeSla,
    },
  ],
};
