/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Czech
export default {
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.automated-path':
    'Automatizovaná cesta',
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.contact-vendor':
    'Kontaktujte dodavatele',
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.contact-vendor-tooltip':
    'Ohledně migrace této aplikace kontaktujte dodavatele.',
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.sign-up-for-eap':
    'Registrovat do programu PEA',
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.track-request':
    'Sledovat žádost',
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.upgrade-app':
    'Upgradovat aplikaci',
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.upgrade-app-tooltip':
    'Tato verze aplikace nepodporuje automatizovanou migraci, ale novější verze ano.',
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.view-path':
    'Zobrazit cestu',
  'com.atlassian.migrations-platform.app-assessment-table.app-decision-value.alternative':
    'Použít alternativu',
  'com.atlassian.migrations-platform.app-assessment-table.app-decision-value.needed':
    'Je potřeba v cloudu',
  'com.atlassian.migrations-platform.app-assessment-table.app-decision-value.not-needed':
    'Není potřeba v cloudu',
  'com.atlassian.migrations-platform.app-assessment-table.app-decision-value.unassigned':
    'Bez učiněného rozhodnutí',
  'com.atlassian.migrations-platform.app-assessment-table.app-notes-value.placeholder':
    'Zde zadejte své poznámky',
  'com.atlassian.migrations-platform.app-assessment-table.app-usage-value.disabled-message':
    'Vypnuto',
  'com.atlassian.migrations-platform.app-assessment-table.app-usage-value.not-applicable-message':
    'Nelze použít*',
  'com.atlassian.migrations-platform.app-assessment-table.app-usage-value.not-applicable-tooltip-page':
    'Toto není aplikace založená na makrech a nezobrazuje se na žádné stránce.',
  'com.atlassian.migrations-platform.app-assessment-table.app-usage-value.not-applicable-tooltip-user':
    'Toto není aplikace založená na makrech a nemůže zobrazovat uživatelská zobrazení maker.',
  'com.atlassian.migrations-platform.app-assessment-table.empty-description':
    'Nemáte žádné aplikace vyžadující migraci pomocí tohoto nástroje.',
  'com.atlassian.migrations-platform.app-assessment-table.head-description.can-be-migrated':
    'Zobrazuje dostupnou cestu migrace dodavatele',
  'com.atlassian.migrations-platform.app-assessment-table.head-description.has-cloud-version':
    'Ukazuje, zda má tato aplikace ekvivalentní cloudovou verzi od stejného dodavatele.',
  'com.atlassian.migrations-platform.app-assessment-table.head-description.migration-notes':
    'Zde si můžete přidat poznámky',
  'com.atlassian.migrations-platform.app-assessment-table.head-description.migration-status':
    'Možnosti stavu, který můžete přidělit své aplikaci',
  'com.atlassian.migrations-platform.app-assessment-table.head-description.pages':
    'Počet stránek obsahujících makra této aplikace',
  'com.atlassian.migrations-platform.app-assessment-table.head-description.users':
    'Počet jedinečných uživatelských zobrazení relevantních maker za posledních 60 dnů',
  'com.atlassian.migrations-platform.app-assessment-table.head-label.can-be-migrated':
    'Lze migrovat',
  'com.atlassian.migrations-platform.app-assessment-table.head-label.has-cloud-version':
    'Existuje v cloudu',
  'com.atlassian.migrations-platform.app-assessment-table.head-label.migration-notes':
    'Poznámky',
  'com.atlassian.migrations-platform.app-assessment-table.head-label.migration-status':
    'Stav',
  'com.atlassian.migrations-platform.app-assessment-table.head-label.pages':
    'Zobrazí se na stránce',
  'com.atlassian.migrations-platform.app-assessment-table.head-label.users':
    'Zobrazeno uživatelem',
  'com.atlassian.migrations-platform.app-migration.back': 'Zpět',
  'com.atlassian.migrations-platform.app-migration.done': 'Dokončeno',
  'com.atlassian.migrations-platform.app-migration.loading': 'Načítání…',
  'com.atlassian.migrations-platform.app-status-value.error': 'Chyba',
  'com.atlassian.migrations-platform.app-status-value.noop-fail':
    'Stav je ignorovaný',
  'com.atlassian.migrations-platform.app-status-value.noop-success':
    'Úspěch bez jakékoli další akce',
  'com.atlassian.migrations-platform.app-status-value.success': 'Úspěch',
  'com.atlassian.migrations-platform.common-ui-app-table.empty-description':
    'Přejděte zpět na domovskou obrazovku migrací a pokračujte v přípravách na migraci.',
  'com.atlassian.migrations-platform.common-ui-app-table.migration-home-cta':
    'Domovská obrazovka migrací',
  'com.atlassian.migrations-platform.consent-modal.cancel-button': 'Zrušit',
  'com.atlassian.migrations-platform.consent-modal.confirm-button': 'Potvrdit',
  'com.atlassian.migrations-platform.consent-modal.description':
    'Aplikace {name} bude mít v průběhu migrace přístup k následujícím datům:',
  'com.atlassian.migrations-platform.consent-modal.heading':
    'Souhlas s migrací dat aplikace',
  'com.atlassian.migrations-platform.consent-modal.marketplace-terms':
    'podmínkami používání',
  'com.atlassian.migrations-platform.consent-modal.scope.app-data-other':
    'Zahrnuje čtení a export dat aplikace obsahujících všechny další informace ukládané aplikací {appName}.',
  'com.atlassian.migrations-platform.consent-modal.scope.app-data-pii':
    'Zahrnuje čtení a export dat aplikace obsahujících identifikovatelné osobní údaje, například uživatelská jména, e-maily nebo adresy.',
  'com.atlassian.migrations-platform.consent-modal.scope.app-data-security':
    'Zahrnuje čtení a export dat aplikace obsahujících bezpečnostní údaje, například hesla, tokeny nebo tajné klíče.',
  'com.atlassian.migrations-platform.consent-modal.scope.app-data-ugc':
    'Zahrnuje čtení a export dat aplikace obsahujících obsah vytvořený uživateli.',
  'com.atlassian.migrations-platform.consent-modal.scope.mig-tracing-identity':
    'Zahrnuje čtení informací o uživatelích a skupinách.',
  'com.atlassian.migrations-platform.consent-modal.scope.mig-tracing-product':
    'Zahrnuje čtení dat souvisejících s produktem, například stránek, webů, požadavků a projektů.',
  'com.atlassian.migrations-platform.consent-modal.scope.product-data-other':
    'Zahrnuje čtení a export produktových dat obsahujících všechny další informace ukládané společností Atlassian.',
  'com.atlassian.migrations-platform.consent-modal.scope.product-data-pii':
    'Zahrnuje čtení a export produktových dat obsahujících identifikovatelné osobní údaje, například uživatelská jména, e-maily nebo adresy.',
  'com.atlassian.migrations-platform.consent-modal.scope.product-data-security':
    'Zahrnuje čtení a export produktových dat obsahujících bezpečnostní údaje, například hesla, tokeny nebo tajné klíče.',
  'com.atlassian.migrations-platform.consent-modal.scope.product-data-ugc':
    'Zahrnuje čtení a export produktových dat obsahujících obsah vytvořený uživateli.',
  'com.atlassian.migrations-platform.consent-modal.terms':
    'Instalací této aplikace vyjadřujete souhlas s {marketplaceTerms} služby Atlassian Marketplace a {vendorPrivacyPolicy} a {vendorName} dodavatele {vendorTerms}.',
  'com.atlassian.migrations-platform.consent-modal.top-vendor':
    'Přední dodavatel',
  'com.atlassian.migrations-platform.consent-modal.vendor-logo':
    'Logo dodavatele {vendorName}',
  'com.atlassian.migrations-platform.consent-modal.vendor-name':
    'od dodavatele {vendorName}',
  'com.atlassian.migrations-platform.consent-modal.vendor-privacy-policy-link':
    'zásadami ochrany osobních údajů',
  'com.atlassian.migrations-platform.consent-modal.vendor-terms-of-use-link':
    'podmínkami používání',
  'com.atlassian.migrations-platform.consent-page.app-assessment-link':
    'Posuďte své aplikace',
  'com.atlassian.migrations-platform.consent-page.contact-vendor-url':
    'kontaktujte dodavatele aplikace',
  'com.atlassian.migrations-platform.consent-page.description':
    'Dodavatelé aplikací mají při migraci dat aplikací přístup k vašemu serveru. Před odsouhlasením si přečtěte zásady jednotlivých aplikací a ujistěte se, že jim rozumíte. Pokud chcete provést migraci, je nutné vyjádřit souhlas, případně změňte své rozhodnutí v tabulce {link}.',
  'com.atlassian.migrations-platform.consent-page.done-button-disabled':
    'Před pokračováním je nutné dokončit posouzení a instalaci a vyjádřit souhlas.',
  'com.atlassian.migrations-platform.consent-page.progress-status-label':
    'odsouhlasených zásad',
  'com.atlassian.migrations-platform.consent-page.revoke-consent':
    'Odvolat souhlas',
  'com.atlassian.migrations-platform.consent-page.status.consent-given':
    'U této aplikace jste odsouhlasili automatizovanou migraci jejích dat externí stranou.',
  'com.atlassian.migrations-platform.consent-page.status.consent-not-given':
    'Je nutné, abyste si tyto zásady migrace dat přečetli a odsouhlasili, jinak nebude možné data aplikace migrovat.',
  'com.atlassian.migrations-platform.consent-page.status.consent-outdated':
    'Zásady, které jste odsouhlasili, byly aktualizovány. Zkontrolujte změny a znovu vyjádřete svůj souhlas. Až poté bude možné provést migraci dat aplikace.',
  'com.atlassian.migrations-platform.consent-page.status.no-automated-migration-path':
    'Tato aplikace nemá cestu automatizované migrace. Pokud potřebujete podporu k migraci, {link}.',
  'com.atlassian.migrations-platform.consent-page.status.no-migrating-alternative':
    'Cesta automatizované migrace mezi alternativními výběry aplikace není k dispozici. Pokud potřebujete podporu k migraci, {link}.',
  'com.atlassian.migrations-platform.consent-page.status.no-migration-needed':
    'Tato aplikace k fungování na vašem cloudovém webu nevyžaduje migraci dat aplikace. Nainstalujte ji, proveďte migraci základních dat a můžete pracovat.',
  'com.atlassian.migrations-platform.consent-page.status.server-app-outdated':
    'Tato verze aplikace nepodporuje migraci dat aplikace. Pokud chcete odsouhlasit příslušné zásady migrace aplikace, je nutné nejdříve aktualizovat verzi vaší serverové aplikace.',
  'com.atlassian.migrations-platform.consent-page.table-header.call-to-action':
    'Podrobnosti zásad',
  'com.atlassian.migrations-platform.consent-page.table-header.consent-status':
    'Stav souhlasu s migrací aplikací',
  'com.atlassian.migrations-platform.consent-page.table-header.needed-in-cloud':
    'Aplikace potřebné v cloudu ({count})',
  'com.atlassian.migrations-platform.consent-page.title':
    'Souhlas s migrací aplikace',
  'com.atlassian.migrations-platform.consent-page.upgrade-app':
    'Aktualizovat aplikaci',
  'com.atlassian.migrations-platform.consent-page.view-policy':
    'Zobrazit zásady',
  'com.atlassian.migrations-platform.no-logo': 'Žádné logo',
  'com.atlassian.migrations-platform.progress-status.complete':
    '{percent} dokončeno',
  'com.atlassian.migrations-platform.progress-status.label':
    '{done} z {total} {unit}',
};
