/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// French
export default {
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.automated-path':
    'Chemin automatisé',
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.contact-vendor':
    'Contacter le fournisseur',
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.contact-vendor-tooltip':
    'Contactez votre fournisseur au sujet de la migration de cette app',
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.sign-up-for-eap':
    "S'inscrire au PAA",
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.track-request':
    'Suivre la demande',
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.upgrade-app':
    "Mettre l'app à niveau",
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.upgrade-app-tooltip':
    "Cette version de l'app ne prend pas en charge la migration automatisée, contrairement à une version ultérieure",
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.view-path':
    'Afficher le chemin',
  'com.atlassian.migrations-platform.app-assessment-table.app-decision-value.alternative':
    "Utiliser l'alternative",
  'com.atlassian.migrations-platform.app-assessment-table.app-decision-value.needed':
    'Nécessaire dans le cloud',
  'com.atlassian.migrations-platform.app-assessment-table.app-decision-value.not-needed':
    'Non nécessaire dans le cloud',
  'com.atlassian.migrations-platform.app-assessment-table.app-decision-value.unassigned':
    'Aucune décision prise',
  'com.atlassian.migrations-platform.app-assessment-table.app-notes-value.placeholder':
    'Saisissez vos notes ici',
  'com.atlassian.migrations-platform.app-assessment-table.app-usage-value.disabled-message':
    'Désactivée',
  'com.atlassian.migrations-platform.app-assessment-table.app-usage-value.not-applicable-message':
    'Non applicable*',
  'com.atlassian.migrations-platform.app-assessment-table.app-usage-value.not-applicable-tooltip-page':
    "Il ne s'agit pas d'une app basée sur des macros et elle n'apparaît sur aucune page",
  'com.atlassian.migrations-platform.app-assessment-table.app-usage-value.not-applicable-tooltip-user':
    "Il ne s'agit pas d'une app basée sur des macros et elle ne peut pas afficher les consultations des macros par les utilisateurs.",
  'com.atlassian.migrations-platform.app-assessment-table.empty-description':
    "Vous n'avez pas d'apps qui doivent être migrées avec cet outil.",
  'com.atlassian.migrations-platform.app-assessment-table.head-description.can-be-migrated':
    'Affiche le parcours de migration du fournisseur disponible',
  'com.atlassian.migrations-platform.app-assessment-table.head-description.has-cloud-version':
    "Indique si cette app dispose d'une version Cloud équivalente du même fournisseur",
  'com.atlassian.migrations-platform.app-assessment-table.head-description.migration-notes':
    'Ajoutez des notes pour vous-même',
  'com.atlassian.migrations-platform.app-assessment-table.head-description.migration-status':
    "Options d'état que vous assignez à votre app",
  'com.atlassian.migrations-platform.app-assessment-table.head-description.pages':
    'Nombre de pages contenant les macros de cette app',
  'com.atlassian.migrations-platform.app-assessment-table.head-description.users':
    'Nombre de consultations uniques des macros pertinentes par les utilisateurs, au cours des 60 derniers jours.',
  'com.atlassian.migrations-platform.app-assessment-table.head-label.can-be-migrated':
    'Peut être migrée',
  'com.atlassian.migrations-platform.app-assessment-table.head-label.has-cloud-version':
    'Existe dans le cloud',
  'com.atlassian.migrations-platform.app-assessment-table.head-label.migration-notes':
    'Notes',
  'com.atlassian.migrations-platform.app-assessment-table.head-label.migration-status':
    'État',
  'com.atlassian.migrations-platform.app-assessment-table.head-label.pages':
    'Apparaît sur',
  'com.atlassian.migrations-platform.app-assessment-table.head-label.users':
    'Consultée par',
  'com.atlassian.migrations-platform.app-migration.back': 'Retour',
  'com.atlassian.migrations-platform.app-migration.done': 'Terminé',
  'com.atlassian.migrations-platform.app-migration.loading': 'Chargement…',
  'com.atlassian.migrations-platform.app-status-value.error': 'Erreur',
  'com.atlassian.migrations-platform.app-status-value.noop-fail':
    "L'état est ignoré",
  'com.atlassian.migrations-platform.app-status-value.noop-success':
    'Opération réussie sans autre action',
  'com.atlassian.migrations-platform.app-status-value.success':
    'Opération réussie',
  'com.atlassian.migrations-platform.common-ui-app-table.empty-description':
    "Revenez à la page d'accueil des migrations pour préparer votre migration.",
  'com.atlassian.migrations-platform.common-ui-app-table.migration-home-cta':
    "Page d'accueil des migrations",
  'com.atlassian.migrations-platform.consent-modal.cancel-button': 'Annuler',
  'com.atlassian.migrations-platform.consent-modal.confirm-button': 'Confirmer',
  'com.atlassian.migrations-platform.consent-modal.description':
    '{name} aura accès aux données suivantes au cours de la migration :',
  'com.atlassian.migrations-platform.consent-modal.heading':
    "Accepter la migration des données d'app",
  'com.atlassian.migrations-platform.consent-modal.marketplace-terms':
    "conditions d'utilisation",
  'com.atlassian.migrations-platform.consent-modal.scope.app-data-other':
    "Veuillez lire et exporter les données d'app contenant toute autre information stockée par {appName}.",
  'com.atlassian.migrations-platform.consent-modal.scope.app-data-pii':
    "Veuillez lire et exporter les données d'app contenant des informations d'identification personnelle, comme des noms d'utilisateur, des e-mails ou des adresses.",
  'com.atlassian.migrations-platform.consent-modal.scope.app-data-security':
    "Veuillez lire et exporter les données d'app contenant des informations de sécurité, comme des mots de passe, des jetons ou des secrets.",
  'com.atlassian.migrations-platform.consent-modal.scope.app-data-ugc':
    "Veuillez lire et exporter les données d'app comportant du contenu créé par les utilisateurs.",
  'com.atlassian.migrations-platform.consent-modal.scope.mig-tracing-identity':
    'Veuillez lire les informations sur les utilisateurs et les groupes.',
  'com.atlassian.migrations-platform.consent-modal.scope.mig-tracing-product':
    'Veuillez lire les données associées au produit, comme les pages, les sites, les tickets et les projets.',
  'com.atlassian.migrations-platform.consent-modal.scope.product-data-other':
    'Veuillez lire et exporter les données du produit contenant toute autre information stockée par Atlassian.',
  'com.atlassian.migrations-platform.consent-modal.scope.product-data-pii':
    "Veuillez lire et exporter les données du produit contenant des informations d'identification personnelle, comme des noms d'utilisateur, des e-mails ou des adresses.",
  'com.atlassian.migrations-platform.consent-modal.scope.product-data-security':
    'Veuillez lire et exporter les données du produit contenant des informations de sécurité, comme des mots de passe, des jetons ou des secrets.',
  'com.atlassian.migrations-platform.consent-modal.scope.product-data-ugc':
    'Veuillez lire et exporter les données du produit comportant du contenu créé par les utilisateurs.',
  'com.atlassian.migrations-platform.consent-modal.terms':
    "En installant cette app, vous acceptez les {marketplaceTerms} d'Atlassian Marketplace, ainsi que la {vendorPrivacyPolicy} et les {vendorTerms} de {vendorName}.",
  'com.atlassian.migrations-platform.consent-modal.top-vendor': 'Top Vendor',
  'com.atlassian.migrations-platform.consent-modal.vendor-logo':
    'Logo {vendorName}',
  'com.atlassian.migrations-platform.consent-modal.vendor-name':
    'par {vendorName}',
  'com.atlassian.migrations-platform.consent-modal.vendor-privacy-policy-link':
    'politique de confidentialité',
  'com.atlassian.migrations-platform.consent-modal.vendor-terms-of-use-link':
    "conditions d'utilisation",
  'com.atlassian.migrations-platform.consent-page.app-assessment-link':
    'Évaluez vos apps',
  'com.atlassian.migrations-platform.consent-page.contact-vendor-url':
    "Contacter le fournisseur de l'app",
  'com.atlassian.migrations-platform.consent-page.description':
    "Les fournisseurs d'apps ont accès à votre serveur lors de la migration de vos données d'app. Veuillez lire la politique de chaque app avant de l'accepter. Vous devez donner votre accord pour procéder à la migration ou changer votre décision dans le tableau {link}.",
  'com.atlassian.migrations-platform.consent-page.done-button-disabled':
    "Vous devez terminer les étapes d'évaluation, d'installation et de consentement avant de poursuivre.",
  'com.atlassian.migrations-platform.consent-page.progress-status-label':
    'politique(s) acceptée(s)',
  'com.atlassian.migrations-platform.consent-page.revoke-consent':
    'Ne plus accepter',
  'com.atlassian.migrations-platform.consent-page.status.consent-given':
    'Vous avez accepté la migration tierce automatisée des données de cette app.',
  'com.atlassian.migrations-platform.consent-page.status.consent-not-given':
    "Vous devez passer en revue et accepter cette politique de migration des données, ou vous ne pourrez pas migrer vos données d'app.",
  'com.atlassian.migrations-platform.consent-page.status.consent-outdated':
    "La politique que vous avez acceptée a été mise à jour. Passez en revue les changements et acceptez-la de nouveau avant de pouvoir migrer vos données d'app.",
  'com.atlassian.migrations-platform.consent-page.status.no-automated-migration-path':
    'Cette app ne dispose pas de parcours de migration automatisé. {link} pour une assistance à la migration.',
  'com.atlassian.migrations-platform.consent-page.status.no-migrating-alternative':
    "Aucun parcours de migration automatisé entre les sélections d'app alternatives n'est disponible. {link} pour une assistance à la migration.",
  'com.atlassian.migrations-platform.consent-page.status.no-migration-needed':
    "Cette app ne nécessite pas de migration des données d'app pour fonctionner sur votre site Cloud. Installez-la, migrez vos données de base, et le tour est joué.",
  'com.atlassian.migrations-platform.consent-page.status.server-app-outdated':
    "Cette version d'app ne prend pas en charge les migrations de données d'app. Vous devez mettre à jour votre version d'app Server pour accepter la politique de migration de l'app concernée.",
  'com.atlassian.migrations-platform.consent-page.table-header.call-to-action':
    'Détails de la politique',
  'com.atlassian.migrations-platform.consent-page.table-header.consent-status':
    "État d'acception de la migration des apps",
  'com.atlassian.migrations-platform.consent-page.table-header.needed-in-cloud':
    'Apps nécessaires dans le cloud ({count})',
  'com.atlassian.migrations-platform.consent-page.title':
    "Accepter la migration de l'app",
  'com.atlassian.migrations-platform.consent-page.upgrade-app':
    "Mettre à jour l'app",
  'com.atlassian.migrations-platform.consent-page.view-policy':
    'Afficher la politique',
  'com.atlassian.migrations-platform.no-logo': 'Aucun logo',
  'com.atlassian.migrations-platform.progress-status.complete':
    '{percent} terminé(s)',
  'com.atlassian.migrations-platform.progress-status.label':
    '{done} sur {total} {unit}',
};
