/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Korean
export default {
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.automated-path':
    '자동화된 경로',
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.contact-vendor':
    '공급업체에 문의',
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.contact-vendor-tooltip':
    '이 앱의 마이그레이션에 대해서 벤더에게 문의하세요',
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.sign-up-for-eap':
    'EAP에 등록',
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.track-request':
    '요청 추적',
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.upgrade-app':
    '앱 업그레이드',
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.upgrade-app-tooltip':
    '이 앱 버전은 자동 마이그레이션을 지원하지 않지만, 이후 버전에서는 지원합니다',
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.view-path':
    '경로 보기',
  'com.atlassian.migrations-platform.app-assessment-table.app-decision-value.alternative':
    '대체 앱 사용',
  'com.atlassian.migrations-platform.app-assessment-table.app-decision-value.needed':
    'Cloud에서 필요함',
  'com.atlassian.migrations-platform.app-assessment-table.app-decision-value.not-needed':
    'Cloud에서 필요하지 않음',
  'com.atlassian.migrations-platform.app-assessment-table.app-decision-value.unassigned':
    '결정되지 않음',
  'com.atlassian.migrations-platform.app-assessment-table.app-notes-value.placeholder':
    '여기에 메모 입력',
  'com.atlassian.migrations-platform.app-assessment-table.app-usage-value.disabled-message':
    '사용 안 함',
  'com.atlassian.migrations-platform.app-assessment-table.app-usage-value.not-applicable-message':
    '해당 없음*',
  'com.atlassian.migrations-platform.app-assessment-table.app-usage-value.not-applicable-tooltip-page':
    '이 앱은 매크로 기반 앱이 아니며 페이지에 나타나지 않습니다',
  'com.atlassian.migrations-platform.app-assessment-table.app-usage-value.not-applicable-tooltip-user':
    '이 앱은 매크로 기반 앱이 아니며 매크로의 사용자 보기를 표시할 수 없습니다',
  'com.atlassian.migrations-platform.app-assessment-table.empty-description':
    '이 도구를 사용하여 마이그레이션해야 하는 앱이 없습니다.',
  'com.atlassian.migrations-platform.app-assessment-table.head-description.can-be-migrated':
    '사용 가능한 공급업체 마이그레이션 경로를 표시합니다',
  'com.atlassian.migrations-platform.app-assessment-table.head-description.has-cloud-version':
    '이 앱에 같은 공급업체에서 제공하는 동등한 Cloud 버전이 있는지 표시합니다',
  'com.atlassian.migrations-platform.app-assessment-table.head-description.migration-notes':
    '여기에 자신을 위해 메모 추가',
  'com.atlassian.migrations-platform.app-assessment-table.head-description.migration-status':
    '앱에 할당할 수 있는 상태 옵션',
  'com.atlassian.migrations-platform.app-assessment-table.head-description.pages':
    '이 앱의 매크로를 포함하는 페이지의 수',
  'com.atlassian.migrations-platform.app-assessment-table.head-description.users':
    '지난 60일 동안 관련 매크로의 고유 사용자 보기의 수',
  'com.atlassian.migrations-platform.app-assessment-table.head-label.can-be-migrated':
    '마이그레이션 가능',
  'com.atlassian.migrations-platform.app-assessment-table.head-label.has-cloud-version':
    'Cloud에 있음',
  'com.atlassian.migrations-platform.app-assessment-table.head-label.migration-notes':
    '메모',
  'com.atlassian.migrations-platform.app-assessment-table.head-label.migration-status':
    '상태',
  'com.atlassian.migrations-platform.app-assessment-table.head-label.pages':
    '표시',
  'com.atlassian.migrations-platform.app-assessment-table.head-label.users':
    '본 사용자',
  'com.atlassian.migrations-platform.app-migration.back': '뒤로',
  'com.atlassian.migrations-platform.app-migration.done': '완료',
  'com.atlassian.migrations-platform.app-migration.loading': '로드 중...',
  'com.atlassian.migrations-platform.app-status-value.error': '오류',
  'com.atlassian.migrations-platform.app-status-value.noop-fail':
    '상태가 무시됨',
  'com.atlassian.migrations-platform.app-status-value.noop-success':
    '추가 작업 없이 성공',
  'com.atlassian.migrations-platform.app-status-value.success': '성공',
  'com.atlassian.migrations-platform.common-ui-app-table.empty-description':
    '마이그레이션 준비를 계속하려면 마이그레이션 홈으로 돌아가세요.',
  'com.atlassian.migrations-platform.common-ui-app-table.migration-home-cta':
    '마이그레이션 홈',
  'com.atlassian.migrations-platform.consent-modal.cancel-button': '취소',
  'com.atlassian.migrations-platform.consent-modal.confirm-button': '확인',
  'com.atlassian.migrations-platform.consent-modal.description':
    '{name}에서 마이그레이션 과정 중에 다음 데이터에 액세스할 수 있습니다:',
  'com.atlassian.migrations-platform.consent-modal.heading':
    '앱 데이터 마이그레이션에 동의',
  'com.atlassian.migrations-platform.consent-modal.marketplace-terms':
    '이용약관',
  'com.atlassian.migrations-platform.consent-modal.scope.app-data-other':
    '{appName}에서 저장한 기타 정보가 포함된 앱 데이터를 읽고 내보냅니다.',
  'com.atlassian.migrations-platform.consent-modal.scope.app-data-pii':
    '사용자 이름, 이메일 또는 주소와 같은 개인 식별 정보가 포함된 앱 데이터를 읽고 내보냅니다.',
  'com.atlassian.migrations-platform.consent-modal.scope.app-data-security':
    '비밀번호, 토큰 또는 암호와 같은 보안 세부 정보가 포함된 앱 데이터를 읽고 내보냅니다.',
  'com.atlassian.migrations-platform.consent-modal.scope.app-data-ugc':
    '사용자가 작성한 콘텐츠가 포함된 앱 데이터를 읽고 내보냅니다.',
  'com.atlassian.migrations-platform.consent-modal.scope.mig-tracing-identity':
    '사용자 및 그룹 정보를 읽습니다.',
  'com.atlassian.migrations-platform.consent-modal.scope.mig-tracing-product':
    '페이지, 사이트, 이슈 및 프로젝트와 같은 제품 관련 데이터를 읽습니다.',
  'com.atlassian.migrations-platform.consent-modal.scope.product-data-other':
    'Atlassian에서 저장한 기타 정보가 포함된 제품 데이터를 읽고 내보냅니다.',
  'com.atlassian.migrations-platform.consent-modal.scope.product-data-pii':
    '사용자 이름, 이메일 또는 주소와 같은 개인 식별 정보가 포함된 제품 데이터를 읽고 내보냅니다.',
  'com.atlassian.migrations-platform.consent-modal.scope.product-data-security':
    '비밀번호, 토큰 또는 암호와 같은 보안 세부 정보가 포함된 제품 데이터를 읽고 내보냅니다.',
  'com.atlassian.migrations-platform.consent-modal.scope.product-data-ugc':
    '사용자가 작성한 콘텐츠가 포함된 제품 데이터를 읽고 내보냅니다.',
  'com.atlassian.migrations-platform.consent-modal.terms':
    '이 앱을 설치하면 Atlassian Marketplace의 {marketplaceTerms} 및 {vendorName}의 {vendorPrivacyPolicy} 및 {vendorTerms}에 동의하게 됩니다.',
  'com.atlassian.migrations-platform.consent-modal.top-vendor': '최상위 공급자',
  'com.atlassian.migrations-platform.consent-modal.vendor-logo':
    '{vendorName} 로고',
  'com.atlassian.migrations-platform.consent-modal.vendor-name':
    '제공: {vendorName}',
  'com.atlassian.migrations-platform.consent-modal.vendor-privacy-policy-link':
    '개인정보 보호정책',
  'com.atlassian.migrations-platform.consent-modal.vendor-terms-of-use-link':
    '이용약관',
  'com.atlassian.migrations-platform.consent-page.app-assessment-link':
    '앱 평가',
  'com.atlassian.migrations-platform.consent-page.contact-vendor-url':
    '앱 공급자에게 문의',
  'com.atlassian.migrations-platform.consent-page.description':
    '앱 데이터를 마이그레이션할 때 앱 공급자는 Server에 액세스할 수 있습니다. 동의하기 전에 각 앱에 대한 정책을 읽고 이해하세요. 마이그레이션하거나 {link} 표의 결정을 변경하려면 동의해야 합니다.',
  'com.atlassian.migrations-platform.consent-page.done-button-disabled':
    '계속하기 전에 평가, 설치 및 동의를 완료해야 합니다.',
  'com.atlassian.migrations-platform.consent-page.progress-status-label':
    '정책에 동의함',
  'com.atlassian.migrations-platform.consent-page.revoke-consent': '동의 철회',
  'com.atlassian.migrations-platform.consent-page.status.consent-given':
    '이 앱에 대한 제3자의 자동화된 앱 데이터 마이그레이션에 동의했습니다.',
  'com.atlassian.migrations-platform.consent-page.status.consent-not-given':
    '이 데이터 마이그레이션 정책을 검토하고 동의해야 합니다. 그렇지 않으면 앱 데이터를 마이그레이션할 수 없습니다.',
  'com.atlassian.migrations-platform.consent-page.status.consent-outdated':
    '동의한 정책이 업데이트되었습니다. 앱 데이터를 마이그레이션하려면 변경 사항을 검토하고 다시 동의하세요.',
  'com.atlassian.migrations-platform.consent-page.status.no-automated-migration-path':
    '이 앱에는 자동화된 마이그레이션 경로가 없습니다. 마이그레이션 지원을 받으려면 {link}.',
  'com.atlassian.migrations-platform.consent-page.status.no-migrating-alternative':
    '선택한 대체 앱 간에 자동화된 마이그레이션 경로를 사용할 수 없습니다. 마이그레이션 지원을 받으려면 {link}.',
  'com.atlassian.migrations-platform.consent-page.status.no-migration-needed':
    '이 앱은 Cloud 사이트에서 작동하기 위해 앱 데이터 마이그레이션을 수행할 필요가 없습니다. 앱을 설치하고 핵심 데이터를 마이그레이션하면 준비가 완료됩니다.',
  'com.atlassian.migrations-platform.consent-page.status.server-app-outdated':
    '이 앱 버전은 앱 데이터 마이그레이션을 지원하지 않습니다. 관련 앱 마이그레이션 정책에 동의하려면 Server 앱 버전을 업데이트해야 합니다.',
  'com.atlassian.migrations-platform.consent-page.table-header.call-to-action':
    '정책 세부 정보',
  'com.atlassian.migrations-platform.consent-page.table-header.consent-status':
    '앱 마이그레이션 동의 상태',
  'com.atlassian.migrations-platform.consent-page.table-header.needed-in-cloud':
    'Cloud에서 필요한 앱({count}개)',
  'com.atlassian.migrations-platform.consent-page.title':
    '앱 마이그레이션에 동의',
  'com.atlassian.migrations-platform.consent-page.upgrade-app': '앱 업데이트',
  'com.atlassian.migrations-platform.consent-page.view-policy': '정책 보기',
  'com.atlassian.migrations-platform.no-logo': '로고 없음',
  'com.atlassian.migrations-platform.progress-status.complete':
    '{percent} 완료',
  'com.atlassian.migrations-platform.progress-status.label':
    '{done}/{total}{unit}',
};
