/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Portuguese (Brazil)
export default {
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.automated-path':
    'Caminho automatizado',
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.contact-vendor':
    'Entre em contato com o fornecedor',
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.contact-vendor-tooltip':
    'Entre em contato com seu fornecedor sobre a migração deste aplicativo',
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.sign-up-for-eap':
    'Faça a inscrição no PAA',
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.track-request':
    'Rastrear a solicitação',
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.upgrade-app':
    'Fazer o upgrade do aplicativo',
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.upgrade-app-tooltip':
    'Essa versão do aplicativo não tem suporte para a migração automatizada, mas uma versão posterior tem',
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.view-path':
    'Visualizar o caminho',
  'com.atlassian.migrations-platform.app-assessment-table.app-decision-value.alternative':
    'Usar alternativa',
  'com.atlassian.migrations-platform.app-assessment-table.app-decision-value.needed':
    'Necessário na nuvem',
  'com.atlassian.migrations-platform.app-assessment-table.app-decision-value.not-needed':
    'Não é necessário na nuvem',
  'com.atlassian.migrations-platform.app-assessment-table.app-decision-value.unassigned':
    'Nenhuma decisão tomada',
  'com.atlassian.migrations-platform.app-assessment-table.app-notes-value.placeholder':
    'Digite suas notas aqui',
  'com.atlassian.migrations-platform.app-assessment-table.app-usage-value.disabled-message':
    'Desativado',
  'com.atlassian.migrations-platform.app-assessment-table.app-usage-value.not-applicable-message':
    'Não se aplica*',
  'com.atlassian.migrations-platform.app-assessment-table.app-usage-value.not-applicable-tooltip-page':
    'Este não é um aplicativo baseado em macro e não aparece em nenhuma página',
  'com.atlassian.migrations-platform.app-assessment-table.app-usage-value.not-applicable-tooltip-user':
    'Este não é um aplicativo baseado em macro e não pode exibir visualizações de usuários de macros',
  'com.atlassian.migrations-platform.app-assessment-table.empty-description':
    'Você não tem nenhum aplicativo que precise migrar com esta ferramenta.',
  'com.atlassian.migrations-platform.app-assessment-table.head-description.can-be-migrated':
    'Mostra o caminho de migração de fornecedor disponível',
  'com.atlassian.migrations-platform.app-assessment-table.head-description.has-cloud-version':
    'Mostra se o aplicativo tem uma versão equivalente na nuvem pelo mesmo fornecedor',
  'com.atlassian.migrations-platform.app-assessment-table.head-description.migration-notes':
    'Adicione notas para si mesmo aqui',
  'com.atlassian.migrations-platform.app-assessment-table.head-description.migration-status':
    'Opções de status que podem ser atribuídas ao aplicativo',
  'com.atlassian.migrations-platform.app-assessment-table.head-description.pages':
    'Número de páginas que contêm as macros deste aplicativo',
  'com.atlassian.migrations-platform.app-assessment-table.head-description.users':
    'Número de visualizações únicas de usuários das macros relevantes, nos últimos 60 dias',
  'com.atlassian.migrations-platform.app-assessment-table.head-label.can-be-migrated':
    'Pode ser migrado',
  'com.atlassian.migrations-platform.app-assessment-table.head-label.has-cloud-version':
    'Existe na nuvem',
  'com.atlassian.migrations-platform.app-assessment-table.head-label.migration-notes':
    'Notas',
  'com.atlassian.migrations-platform.app-assessment-table.head-label.migration-status':
    'Status',
  'com.atlassian.migrations-platform.app-assessment-table.head-label.pages':
    'Aparece em',
  'com.atlassian.migrations-platform.app-assessment-table.head-label.users':
    'Visto por',
  'com.atlassian.migrations-platform.app-migration.back': 'Voltar',
  'com.atlassian.migrations-platform.app-migration.done': 'Concluído',
  'com.atlassian.migrations-platform.app-migration.loading': 'Carregando...',
  'com.atlassian.migrations-platform.app-status-value.error': 'Erro',
  'com.atlassian.migrations-platform.app-status-value.noop-fail':
    'O status é ignorado',
  'com.atlassian.migrations-platform.app-status-value.noop-success':
    'Sucesso, nenhuma ação adicional necessária',
  'com.atlassian.migrations-platform.app-status-value.success': 'Sucesso',
  'com.atlassian.migrations-platform.common-ui-app-table.empty-description':
    'Volte para a página inicial para continuar a se preparar para a migração.',
  'com.atlassian.migrations-platform.common-ui-app-table.migration-home-cta':
    'Página inicial de migrações',
  'com.atlassian.migrations-platform.consent-modal.cancel-button': 'Cancelar',
  'com.atlassian.migrations-platform.consent-modal.confirm-button': 'Confirmar',
  'com.atlassian.migrations-platform.consent-modal.description':
    '{name} vai ter acesso aos seguintes dados durante a migração:',
  'com.atlassian.migrations-platform.consent-modal.heading':
    'Concordo com a migração de dados do aplicativo',
  'com.atlassian.migrations-platform.consent-modal.marketplace-terms':
    'Termos de uso',
  'com.atlassian.migrations-platform.consent-modal.scope.app-data-other':
    'Ler e exportar dados do aplicativo que contenham qualquer outra informação armazenada por {appName}.',
  'com.atlassian.migrations-platform.consent-modal.scope.app-data-pii':
    'Ler e exportar dados do aplicativo que contenham informações pessoais identificáveis como nomes de usuário, e-mails ou endereços.',
  'com.atlassian.migrations-platform.consent-modal.scope.app-data-security':
    'Ler e exportar dados do aplicativo que contenham informações de segurança como senhas, tokens ou segredos.',
  'com.atlassian.migrations-platform.consent-modal.scope.app-data-ugc':
    'Ler e exportar dados do aplicativo que contenham conteúdo criado por usuários.',
  'com.atlassian.migrations-platform.consent-modal.scope.mig-tracing-identity':
    'Ler informações de usuários e de grupos.',
  'com.atlassian.migrations-platform.consent-modal.scope.mig-tracing-product':
    'Ler dados relacionados ao produto como páginas, sites, itens e projetos.',
  'com.atlassian.migrations-platform.consent-modal.scope.product-data-other':
    'Ler e exportar dados do produto que contenham quaisquer outras informações armazenadas pela Atlassian.',
  'com.atlassian.migrations-platform.consent-modal.scope.product-data-pii':
    'Ler e exportar dados do produto que contenham informações pessoais identificáveis como nomes de usuário, e-mails ou endereços.',
  'com.atlassian.migrations-platform.consent-modal.scope.product-data-security':
    'Ler e exportar dados do produto que contenham informações de segurança como senhas, tokens ou segredos.',
  'com.atlassian.migrations-platform.consent-modal.scope.product-data-ugc':
    'Ler e exportar dados do produto que contenham conteúdo criado por usuários.',
  'com.atlassian.migrations-platform.consent-modal.terms':
    'Ao instalar este aplicativo, você concorda com os {marketplaceTerms} do Atlassian Marketplace e com a {vendorPrivacyPolicy} e os {vendorTerms} da {vendorName}.',
  'com.atlassian.migrations-platform.consent-modal.top-vendor':
    'Melhores fornecedores',
  'com.atlassian.migrations-platform.consent-modal.vendor-logo':
    'Logo da {vendorName}',
  'com.atlassian.migrations-platform.consent-modal.vendor-name':
    'por {vendorName}',
  'com.atlassian.migrations-platform.consent-modal.vendor-privacy-policy-link':
    'Política de privacidade',
  'com.atlassian.migrations-platform.consent-modal.vendor-terms-of-use-link':
    'Termos de uso',
  'com.atlassian.migrations-platform.consent-page.app-assessment-link':
    'Avalie seus aplicativos',
  'com.atlassian.migrations-platform.consent-page.contact-vendor-url':
    'Entre em contato com o fornecedor do aplicativo',
  'com.atlassian.migrations-platform.consent-page.description':
    'Os fornecedores de aplicativo têm acesso ao servidor ao migrarem os dados do aplicativo. Leia e entenda a política de cada aplicativo antes de concordar. Você deve concordar para migrar ou alterar a decisão na tabela {link}.',
  'com.atlassian.migrations-platform.consent-page.done-button-disabled':
    'Você deve terminar de avaliar, instalar e consentir antes de prosseguir.',
  'com.atlassian.migrations-platform.consent-page.progress-status-label':
    'políticas aceitas',
  'com.atlassian.migrations-platform.consent-page.revoke-consent':
    'Revogar aceitação',
  'com.atlassian.migrations-platform.consent-page.status.consent-given':
    'Você concordou com a migração automatizada de dados de aplicativos de terceiros para este aplicativo.',
  'com.atlassian.migrations-platform.consent-page.status.consent-not-given':
    'Você precisa revisar e concordar com esta política de migração de dados, senão não é possível migrar os dados do aplicativo.',
  'com.atlassian.migrations-platform.consent-page.status.consent-outdated':
    'A política com a qual você concordou foi atualizada. Verifique as mudanças e concorde de novo para poder migrar os dados do aplicativo.',
  'com.atlassian.migrations-platform.consent-page.status.no-automated-migration-path':
    'Este aplicativo não tem um caminho automatizado de migração. {link} para suporte sobre migração.',
  'com.atlassian.migrations-platform.consent-page.status.no-migrating-alternative':
    'Não há um caminho automático de migração entre seleções alternativas do aplicativo disponível. {link} para suporte sobre migração.',
  'com.atlassian.migrations-platform.consent-page.status.no-migration-needed':
    'Este aplicativo não exige uma migração de dados do aplicativo para funcionar no seu site na nuvem. Basta fazer a instalação e migrar os dados principais para poder usá-lo.',
  'com.atlassian.migrations-platform.consent-page.status.server-app-outdated':
    'Esta versão do aplicativo não suporta migrações de dados do aplicativo. Você precisa atualizar a versão do servidor do aplicativo para concordar com a política de migração do aplicativo apropriado.',
  'com.atlassian.migrations-platform.consent-page.table-header.call-to-action':
    'Informações da política',
  'com.atlassian.migrations-platform.consent-page.table-header.consent-status':
    'Status de aceitação da migração de aplicativos',
  'com.atlassian.migrations-platform.consent-page.table-header.needed-in-cloud':
    'Aplicativos necessários na nuvem ({count})',
  'com.atlassian.migrations-platform.consent-page.title':
    'Concordo com a migração do aplicativo',
  'com.atlassian.migrations-platform.consent-page.upgrade-app':
    'Atualizar aplicativo',
  'com.atlassian.migrations-platform.consent-page.view-policy': 'Ver política',
  'com.atlassian.migrations-platform.no-logo': 'Sem logotipo',
  'com.atlassian.migrations-platform.progress-status.complete':
    '{percent} completa',
  'com.atlassian.migrations-platform.progress-status.label':
    '{done} de {total} {unit}',
};
