/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Chinese
export default {
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.automated-path':
    '自动路径',
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.contact-vendor':
    '联系供应商',
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.contact-vendor-tooltip':
    '请联系供应商以了解如何迁移此应用',
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.sign-up-for-eap':
    '注册 EAP',
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.track-request':
    '跟踪请求',
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.upgrade-app':
    '升级应用',
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.upgrade-app-tooltip':
    '此应用版本不支持自动迁移，但后续版本支持',
  'com.atlassian.migrations-platform.app-assessment-table.app-can-be-migrated.view-path':
    '查看路径',
  'com.atlassian.migrations-platform.app-assessment-table.app-decision-value.alternative':
    '使用替代版本',
  'com.atlassian.migrations-platform.app-assessment-table.app-decision-value.needed':
    '云端需要',
  'com.atlassian.migrations-platform.app-assessment-table.app-decision-value.not-needed':
    '云端不需要',
  'com.atlassian.migrations-platform.app-assessment-table.app-decision-value.unassigned':
    '未决定',
  'com.atlassian.migrations-platform.app-assessment-table.app-notes-value.placeholder':
    '在此处输入备注',
  'com.atlassian.migrations-platform.app-assessment-table.app-usage-value.disabled-message':
    '已禁用',
  'com.atlassian.migrations-platform.app-assessment-table.app-usage-value.not-applicable-message':
    '不适用*',
  'com.atlassian.migrations-platform.app-assessment-table.app-usage-value.not-applicable-tooltip-page':
    '这不是一个基于宏的应用，因此不会出现在任何页面上',
  'com.atlassian.migrations-platform.app-assessment-table.app-usage-value.not-applicable-tooltip-user':
    '这不是一个基于宏的应用，因此无法显示宏的用户视图',
  'com.atlassian.migrations-platform.app-assessment-table.empty-description':
    '您的应用都无需通过此工具进行迁移。',
  'com.atlassian.migrations-platform.app-assessment-table.head-description.can-be-migrated':
    '显示可用的供应商迁移路径',
  'com.atlassian.migrations-platform.app-assessment-table.head-description.has-cloud-version':
    '显示此应用是否具有来自同一供应商的等效云端版本',
  'com.atlassian.migrations-platform.app-assessment-table.head-description.migration-notes':
    '在此处为您自己添加备注',
  'com.atlassian.migrations-platform.app-assessment-table.head-description.migration-status':
    '可分配给应用的状态选项',
  'com.atlassian.migrations-platform.app-assessment-table.head-description.pages':
    '包含此应用的宏的页数',
  'com.atlassian.migrations-platform.app-assessment-table.head-description.users':
    '过去 60 天内，相关宏的唯一用户浏览次数',
  'com.atlassian.migrations-platform.app-assessment-table.head-label.can-be-migrated':
    '可迁移',
  'com.atlassian.migrations-platform.app-assessment-table.head-label.has-cloud-version':
    '已在云端',
  'com.atlassian.migrations-platform.app-assessment-table.head-label.migration-notes':
    '备注',
  'com.atlassian.migrations-platform.app-assessment-table.head-label.migration-status':
    '状态',
  'com.atlassian.migrations-platform.app-assessment-table.head-label.pages':
    '显示页面',
  'com.atlassian.migrations-platform.app-assessment-table.head-label.users':
    '查看的用户',
  'com.atlassian.migrations-platform.app-migration.back': '返回',
  'com.atlassian.migrations-platform.app-migration.done': '完成',
  'com.atlassian.migrations-platform.app-migration.loading': '正在加载...',
  'com.atlassian.migrations-platform.app-status-value.error': '错误',
  'com.atlassian.migrations-platform.app-status-value.noop-fail': '状态已忽略',
  'com.atlassian.migrations-platform.app-status-value.noop-success':
    '成功，无需后续操作',
  'com.atlassian.migrations-platform.app-status-value.success': '成功',
  'com.atlassian.migrations-platform.common-ui-app-table.empty-description':
    '返回迁移主页，继续为迁移做准备。',
  'com.atlassian.migrations-platform.common-ui-app-table.migration-home-cta':
    '迁移主页',
  'com.atlassian.migrations-platform.consent-modal.cancel-button': '取消',
  'com.atlassian.migrations-platform.consent-modal.confirm-button': '确认',
  'com.atlassian.migrations-platform.consent-modal.description':
    '迁移期间，{name} 将获得以下数据的访问权限：',
  'com.atlassian.migrations-platform.consent-modal.heading': '同意迁移应用数据',
  'com.atlassian.migrations-platform.consent-modal.marketplace-terms':
    '使用条款',
  'com.atlassian.migrations-platform.consent-modal.scope.app-data-other':
    '读取并导出包含 {appName} 存储的其他信息的应用数据。',
  'com.atlassian.migrations-platform.consent-modal.scope.app-data-pii':
    '读取并导出包含用户名、电子邮件或地址等个人识别信息的应用数据。',
  'com.atlassian.migrations-platform.consent-modal.scope.app-data-security':
    '读取并导出包含密码、信令或密钥等安全细节的应用数据。',
  'com.atlassian.migrations-platform.consent-modal.scope.app-data-ugc':
    '读取并导出包含用户所创建内容的应用数据。',
  'com.atlassian.migrations-platform.consent-modal.scope.mig-tracing-identity':
    '读取用户和群组信息。',
  'com.atlassian.migrations-platform.consent-modal.scope.mig-tracing-product':
    '读取产品相关数据，如页面、站点、事务和项目。',
  'com.atlassian.migrations-platform.consent-modal.scope.product-data-other':
    '读取并导出包含 Atlassian 存储的其他信息的应用数据。',
  'com.atlassian.migrations-platform.consent-modal.scope.product-data-pii':
    '读取并导出包含用户名、电子邮件或地址等个人识别信息的产品数据。',
  'com.atlassian.migrations-platform.consent-modal.scope.product-data-security':
    '读取并导出包含密码、信令或密钥等安全细节的产品数据。',
  'com.atlassian.migrations-platform.consent-modal.scope.product-data-ugc':
    '读取并导出包含用户所创建内容的产品数据。',
  'com.atlassian.migrations-platform.consent-modal.terms':
    '安装此应用即表明您同意 Atlassian Marketplace 的{marketplaceTerms}以及 {vendorName} 的{vendorPrivacyPolicy}和{vendorTerms}。',
  'com.atlassian.migrations-platform.consent-modal.top-vendor': '顶级供应商',
  'com.atlassian.migrations-platform.consent-modal.vendor-logo':
    '{vendorName} 徽标',
  'com.atlassian.migrations-platform.consent-modal.vendor-name':
    '来自 {vendorName}',
  'com.atlassian.migrations-platform.consent-modal.vendor-privacy-policy-link':
    '隐私政策',
  'com.atlassian.migrations-platform.consent-modal.vendor-terms-of-use-link':
    '使用条款',
  'com.atlassian.migrations-platform.consent-page.app-assessment-link':
    '评估您的应用',
  'com.atlassian.migrations-platform.consent-page.contact-vendor-url':
    '联系应用供应商',
  'com.atlassian.migrations-platform.consent-page.description':
    '应用供应商在迁移您的应用数据时可访问您的服务器。同意之前，请阅读并了解各应用的相关政策。您必须同意后才能迁移或更改您在 {link} 表中的决定。',
  'com.atlassian.migrations-platform.consent-page.done-button-disabled':
    '完成评估、安装并同意后才能继续。',
  'com.atlassian.migrations-platform.consent-page.progress-status-label':
    '已同意的政策',
  'com.atlassian.migrations-platform.consent-page.revoke-consent': '撤销同意',
  'com.atlassian.migrations-platform.consent-page.status.consent-given':
    '您已同意为此应用实施第三方自动化应用数据迁移。',
  'com.atlassian.migrations-platform.consent-page.status.consent-not-given':
    '您必须查看并同意此数据迁移政策，否则无法迁移您的应用数据。',
  'com.atlassian.migrations-platform.consent-page.status.consent-outdated':
    '您同意的政策已更新。请查看变更并再次同意，然后才能迁移您的应用数据。',
  'com.atlassian.migrations-platform.consent-page.status.no-automated-migration-path':
    '此应用没有自动迁移路径。迁移支持的链接 {link}。',
  'com.atlassian.migrations-platform.consent-page.status.no-migrating-alternative':
    '未提供备用应用选择之间的自动化迁移路径。迁移支持的链接 {link}。',
  'com.atlassian.migrations-platform.consent-page.status.no-migration-needed':
    '此应用无需迁移应用数据即可在您的云站点上正常运行。安装应用，迁移核心数据，然后即可开始使用。',
  'com.atlassian.migrations-platform.consent-page.status.server-app-outdated':
    '此应用版本不支持迁移应用数据。您必须先更新您的服务器应用版本，以便同意相关应用迁移政策。',
  'com.atlassian.migrations-platform.consent-page.table-header.call-to-action':
    '政策详情',
  'com.atlassian.migrations-platform.consent-page.table-header.consent-status':
    '应用迁移同意状态',
  'com.atlassian.migrations-platform.consent-page.table-header.needed-in-cloud':
    '云端需要的应用（{count} 个）',
  'com.atlassian.migrations-platform.consent-page.title': '同意迁移应用',
  'com.atlassian.migrations-platform.consent-page.upgrade-app': '更新应用',
  'com.atlassian.migrations-platform.consent-page.view-policy': '查看政策',
  'com.atlassian.migrations-platform.no-logo': '无徽标',
  'com.atlassian.migrations-platform.progress-status.complete':
    '已完成 {percent}',
  'com.atlassian.migrations-platform.progress-status.label':
    '{done}/{total} {unit}',
};
