/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Czech
export default {
  'cross_product_search_dialog.confluence.tab_label': 'Confluence',
  'cross_product_search_dialog.jira.tab_label': 'Jira',
  'global_search.jira.advanced_issue_search_label':
    'Pokročilé vyhledávání požadavků',
  'global_search.jira.advanced_search_boards': 'Boardy',
  'global_search.jira.advanced_search_filters': 'Filtry',
  'global_search.jira.advanced_search_issues': 'Požadavky',
  'global_search.jira.advanced_search_label': 'Přejít na všechny:',
  'global_search.jira.advanced_search_people': 'Lidi',
  'global_search.jira.advanced_search_projects': 'Projekty',
  'global_search.jira.search_placeholder': 'Vyhledat v Jira',
  'product_search_dialog.confluence.advanced_search_with_product_prefix':
    'Pokročilé vyhledávání v Confluence',
  'product_search_dialog.confluence.assignee_filters_find_more':
    'Vyhledejte pověřenou osobu',
  'product_search_dialog.confluence.clear_filters': 'Vymazat filtry',
  'product_search_dialog.confluence.contributor_filters':
    'Filtrovat podle přispěvatele',
  'product_search_dialog.confluence.contributor_filters_find_more':
    'Vyhledejte přispěvatele',
  'product_search_dialog.confluence.filters_applied':
    'Vypadá to, že jste použili nějaké filtry',
  'product_search_dialog.confluence.pages_blogs_attachments_section_heading':
    'Stránky, blogy a přílohy',
  'product_search_dialog.confluence.people_section_heading': 'Lidé',
  'product_search_dialog.confluence.search_input_expanded_placeholder':
    'Hledat v Confluence',
  'product_search_dialog.confluence.space_filters': 'Filtrovat podle prostoru',
  'product_search_dialog.confluence.space_filters_find_more':
    'Vyhledejte prostor',
  'product_search_dialog.confluence.spaces_section_heading': 'Prostory',
  'product_search_dialog.empty.no_results_body':
    'Zkuste to znovu s jiným termínem nebo zpřesněte výsledky pomocí <a>pokročilého vyhledávání</a>.',
  'product_search_dialog.empty.no_results_heading':
    'Nepodařilo se nám najít nic, co by odpovídalo vašemu vyhledávání.',
  'product_search_dialog.error.failed_search_body':
    'Možná šlo jen o náhodnou chybku. Nejlepší bude <a>zkusit to znovu</a>.',
  'product_search_dialog.error.failed_search_heading':
    'Máme problém s vyhledáváním',
  'product_search_dialog.give_feedback': 'Poskytnout zpětnou vazbu',
  'product_search_dialog.jira.advanced_search_with_product_prefix':
    'Pokročilé vyhledávání požadavků v Jira',
  'product_search_dialog.jira.assignee_filters':
    'Filtrovat podle pověřené osoby',
  'product_search_dialog.jira.boards_icon_accessibility_text': 'Ikona boardu',
  'product_search_dialog.jira.boards_projects_filters_section_heading':
    'Boardy, projekty a filtry',
  'product_search_dialog.jira.issues_section_heading': 'Požadavky',
  'product_search_dialog.jira.project_filters': 'Filtrovat podle projektu',
  'product_search_dialog.jira.project_filters_find_more': 'Vyhledejte projekt',
  'product_search_dialog.jira.recent_boards_projects_filters_section_heading':
    'Nedávné boardy, projekty a filtry',
  'product_search_dialog.jira.recently_viewed_issues_section_heading':
    'Nedávno zobrazené požadavky',
  'product_search_dialog.jira.view_all_issues':
    'Pokročilé vyhledávání požadavků',
  'product_search_dialog.more_filters': 'Zobrazit všechny filtry',
  'product_search_dialog.recent_spaces_section_heading': 'Nedávné prostory',
  'product_search_dialog.recently_viewed_heading': 'Rozšířené vyhledávání',
  'product_search_dialog.recently_viewed_section_heading': 'Nedávno zobrazené',
  'product_search_dialog.recently_worked_with_section_heading':
    'Nedávná spolupráce s',
  'product_search_dialog.search_input_collapsed_placeholder': 'Vyhledat',
  'product_search_dialog.search_people_link': 'Vyhledat lidi',
  'product_search_dialog.show_all_results_link': 'Zobrazit všechny výsledky',
  'product_search_dialog.show_more_results_link': 'Zobrazit více',
  'search_dialog.filters.group.show-more': 'Zobrazit více',
};
