/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Danish
export default {
  'cross_product_search_dialog.confluence.tab_label': 'Confluence',
  'cross_product_search_dialog.jira.tab_label': 'Jira',
  'global_search.jira.advanced_issue_search_label': 'Avanceret sagssøgning',
  'global_search.jira.advanced_search_boards': 'Tavler',
  'global_search.jira.advanced_search_filters': 'Filtre',
  'global_search.jira.advanced_search_issues': 'Sager',
  'global_search.jira.advanced_search_label': 'Gå til alle:',
  'global_search.jira.advanced_search_people': 'Personer',
  'global_search.jira.advanced_search_projects': 'Projekter',
  'global_search.jira.search_placeholder': 'Søg på Jira',
  'product_search_dialog.confluence.advanced_search_with_product_prefix':
    'Avanceret Confluence-søgning',
  'product_search_dialog.confluence.assignee_filters_find_more':
    'Find en modtager',
  'product_search_dialog.confluence.clear_filters': 'Ryd filtre',
  'product_search_dialog.confluence.contributor_filters':
    'Filtrér efter bidragyder',
  'product_search_dialog.confluence.contributor_filters_find_more':
    'Find en bidragsyder',
  'product_search_dialog.confluence.filters_applied':
    'Det lader til, at du anvender filtre',
  'product_search_dialog.confluence.pages_blogs_attachments_section_heading':
    'Sider, blogs og bilag',
  'product_search_dialog.confluence.people_section_heading': 'Personer',
  'product_search_dialog.confluence.search_input_expanded_placeholder':
    'Søg i Confluence',
  'product_search_dialog.confluence.space_filters': 'Filtrér efter område',
  'product_search_dialog.confluence.space_filters_find_more': 'Find et område',
  'product_search_dialog.confluence.spaces_section_heading': 'Områder',
  'product_search_dialog.empty.no_results_body':
    'Prøv igen med et andet ord, eller indsnævr resultaterne via <a>Avanceret søgning</a>',
  'product_search_dialog.empty.no_results_heading':
    'Vi kunne ikke finde noget, der matchede din søgning.',
  'product_search_dialog.error.failed_search_body':
    'Det kan være et midlertidigt problem. Det bedste, du kan gøre, er at <a>prøve igen.</a>',
  'product_search_dialog.error.failed_search_heading':
    'Vi har problemer med at søge',
  'product_search_dialog.give_feedback': 'Giv feedback',
  'product_search_dialog.jira.advanced_search_with_product_prefix':
    'Avanceret Jira-sagssøgning',
  'product_search_dialog.jira.assignee_filters': 'Filtrer efter modtager',
  'product_search_dialog.jira.boards_icon_accessibility_text': 'Tavleikon',
  'product_search_dialog.jira.boards_projects_filters_section_heading':
    'Tavler, projekter og filtre',
  'product_search_dialog.jira.issues_section_heading': 'Sager',
  'product_search_dialog.jira.project_filters': 'Filtrer efter projekt',
  'product_search_dialog.jira.project_filters_find_more': 'Find et projekt',
  'product_search_dialog.jira.recent_boards_projects_filters_section_heading':
    'Seneste tavler, projekter og filtre',
  'product_search_dialog.jira.recently_viewed_issues_section_heading':
    'Senest viste sager',
  'product_search_dialog.jira.view_all_issues': 'Avanceret søgning efter sager',
  'product_search_dialog.more_filters': 'Vis alle filtre',
  'product_search_dialog.recent_spaces_section_heading': 'Seneste områder',
  'product_search_dialog.recently_viewed_heading': 'Avanceret søgning',
  'product_search_dialog.recently_viewed_section_heading': 'Set for nylig',
  'product_search_dialog.recently_worked_with_section_heading':
    'Arbejdet med for nylig',
  'product_search_dialog.search_input_collapsed_placeholder': 'Søg',
  'product_search_dialog.search_people_link': 'Søg efter personer',
  'product_search_dialog.show_all_results_link': 'Se alle resultater',
  'product_search_dialog.show_more_results_link': 'Vis mere',
  'search_dialog.filters.group.show-more': 'Vis flere',
};
