/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Slovak
export default {
  'cross_product_search_dialog.confluence.tab_label': 'Confluence',
  'cross_product_search_dialog.jira.tab_label': 'Jira',
  'global_search.jira.advanced_issue_search_label':
    'Rozšírené vyhľadávanie problémov',
  'global_search.jira.advanced_search_boards': 'Nástenky',
  'global_search.jira.advanced_search_filters': 'Filtre',
  'global_search.jira.advanced_search_issues': 'Problémy',
  'global_search.jira.advanced_search_label': 'Prejsť na všetky:',
  'global_search.jira.advanced_search_people': 'Ľudia',
  'global_search.jira.advanced_search_projects': 'Projekty',
  'global_search.jira.search_placeholder': 'Prehľadávať Jira',
  'product_search_dialog.confluence.advanced_search_with_product_prefix':
    'Rozšírené vyhľadávanie v Confluence',
  'product_search_dialog.confluence.assignee_filters_find_more':
    'Vyhľadajte poverenú osobu',
  'product_search_dialog.confluence.clear_filters': 'Vymazať filtre',
  'product_search_dialog.confluence.contributor_filters':
    'Filtrovať podľa prispievateľov',
  'product_search_dialog.confluence.contributor_filters_find_more':
    'Vyhľadať prispievateľa',
  'product_search_dialog.confluence.filters_applied':
    'Zdá sa, že ste použili nejaké filtre',
  'product_search_dialog.confluence.pages_blogs_attachments_section_heading':
    'Stránky, blogy a prílohy',
  'product_search_dialog.confluence.people_section_heading': 'Ľudia',
  'product_search_dialog.confluence.search_input_expanded_placeholder':
    'Hľadať v Confluence',
  'product_search_dialog.confluence.space_filters':
    'Filtrovať podľa priestorov',
  'product_search_dialog.confluence.space_filters_find_more':
    'Vyhľadať priestor',
  'product_search_dialog.confluence.spaces_section_heading': 'Priestory',
  'product_search_dialog.empty.no_results_body':
    'Skúste zadať iný výraz alebo výberom možnosti <a>Rozšírené vyhľadávanie</a> výsledky spresnite.',
  'product_search_dialog.empty.no_results_heading':
    'Nepodarilo sa nám nájsť nič, čo by zodpovedalo vášmu vyhľadávaniu.',
  'product_search_dialog.error.failed_search_body':
    'Môže to byť iba drobný problém. Najlepšie je <a>skúsiť to znova.</a>',
  'product_search_dialog.error.failed_search_heading':
    'Vyskytol sa problém s vyhľadávaním',
  'product_search_dialog.give_feedback': 'Poskytnúť spätnú väzbu',
  'product_search_dialog.jira.advanced_search_with_product_prefix':
    'Rozšírené vyhľadávanie problémov v Jira',
  'product_search_dialog.jira.assignee_filters':
    'Filtrovať podľa poverenej osoby',
  'product_search_dialog.jira.boards_icon_accessibility_text': 'Ikona nástenky',
  'product_search_dialog.jira.boards_projects_filters_section_heading':
    'Nástenky, projekty a filtre',
  'product_search_dialog.jira.issues_section_heading': 'Problémy',
  'product_search_dialog.jira.project_filters': 'Filtrovať podľa projektu',
  'product_search_dialog.jira.project_filters_find_more': 'Vyhľadajte projekt',
  'product_search_dialog.jira.recent_boards_projects_filters_section_heading':
    'Nedávne nástenky, projekty a filtre',
  'product_search_dialog.jira.recently_viewed_issues_section_heading':
    'Nedávno zobrazené problémy',
  'product_search_dialog.jira.view_all_issues': 'Rozšírené hľadanie problémov',
  'product_search_dialog.more_filters': 'Zobraziť všetky filtre',
  'product_search_dialog.recent_spaces_section_heading':
    'Naposledy použité priestory',
  'product_search_dialog.recently_viewed_heading': 'Rozšírené vyhľadávanie',
  'product_search_dialog.recently_viewed_section_heading':
    'Naposledy zobrazené',
  'product_search_dialog.recently_worked_with_section_heading':
    'Posledná spolupráca:',
  'product_search_dialog.search_input_collapsed_placeholder': 'Vyhľadať',
  'product_search_dialog.search_people_link': 'Vyhľadať ľudí',
  'product_search_dialog.show_all_results_link': 'Zobraziť všetky výsledky',
  'product_search_dialog.show_more_results_link': 'Zobraziť viac',
  'search_dialog.filters.group.show-more': 'Zobraziť viac',
};
