/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Vietnamese
export default {
  'cross_product_search_dialog.confluence.tab_label': 'Confluence',
  'cross_product_search_dialog.jira.tab_label': 'Jira',
  'global_search.jira.advanced_issue_search_label': 'Tìm kiếm vấn đề nâng cao',
  'global_search.jira.advanced_search_boards': 'Bảng',
  'global_search.jira.advanced_search_filters': 'Bộ lọc',
  'global_search.jira.advanced_search_issues': 'Vấn đề',
  'global_search.jira.advanced_search_label': 'Đến tất cả:',
  'global_search.jira.advanced_search_people': 'Con người',
  'global_search.jira.advanced_search_projects': 'Dự án',
  'global_search.jira.search_placeholder': 'Tìm kiếm Jira',
  'product_search_dialog.confluence.advanced_search_with_product_prefix':
    'Tính năng tìm kiếm nâng cao của Confluence',
  'product_search_dialog.confluence.assignee_filters_find_more':
    'Tìm người được chỉ định',
  'product_search_dialog.confluence.clear_filters': 'Xóa bộ lọc',
  'product_search_dialog.confluence.contributor_filters':
    'Lọc theo nhà phân phối',
  'product_search_dialog.confluence.contributor_filters_find_more':
    'Tìm nhà phân phối',
  'product_search_dialog.confluence.filters_applied':
    'Có vẻ bạn đã áp dụng một số tùy chọn lọc',
  'product_search_dialog.confluence.pages_blogs_attachments_section_heading':
    'Các trang, blog và tài liệu đính kèm',
  'product_search_dialog.confluence.people_section_heading': 'Con người',
  'product_search_dialog.confluence.search_input_expanded_placeholder':
    'Tìm kiếm Confluence',
  'product_search_dialog.confluence.space_filters': 'Lọc theo không gian',
  'product_search_dialog.confluence.space_filters_find_more': 'Tìm không gian',
  'product_search_dialog.confluence.spaces_section_heading': 'Không gian',
  'product_search_dialog.empty.no_results_body':
    'Hãy thử lại với cụm từ tím kiếm khác hoặc tinh chỉnh kết quả của bạn bằng <a>Tìm kiếm nâng cao</a>',
  'product_search_dialog.empty.no_results_heading':
    'Không tìm thấy bất kỳ nội dung nào phù hợp với nội dung tìm kiếm của bạn.',
  'product_search_dialog.error.failed_search_body':
    'Có thể đã xảy ra sự cố. Tốt nhất nên <a>thử lại.</a>',
  'product_search_dialog.error.failed_search_heading':
    'Đã gặp sự cố khi tìm kiếm',
  'product_search_dialog.give_feedback': 'Gửi ý kiến phản hồi',
  'product_search_dialog.jira.advanced_search_with_product_prefix':
    'Tính năng tìm kiếm nâng cao của Jira',
  'product_search_dialog.jira.assignee_filters': 'Lọc theo người được chỉ định',
  'product_search_dialog.jira.boards_icon_accessibility_text':
    'Biểu tượng bảng',
  'product_search_dialog.jira.boards_projects_filters_section_heading':
    'Bảng, dự án và mục lọc',
  'product_search_dialog.jira.issues_section_heading': 'Vấn đề',
  'product_search_dialog.jira.project_filters': 'Lọc theo dự án',
  'product_search_dialog.jira.project_filters_find_more': 'Tìm dự án',
  'product_search_dialog.jira.recent_boards_projects_filters_section_heading':
    'Bảng, dự án và mục lọc gần đây',
  'product_search_dialog.jira.recently_viewed_issues_section_heading':
    'Vấn đề mới xem gần đây',
  'product_search_dialog.jira.view_all_issues': 'Tìm kiếm nâng cao các vấn đề',
  'product_search_dialog.more_filters': 'Xem tất cả bộ lọc',
  'product_search_dialog.recent_spaces_section_heading': 'Không gian gần đây',
  'product_search_dialog.recently_viewed_heading': 'Tìm kiếm nâng cao',
  'product_search_dialog.recently_viewed_section_heading': 'Đã xem gần đây',
  'product_search_dialog.recently_worked_with_section_heading':
    'Người đã cùng làm việc gần đây',
  'product_search_dialog.search_input_collapsed_placeholder': 'Tìm kiếm',
  'product_search_dialog.search_people_link': 'Tìm kiếm người',
  'product_search_dialog.show_all_results_link': 'Xem tất cả kết quả',
  'product_search_dialog.show_more_results_link': 'Hiển thị thêm',
  'search_dialog.filters.group.show-more': 'Hiển thị thêm',
};
