/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Danish
export default {
  'migration.choose.what.to.migrate.app.selection.radio.all.label.main': 'Alle',
  'migration.choose.what.to.migrate.app.selection.radio.all.label.sub':
    'Alle – {appsCount} er markeret som nødvendige i skyen med en overførselssti',
  'migration.choose.what.to.migrate.app.selection.radio.none.label': 'Ingen',
  'migration.choose.what.to.migrate.app.selection.tooltip.no-apps':
    'Du har ikke markeret nogen apps som nødvendige i skyen. Hvis du vil overføre appdata, skal du ændre din beslutning under appvurderingen.',
};
