/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Japanese
export default {
  'fabric.notificationList.allyListDescription':
    '通知は最新のものから順に並べ替えられています',
  'fabric.notificationList.changeBoardingAcknowledge': 'OK',
  'fabric.notificationList.changeBoardingBodyText':
    '整理しやすくするために、既読の通知を非表示にできるようになりました。[<strong>未読のみ表示</strong>] を選択して通知をフィルタリングすることで、最新のアクティビティの状況を確認できます。',
  'fabric.notificationList.changeBoardingLearnMore': 'さらに詳しく',
  'fabric.notificationList.changeBoardingTitle': '重要なことに集中',
  'fabric.notificationList.contentLoadFailure': '読み込めません',
  'fabric.notificationList.direct': '直接',
  'fabric.notificationList.globalErrorBoundaryDescription':
    'エラーは追跡されていますが、更新しても問題が解決しない場合はお気軽にお問い合わせください。',
  'fabric.notificationList.markAllAsRead': 'すべて既読にする',
  'fabric.notificationList.markNotificationAsRead': '既読にする',
  'fabric.notificationList.markNotificationAsUnread': '未読にする',
  'fabric.notificationList.noNotificationsLoadingDescription':
    '過去 30 日間の通知はありません。',
  'fabric.notificationList.noUnreadNotifications':
    '過去 30 日間のすべての通知は<strong>既読</strong>です。',
  'fabric.notificationList.notifications': '通知',
  'fabric.notificationList.notificationsLoadingErrorDescription':
    '現在、通知をこれ以上読み込めません。後でもう一度お試しください',
  'fabric.notificationList.notificationsLoadingErrorTitle':
    'エラーが発生しました',
  'fabric.notificationList.onlyShowUnread': '未読のみ表示',
  'fabric.notificationList.readAllNotifications.description':
    '過去 30 日間の<strong>未読</strong>通知はこれで全部です。',
  'fabric.notificationList.timeGroupingLatest': '最新',
  'fabric.notificationList.timeGroupingOlder': 'さらに前',
  'fabric.notificationList.timeGroupingToday': '今日',
  'fabric.notificationList.timeGroupingYesterday': '昨日',
  'fabric.notificationList.title': '通知',
  'fabric.notificationList.unread': '未読のみ表示',
  'fabric.notificationList.upToDate.description':
    '過去 30 日間の通知はこれで全部です。',
  'fabric.notificationList.watching': 'ウォッチ',
};
