/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Dutch
export default {
  'fabric.notificationList.allyListDescription':
    'Je meldingen, gesorteerd op meest recent',
  'fabric.notificationList.changeBoardingAcknowledge': 'Oké',
  'fabric.notificationList.changeBoardingBodyText':
    'Om je te helpen georganiseerd te blijven, kun je nu meldingen verbergen die je al hebt gelezen. Je kunt meldingen filteren door <strong>Alleen ongelezen weergeven</strong> te selecteren om op de hoogte te blijven van de meest recente activiteit.',
  'fabric.notificationList.changeBoardingLearnMore': 'Meer informatie',
  'fabric.notificationList.changeBoardingTitle':
    'Blijf gefocust op wat belangrijk is',
  'fabric.notificationList.contentLoadFailure': 'Kan niet laden',
  'fabric.notificationList.direct': 'Direct',
  'fabric.notificationList.globalErrorBoundaryDescription':
    'We houden dit soort foutmeldingen bij, maar je kunt altijd contact met ons opnemen wanneer vernieuwen niet helpt.',
  'fabric.notificationList.markAllAsRead': 'Alles markeren als gelezen',
  'fabric.notificationList.markNotificationAsRead': 'Markeren als gelezen',
  'fabric.notificationList.markNotificationAsUnread': 'Markeren als ongelezen',
  'fabric.notificationList.noNotificationsLoadingDescription':
    'Je hebt geen meldingen van de afgelopen 30 dagen.',
  'fabric.notificationList.noUnreadNotifications':
    'Je hebt alle meldingen van de afgelopen 30 dagen <strong>gelezen</strong>.',
  'fabric.notificationList.notifications': 'Meldingen',
  'fabric.notificationList.notificationsLoadingErrorDescription':
    'We konden momenteel niet meer meldingen laden, probeer het later opnieuw',
  'fabric.notificationList.notificationsLoadingErrorTitle':
    'Er is iets misgegaan',
  'fabric.notificationList.onlyShowUnread': 'Alleen ongelezen weergeven',
  'fabric.notificationList.readAllNotifications.description':
    'Dit zijn al je <strong>ongelezen </strong>meldingen van de afgelopen 30 dagen.',
  'fabric.notificationList.timeGroupingLatest': 'Recentst',
  'fabric.notificationList.timeGroupingOlder': 'Ouder',
  'fabric.notificationList.timeGroupingToday': 'Vandaag',
  'fabric.notificationList.timeGroupingYesterday': 'Gisteren',
  'fabric.notificationList.title': 'Meldingen',
  'fabric.notificationList.unread': 'Alleen ongelezen weergeven',
  'fabric.notificationList.upToDate.description':
    'Dit zijn al je meldingen van de afgelopen 30 dagen.',
  'fabric.notificationList.watching': 'Volgend',
};
