/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Chinese
export default {
  'fabric.notificationList.allyListDescription': '您的通知已按最近时间顺序排序',
  'fabric.notificationList.changeBoardingAcknowledge': '确定',
  'fabric.notificationList.changeBoardingBodyText':
    '为了帮助您保持条理，现在可以隐藏已阅读的通知。通过选择<strong>仅显示未读</strong>来筛选通知，以及时了解最新活动。',
  'fabric.notificationList.changeBoardingLearnMore': '了解更多',
  'fabric.notificationList.changeBoardingTitle': '专注于重要的事务',
  'fabric.notificationList.contentLoadFailure': '无法加载',
  'fabric.notificationList.direct': '直接',
  'fabric.notificationList.globalErrorBoundaryDescription':
    '我们会持续跟踪这些错误，但如果刷新不能解决问题，请随时与我们联系。',
  'fabric.notificationList.markAllAsRead': '全部标记为已读',
  'fabric.notificationList.markNotificationAsRead': '标记为已读',
  'fabric.notificationList.markNotificationAsUnread': '标记为未读',
  'fabric.notificationList.noNotificationsLoadingDescription':
    '您在过去 30 天内没有任何通知。',
  'fabric.notificationList.noUnreadNotifications':
    '您已<strong>阅读</strong>过去 30 天内的所有通知。',
  'fabric.notificationList.notifications': '通知',
  'fabric.notificationList.notificationsLoadingErrorDescription':
    '当前无法加载更多通知，请稍后重试',
  'fabric.notificationList.notificationsLoadingErrorTitle': '出错了',
  'fabric.notificationList.onlyShowUnread': '仅显示未读',
  'fabric.notificationList.readAllNotifications.description':
    '这是您过去 30 天内的所有<strong>未读</strong>通知。',
  'fabric.notificationList.timeGroupingLatest': '最新',
  'fabric.notificationList.timeGroupingOlder': '更早',
  'fabric.notificationList.timeGroupingToday': '今天',
  'fabric.notificationList.timeGroupingYesterday': '昨天',
  'fabric.notificationList.title': '通知',
  'fabric.notificationList.unread': '仅显示未读',
  'fabric.notificationList.upToDate.description':
    '这是您过去 30 天内的所有通知。',
  'fabric.notificationList.watching': '已关注',
};
