/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// undefined
export default {
  'dragonfruit-create-component-modal.component-type-select.label-placeholder':
    '選取元件類型',
  'dragonfruit-create-component-modal.create-component-error-flag-title':
    '建立元件時發生錯誤',
  'dragonfruit-create-component-modal.create-component-form-create-team-button':
    '開始建立團隊',
  'dragonfruit-create-component-modal.create-component-name-field-placeholder':
    '輸入元件名稱',
  'dragonfruit-create-component-modal.create-component-owner-field-helper-message':
    '負責維護元件的團隊。',
  'dragonfruit-navigation.create-component-modal.create-component-form-modal-dialog-title':
    '建立元件',
};
