import {
  Annotation,
  AnnotationResult,
  AnnotationSeverity,
  AnnotationType,
} from '../types';

export const annotations: Annotation[] = [
  {
    uuid: 'annotation-1',
    annotation_type: AnnotationType.Bug,
    details: 'Bug Failed Critical Annotation Bug Failed Critical Annotation',
    external_id: 'annotation-1-external',
    line: 10,
    link: 'http://annotation-1',
    path: 'annotation.java',
    result: AnnotationResult.Failed,
    severity: AnnotationSeverity.Critical,
    summary: 'Bug Failed Critical Annotation',
    type: 'type-1',
    created_on: '2010-05-25T02:01:44.578Z',
    updated_on: '2010-05-25T02:01:44.578Z',
  },
  {
    uuid: 'annotation-2',
    annotation_type: AnnotationType.CodeSmell,
    details:
      'CodeSmell Passed High Annotation CodeSmell Passed High Annotation',
    external_id: 'annotation-2-external',
    line: 12,
    link: 'http://annotation-2',
    path: 'src/application/common/main.java',
    result: AnnotationResult.Passed,
    severity: AnnotationSeverity.High,
    summary: 'CodeSmell Passed High Annotation',
    type: 'type-2',
    created_on: '2010-05-25T02:01:44.578Z',
    updated_on: '2010-05-25T02:01:44.578Z',
  },
  {
    uuid: 'annotation-4',
    annotation_type: AnnotationType.Vulnerability,
    details:
      'Vulnerability Skipped Medium Annotation Vulnerability Skipped Medium Annotation',
    external_id: 'annotation-4-external',
    line: 10,
    link: 'http://annotation-4',
    path: 'annotation.java',
    result: AnnotationResult.Skipped,
    severity: AnnotationSeverity.Medium,
    summary: 'Vulnerability Skipped Medium Annotation',
    type: 'type-4',
    created_on: '2010-05-25T02:01:44.578Z',
    updated_on: '2010-05-25T02:01:44.578Z',
  },
  {
    uuid: 'annotation-3',
    annotation_type: AnnotationType.Vulnerability,
    details:
      'Vulnerability Ignored Low Annotation Vulnerability Ignored Low Annotation',
    external_id: 'annotation-3-external',
    line: 10,
    link: 'http://annotation-3',
    path: 'annotation.java',
    result: AnnotationResult.Ignored,
    severity: AnnotationSeverity.Low,
    summary: 'Vulnerability Ignored Low Annotation',
    type: 'type-3',
    created_on: '2010-05-25T02:01:44.578Z',
    updated_on: '2010-05-25T02:01:44.578Z',
  },
];
