import { Report, ReportResult, ReportType } from '../types';

export const reports: Report[] = [
  {
    uuid: 'report-1',
    report_type: ReportType.Bug,
    type: 'type-1',
    title: 'Bug Passed Report',
    details: 'Bug Passed Report Bug Passed Report',
    result: ReportResult.Passed,
    reporter: 'reporter-1',
    external_id: 'report-1-external',
    created_on: '2010-05-25T02:01:44.578Z',
    updated_on: '2010-05-25T02:01:44.578Z',
    is_locked: false,
    data: [
      { title: 'FAILED', type: 'BOOLEAN', value: true },
      { title: 'Run date', type: 'DATE', value: '2019-10-11T05:45:16.468Z' },
      { title: 'Test duration', type: 'DURATION', value: 5000 },
      {
        title: 'Link',
        type: 'LINK',
        value: {
          text: 'PDF Report',
          href: 'https://bug-tool.atlassian.com/report/10.pdf',
        },
      },
      { title: 'Number of tests', type: 'NUMBER', value: 1 },
      { title: 'Failure percentage', type: 'PERCENTAGE', value: 100 },
      { title: 'Text', type: 'TEXT', value: 'Bug found please fix.' },
    ],
  },
  {
    uuid: 'report-2',
    report_type: ReportType.Coverage,
    type: 'type-2',
    title: 'Coverage Failed Report',
    details: 'Coverage Failed Report Coverage Failed Report',
    result: ReportResult.Failed,
    reporter: 'reporter-2',
    external_id: 'report-2-external',
    created_on: '2010-05-25T02:01:44.578Z',
    updated_on: '2010-05-25T02:01:44.578Z',
    is_locked: false,
  },
  {
    uuid: 'report-3',
    report_type: ReportType.Security,
    type: 'type-3',
    title: 'Security Pending Report',
    details: 'Security Pending Report Security Pending Report',
    result: ReportResult.Pending,
    reporter: 'reporter-3',
    external_id: 'report-3-external',
    created_on: '2010-05-25T02:01:44.578Z',
    updated_on: '2010-05-25T02:01:44.578Z',
    is_locked: false,
  },
  {
    uuid: 'report-4',
    report_type: ReportType.Test,
    type: 'type-4',
    title: 'Test Unknown Report',
    details: 'Test Unknown Report Test Unknown Report',
    result: ReportResult.Unknown,
    reporter: 'reporter-4',
    external_id: 'report-4-external',
    created_on: '2010-05-25T02:01:44.578Z',
    updated_on: '2010-05-25T02:01:44.578Z',
    is_locked: false,
  },
  {
    uuid: 'report-4',
    report_type: ReportType.Test,
    type: 'type-4',
    title: 'Locked Report',
    details: 'Test Report Test Report',
    result: ReportResult.Unknown,
    reporter: 'reporter-4',
    external_id: 'report-4-external',
    created_on: '2010-05-25T02:01:44.578Z',
    updated_on: '2010-05-25T02:01:44.578Z',
    is_locked: true,
  },
];
