/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Japanese
export default {
  'dragonfruit-site-permissions.cannotAccessDragonfruit':
    'Compass にアクセスできません',
  'dragonfruit-site-permissions.contactAdministrator':
    '管理者に連絡してください。',
  'dragonfruit-site-permissions.needAccessToJira':
    'Compass を使用するには、{JiraLink} へのアクセスが必要です。',
};
