/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Czech
export default {
  'jira-portfolio-plan-wizard.common-popup-multi-select.excluded-from-plan':
    'Vyloučené z plánu',
  'jira-portfolio-plan-wizard.refine-issues.all-statuses-from-category':
    'Všechny stavy kategorie {categoryName}',
  'jira-portfolio-plan-wizard.refine-issues.back-to-create-plan':
    'Zpět na vytváření plánu',
  'jira-portfolio-plan-wizard.refine-issues.choose-status-placeholder':
    'Zvolit stav',
  'jira-portfolio-plan-wizard.refine-issues.choose-type-placeholder':
    'Zvolit typ',
  'jira-portfolio-plan-wizard.refine-issues.days-since-done-validation':
    'Zadejte celé číslo.',
  'jira-portfolio-plan-wizard.refine-issues.description':
    'Nastavte pravidla vyloučení požadavků, které v tomto plánu nechcete zobrazit. Tato pravidla lze později změnit.',
  'jira-portfolio-plan-wizard.refine-issues.description-settings':
    'Upravte pravidla vyloučení požadavků, které v tomto plánu nechcete zobrazit.',
  'jira-portfolio-plan-wizard.refine-issues.exclude-days-after':
    '{value, plural, one {den} few {dny} many {dne} other {dnů}}',
  'jira-portfolio-plan-wizard.refine-issues.exclude-days-label':
    'Vyloučit vyřešené požadavky po',
  'jira-portfolio-plan-wizard.refine-issues.exclude-days-label-status-category-change-date':
    'Vyloučit všechny dokončené požadavky po',
  'jira-portfolio-plan-wizard.refine-issues.exclude-days-learn-more':
    'Další informace',
  'jira-portfolio-plan-wizard.refine-issues.exclude-days-subscript':
    '{value, plural, one {V tomto plánu se nezobrazí žádné požadavky, které se nacházejí v kategorii stavů „Hotovo“ déle než {value} den. {LearnMoreLink}} few {V tomto plánu se nezobrazí žádné požadavky, které se nacházejí v kategorii stavů „Hotovo“ déle než {value} dny. {LearnMoreLink}} many {V tomto plánu se nezobrazí žádné požadavky, které se nacházejí v kategorii stavů „Hotovo“ déle než {value} dne. {LearnMoreLink}} other {V tomto plánu se nezobrazí žádné požadavky, které se nacházejí v kategorii stavů „Hotovo“ déle než {value} dnů. {LearnMoreLink}}}',
  'jira-portfolio-plan-wizard.refine-issues.exclude-days-subscript-status-change-category-done':
    '{value, plural, one {V plánu se nezobrazí žádné požadavky, které byly označeny jako dokončené před více než {value} dnem. {LearnMoreLink}} few {V plánu se nezobrazí žádné požadavky, které byly označeny jako dokončené před více než {value} dny. {LearnMoreLink}} many {V plánu se nezobrazí žádné požadavky, které byly označeny jako dokončené před více než {value} dny. {LearnMoreLink}} other {V plánu se nezobrazí žádné požadavky, které byly označeny jako dokončené před více než {value} dny. {LearnMoreLink}}}',
  'jira-portfolio-plan-wizard.refine-issues.exclude-issue-type-label':
    'Vyloučení typů požadavků',
  'jira-portfolio-plan-wizard.refine-issues.exclude-releases':
    'Vyloučit vydání',
  'jira-portfolio-plan-wizard.refine-issues.exclude-status-type-label':
    'Vyloučit stavy',
  'jira-portfolio-plan-wizard.refine-issues.no-statuses-excluded':
    'Z plánu nejsou vyloučeny žádné stavy požadavků',
  'jira-portfolio-plan-wizard.refine-issues.no-types-excluded':
    'Z plánu nejsou vyloučeny žádné typy požadavků',
  'jira-portfolio-plan-wizard.refine-issues.num-excluded-releases':
    '{numExcludedReleases, plural, one {{numExcludedReleases} vydání vyloučeno} few {{numExcludedReleases} vydání vyloučena} many {{numExcludedReleases} vydání vyloučeno} other {{numExcludedReleases} vydání vyloučeno}}',
  'jira-portfolio-plan-wizard.refine-issues.status': 'Stav',
  'jira-portfolio-plan-wizard.refine-issues.status-loading': 'načítání…',
  'jira-portfolio-plan-wizard.refine-issues.status-no-options':
    'Žádné možnosti',
  'jira-portfolio-plan-wizard.refine-issues.title':
    'Zpřesnit zobrazené požadavky',
  'jira-portfolio-plan-wizard.refine-issues.title-settings-page':
    'Pravidla vyloučení',
  'jira-portfolio-plan-wizard.refine-issues.type': 'Typ',
  'jira-portfolio-plan-wizard.refine-issues.types-loading': 'načítání…',
  'jira-portfolio-plan-wizard.refine-issues.types-no-options': 'Žádné možnosti',
  'jira-portfolio-plan-wizard.refine-issues.view-releases': 'Zobrazit vydání',
  'jira-portfolio-plan-wizard.refine-issues.view-releases-cancel': 'Zrušit',
  'jira-portfolio-plan-wizard.remove-issues.default-status': 'k vyřešení',
  'jira-portfolio-plan-wizard.remove-issues.description':
    'Níže uvedené požadavky byly odebrány z plánu, ale v Jira stále existují. Vyberte jakékoli z nich, které chcete znovu zahrnout. Požadavků můžete načíst maximálně {issueLimit}.',
  'jira-portfolio-plan-wizard.remove-issues.epic': 'epic',
  'jira-portfolio-plan-wizard.remove-issues.hierarchy': 'Hierarchie',
  'jira-portfolio-plan-wizard.remove-issues.hierarchy-divider': 'do',
  'jira-portfolio-plan-wizard.remove-issues.loading': 'načítání',
  'jira-portfolio-plan-wizard.remove-issues.more': 'další možnosti',
  'jira-portfolio-plan-wizard.remove-issues.no-available-excluded-issues':
    'Nejsou k dispozici žádné požadavky, které by bylo možné znovu zahrnout do plánu.',
  'jira-portfolio-plan-wizard.remove-issues.reinclude': 'Znovu zahrnout',
  'jira-portfolio-plan-wizard.remove-issues.search-issues':
    'Vyhledat požadavky',
  'jira-portfolio-plan-wizard.remove-issues.select-only-descendants':
    'Vybrat pouze odvozené požadavky',
  'jira-portfolio-plan-wizard.remove-issues.select-this-and-all-descendants':
    'Vybrat tento a všechny odvozené požadavky',
  'jira-portfolio-plan-wizard.remove-issues.story': 'story',
  'jira-portfolio-plan-wizard.remove-issues.subtask': 'podúkol',
  'jira-portfolio-plan-wizard.remove-issues.table-header-deselect-all':
    'Zrušit výběr všech',
  'jira-portfolio-plan-wizard.remove-issues.table-header-issue': 'Požadavek',
  'jira-portfolio-plan-wizard.remove-issues.table-header-select-all':
    'Vybrat vše',
  'jira-portfolio-plan-wizard.remove-issues.table-header-status': 'Stav',
  'jira-portfolio-plan-wizard.remove-issues.title': 'Odebrané požadavky',
  'jira-portfolio-plan-wizard.view-releases.description-exclude':
    'Vyberte vydání, která chcete vyloučit z plánu. Vyloučí se tím všechny požadavky asociované s daným vydáním.',
  'jira-portfolio-plan-wizard.view-releases.description-re-include':
    'Vydání, která už byla vydána, jsou z plánu vyloučena. V seznamu níže vyberte případná vydání, která chcete znovu zahrnout.',
  'jira-portfolio-plan-wizard.view-releases.description-select-re-include':
    'Vyberte vydání, která chcete znovu zahrnout do plánu. Zahrnou se tím všechny požadavky asociované s daným vydáním.',
  'jira-portfolio-plan-wizard.view-releases.modal-close': 'Zrušit',
  'jira-portfolio-plan-wizard.view-releases.modal-exclude': 'Vyloučit',
  'jira-portfolio-plan-wizard.view-releases.modal-heading': 'Vydání',
  'jira-portfolio-plan-wizard.view-releases.modal-include': 'Zahrnout',
  'jira-portfolio-plan-wizard.view-releases.option-exclude':
    'Vydání zahrnutá v plánu',
  'jira-portfolio-plan-wizard.view-releases.option-re-include':
    'Vydání vyloučená z plánu',
  'jira-portfolio-plan-wizard.view-releases.project-select.all': 'Vše',
  'jira-portfolio-plan-wizard.view-releases.project-select.all-projects':
    'Všechny projekty',
  'jira-portfolio-plan-wizard.view-releases.project-select.clear-selected':
    'Vymazat vybrané',
  'jira-portfolio-plan-wizard.view-releases.project-select.label': 'Projekt',
  'jira-portfolio-plan-wizard.view-releases.project-select.loading':
    'Načítání…',
  'jira-portfolio-plan-wizard.view-releases.project-select.none':
    'Žádné dostupné projekty',
  'jira-portfolio-plan-wizard.view-releases.released': 'vydáno',
  'jira-portfolio-plan-wizard.view-releases.search-for-release':
    'Vyhledejte vydání…',
  'jira-portfolio-plan-wizard.view-releases.selected-release-count-label':
    '{numSelectedReleases, plural, one {{numSelectedReleases} vybrané verze} few {{numSelectedReleases} vybrané verze} many {{numSelectedReleases} vybrané verze} other {{numSelectedReleases} vybrané verze}}',
  'jira-portfolio-plan-wizard.view-releases.table-header-deselect-all':
    'Zrušit výběr všech',
  'jira-portfolio-plan-wizard.view-releases.table-header-relesea-date':
    'Datum vydání',
  'jira-portfolio-plan-wizard.view-releases.table-header-select-all':
    'Vybrat vše',
  'jira-portfolio-plan-wizard.view-releases.table-header-start-date':
    'Počáteční datum',
  'jira-portfolio-plan-wizard.view-releases.table-header-status': 'Stav',
  'jira-portfolio-plan-wizard.view-releases.table-header-title': 'Název',
  'jira-portfolio-plan-wizard.view-releases.table-no-available-releases-exclude':
    'Nejsou k dispozici žádná vydání, která byste mohli vyloučit z plánu.',
  'jira-portfolio-plan-wizard.view-releases.table-no-available-releases-include':
    'Nejsou k dispozici žádná vydání, která byste mohli zahrnout do plánu.',
  'jira-portfolio-plan-wizard.view-releases.title': 'Vydání',
  'jira.portfolio-plan-wizard.common-issue-count.issues-in-plan':
    'Požadavky v plánu',
  'jira.portfolio-plan-wizard.over-limit-flag.title':
    'Plán se nepodařilo vytvořit',
  'jira.portfolio-plan-wizard.over-limit-flag.too-many-issues':
    '{limit, plural, one {Plán překročil limit požadavků ({limit}). Zkuste odebrat zdroj požadavků nebo nastavit pravidla tak, abyste z plánu vyloučili více požadavků.} few {Plán překročil limit požadavků ({limit}). Zkuste odebrat zdroj požadavků nebo nastavit pravidla tak, abyste z plánu vyloučili více požadavků.} many {Plán překročil limit požadavků ({limit}). Zkuste odebrat zdroj požadavků nebo nastavit pravidla tak, abyste z plánu vyloučili více požadavků.} other {Plán překročil limit požadavků ({limit}). Zkuste odebrat zdroj požadavků nebo nastavit pravidla tak, abyste z plánu vyloučili více požadavků.}}',
  'jira.portfolio-plan-wizard.over-limit-flag.too-many-projects':
    '{limit, plural, one {Vybrané zdroje se připojují k více než {limit} projektu. Bude potřeba změnit zdroje požadavků tak, aby zahrnovaly méně projektů.} few {Vybrané zdroje se připojují k více než {limit} projektům. Bude potřeba změnit zdroje požadavků tak, aby zahrnovaly méně projektů.} many {Vybrané zdroje se připojují k více než {limit} projektům. Bude potřeba změnit zdroje požadavků tak, aby zahrnovaly méně projektů.} other {Vybrané zdroje se připojují k více než {limit} projektům. Bude potřeba změnit zdroje požadavků tak, aby zahrnovaly méně projektů.}}',
  'jira.portfolio-plan-wizard.plan-form.cancel': 'Zrušit',
  'jira.portfolio-plan-wizard.plan-form.create': 'Vytvořit',
  'jira.portfolio-plan-wizard.plan-form.issue-sources-description-settings-status-category-change-date':
    'Zdroje požadavků tvoří rozsah vašeho plánu. Pokud nemůžete najít konkrétní požadavek, {LearnMoreLink}.',
  'jira.portfolio-plan-wizard.plan-form.issue-sources-empty-error':
    'Pokračujte výběrem zdroje požadavků.',
  'jira.portfolio-plan-wizard.plan-form.issue-sources-field.add-another':
    'Přidat další',
  'jira.portfolio-plan-wizard.plan-form.issue-sources-label':
    'Zdroje požadavků',
  'jira.portfolio-plan-wizard.plan-form.issue-sources-title-settings':
    'Zdroje požadavků',
  'jira.portfolio-plan-wizard.plan-form.learn-more':
    'přečtěte si další informace o chybějících požadavcích',
  'jira.portfolio-plan-wizard.plan-form.name-empty-error':
    'Pokračujte zadáním názvu plánu.',
  'jira.portfolio-plan-wizard.plan-form.name-hit-limit-error':
    '{limit, plural, one {Zadejte název plánu s méně než {limit} znakem.} few {Zadejte název plánu s méně než {limit} znaky.} many {Zadejte název plánu s méně než {limit} znaku.} other {Zadejte název plánu s méně než {limit} znaky.}}',
  'jira.portfolio-plan-wizard.plan-form.name-label': 'Název plánu',
  'jira.portfolio-plan-wizard.plan-form.name-placeholder':
    'Zadejte název plánu',
  'jira.portfolio-plan-wizard.plan-form.permission-field.open': 'Otevřený',
  'jira.portfolio-plan-wizard.plan-form.permission-field.open-explained':
    'Plán si mohou zobrazit a upravit všichni uživatelé nástroje Advanced Roadmaps. Přístup můžete omezit později.',
  'jira.portfolio-plan-wizard.plan-form.permission-field.private': 'Soukromý',
  'jira.portfolio-plan-wizard.plan-form.permission-field.private-explained':
    'Plán si můžete zobrazit pouze vy. Později jej můžete sdílet s jednotlivci nebo skupinami.',
  'jira.portfolio-plan-wizard.plan-form.permission-label': 'Přístup',
  'jira.portfolio-plan-wizard.plan-form.set-exclusion-rules.label':
    'Nastavit pravidla vyloučení',
  'jira.portfolio-plan-wizard.plan-form.set-exclusion-rules.no-issue-sources-tooltip':
    'Vyberte zdroj požadavků a nastavte pravidla',
  'jira.portfolio-plan-wizard.plan-form.set-exclusion-rules.projects-over-limit-tooltip':
    'Upravte své zdroje požadavků tak, aby zahrnovaly méně projektů než {limit}.',
  'jira.portfolio-plan-wizard.plan-form.set-rules-heading':
    'Zpřesnit zobrazené požadavky',
  'jira.portfolio-plan-wizard.plan-form.set-rules-message':
    'Nastavte pravidla vyloučení určitých požadavků z vybraných zdrojů.',
  'jira.portfolio-plan-wizard.plan-form.subtitle':
    'Nastavte připojení ke zdrojům požadavků v Jira Software a vytvořte plán, který bude vždy synchronizovaný podle vaší práce.',
  'jira.portfolio-plan-wizard.plan-form.tell-me-more': 'Další informace',
  'jira.portfolio-plan-wizard.plan-form.title': 'Vytvořit plán',
};
