/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Korean
export default {
  'jira-portfolio-plan-wizard.common-popup-multi-select.excluded-from-plan':
    '계획에서 제외됨',
  'jira-portfolio-plan-wizard.refine-issues.all-statuses-from-category':
    '모든 {categoryName} 상태',
  'jira-portfolio-plan-wizard.refine-issues.back-to-create-plan':
    '계획 만들기로 돌아가기',
  'jira-portfolio-plan-wizard.refine-issues.choose-status-placeholder':
    '상태 선택',
  'jira-portfolio-plan-wizard.refine-issues.choose-type-placeholder':
    '유형 선택',
  'jira-portfolio-plan-wizard.refine-issues.days-since-done-validation':
    '정수를 입력해 주세요.',
  'jira-portfolio-plan-wizard.refine-issues.description':
    '이 계획에서 볼 필요가 없는 이슈를 제외하는 규칙을 설정하세요. 이러한 규칙은 나중에 변경할 수 있습니다.',
  'jira-portfolio-plan-wizard.refine-issues.description-settings':
    '이 계획에서 볼 필요가 없는 이슈를 제외하는 규칙을 편집하세요.',
  'jira-portfolio-plan-wizard.refine-issues.exclude-days-after':
    '{value, plural, other {일}}',
  'jira-portfolio-plan-wizard.refine-issues.exclude-days-label':
    '다음 이후에 해결된 이슈 제외',
  'jira-portfolio-plan-wizard.refine-issues.exclude-days-label-status-category-change-date':
    '다음 이후에 완료된 이슈 제외',
  'jira-portfolio-plan-wizard.refine-issues.exclude-days-learn-more':
    '자세히 알아보기',
  'jira-portfolio-plan-wizard.refine-issues.exclude-days-subscript':
    '{value, plural, other {{value}일 이상 완료 상태 카테고리에 있는 이슈는 이 계획에 표시되지 않습니다. {LearnMoreLink}}}',
  'jira-portfolio-plan-wizard.refine-issues.exclude-days-subscript-status-change-category-done':
    '{value, plural, other {{value}일 이상 완료로 표시된 이슈는 계획에 표시되지 않습니다. {LearnMoreLink}}}',
  'jira-portfolio-plan-wizard.refine-issues.exclude-issue-type-label':
    '이슈 유형 제외',
  'jira-portfolio-plan-wizard.refine-issues.exclude-releases': '릴리스 제외',
  'jira-portfolio-plan-wizard.refine-issues.exclude-status-type-label':
    '상태 제외',
  'jira-portfolio-plan-wizard.refine-issues.no-statuses-excluded':
    '계획에서 0개의 이슈 상태 제외됨',
  'jira-portfolio-plan-wizard.refine-issues.no-types-excluded':
    '계획에서 0개의 이슈 유형 제외됨',
  'jira-portfolio-plan-wizard.refine-issues.num-excluded-releases':
    '{numExcludedReleases, plural, other {{numExcludedReleases}개의 릴리스가 제외됨}}',
  'jira-portfolio-plan-wizard.refine-issues.status': '상태',
  'jira-portfolio-plan-wizard.refine-issues.status-loading': '로드 중...',
  'jira-portfolio-plan-wizard.refine-issues.status-no-options': '옵션 없음',
  'jira-portfolio-plan-wizard.refine-issues.title': '표시되는 이슈 상세 검색',
  'jira-portfolio-plan-wizard.refine-issues.title-settings-page': '제외 규칙',
  'jira-portfolio-plan-wizard.refine-issues.type': '유형',
  'jira-portfolio-plan-wizard.refine-issues.types-loading': '로드 중...',
  'jira-portfolio-plan-wizard.refine-issues.types-no-options': '옵션 없음',
  'jira-portfolio-plan-wizard.refine-issues.view-releases': '릴리스 보기',
  'jira-portfolio-plan-wizard.refine-issues.view-releases-cancel': '취소',
  'jira-portfolio-plan-wizard.remove-issues.default-status': '할 일',
  'jira-portfolio-plan-wizard.remove-issues.description':
    '아래 이슈는 계획에서 제거되었지만 아직 Jira에 있습니다. 다시 포함할 항목을 모두 선택하세요. 최대 {issueLimit}개의 이슈를 로드할 수 있습니다.',
  'jira-portfolio-plan-wizard.remove-issues.epic': '에픽',
  'jira-portfolio-plan-wizard.remove-issues.hierarchy': '계층 구조',
  'jira-portfolio-plan-wizard.remove-issues.hierarchy-divider': '~',
  'jira-portfolio-plan-wizard.remove-issues.loading': '로드 중',
  'jira-portfolio-plan-wizard.remove-issues.more': '추가 옵션',
  'jira-portfolio-plan-wizard.remove-issues.no-available-excluded-issues':
    '계획에 다시 포함할 수 있는 이슈가 없습니다.',
  'jira-portfolio-plan-wizard.remove-issues.reinclude': '다시 포함',
  'jira-portfolio-plan-wizard.remove-issues.search-issues': '이슈 검색',
  'jira-portfolio-plan-wizard.remove-issues.select-only-descendants':
    '하위 이슈만 선택',
  'jira-portfolio-plan-wizard.remove-issues.select-this-and-all-descendants':
    '이 이슈와 모든 하위 이슈 선택',
  'jira-portfolio-plan-wizard.remove-issues.story': '스토리',
  'jira-portfolio-plan-wizard.remove-issues.subtask': '하위 작업',
  'jira-portfolio-plan-wizard.remove-issues.table-header-deselect-all':
    '모두 선택 해제',
  'jira-portfolio-plan-wizard.remove-issues.table-header-issue': '이슈',
  'jira-portfolio-plan-wizard.remove-issues.table-header-select-all':
    '모두 선택',
  'jira-portfolio-plan-wizard.remove-issues.table-header-status': '상태',
  'jira-portfolio-plan-wizard.remove-issues.title': '제거된 이슈',
  'jira-portfolio-plan-wizard.view-releases.description-exclude':
    '계획에서 제외할 릴리스를 선택하세요. 릴리스와 연관된 모든 이슈를 제외합니다.',
  'jira-portfolio-plan-wizard.view-releases.description-re-include':
    '이미 출시된 릴리스는 계획에서 제외됩니다. 다시 포함하려는 릴리스를 아래에서 선택하세요.',
  'jira-portfolio-plan-wizard.view-releases.description-select-re-include':
    '계획에 다시 포함할 릴리스를 선택하세요. 릴리스와 연관된 모든 이슈를 포함합니다.',
  'jira-portfolio-plan-wizard.view-releases.modal-close': '취소',
  'jira-portfolio-plan-wizard.view-releases.modal-exclude': '제외',
  'jira-portfolio-plan-wizard.view-releases.modal-heading': '릴리스',
  'jira-portfolio-plan-wizard.view-releases.modal-include': '포함',
  'jira-portfolio-plan-wizard.view-releases.option-exclude':
    '계획에 포함된 릴리스',
  'jira-portfolio-plan-wizard.view-releases.option-re-include':
    '계획에서 제외된 릴리스',
  'jira-portfolio-plan-wizard.view-releases.project-select.all': '전체',
  'jira-portfolio-plan-wizard.view-releases.project-select.all-projects':
    '모든 프로젝트',
  'jira-portfolio-plan-wizard.view-releases.project-select.clear-selected':
    '항목 선택 해제',
  'jira-portfolio-plan-wizard.view-releases.project-select.label': '프로젝트',
  'jira-portfolio-plan-wizard.view-releases.project-select.loading':
    '로드 중...',
  'jira-portfolio-plan-wizard.view-releases.project-select.none':
    '사용할 수 있는 프로젝트 없음',
  'jira-portfolio-plan-wizard.view-releases.released': '릴리스됨',
  'jira-portfolio-plan-wizard.view-releases.search-for-release':
    '릴리스 검색...',
  'jira-portfolio-plan-wizard.view-releases.selected-release-count-label':
    '{numSelectedReleases, plural, other {릴리스 {numSelectedReleases}개 선택됨}}',
  'jira-portfolio-plan-wizard.view-releases.table-header-deselect-all':
    '모두 선택 해제',
  'jira-portfolio-plan-wizard.view-releases.table-header-relesea-date':
    '릴리스 날짜',
  'jira-portfolio-plan-wizard.view-releases.table-header-select-all':
    '모두 선택',
  'jira-portfolio-plan-wizard.view-releases.table-header-start-date':
    '시작 날짜',
  'jira-portfolio-plan-wizard.view-releases.table-header-status': '상태',
  'jira-portfolio-plan-wizard.view-releases.table-header-title': '제목',
  'jira-portfolio-plan-wizard.view-releases.table-no-available-releases-exclude':
    '계획에서 제외할 수 있는 릴리스가 없습니다.',
  'jira-portfolio-plan-wizard.view-releases.table-no-available-releases-include':
    '계획에 포함할 수 있는 릴리스가 없습니다.',
  'jira-portfolio-plan-wizard.view-releases.title': '릴리스',
  'jira.portfolio-plan-wizard.common-issue-count.issues-in-plan': '계획의 이슈',
  'jira.portfolio-plan-wizard.over-limit-flag.title': '계획을 만들 수 없습니다',
  'jira.portfolio-plan-wizard.over-limit-flag.too-many-issues':
    '{limit, plural, other {계획에서 {limit}개 이슈 제한을 초과했습니다. 이슈 소스를 제거하거나 계획에서 더 많은 이슈를 제외하도록 규칙을 설정해 보세요.}}',
  'jira.portfolio-plan-wizard.over-limit-flag.too-many-projects':
    '{limit, plural, other {선택한 소스는 {limit}개보다 많은 프로젝트에 연결됩니다. 이슈 소스에 더 적은 프로젝트가 포함되도록 변경해야 합니다.}}',
  'jira.portfolio-plan-wizard.plan-form.cancel': '취소',
  'jira.portfolio-plan-wizard.plan-form.create': '만들기',
  'jira.portfolio-plan-wizard.plan-form.issue-sources-description-settings-status-category-change-date':
    '이슈 소스가 계획의 범위를 형성합니다. 특정 이슈를 찾을 수 없는 경우 {LearnMoreLink}.',
  'jira.portfolio-plan-wizard.plan-form.issue-sources-empty-error':
    '계속하려면 이슈 소스를 선택하세요.',
  'jira.portfolio-plan-wizard.plan-form.issue-sources-field.add-another':
    '다른 항목 추가',
  'jira.portfolio-plan-wizard.plan-form.issue-sources-label': '이슈 소스',
  'jira.portfolio-plan-wizard.plan-form.issue-sources-title-settings':
    '이슈 소스',
  'jira.portfolio-plan-wizard.plan-form.learn-more':
    '누락된 이슈에 대해 자세히 알아보기',
  'jira.portfolio-plan-wizard.plan-form.name-empty-error':
    '계속하려면 계획 이름을 입력하세요.',
  'jira.portfolio-plan-wizard.plan-form.name-hit-limit-error':
    '{limit, plural, other {{limit}자 미만의 계획 이름을 입력하세요.}}',
  'jira.portfolio-plan-wizard.plan-form.name-label': '계획 이름',
  'jira.portfolio-plan-wizard.plan-form.name-placeholder':
    '계획 이름을 입력하세요',
  'jira.portfolio-plan-wizard.plan-form.permission-field.open': '열기',
  'jira.portfolio-plan-wizard.plan-form.permission-field.open-explained':
    '모든 Advanced Roadmaps 사용자가 계획을 보고 편집할 수 있습니다. 나중에 액세스를 제한할 수 있습니다.',
  'jira.portfolio-plan-wizard.plan-form.permission-field.private': '비공개',
  'jira.portfolio-plan-wizard.plan-form.permission-field.private-explained':
    '사용자 자신만 계획을 볼 수 있습니다. 나중에 개별 사용자 또는 그룹과 공유할 수 있습니다.',
  'jira.portfolio-plan-wizard.plan-form.permission-label': '액세스',
  'jira.portfolio-plan-wizard.plan-form.set-exclusion-rules.label':
    '제외 규칙 설정',
  'jira.portfolio-plan-wizard.plan-form.set-exclusion-rules.no-issue-sources-tooltip':
    '이슈 소스를 선택하여 규칙을 설정',
  'jira.portfolio-plan-wizard.plan-form.set-exclusion-rules.projects-over-limit-tooltip':
    '{limit}개 미만의 프로젝트를 포함하려면 이슈 소스를 편집합니다',
  'jira.portfolio-plan-wizard.plan-form.set-rules-heading':
    '표시되는 이슈 상세 검색',
  'jira.portfolio-plan-wizard.plan-form.set-rules-message':
    '선택한 이슈 소스에서 특정 이슈를 제외하려면 규칙을 설정하세요.',
  'jira.portfolio-plan-wizard.plan-form.subtitle':
    'Jira Software의 이슈 소스에 연결하여 항상 업무와 동기화되는 로드맵을 만드세요.',
  'jira.portfolio-plan-wizard.plan-form.tell-me-more': '자세히 알아보기',
  'jira.portfolio-plan-wizard.plan-form.title': '계획 만들기',
};
