/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Ukrainian
export default {
  'jira-portfolio-plan-wizard.common-popup-multi-select.excluded-from-plan':
    'Виключено з плану',
  'jira-portfolio-plan-wizard.refine-issues.all-statuses-from-category':
    'Усі статуси: {categoryName}',
  'jira-portfolio-plan-wizard.refine-issues.back-to-create-plan':
    'Повернутися до створення плану',
  'jira-portfolio-plan-wizard.refine-issues.choose-status-placeholder':
    'Вибрати статус',
  'jira-portfolio-plan-wizard.refine-issues.choose-type-placeholder':
    'Вибрати тип',
  'jira-portfolio-plan-wizard.refine-issues.days-since-done-validation':
    'Введіть ціле число.',
  'jira-portfolio-plan-wizard.refine-issues.description':
    'Установіть правила, щоб не показувати проблеми, які ви не хочете бачити в цьому плані. Пізніше ви можете змінити ці правила.',
  'jira-portfolio-plan-wizard.refine-issues.description-settings':
    'Відредагуйте правила, щоб не показувати проблеми, які ви не хочете бачити в цьому плані.',
  'jira-portfolio-plan-wizard.refine-issues.exclude-days-after':
    '{value, plural, one {день} few {дні} many {днів} other {дня}}',
  'jira-portfolio-plan-wizard.refine-issues.exclude-days-label':
    'Не показувати вирішені проблеми після',
  'jira-portfolio-plan-wizard.refine-issues.exclude-days-label-status-category-change-date':
    'Не показувати жодних вирішених проблем після',
  'jira-portfolio-plan-wizard.refine-issues.exclude-days-learn-more':
    'Докладніше',
  'jira-portfolio-plan-wizard.refine-issues.exclude-days-subscript':
    '{value, plural, one {Проблеми, що мають категорію стану «Виконані» понад {value} день, у цьому тарифі не відображатимуться. {LearnMoreLink}} few {Проблеми, що мають категорію стану «Виконані» понад {value} дні, у цьому тарифі не відображатимуться. {LearnMoreLink}} many {Проблеми, що мають категорію стану «Виконані» понад {value} днів, у цьому тарифі не відображатимуться. {LearnMoreLink}} other {Проблеми, що мають категорію стану «Виконані» понад {value} дня, у цьому тарифі не відображатимуться. {LearnMoreLink}}}',
  'jira-portfolio-plan-wizard.refine-issues.exclude-days-subscript-status-change-category-done':
    '{value, plural, one {Проблеми, позначені як виконані понад {value} день тому, у цьому тарифі не відображатимуться. {LearnMoreLink}} few {Проблеми, позначені як виконані понад {value} дні тому, у цьому тарифі не відображатимуться. {LearnMoreLink}} many {Проблеми, позначені як виконані понад {value} днів тому, у цьому тарифі не відображатимуться. {LearnMoreLink}} other {Проблеми, позначені як виконані понад {value} дня тому, у цьому тарифі не відображатимуться. {LearnMoreLink}}}',
  'jira-portfolio-plan-wizard.refine-issues.exclude-issue-type-label':
    'Виключення типів проблем',
  'jira-portfolio-plan-wizard.refine-issues.exclude-releases':
    'Виключити випуски',
  'jira-portfolio-plan-wizard.refine-issues.exclude-status-type-label':
    'Виключити стани',
  'jira-portfolio-plan-wizard.refine-issues.no-statuses-excluded':
    '0 станів проблем не включатимуться в план',
  'jira-portfolio-plan-wizard.refine-issues.no-types-excluded':
    '0 типів проблем не включатимуться в план',
  'jira-portfolio-plan-wizard.refine-issues.num-excluded-releases':
    '{numExcludedReleases, plural, one {Виключено {numExcludedReleases} випуск} few {Виключено {numExcludedReleases} випуски} many {Виключено {numExcludedReleases} випусків} other {Виключено {numExcludedReleases} випуску}}',
  'jira-portfolio-plan-wizard.refine-issues.status': 'Стан',
  'jira-portfolio-plan-wizard.refine-issues.status-loading': 'Завантаження...',
  'jira-portfolio-plan-wizard.refine-issues.status-no-options':
    'Немає варіантів',
  'jira-portfolio-plan-wizard.refine-issues.title':
    'Показано відфільтровані проблеми',
  'jira-portfolio-plan-wizard.refine-issues.title-settings-page':
    'Виключити правила',
  'jira-portfolio-plan-wizard.refine-issues.type': 'Тип',
  'jira-portfolio-plan-wizard.refine-issues.types-loading': 'Завантаження...',
  'jira-portfolio-plan-wizard.refine-issues.types-no-options':
    'Немає варіантів',
  'jira-portfolio-plan-wizard.refine-issues.view-releases':
    'Переглянути випуски',
  'jira-portfolio-plan-wizard.refine-issues.view-releases-cancel': 'Скасувати',
  'jira-portfolio-plan-wizard.remove-issues.default-status':
    'необхідно виконати',
  'jira-portfolio-plan-wizard.remove-issues.description':
    'Наведені нижче проблеми вилучено з плану, але вони залишаються в Jira. Виберіть ті, які ви хочете включити знову. Максимальна кількість проблем для завантаження: {issueLimit}',
  'jira-portfolio-plan-wizard.remove-issues.epic': 'епос',
  'jira-portfolio-plan-wizard.remove-issues.hierarchy': 'Ієрархія',
  'jira-portfolio-plan-wizard.remove-issues.hierarchy-divider': 'по',
  'jira-portfolio-plan-wizard.remove-issues.loading': 'завантаження',
  'jira-portfolio-plan-wizard.remove-issues.more': 'інші варіанти',
  'jira-portfolio-plan-wizard.remove-issues.no-available-excluded-issues':
    'Немає проблем для повторного включення в план.',
  'jira-portfolio-plan-wizard.remove-issues.reinclude': 'Повторно включити',
  'jira-portfolio-plan-wizard.remove-issues.search-issues': 'Пошук проблем',
  'jira-portfolio-plan-wizard.remove-issues.select-only-descendants':
    'Вибрати лише дочірні проблеми',
  'jira-portfolio-plan-wizard.remove-issues.select-this-and-all-descendants':
    'Вибрати цю та всі дочірні проблеми',
  'jira-portfolio-plan-wizard.remove-issues.story': 'історія',
  'jira-portfolio-plan-wizard.remove-issues.subtask': 'підзавдання',
  'jira-portfolio-plan-wizard.remove-issues.table-header-deselect-all':
    'Скасувати вибір усіх',
  'jira-portfolio-plan-wizard.remove-issues.table-header-issue': 'Проблема',
  'jira-portfolio-plan-wizard.remove-issues.table-header-select-all':
    'Вибрати всі',
  'jira-portfolio-plan-wizard.remove-issues.table-header-status': 'Стан',
  'jira-portfolio-plan-wizard.remove-issues.title': 'Видалені проблеми',
  'jira-portfolio-plan-wizard.view-releases.description-exclude':
    'Виберіть випуски, які не потрібно включати в план. Жодні проблеми, пов’язані з цим випуском, не включатимуться в план.',
  'jira-portfolio-plan-wizard.view-releases.description-re-include':
    'Жодні готові випуски не включатимуться в план. Нижче виберіть ті, які ви хочете включити знову.',
  'jira-portfolio-plan-wizard.view-releases.description-select-re-include':
    'Виберіть випуски, які потрібно повторно включити до плану. Також буде включено всі проблеми, пов’язані з випуском.',
  'jira-portfolio-plan-wizard.view-releases.modal-close': 'Скасувати',
  'jira-portfolio-plan-wizard.view-releases.modal-exclude': 'Виключити',
  'jira-portfolio-plan-wizard.view-releases.modal-heading': 'Випуски',
  'jira-portfolio-plan-wizard.view-releases.modal-include': 'Включити',
  'jira-portfolio-plan-wizard.view-releases.option-exclude':
    'Випуски, включені в план',
  'jira-portfolio-plan-wizard.view-releases.option-re-include':
    'Випуски, виключені з плану',
  'jira-portfolio-plan-wizard.view-releases.project-select.all': 'Усі',
  'jira-portfolio-plan-wizard.view-releases.project-select.all-projects':
    'Усі проекти',
  'jira-portfolio-plan-wizard.view-releases.project-select.clear-selected':
    'Скасувати вибір',
  'jira-portfolio-plan-wizard.view-releases.project-select.label': 'Проєкт',
  'jira-portfolio-plan-wizard.view-releases.project-select.loading':
    'Завантаження...',
  'jira-portfolio-plan-wizard.view-releases.project-select.none':
    'Немає доступних проектів',
  'jira-portfolio-plan-wizard.view-releases.released': 'випущено',
  'jira-portfolio-plan-wizard.view-releases.search-for-release':
    'Пошук випуску…',
  'jira-portfolio-plan-wizard.view-releases.selected-release-count-label':
    '{numSelectedReleases, plural, one {Вибрано {numSelectedReleases} випуск} few {Вибрано {numSelectedReleases} випуски} many {Вибрано {numSelectedReleases} випусків} other {Вибрано {numSelectedReleases} випусків}}',
  'jira-portfolio-plan-wizard.view-releases.table-header-deselect-all':
    'Скасувати вибір усіх',
  'jira-portfolio-plan-wizard.view-releases.table-header-relesea-date':
    'Дата випуску',
  'jira-portfolio-plan-wizard.view-releases.table-header-select-all':
    'Вибрати всі',
  'jira-portfolio-plan-wizard.view-releases.table-header-start-date':
    'Дата початку',
  'jira-portfolio-plan-wizard.view-releases.table-header-status': 'Стан',
  'jira-portfolio-plan-wizard.view-releases.table-header-title': 'Назва',
  'jira-portfolio-plan-wizard.view-releases.table-no-available-releases-exclude':
    'Немає випусків для виключення з плану.',
  'jira-portfolio-plan-wizard.view-releases.table-no-available-releases-include':
    'Немає випусків для включення до плану.',
  'jira-portfolio-plan-wizard.view-releases.title': 'Випуски',
  'jira.portfolio-plan-wizard.common-issue-count.issues-in-plan':
    'Проблеми, включені в план',
  'jira.portfolio-plan-wizard.over-limit-flag.title':
    'Не вдалося створити план',
  'jira.portfolio-plan-wizard.over-limit-flag.too-many-issues':
    '{limit, plural, one {У плані забагато проблем (ліміт — {limit} проблема). Спробуйте видалити джерело проблеми або налаштувати правила так, щоб виключити певну кількість проблем із плану.} few {У плані забагато проблем (ліміт — {limit} проблеми). Спробуйте видалити джерело проблеми або налаштувати правила так, щоб виключити певну кількість проблем із плану.} many {У плані забагато проблем (ліміт — {limit} проблем). Спробуйте видалити джерело проблеми або налаштувати правила так, щоб виключити певну кількість проблем із плану.} other {У плані забагато проблем (ліміт — {limit} проблем). Спробуйте видалити джерело проблеми або налаштувати правила так, щоб виключити певну кількість проблем із плану.}}',
  'jira.portfolio-plan-wizard.over-limit-flag.too-many-projects':
    '{limit, plural, one {Вибрані вами джерела зв’язані з більш ніж {limit} проектом. Змініть джерела проблем, щоб зменшити кількість зв’язаних проектів.} few {Вибрані вами джерела зв’язані з більш ніж {limit} проектами. Змініть джерела проблем, щоб зменшити кількість зв’язаних проектів.} many {Вибрані вами джерела зв’язані з більш ніж {limit} проектами. Змініть джерела проблем, щоб зменшити кількість зв’язаних проектів.} other {Вибрані вами джерела зв’язані з більш ніж {limit} проектами. Змініть джерела проблем, щоб зменшити кількість зв’язаних проектів.}}',
  'jira.portfolio-plan-wizard.plan-form.cancel': 'Скасувати',
  'jira.portfolio-plan-wizard.plan-form.create': 'Створити',
  'jira.portfolio-plan-wizard.plan-form.issue-sources-description-settings-status-category-change-date':
    'Джерела проблем у вашому плані. Якщо не вдається знайти певну проблему, {LearnMoreLink}.',
  'jira.portfolio-plan-wizard.plan-form.issue-sources-empty-error':
    'Щоб продовжити, виберіть джерело проблеми.',
  'jira.portfolio-plan-wizard.plan-form.issue-sources-field.add-another':
    'Додати ще',
  'jira.portfolio-plan-wizard.plan-form.issue-sources-label': 'Джерело проблем',
  'jira.portfolio-plan-wizard.plan-form.issue-sources-title-settings':
    'Джерело проблем',
  'jira.portfolio-plan-wizard.plan-form.learn-more':
    'отримайте докладні відомості про відсутні проблеми',
  'jira.portfolio-plan-wizard.plan-form.name-empty-error':
    'Щоб продовжити, введіть назву плану.',
  'jira.portfolio-plan-wizard.plan-form.name-hit-limit-error':
    '{limit, plural, one {Укажіть назву плану довжиною до {limit} символу} few {Укажіть назву плану довжиною до {limit} символів} many {Укажіть назву плану довжиною до {limit} символів} other {Укажіть назву плану довжиною до {limit} символу}}',
  'jira.portfolio-plan-wizard.plan-form.name-label': 'Назва плану',
  'jira.portfolio-plan-wizard.plan-form.name-placeholder':
    'Введіть назву плану',
  'jira.portfolio-plan-wizard.plan-form.permission-field.open': 'Відкритий',
  'jira.portfolio-plan-wizard.plan-form.permission-field.open-explained':
    'Усі користувачі Advanced Roadmaps можуть переглядати й редагувати план. Ви можете обмежити доступ пізніше.',
  'jira.portfolio-plan-wizard.plan-form.permission-field.private': 'Приватний',
  'jira.portfolio-plan-wizard.plan-form.permission-field.private-explained':
    'Тільки ви можете бачити цей план. Пізніше можна буде поділитися ним із певними користувачами чи групами.',
  'jira.portfolio-plan-wizard.plan-form.permission-label': 'Доступ',
  'jira.portfolio-plan-wizard.plan-form.set-exclusion-rules.label':
    'Установити правила виключення',
  'jira.portfolio-plan-wizard.plan-form.set-exclusion-rules.no-issue-sources-tooltip':
    'Щоб налаштувати правила, виберіть джерело проблеми',
  'jira.portfolio-plan-wizard.plan-form.set-exclusion-rules.projects-over-limit-tooltip':
    'Відредагуйте джерела проблем, щоб кількість включених проектів не перевищувала {limit}',
  'jira.portfolio-plan-wizard.plan-form.set-rules-heading':
    'Показано відфільтровані проблеми',
  'jira.portfolio-plan-wizard.plan-form.set-rules-message':
    'Установіть правила, щоб виключити певні проблеми з вибраних джерел.',
  'jira.portfolio-plan-wizard.plan-form.subtitle':
    'Підключіться до джерел проблем у Jira Software, щоб створити план розробки, який буде завжди синхронізуватися з вашою роботою.',
  'jira.portfolio-plan-wizard.plan-form.tell-me-more': 'Докладніше',
  'jira.portfolio-plan-wizard.plan-form.title': 'Створити план',
};
