/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// English (Instrumented)
export default {
  'ptc.pm.collaborators.title': '⁣⁢Your Collaborators‍⁯⁯‌⁪⁡‍⁠⁠⁬⁮⁡؜⁡‌⁮⁭؜⁡⁮⁪⁣⁤',
  'ptc.pm.error-heading': '⁣⁢Something’s gone wrong⁡؜⁡‌⁪⁬؜⁠⁭⁭‍⁮⁪‍⁭⁬⁠‌⁯⁠⁠⁠⁬⁡‌⁣⁤',
  'ptc.pm.error-image-alt-text':
    '⁣⁢A broken robot and a number of people busy fixing it.⁠؜⁡⁠؜⁬⁬؜؜⁮⁯⁠⁫⁮⁠‍⁯⁯‍⁫‌⁪‍⁣⁤',
  'ptc.pm.error-text':
    '⁣⁢We keep track of these errors, but feel free to contact us if refreshing doesn’t fix things⁪⁬⁬‍⁮⁬⁫⁮⁡‍‌⁫⁪‌⁭⁬⁪⁬؜⁠⁬⁮؜؜⁣⁤',
  'ptc.pm.invite-a-teammate.': '⁣⁢Invite a teammate⁯⁮‍⁫⁮⁪⁪⁬‍⁬⁭⁬⁭⁯⁪⁭⁠⁭؜⁣⁤',
  'ptc.pm.people': '⁣⁢People؜⁯⁡⁮‌⁭⁡⁭‌‍⁯⁡‌⁡⁡⁡؜‍⁭⁣⁤',
  'ptc.pm.start-a-team': '⁣⁢Start a team⁭⁭⁠⁬⁠⁬⁫؜‍⁯⁪⁡⁮⁬⁮⁪⁠‍⁮⁫⁮⁫⁫⁯⁣⁤',
  'ptc.pm.view-all-people-teams':
    '⁣⁢Search people and teams⁭؜⁬⁡⁡⁡⁯‍⁮⁪⁠⁡⁯⁭⁬⁪⁠⁬؜⁡⁯⁠⁡⁠؜⁣⁤',
  'ptc.pm.view-your-profile': '⁣⁢View your profile⁭⁪⁫⁠؜⁭⁮⁠⁡⁫⁡⁯⁠⁯⁬‌‌؜‍⁭⁭⁭⁮⁡⁣⁤',
  'ptc.pm.your-teams.title': '⁣⁢Your Teams⁭⁯‍؜⁮⁪⁡⁡⁯⁪⁬⁡⁮؜⁪⁮⁡⁯⁫‌⁪⁡⁡‌⁠؜⁣⁤',
};
