/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Spanish
export default {
  'ptc.pm.collaborators.title': 'Tus colaboradores',
  'ptc.pm.error-heading': 'Algo ha ido mal',
  'ptc.pm.error-image-alt-text':
    'Un robot roto y varias personas ocupadas intentando arreglarlo.',
  'ptc.pm.error-text':
    'Realizamos un seguimiento de estos errores, pero ponte en contacto con nosotros si actualizar no soluciona el problema',
  'ptc.pm.invite-a-teammate.': 'Invitar a un compañero de equipo',
  'ptc.pm.people': 'Personas',
  'ptc.pm.start-a-team': 'Comenzar un equipo',
  'ptc.pm.view-all-people-teams': 'Buscar personas y equipos',
  'ptc.pm.view-your-profile': 'Ver tu perfil',
  'ptc.pm.your-teams.title': 'Tus equipos',
};
