/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Polish
export default {
  'ptc.pm.collaborators.title': 'Twoi współpracownicy',
  'ptc.pm.error-heading': 'Coś poszło nie tak',
  'ptc.pm.error-image-alt-text':
    'Zepsuty robot i grupa ludzi zajętych naprawianiem go.',
  'ptc.pm.error-text':
    'Monitorujemy te błędy, ale możesz się z nami kontaktować, jeśli odświeżenie nie rozwiąże problemu.',
  'ptc.pm.invite-a-teammate.': 'Zaproś osobę do zespołu',
  'ptc.pm.people': 'Osoby',
  'ptc.pm.start-a-team': 'Utwórz zespół',
  'ptc.pm.view-all-people-teams': 'Wyszukaj osoby i zespoły',
  'ptc.pm.view-your-profile': 'Wyświetl własny profil',
  'ptc.pm.your-teams.title': 'Twoje zespoły',
};
