/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Swedish
export default {
  'ptc.pm.collaborators.title': 'Dina medarbetare',
  'ptc.pm.error-heading': 'Något har gått fel',
  'ptc.pm.error-image-alt-text':
    'En trasig robot och ett antal människor som försöker fixa den.',
  'ptc.pm.error-text':
    'Vi håller koll på dessa fel, men du får gärna kontakta oss om det inte hjälper att uppdatera sidan',
  'ptc.pm.invite-a-teammate.': 'Bjud in en teammedlem',
  'ptc.pm.people': 'Personer',
  'ptc.pm.start-a-team': 'Starta ett team',
  'ptc.pm.view-all-people-teams': 'Sök efter personer och team',
  'ptc.pm.view-your-profile': 'Visa din profil',
  'ptc.pm.your-teams.title': 'Dina team',
};
