/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// English (Instrumented)
export default {
  'dragonfruit-navigation-settings.settings-navigation-data':
    '⁣⁢Data⁡⁯‍‍⁫⁫⁬⁯⁪‍؜‍⁫‍⁯⁫⁭⁯⁯⁫⁭؜‍⁣⁤',
  'dragonfruit-navigation-settings.settings-navigation-general':
    '⁣⁢General⁠⁪⁮⁫⁭‌⁫⁫‍‍⁠‌⁠⁮⁬⁯‍⁡⁬‌⁮⁮⁠⁭⁭⁡⁭؜⁣⁤',
  'dragonfruit-navigation-settings.settings-navigation-manage-apps.nonfinal':
    '⁣⁢Apps⁫⁭⁡⁡⁬؜⁮‍‌؜⁪⁪⁮؜؜⁭⁪⁪⁫⁣⁤',
  'dragonfruit-navigation-settings.settings-navigation-scorecards':
    '⁣⁢Scorecards⁪‍⁯⁡‍⁪⁮⁯؜⁠⁭⁬⁪‌‍⁠‌⁬‌‌⁡‍⁣⁤',
  'dragonfruit-navigation-settings.settings-navigation-title':
    '⁣⁢Compass settings⁫‌⁬⁫⁠‍‌⁭⁪⁮‌⁡⁬⁬؜⁯‍⁪⁠؜⁪⁭؜⁠‌⁯⁣⁤',
  'dragonfruit-navigation.alpha-lozenge-text':
    '⁣⁢Alpha‌⁯⁯‌⁪⁡⁠⁪⁬⁬⁠‍⁬‌⁮‍⁫‍⁪‌⁯⁫‌؜⁣⁤',
  'dragonfruit-navigation.compass-documentation.nonfinal':
    '⁣⁢Compass documentation⁫⁭⁭⁫⁬⁭⁭⁠؜⁡⁫⁭⁫⁠؜‍⁯⁠‌⁣⁤',
  'dragonfruit-navigation.feedback-collector.button.nonfinal':
    '⁣⁢Give feedback⁪⁯⁫⁫⁫⁡‍‍⁫⁭‌؜⁯؜‌⁯⁬‌⁭‌؜‍⁯؜⁮⁣⁤',
  'dragonfruit-navigation.help.community-support':
    '⁣⁢Community support‍⁬⁯⁫‌⁬؜⁫⁪⁮⁫؜‌⁡⁭‍‍؜⁭⁭⁫⁮⁪⁫⁣⁤',
  'dragonfruit-navigation.help.statuspage':
    '⁣⁢Status page؜⁮‌⁠⁮⁫⁯⁪‍⁡⁪⁬⁬‌⁮⁠⁮⁠⁠⁡‌⁫⁮⁣⁤',
  'dragonfruit-navigation.insights-popup.insights-description.nonfinal':
    '⁣⁢Track company-wide initiatives with insights!⁭؜⁡⁠⁡⁮⁡⁪‌⁮⁬⁠⁪⁠⁡‌‍؜⁪؜⁭‌⁣⁤',
  'dragonfruit-navigation.insights-popup.insights-label.nonfinal':
    '⁣⁢Insights‌⁡؜⁪؜⁡⁫⁠⁭؜⁮‌‌⁬⁠⁭⁫⁪⁯⁡‌⁠⁠⁣⁤',
  'dragonfruit-navigation.integrations':
    '⁣⁢Integrations⁮‌؜⁬⁭⁪⁬⁡⁪⁫‌⁪⁪؜؜⁪⁠⁪⁭⁬⁯؜⁮⁮⁫⁮⁣⁤',
  'dragonfruit-navigation.profile-popup.account-settings.nonfinal':
    '⁣⁢Account settings⁬⁠⁬‍⁮⁭‌⁠⁮⁬⁬⁡‍⁯؜⁯⁭⁡⁣⁤',
  'dragonfruit-navigation.profile-popup.logout':
    '⁣⁢Log out⁡⁪‍⁫⁪⁬‍⁮⁡⁫⁡⁭‌⁯⁬⁬⁡؜‍⁣⁤',
  'dragonfruit-navigation.profile-popup.profile':
    '⁣⁢Profile⁡⁪‍⁡⁬⁮؜⁮⁡‍‌⁪؜⁠⁠⁡⁭‌⁡⁡⁡⁭⁡⁭⁣⁤',
  'dragonfruit-navigation.profile-popup.your-profile-and-settings':
    '⁣⁢Your profile and settings‍؜‌⁫⁯؜⁬‌⁠⁠⁮⁪‌⁮‌⁠‌؜⁬‌⁣⁤',
  'dragonfruit-navigation.settings-tooltip-text':
    '⁣⁢Settings⁬⁯⁬؜⁫⁭⁠⁯⁭؜⁭⁡‌⁮⁠⁭‌⁫⁮⁪‍⁯⁫⁬⁭⁣⁤',
  'dragonfruit-navigation.switcher.tooltip.nonfinal':
    '⁣⁢Switch to...⁫⁭⁡⁮⁮⁠⁭‍⁮‌⁪⁪⁯⁡⁡⁮⁬⁠⁬⁠⁠⁭⁭⁣⁤',
};
