/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Japanese
export default {
  'dragonfruit-navigation-settings.settings-navigation-data': 'データ',
  'dragonfruit-navigation-settings.settings-navigation-general': '一般',
  'dragonfruit-navigation-settings.settings-navigation-scorecards':
    'スコアカード',
  'dragonfruit-navigation-settings.settings-navigation-title': 'Compass の設定',
  'dragonfruit-navigation.alpha-lozenge-text': 'アルファ版',
  'dragonfruit-navigation.help.community-support': 'コミュニティ サポート',
  'dragonfruit-navigation.help.statuspage': 'ステータス ページ',
  'dragonfruit-navigation.integrations': '統合',
  'dragonfruit-navigation.profile-popup.logout': 'ログアウト',
  'dragonfruit-navigation.profile-popup.profile': 'プロファイル',
  'dragonfruit-navigation.profile-popup.your-profile-and-settings':
    'プロファイルと設定',
  'dragonfruit-navigation.settings-tooltip-text': '設定',
};
