/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Norwegian Bokmål
export default {
  'dragonfruit-navigation-settings.settings-navigation-data': 'Data',
  'dragonfruit-navigation-settings.settings-navigation-general': 'Generelt',
  'dragonfruit-navigation-settings.settings-navigation-scorecards': 'Poengkort',
  'dragonfruit-navigation-settings.settings-navigation-title':
    'Compass-innstillinger',
  'dragonfruit-navigation.alpha-lozenge-text': 'Alfa',
  'dragonfruit-navigation.help.community-support': 'Støtte fra fellesskapet',
  'dragonfruit-navigation.help.statuspage': 'Statusside',
  'dragonfruit-navigation.integrations': 'Integrasjoner',
  'dragonfruit-navigation.profile-popup.logout': 'Logg av',
  'dragonfruit-navigation.profile-popup.profile': 'Profil',
  'dragonfruit-navigation.profile-popup.your-profile-and-settings':
    'Profil og innstillinger',
  'dragonfruit-navigation.settings-tooltip-text': 'Innstillinger',
};
