/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Dutch
export default {
  'dragonfruit-navigation-settings.settings-navigation-data': 'Gegevens',
  'dragonfruit-navigation-settings.settings-navigation-general': 'Algemeen',
  'dragonfruit-navigation-settings.settings-navigation-scorecards':
    'Scorecards',
  'dragonfruit-navigation-settings.settings-navigation-title':
    'Compass-instellingen',
  'dragonfruit-navigation.alpha-lozenge-text': 'Alfa',
  'dragonfruit-navigation.help.community-support': 'Community-support',
  'dragonfruit-navigation.help.statuspage': 'Statuspagina',
  'dragonfruit-navigation.integrations': 'Integraties',
  'dragonfruit-navigation.profile-popup.logout': 'Uitloggen',
  'dragonfruit-navigation.profile-popup.profile': 'Profiel',
  'dragonfruit-navigation.profile-popup.your-profile-and-settings':
    'Je profiel en instellingen',
  'dragonfruit-navigation.settings-tooltip-text': 'Instellingen',
};
