/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Polish
export default {
  'dragonfruit-navigation-settings.settings-navigation-data': 'Dane',
  'dragonfruit-navigation-settings.settings-navigation-general': 'Ogólne',
  'dragonfruit-navigation-settings.settings-navigation-scorecards':
    'Karty wyników',
  'dragonfruit-navigation-settings.settings-navigation-title':
    'Compass — ustawienia',
  'dragonfruit-navigation.alpha-lozenge-text': 'Alfa',
  'dragonfruit-navigation.help.community-support': 'Wsparcie społeczności',
  'dragonfruit-navigation.help.statuspage': 'Strona statusu',
  'dragonfruit-navigation.integrations': 'Integracje',
  'dragonfruit-navigation.profile-popup.logout': 'Wyloguj',
  'dragonfruit-navigation.profile-popup.profile': 'Profil',
  'dragonfruit-navigation.profile-popup.your-profile-and-settings':
    'Twój profil i ustawienia',
  'dragonfruit-navigation.settings-tooltip-text': 'Ustawienia',
};
