/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Portuguese (Brazil)
export default {
  'dragonfruit-navigation-settings.settings-navigation-data': 'Dados',
  'dragonfruit-navigation-settings.settings-navigation-general': 'Geral',
  'dragonfruit-navigation-settings.settings-navigation-scorecards':
    'Indicadores de desempenho',
  'dragonfruit-navigation-settings.settings-navigation-title':
    'Configurações do Compass',
  'dragonfruit-navigation.alpha-lozenge-text': 'Alfa',
  'dragonfruit-navigation.help.community-support': 'Suporte da comunidade',
  'dragonfruit-navigation.help.statuspage': 'Página de status',
  'dragonfruit-navigation.integrations': 'Integrações',
  'dragonfruit-navigation.profile-popup.logout': 'Sair',
  'dragonfruit-navigation.profile-popup.profile': 'Perfil',
  'dragonfruit-navigation.profile-popup.your-profile-and-settings':
    'Seu perfil e configurações',
  'dragonfruit-navigation.settings-tooltip-text': 'Configurações',
};
