/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Thai
export default {
  'dragonfruit-navigation-settings.settings-navigation-data': 'ข้อมูล',
  'dragonfruit-navigation-settings.settings-navigation-general': 'ทั่วไป',
  'dragonfruit-navigation-settings.settings-navigation-scorecards':
    'การ์ดคะแนน',
  'dragonfruit-navigation-settings.settings-navigation-title':
    'การตั้งค่า Compass',
  'dragonfruit-navigation.alpha-lozenge-text': 'อัลฟ่า',
  'dragonfruit-navigation.help.community-support': 'การสนับสนุนจากชุมชน',
  'dragonfruit-navigation.help.statuspage': 'หน้าข้อมูลสถานะ',
  'dragonfruit-navigation.integrations': 'การบูรณาการ',
  'dragonfruit-navigation.profile-popup.logout': 'ออกจากระบบ',
  'dragonfruit-navigation.profile-popup.profile': 'โปรไฟล์',
  'dragonfruit-navigation.profile-popup.your-profile-and-settings':
    'โปรไฟล์และการตั้งค่าของคุณ',
  'dragonfruit-navigation.settings-tooltip-text': 'การตั้งค่า',
};
