/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Chinese
export default {
  'dragonfruit-navigation-settings.settings-navigation-data': '数据',
  'dragonfruit-navigation-settings.settings-navigation-general': '常规',
  'dragonfruit-navigation-settings.settings-navigation-scorecards': '记分卡',
  'dragonfruit-navigation-settings.settings-navigation-title': 'Compass 设置',
  'dragonfruit-navigation.alpha-lozenge-text': 'Alpha 版',
  'dragonfruit-navigation.help.community-support': '社区支持',
  'dragonfruit-navigation.help.statuspage': '状态页面',
  'dragonfruit-navigation.integrations': '集成',
  'dragonfruit-navigation.profile-popup.logout': '注销',
  'dragonfruit-navigation.profile-popup.profile': '个人资料',
  'dragonfruit-navigation.profile-popup.your-profile-and-settings':
    '您的个人资料和设置',
  'dragonfruit-navigation.settings-tooltip-text': '设置',
};
