/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Hungarian
export default {
  'dragonfruit-scorecards.apply-scorecard-modal.applicable-scorecards-select-no-scorecards':
    'Nincs megjeleníthető eredménymutató',
  'dragonfruit-scorecards.apply-scorecard-modal.applicable-scorecards-select-placeholder':
    'Válassz egy eredménymutatót',
  'dragonfruit-scorecards.apply-scorecard-modal.flags.apply-scorecard-failure-flag-description':
    'Hiba történt a(z) {scorecardName} eredménymutató komponensre való alkalmazása során.',
  'dragonfruit-scorecards.apply-scorecard-modal.flags.apply-scorecard-failure-flag-title':
    'Az eredménymutatót nem sikerült alkalmazni',
  'dragonfruit-scorecards.apply-scorecard-modal.flags.apply-scorecard-success-flag-description':
    'Sikeresen alkalmaztad a(z) {scorecardName} eredménymutatót a komponensre.',
  'dragonfruit-scorecards.apply-scorecard-modal.flags.apply-scorecard-success-flag-title':
    'Eredménymutató sikeresen alkalmazva',
  'dragonfruit-scorecards.common.ui.criterias.completed': 'Kész',
  'dragonfruit-scorecards.common.ui.criterias.notCompleted': 'Nincs kész',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.componentLabel':
    'Komponens',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.importanceLabel':
    'Standard',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.importanceTypeRecommended':
    'Ajánlott',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.importanceTypeRequired':
    'Kötelező',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.importanceTypeUserDefined':
    'Felhasználó által definiált',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.ownerLabel':
    'Tulajdonos',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.tooltip.application-component-icon':
    'Alkalmazás komponens',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.tooltip.importanceTypeRecommended':
    'A komponensek ajánlott standardjai',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.tooltip.importanceTypeRequired':
    'A komponensek kötelező eredménymutatója',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.tooltip.importanceTypeUserDefined':
    'A rendszer alkalmazta a felhasználó által definiált standardot a kijelölt komponensekre',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.tooltip.library-component-icon':
    'Könyvtár komponens',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.tooltip.other-component-icon':
    'Egyéb komponens',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.tooltip.service-component-icon':
    'Szolgáltatás komponens',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.error.description':
    'Az eredménymutató nem töltődik be. Próbáld meg frissíteni az oldalt.',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.error.title':
    'Hoppá! Hiba történt',
  'dragonfruit-scorecards.remove-scorecard-modal.content':
    'Biztosan el szeretnéd távolítani ezt az eredménymutatót a komponensből?',
  'dragonfruit-scorecards.remove-scorecard-modal.failure-flag.title':
    'Hiba történt az eredménymutató eltávolításakor',
  'dragonfruit-scorecards.remove-scorecard-modal.success-flag.content':
    'A(z) {scorecardName} eredménymutató sikeresen eltávolítva a komponensből.',
  'dragonfruit-scorecards.remove-scorecard-modal.success-flag.title':
    'Az eredménymutató eltávolítása sikerült',
  'dragonfruit-scorecards.remove-scorecard-modal.title':
    'Eredménymutató eltávolítása',
  'dragonfruit-scorecards.scorecard-quick-view.criteria.service-has-description':
    'A szolgáltatás rendelkezik leírással',
  'dragonfruit-scorecards.scorecard-quick-view.criteria.service-has-linked-chat-channel':
    'A szolgáltatás rendelkezik csevegőcsatornával',
  'dragonfruit-scorecards.scorecard-quick-view.criteria.service-has-linked-dashboard':
    'A szolgáltatás rendelkezik irányítópulttal',
  'dragonfruit-scorecards.scorecard-quick-view.criteria.service-has-linked-document':
    'A szolgáltatás rendelkezik dokumentációval',
  'dragonfruit-scorecards.scorecard-quick-view.criteria.service-has-linked-on-call':
    'A szolgáltatás rendelkezik ügyelettel',
  'dragonfruit-scorecards.scorecard-quick-view.criteria.service-has-linked-project':
    'A szolgáltatás rendelkezik projekttel',
  'dragonfruit-scorecards.scorecard-quick-view.criteria.service-has-linked-repository':
    'A szolgáltatás rendelkezik adattárral',
  'dragonfruit-scorecards.scorecard-quick-view.criteria.service-has-owner':
    'A szolgáltatásnak van tulajdonoscsapata',
  'dragonfruit-scorecards.scorecard-summary.scorecard-standard.recommended-icon':
    'Ajánlott ikon',
  'dragonfruit-scorecards.scorecard-summary.scorecard-standard.required-icon':
    'Kötelező ikon',
  'dragonfruit-scorecards.scorecard-summary.scorecard-standard.user-defined-icon':
    'Felhasználó által definiált ikon',
  'dragonfruit-scorecards.ui.scorecard-quick-view.quick-view-details.no-criteria.body':
    'Az ismételt próbálkozáshoz töltsd be újra.',
  'dragonfruit-scorecards.ui.scorecard-quick-view.quick-view-details.no-criteria.callToActionText':
    'Újratöltés',
  'dragonfruit-scorecards.ui.scorecard-quick-view.quick-view-details.no-criteria.title':
    'Nincs megjeleníthető feltétel',
  'dragonfruit-scorecards.ui.scorecards-quick-view-container.load-failure.body':
    'Az eredménymutatók nem töltődnek be. Próbáld meg frissíteni az oldalt.',
  'dragonfruit-scorecards.ui.scorecards-quick-view-container.load-failure.title':
    'Hoppá! Hiba történt',
  'dragonfruit-scorecards.ui.scorecards-quick-view-container.no-scorecards.body':
    'Építs és futtass komponenseket eredménymutatókkal, hogy iránymutatást adjanak.',
  'dragonfruit-scorecards.ui.scorecards-quick-view-container.no-scorecards.callToActionText':
    'Eredménymutató létrehozása',
  'dragonfruit-scorecards.ui.scorecards-quick-view-container.no-scorecards.title':
    'Első lépések az eredménymutatókkal',
  'dragonfruit-scorecards.ui.scorecards-quick-view.manage-scorecards':
    'Eredménymutatók kezelése',
  'dragonfruit-scorecards.ui.scorecards-quick-view.view-scorecard':
    'Eredménymutató megtekintése',
};
