/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Portuguese (Brazil)
export default {
  'dragonfruit-scorecards.apply-scorecard-modal.applicable-scorecards-select-no-scorecards':
    'Sem indicadores de desempenho para exibir',
  'dragonfruit-scorecards.apply-scorecard-modal.applicable-scorecards-select-placeholder':
    'Escolher um indicador de desempenho',
  'dragonfruit-scorecards.apply-scorecard-modal.flags.apply-scorecard-failure-flag-description':
    'Algo deu errado ao aplicar o indicador de desempenho {scorecardName} a este componente.',
  'dragonfruit-scorecards.apply-scorecard-modal.flags.apply-scorecard-failure-flag-title':
    'Indicador de desempenho não aplicado',
  'dragonfruit-scorecards.apply-scorecard-modal.flags.apply-scorecard-success-flag-description':
    'Você aplicou com sucesso o indicador de desempenho {scorecardName} a este componente.',
  'dragonfruit-scorecards.apply-scorecard-modal.flags.apply-scorecard-success-flag-title':
    'Indicador de desempenho aplicado',
  'dragonfruit-scorecards.common.ui.criterias.completed': 'Concluído',
  'dragonfruit-scorecards.common.ui.criterias.notCompleted': 'Não concluído',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.componentLabel':
    'Componente',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.importanceLabel':
    'Padrão',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.importanceTypeRecommended':
    'Recomendado',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.importanceTypeRequired':
    'Obrigatório',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.importanceTypeUserDefined':
    'Definido pelo usuário',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.ownerLabel':
    'Proprietário',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.tooltip.application-component-icon':
    'Componente do aplicativo',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.tooltip.importanceTypeRecommended':
    'Padrão recomendado para componentes',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.tooltip.importanceTypeRequired':
    'Indicador de desempenho obrigatório para componentes',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.tooltip.importanceTypeUserDefined':
    'Padrão definido pelo usuário aplicado para selecionar componentes',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.tooltip.library-component-icon':
    'Componente da biblioteca',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.tooltip.other-component-icon':
    'Outro componente',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.tooltip.service-component-icon':
    'Componente do serviço',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.error.description':
    'O indicador de desempenho não está carregando, tente atualizar a página.',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.error.title':
    'Opa! Algo deu errado',
  'dragonfruit-scorecards.remove-scorecard-modal.content':
    'Tem certeza de que você quer remover o indicador de desempenho deste componente?',
  'dragonfruit-scorecards.remove-scorecard-modal.failure-flag.title':
    'Erro ao remover o indicador de desempenho',
  'dragonfruit-scorecards.remove-scorecard-modal.success-flag.content':
    '{scorecardName} removido com sucesso deste componente.',
  'dragonfruit-scorecards.remove-scorecard-modal.success-flag.title':
    'Indicador de desempenho removido com sucesso',
  'dragonfruit-scorecards.remove-scorecard-modal.title':
    'Remova este indicador de desempenho',
  'dragonfruit-scorecards.scorecard-quick-view.criteria.service-has-description':
    'O serviço tem uma descrição',
  'dragonfruit-scorecards.scorecard-quick-view.criteria.service-has-linked-chat-channel':
    'O serviço tem um canal de bate-papo',
  'dragonfruit-scorecards.scorecard-quick-view.criteria.service-has-linked-dashboard':
    'O serviço tem um painel',
  'dragonfruit-scorecards.scorecard-quick-view.criteria.service-has-linked-document':
    'O serviço tem uma documentação',
  'dragonfruit-scorecards.scorecard-quick-view.criteria.service-has-linked-on-call':
    'O serviço tem plantão',
  'dragonfruit-scorecards.scorecard-quick-view.criteria.service-has-linked-project':
    'O serviço tem um projeto',
  'dragonfruit-scorecards.scorecard-quick-view.criteria.service-has-linked-repository':
    'O serviço tem um repositório',
  'dragonfruit-scorecards.scorecard-quick-view.criteria.service-has-owner':
    'O serviço tem uma equipe do proprietário',
  'dragonfruit-scorecards.scorecard-summary.scorecard-standard.recommended-icon':
    'Ícone recomendado',
  'dragonfruit-scorecards.scorecard-summary.scorecard-standard.required-icon':
    'Ícone obrigatório',
  'dragonfruit-scorecards.scorecard-summary.scorecard-standard.user-defined-icon':
    'Ícone definido pelo usuário',
  'dragonfruit-scorecards.ui.scorecard-quick-view.quick-view-details.no-criteria.body':
    'Recarregue e tente de novo.',
  'dragonfruit-scorecards.ui.scorecard-quick-view.quick-view-details.no-criteria.callToActionText':
    'Recarregar',
  'dragonfruit-scorecards.ui.scorecard-quick-view.quick-view-details.no-criteria.title':
    'Sem critérios para exibição',
  'dragonfruit-scorecards.ui.scorecards-quick-view-container.load-failure.body':
    'Os indicadores de desempenho não estão carregando, tente atualizar a página.',
  'dragonfruit-scorecards.ui.scorecards-quick-view-container.load-failure.title':
    'Opa! Algo deu errado',
  'dragonfruit-scorecards.ui.scorecards-quick-view-container.no-scorecards.body':
    'Crie e execute componentes com indicadores de desempenho para guiar você.',
  'dragonfruit-scorecards.ui.scorecards-quick-view-container.no-scorecards.callToActionText':
    'Criar indicador de desempenho',
  'dragonfruit-scorecards.ui.scorecards-quick-view-container.no-scorecards.title':
    'Primeiros passos com indicadores de desempenho',
  'dragonfruit-scorecards.ui.scorecards-quick-view.manage-scorecards':
    'Gerenciar indicadores de desempenho',
  'dragonfruit-scorecards.ui.scorecards-quick-view.view-scorecard':
    'Visualizar indicador de desempenho',
};
