/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Swedish
export default {
  'dragonfruit-scorecards.apply-scorecard-modal.applicable-scorecards-select-no-scorecards':
    'Inga poängkort att visa',
  'dragonfruit-scorecards.apply-scorecard-modal.applicable-scorecards-select-placeholder':
    'Välj ett poängkort',
  'dragonfruit-scorecards.apply-scorecard-modal.flags.apply-scorecard-failure-flag-description':
    'Något gick fel när poängkortet {scorecardName} skulle tillämpas för komponenten.',
  'dragonfruit-scorecards.apply-scorecard-modal.flags.apply-scorecard-failure-flag-title':
    'Poängkortet har inte tillämpats',
  'dragonfruit-scorecards.apply-scorecard-modal.flags.apply-scorecard-success-flag-description':
    'Du har tillämpat poängkortet {scorecardName} för komponenten.',
  'dragonfruit-scorecards.apply-scorecard-modal.flags.apply-scorecard-success-flag-title':
    'Poängkortet har tillämpats',
  'dragonfruit-scorecards.common.ui.criterias.completed': 'Slutfört',
  'dragonfruit-scorecards.common.ui.criterias.notCompleted': 'Ej slutfört',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.componentLabel':
    'Komponent',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.importanceLabel':
    'Standard',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.importanceTypeRecommended':
    'Rekommenderas',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.importanceTypeRequired':
    'Krävs',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.importanceTypeUserDefined':
    'Användardefinierat',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.ownerLabel':
    'Ägare',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.tooltip.application-component-icon':
    'Programkomponent',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.tooltip.importanceTypeRecommended':
    'Rekommenderad standard för komponenter',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.tooltip.importanceTypeRequired':
    'Obligatoriskt poängkort för komponenter',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.tooltip.importanceTypeUserDefined':
    'Användardefinierad standard tillämpas för vissa komponenter',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.tooltip.library-component-icon':
    'Bibliotekskomponent',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.tooltip.other-component-icon':
    'Annan komponent',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.tooltip.service-component-icon':
    'Tjänstekomponent',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.error.description':
    'Vi kan inte läsa in poängkortet, prova att uppdatera sidan.',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.error.title':
    'Hoppsan! Något gick fel',
  'dragonfruit-scorecards.remove-scorecard-modal.content':
    'Är du säker på att du vill ta bort poängkortet från komponenten?',
  'dragonfruit-scorecards.remove-scorecard-modal.failure-flag.title':
    'Det gick inte att ta bort poängkortet',
  'dragonfruit-scorecards.remove-scorecard-modal.success-flag.content':
    '{scorecardName} har tagits bort från komponenten.',
  'dragonfruit-scorecards.remove-scorecard-modal.success-flag.title':
    'Poängkortet har tagits bort',
  'dragonfruit-scorecards.remove-scorecard-modal.title': 'Ta bort poängkortet',
  'dragonfruit-scorecards.scorecard-quick-view.criteria.service-has-description':
    'Tjänsten har en beskrivning',
  'dragonfruit-scorecards.scorecard-quick-view.criteria.service-has-linked-chat-channel':
    'Tjänsten har en chattkanal',
  'dragonfruit-scorecards.scorecard-quick-view.criteria.service-has-linked-dashboard':
    'Tjänsten har en dashboard',
  'dragonfruit-scorecards.scorecard-quick-view.criteria.service-has-linked-document':
    'Tjänsten har dokumentation',
  'dragonfruit-scorecards.scorecard-quick-view.criteria.service-has-linked-on-call':
    'Tjänsten har on-call-schema',
  'dragonfruit-scorecards.scorecard-quick-view.criteria.service-has-linked-project':
    'Tjänsten har ett projekt',
  'dragonfruit-scorecards.scorecard-quick-view.criteria.service-has-linked-repository':
    'Tjänsten har en lagringsplats',
  'dragonfruit-scorecards.scorecard-quick-view.criteria.service-has-owner':
    'Tjänsten har ett ägarteam',
  'dragonfruit-scorecards.scorecard-summary.scorecard-standard.recommended-icon':
    'Ikonen Rekommenderas',
  'dragonfruit-scorecards.scorecard-summary.scorecard-standard.required-icon':
    'Ikonen Krävs',
  'dragonfruit-scorecards.scorecard-summary.scorecard-standard.user-defined-icon':
    'Ikonen Användardefinierat',
  'dragonfruit-scorecards.ui.scorecard-quick-view.quick-view-details.no-criteria.body':
    'Uppdatera och försök igen.',
  'dragonfruit-scorecards.ui.scorecard-quick-view.quick-view-details.no-criteria.callToActionText':
    'Uppdatera',
  'dragonfruit-scorecards.ui.scorecard-quick-view.quick-view-details.no-criteria.title':
    'Inga kriterier att visa',
  'dragonfruit-scorecards.ui.scorecards-quick-view-container.load-failure.body':
    'Vi kan inte läsa in poängkorten, prova att uppdatera sidan.',
  'dragonfruit-scorecards.ui.scorecards-quick-view-container.load-failure.title':
    'Hoppsan! Något gick fel',
  'dragonfruit-scorecards.ui.scorecards-quick-view-container.no-scorecards.body':
    'Skapa och kör komponenter med hjälp från poängkort.',
  'dragonfruit-scorecards.ui.scorecards-quick-view-container.no-scorecards.callToActionText':
    'Skapa poängkort',
  'dragonfruit-scorecards.ui.scorecards-quick-view-container.no-scorecards.title':
    'Kom igång med poängkort',
  'dragonfruit-scorecards.ui.scorecards-quick-view.manage-scorecards':
    'Hantera poängkort',
  'dragonfruit-scorecards.ui.scorecards-quick-view.view-scorecard':
    'Visa poängkort',
};
