/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// undefined
export default {
  'dragonfruit-scorecards.apply-scorecard-modal.applicable-scorecards-select-no-scorecards':
    '沒有可顯示的計分卡',
  'dragonfruit-scorecards.apply-scorecard-modal.applicable-scorecards-select-placeholder':
    '選擇計分卡',
  'dragonfruit-scorecards.apply-scorecard-modal.flags.apply-scorecard-failure-flag-description':
    '將「{scorecardName}」計分卡套用至此元件時發生錯誤。',
  'dragonfruit-scorecards.apply-scorecard-modal.flags.apply-scorecard-failure-flag-title':
    '未套用計分卡',
  'dragonfruit-scorecards.apply-scorecard-modal.flags.apply-scorecard-success-flag-description':
    '您已成功將「{scorecardName}」計分卡套用至此元件。',
  'dragonfruit-scorecards.apply-scorecard-modal.flags.apply-scorecard-success-flag-title':
    '已套用計分卡',
  'dragonfruit-scorecards.common.ui.criterias.completed': '已完成',
  'dragonfruit-scorecards.common.ui.criterias.notCompleted': '未完成',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.componentLabel':
    '元件',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.importanceLabel':
    '標準',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.importanceTypeRecommended':
    '建議',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.importanceTypeRequired':
    '必要',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.importanceTypeUserDefined':
    '使用者定義',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.ownerLabel':
    '負責人',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.tooltip.application-component-icon':
    '應用程式元件',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.tooltip.importanceTypeRecommended':
    '元件的建議標準',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.tooltip.importanceTypeRequired':
    '元件的必要計分卡',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.tooltip.importanceTypeUserDefined':
    '套用到所選元件的使用者定義標準',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.tooltip.library-component-icon':
    '資料庫元件',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.tooltip.other-component-icon':
    '其它元件',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.details.tooltip.service-component-icon':
    '服務元件',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.error.description':
    '計分卡無法載入，請嘗試重新整理頁面。',
  'dragonfruit-scorecards.common.ui.scorecard-full-view.error.title':
    '糟糕！發生錯誤',
  'dragonfruit-scorecards.remove-scorecard-modal.content':
    '您確定要從此元件移除此計分卡嗎？',
  'dragonfruit-scorecards.remove-scorecard-modal.failure-flag.title':
    '移除計分卡時發生錯誤',
  'dragonfruit-scorecards.remove-scorecard-modal.success-flag.content':
    '已成功將 {scorecardName} 從此元件中移除。',
  'dragonfruit-scorecards.remove-scorecard-modal.success-flag.title':
    '成功移除計分卡',
  'dragonfruit-scorecards.remove-scorecard-modal.title': '移除此計分卡',
  'dragonfruit-scorecards.scorecard-summary.scorecard-standard.recommended-icon':
    '「建議」圖示',
  'dragonfruit-scorecards.scorecard-summary.scorecard-standard.required-icon':
    '「必要」圖示',
  'dragonfruit-scorecards.scorecard-summary.scorecard-standard.user-defined-icon':
    '「使用者定義」圖示',
  'dragonfruit-scorecards.ui.scorecard-quick-view.quick-view-details.no-criteria.body':
    '重新載入以再試一次。',
  'dragonfruit-scorecards.ui.scorecard-quick-view.quick-view-details.no-criteria.callToActionText':
    '重新載入',
  'dragonfruit-scorecards.ui.scorecard-quick-view.quick-view-details.no-criteria.title':
    '沒有要顯示的條件',
  'dragonfruit-scorecards.ui.scorecards-quick-view-container.load-failure.body':
    '計分卡無法載入，請嘗試重新整理頁面。',
  'dragonfruit-scorecards.ui.scorecards-quick-view-container.load-failure.title':
    '糟糕！發生錯誤',
  'dragonfruit-scorecards.ui.scorecards-quick-view-container.no-scorecards.body':
    '使用計分卡建置並執行元件以引導您。',
  'dragonfruit-scorecards.ui.scorecards-quick-view-container.no-scorecards.callToActionText':
    '建立計分卡',
  'dragonfruit-scorecards.ui.scorecards-quick-view-container.no-scorecards.title':
    '開始使用計分卡',
  'dragonfruit-scorecards.ui.scorecards-quick-view.manage-scorecards':
    '管理計分卡',
  'dragonfruit-scorecards.ui.scorecards-quick-view.view-scorecard':
    '檢視計分卡',
};
