#!/bin/bash

set -e

export BITBUCKET_BUILD_NUMBER=${BITBUCKET_BUILD_NUMBER:-local}
export PACKAGE_VERSION=${npm_package_version:-0.0.0}

export SERVICE_NAME=${SERVICE_NAME:-af-service-dashboard}

export MICROS_ENV=${MICROS_ENV:-ddev}
export MICROS_ENVTYPE=${MICROS_ENV_TYPE:-dev}

export IMAGE_VERSION=${IMAGE_VERSION:-0.0.0}
export IMAGE_TAG=${IMAGE_NAME}:${IMAGE_VERSION}

export PG_AF_SERVICE_DASHBOARD_HOST=${PG_AF_SERVICE_DASHBOARD_HOST:-localhost}
export PG_AF_SERVICE_DASHBOARD_PORT=${PG_AF_SERVICE_DASHBOARD_PORT:-5433}
export PG_AF_SERVICE_DASHBOARD_ROLE=${PG_AF_SERVICE_DASHBOARD_ROLE:-postgres}
export PG_AF_SERVICE_DASHBOARD_PASSWORD=${PG_AF_SERVICE_DASHBOARD_PASSWORD:-password}
export PG_AF_SERVICE_DASHBOARD_SCHEMA=${PG_AF_SERVICE_DASHBOARD_SCHEMA:-postgres}

export BITBUCKET_USERNAME=${BITBUCKET_USERNAME:-user} # replace with your own
export BITBUCKET_PASSWORD=${BITBUCKET_PASSWORD:-password} # replace with your own

export AFP_SLACK_TOKEN=${AFP_SLACK_TOKEN:-token}
