/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Japanese
export default {
  'dragonfruit-components.component-list.owners.contacts-add-owner':
    '所有者を追加',
  'dragonfruit-page-component-list.error-message': '問題が発生しました',
  'dragonfruit-page-component-list.error-message-description':
    'もう一度お試しください',
  'dragonfruit-page-team-details.add-component-modal.component-options-fetch-error-message':
    'コンポーネント リストを読み込めませんでした。',
  'dragonfruit-page-team-details.add-component-modal.heading':
    'このチームにコンポーネントを割り当てる',
  'dragonfruit-page-team-details.add-component-modal.search-placeholder':
    'コンポーネントを選択',
  'dragonfruit-page-team-details.component-option-label.managed-externally':
    '外部で管理',
  'dragonfruit-page-team-details.component-option-label.no-owner': '所有者なし',
  'dragonfruit-page-team-details.components-list.actions.externally-managed.tooltip':
    '外部で管理されているコンポーネント',
  'dragonfruit-page-team-details.components-list.actions.label':
    '{component} に対するアクション',
  'dragonfruit-page-team-details.components-list.actions.remove.label':
    'チームから {component} を削除',
  'dragonfruit-page-team-details.components-list.actions.remove.text':
    'チームから削除',
  'dragonfruit-page-team-details.components-list.actions.settings.label':
    '{component} の設定',
  'dragonfruit-page-team-details.components-list.actions.settings.text': '設定',
  'dragonfruit-page-team-details.owner-override-confirmation-modal.close-button':
    'キャンセル',
  'dragonfruit-page-team-details.owner-override-confirmation-modal.content':
    'このコンポーネントは既にチームによって所有されています。このコンポーネントを別のチームに割り当ててもよろしいですか? ',
  'dragonfruit-page-team-details.owner-override-confirmation-modal.heading':
    'オーナー チームを変更してもよろしいですか? ',
  'dragonfruit-page-team-details.owner-override-confirmation-modal.submit-button':
    '保存',
  'dragonfruit-page-team-details.services.flags.copy-owner-ari-flag-failure':
    'ID をコピーできませんでした。もう一度お試しください。',
  'dragonfruit-page-team-details.services.flags.copy-owner-ari-flag-success':
    'ID がコピーされました。',
  'dragonfruit-page-team-details.services.flags.update-owner-ari-flag-failure-description':
    '所有権を割り当てられませんでした',
  'dragonfruit-page-team-details.services.flags.update-owner-flag-success-action':
    'コンポーネントを表示',
  'dragonfruit-page-team-details.services.flags.update-owner-flag-success-description':
    '{componentType} {componentName} がこのチームのダッシュボードに正常に追加されました。',
  'dragonfruit-page-team-details.services.flags.update-owner-flag-success-title':
    '{componentName} の所有権を割り当てました',
  'page-team-details.components-owned.empty-view.create-component-button':
    'コンポーネントを作成',
  'page-team-details.components-owned.empty-view.description':
    'チームが所有するコンポーネントを追加すると、ここに表示されるようになります。',
  'page-team-details.components-owned.empty-view.header':
    'チームが所有するコンポーネントを参照',
  'page-team-details.components-owned.error-view.header':
    'チームが所有するコンポーネントを取得できませんでした。',
  'page-team-details.main-skip-link-title': 'チームの詳細',
  'page-team-details.team-dashboard.actions.add-component':
    'コンポーネントを追加',
  'page-team-details.team-dashboard.actions.copy-owner-ari':
    '所有者 ID をコピー',
  'page-team-details.team-dashboard.right-sidebar-skip-link-title':
    'チームの詳細',
  'page-team-details.team-dashboard.section.owned-components':
    'チームのコンポーネント',
};
