/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Korean
export default {
  'people-and-teams.people-menu.collaborators.title': '내 공동 작업자',
  'people-and-teams.people-menu.error-heading': '오류가 발생했습니다',
  'people-and-teams.people-menu.error-image-alt-text':
    '고장난 로봇과 고치느라 바쁜 몇 명의 사람입니다.',
  'people-and-teams.people-menu.error-text':
    '이러한 오류는 계속 추적하지만, 페이지를 새로 고친 후에도 문제가 해결되지 않으면 언제든지 문의해 주세요',
  'people-and-teams.people-menu.invite-a-teammate.': '팀원 초대',
  'people-and-teams.people-menu.invite.teammates': '{product}에 사용자 추가',
  'people-and-teams.people-menu.start-a-team': '팀 시작하기',
  'people-and-teams.people-menu.teams': '팀',
  'people-and-teams.people-menu.view-all-people-teams': '사용자 및 팀 검색',
  'people-and-teams.people-menu.view-your-profile': '내 프로필 보기',
  'people-and-teams.people-menu.your-teams.title': '내 팀',
};
