/**
      THIS IS A CODE-GENERATED FILE PLEASE DO NOT EDIT
      TO MAKE CHANGES TO THIS FILE PLEASE FIRST READ THE README IN
      scripts/generate-redirect-list/README.md
    */
module.exports = [
  [
    '/guidelines/designPrinciples/design-principles',
    '/resources/atlassian-design-principles',
  ],
  ['/guidelines/brand', '/brand'],
  ['/guidelines/brand/personality', '/brand/personality'],
  ['/guidelines/brand/writing-style-1', '/content/writing-style/'],
  ['/guidelines/brand/color', '/foundations/color/'],
  ['/guidelines/brand/illustrations', '/foundations/illustrations/'],
  ['/guidelines/brand/logos', '/foundations/logos/'],
  ['/guidelines/brand/typography', '/foundations/typography/'],
  ['/guidelines/marketing/overview', '/'],
  [
    '/guidelines/marketing/foundations/illustrations',
    '/foundations/illustrations/',
  ],
  ['/guidelines/marketing/foundations/icons', '/foundations/iconography/'],
  ['/guidelines/marketing/foundations/color-usage', '/foundations/color/'],
  [
    '/guidelines/marketing/foundations/presentations',
    '/resources/presentation-kit/',
  ],
  ['/guidelines/marketing/foundations/motion', '/'],
  ['/guidelines/marketing/foundations/typography', '/foundations/typography/'],
  ['/guidelines/marketing/resources/logo-files', '/resources/logo-library/'],
  [
    '/guidelines/marketing/resources/illustration-library',
    '/resources/illustration-library/',
  ],
  ['/guidelines/marketing/resources/icons-library', '/'],
  [
    '/guidelines/marketing/resources/color-files',
    '/resources/color-palette-resources/',
  ],
  ['/guidelines/marketing/resources/fonts', '/resources/fonts/'],
  [
    '/guidelines/marketing/resources/presentation-kit',
    '/resources/presentation-kit/',
  ],
  ['/guidelines/marketing/resources/templates', '/resources/templates/'],
  ['/guidelines/product/overview', '/'],
  [
    '/guidelines/product/foundations/accessibility',
    '/foundations/accessibility/',
  ],
  ['/guidelines/product/foundations/color', '/foundations/color/'],
  ['/guidelines/product/foundations/grid', '/foundations/grid/'],
  ['/guidelines/product/foundations/iconography', '/foundations/iconography/'],
  ['/guidelines/product/foundations/typography', '/foundations/typography/'],
  ['/guidelines/product/foundations/writing-style', '/content/writing-style/'],
  ['/guidelines/product/components/avatars', '/components/avatar/'],
  ['/guidelines/product/components/badges', '/components/badge/'],
  ['/guidelines/product/components/banners', '/components/banner/'],
  ['/guidelines/product/components/breadcrumbs', '/components/breadcrumbs/'],
  ['/guidelines/product/components/buttons', '/components/button/'],
  ['/guidelines/product/components/checkboxes', '/components/checkbox/'],
  ['/guidelines/product/components/code', '/components/code/'],
  [
    '/guidelines/product/components/date-picker',
    'https://atlaskit.atlassian.com/packages/design-system/datetime-picker',
  ],
  ['/guidelines/product/components/drop-menu', '/components/dropdown-menu/'],
  ['/guidelines/product/components/flag-messages', '/components/flag/'],
  [
    '/guidelines/product/components/inline-dialog',
    '/components/inline-dialog/',
  ],
  ['/guidelines/product/components/inline-edit', '/components/inline-edit/'],
  [
    '/guidelines/product/components/inline-messages',
    '/components/inline-message/',
  ],
  ['/guidelines/product/components/logos-in-product', '/components/logo/'],
  ['/guidelines/product/components/lozenges', '/components/lozenge/'],
  ['/guidelines/product/components/messages', '/patterns/messages'],
  ['/guidelines/product/components/modal-dialog', '/components/modal-dialog/'],
  ['/guidelines/product/components/pagination', '/components/pagination/'],
  [
    '/guidelines/product/components/progress-indicators',
    '/components/progress-indicator/',
  ],
  [
    '/guidelines/product/components/progress-tracker',
    '/components/progress-tracker/',
  ],
  ['/guidelines/product/components/radios', '/components/radio/'],
  [
    '/guidelines/product/components/section-messages',
    '/components/section-message/',
  ],
  ['/guidelines/product/components/select', '/components/select/'],
  ['/guidelines/product/components/spinners', '/components/spinner/'],
  [
    '/guidelines/product/components/tables',
    'https://atlaskit.atlassian.com/packages/core/dynamic-table',
  ],
  ['/guidelines/product/components/tabs', '/components/tabs/'],
  ['/guidelines/product/components/tags', '/components/tag/'],
  ['/guidelines/product/components/text-field', '/components/textfield/'],
  ['/guidelines/product/components/toggles', '/components/toggle/'],
  ['/guidelines/product/components/tooltips', '/components/tooltip/'],
  [
    '/guidelines/product/patterns/user-value-modals',
    '/patterns/benefits-modal',
  ],
  [
    '/guidelines/product/patterns/color-palette',
    '/foundations/color/color-palette/',
  ],
  [
    '/guidelines/product/patterns/comments',
    'https://atlaskit.atlassian.com/packages/design-system/comment',
  ],
  ['/guidelines/product/patterns/forms', '/patterns/forms/'],
  ['/guidelines/product/patterns/inline-edit', '/components/inline-edit/'],
  ['/guidelines/product/patterns/media-picker', '/patterns/media-picker/'],
  ['/guidelines/product/patterns/page-header', '/components/page-header/'],
  ['/guidelines/product/patterns/spotlight', '/patterns/spotlight/'],
  [
    '/guidelines/product/first-impressions/first-impressions-overview',
    '/patterns/first-impressions/',
  ],
  [
    '/guidelines/product/first-impressions/new-or-updated-feature',
    '/patterns/first-impressions/new-or-updated-feature/',
  ],
  [
    '/guidelines/product/first-impressions/new-experience',
    '/patterns/first-impressions/new-experience/',
  ],
  [
    '/guidelines/product/first-impressions/first-impression-emotions',
    '/patterns/first-impressions/user-emotions/',
  ],
  [
    '/guidelines/product/first-impressions/first-impression-sizes',
    '/patterns/first-impressions/user-journey-sizes/',
  ],
  [
    '/guidelines/product/resources/web-product-gui-pack',
    '/resources/sketch-library',
  ],
  ['/guidelines/voiceAndTone/', '/content'],
  ['/guidelines/voiceAndTone/personas', '/'],
  [
    '/guidelines/voiceAndTone/language-grammar',
    '/content/language-and-grammar/',
  ],
  ['/guidelines/voiceAndTone/glossary-test', '/content/glossary/'],
  [
    '/guidelines/voiceAndTone/writing-error-messages',
    '/content/messaging-guidelines/writing-error-messages/',
  ],
  ['/guidelines/handy/license', '/license'],
  ['/guidelines/handy/whats-new', '/'],
  ['/patterns/inline-edit', '/components/inline-edit'],
  ['/patterns/page-header', '/components/page-header'],
  ['/server', '/'],
  ['/server/changelog', '/'],
  ['/server/foundations/colors', '/foundations/color'],
  ['/server/foundations/iconography', '/foundations/iconography'],
  ['/server/foundations/typography', '/foundations/typography'],
  ['/server/foundations/writing-style', '/content/writing-style'],
  ['/server/components/avatars', '/components/avatar'],
  ['/server/components/badges', '/components/badge'],
  ['/server/components/buttons', '/components/button'],
  [
    '/server/components/date-picker',
    'https://atlaskit.atlassian.com/packages/design-system/datetime-picker',
  ],
  ['/server/components/dropdowns', '/components/dropdown-menu'],
  ['/server/components/forms', '/patterns/forms'],
  ['/server/components/inline-dialog', '/components/inline-dialog'],
  ['/server/components/lozenges', '/components/lozenge'],
  ['/server/components/messages', '/patterns/messages'],
  ['/server/components/modal-dialog', '/components/modal-dialog'],
  [
    '/server/components/navigation',
    'https://atlaskit.atlassian.com/packages/navigation/atlassian-navigation',
  ],
  ['/server/components/page-header', '/components/page-header'],
  ['/server/components/progress-indicators', '/components/progress-indicator'],
  [
    '/server/components/tables',
    'https://atlaskit.atlassian.com/packages/core/dynamic-table',
  ],
  ['/server/components/tabs', '/components/tabs'],
  ['/server/components/toggles', '/components/toggle'],
  ['/server/components/tooltips', '/components/tooltip'],
  ['/server/patterns/date-formats', '/'],
  ['/server/patterns/focused-tasks', '/'],
  ['/server/patterns/inline-edit', '/components/inline-edit'],
  ['/server/patterns/mentions', '/'],
  ['/server/patterns/progress-tracker', '/components/progress-tracker'],
  [
    '/server/patterns/sidebar',
    'https://atlaskit.atlassian.com/packages/navigation/side-navigation',
  ],
  ['/content/glossary', '/content/vocabulary'],
  ['/content/messaging-guidelines', '/content/writing-guidelines'],
  [
    '/content/messaging-guidelines/writing-error-messages',
    '/content/writing-guidelines/writing-error-messages',
  ],
  [
    '/content/messaging-guidelines/empty-state',
    '/content/writing-guidelines/empty-state',
  ],
  [
    '/content/messaging-guidelines/feature-discovery',
    '/content/writing-guidelines/feature-discovery',
  ],
  [
    '/content/messaging-guidelines/writing-an-info-message',
    '/content/writing-guidelines/writing-an-info-message',
  ],
  [
    '/content/messaging-guidelines/writing-a-success-message',
    '/content/writing-guidelines/writing-a-success-message',
  ],
  [
    '/content/messaging-guidelines/writing-a-warning-message',
    '/content/writing-guidelines/writing-a-warning-message',
  ],
  ['/foundations/color-palette', '/foundations/color/color-palette'],
  ['/patterns/benefits-modal', '/components/onboarding/benefits-modal/usage'],
  ['/patterns/spotlight', '/components/onboarding/examples'],
];
