/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// English (Instrumented)
export default {
  'dragonfruit-page-component-details.announcements.component-announcements.delete-announcement-modal.error-handling.component-not-found-error-flag-description.nonfinal':
    '⁣⁢The component that the announcement belongs to could not be found, and may have been recently deleted.‌‍⁫⁫‍⁭‍‍⁮⁡⁯⁬؜؜⁭⁯⁬‌‍⁡⁮⁫⁣⁤',
  'dragonfruit-page-component-details.announcements.component-announcements.delete-announcement-modal.error-handling.flags.delete-announcement-error-flag-title.nonfinal':
    '⁣⁢Error deleting announcement⁬‍‌⁠⁪⁬⁯⁡⁬‍⁯⁬؜⁯⁮⁡⁮⁠⁠⁯‌⁫⁣⁤',
  'dragonfruit-page-component-details.announcements.component-announcements.delete-announcement-modal.error-handling.flags.delete-announcement-success-flag-title.nonfinal':
    '⁣⁢Successfully deleted announcement⁪⁮‌⁪⁠⁪⁪؜⁪‌‍‍⁪⁭⁭؜‍⁠‌؜⁡⁯⁯⁣⁤',
  'dragonfruit-page-component-details.announcements.component-announcements.delete-announcement-modal.modal-description.nonfinal':
    '⁣⁢Are you sure you want to delete this announcement?⁮⁯؜⁭⁬⁭⁫⁯⁮؜⁫⁯⁮⁫⁪⁯⁬⁡‍⁠؜⁪⁬⁪؜⁠⁣⁤',
  'dragonfruit-page-component-details.announcements.component-announcements.delete-announcement-modal.modal-title.nonfinal':
    '⁣⁢Delete announcement؜⁡⁯⁪⁬⁮⁡⁪⁪⁭⁯‌‍‌‌⁡⁭⁭⁠⁣⁤',
  'dragonfruit-page-component-details.announcements.component-announcements.update-announcement-modal.error-handling.announcement-not-found-error-flag-description.nonfinal':
    '⁣⁢The announcement could not be found, and may have been recently deleted.⁯⁡⁭⁫‍⁠‍؜⁪⁯⁮‍⁬⁫⁠⁭⁮؜؜⁬⁫⁮⁣⁤',
  'dragonfruit-page-component-details.announcements.component-announcements.update-announcement-modal.error-handling.component-not-found-error-flag-description.nonfinal':
    '⁣⁢The component that the announcement belongs to could not be found, and may have been recently deleted.⁫⁪‌⁫؜⁠⁪⁭⁪⁮⁭⁡⁫⁡‌‌⁫⁯؜⁫⁣⁤',
  'dragonfruit-page-component-details.announcements.component-announcements.update-announcement-modal.error-handling.flags.update-announcement-error-flag-title.nonfinal':
    '⁣⁢Error updating announcement‍⁫‌⁭⁬⁠⁮⁯⁫⁪⁫؜⁡؜⁯⁡⁮⁯⁡⁡⁫⁪⁭⁫⁣⁤',
  'dragonfruit-page-component-details.announcements.component-announcements.update-announcement-modal.error-handling.flags.update-announcement-success-flag-title.nonfinal':
    '⁣⁢Successfully updated announcement⁭⁡‌⁡⁠⁠⁮؜⁭⁭؜‍⁯⁮‌⁮⁬⁭⁡⁠⁫⁮؜⁠⁡‍⁣⁤',
  'dragonfruit-page-component-details.announcements.create-announcement-modal.create-announcement-form.announcement-component-field-label.nonfinal':
    '⁣⁢From⁭⁯⁪⁭⁭⁠⁭⁪⁭‌⁬⁬‌⁭⁬⁭؜⁮⁭⁡⁬⁪⁣⁤',
  'dragonfruit-page-component-details.announcements.create-announcement-modal.create-announcement-form.announcement-description-field-placeholder.nonfinal':
    '⁣⁢Enter an announcement description⁮⁮⁮⁭‌⁪⁬⁬؜⁡‍⁮⁬⁭⁡‌⁯⁬‍⁯⁫⁡⁪⁣⁤',
  'dragonfruit-page-component-details.announcements.create-announcement-modal.create-announcement-form.announcement-target-date-field-helper-message.nonfinal':
    '⁣⁢When the updates in the announcement will take effect.⁯⁫⁡⁭⁠⁪⁮‍‌‌‍⁪؜⁭⁭⁮⁮‌‍⁡⁣⁤',
  'dragonfruit-page-component-details.announcements.create-announcement-modal.create-announcement-form.announcement-target-date-field-label.nonfinal':
    '⁣⁢Target date⁫⁭⁮⁫‍‌⁬⁬⁭‌⁠⁮⁪؜⁭⁬⁮⁬⁫⁮⁭⁣⁤',
  'dragonfruit-page-component-details.announcements.create-announcement-modal.create-announcement-form.announcement-target-date-picker-placeholder.nonfinal':
    '⁣⁢Select a target date⁡⁠⁯⁡⁭‍⁮⁠⁮؜⁮⁪⁬⁬⁡⁬‌⁯⁯⁡‍⁪⁡⁬⁬⁪⁣⁤',
  'dragonfruit-page-component-details.announcements.create-announcement-modal.create-announcement-form.announcement-title-field-label.nonfinal':
    '⁣⁢Title⁮‌⁯⁭‍؜⁪⁮⁮⁪؜⁭⁯⁡⁭⁡؜⁫؜⁫⁬⁭⁠⁮⁣⁤',
  'dragonfruit-page-component-details.announcements.create-announcement-modal.create-announcement-form.announcement-title-field-placeholder.nonfinal':
    '⁣⁢Enter an announcement title⁪⁮⁭⁭‍⁪⁯⁯⁯⁭‍⁠⁮‍⁯‍⁬⁣⁤',
  'dragonfruit-page-component-details.announcements.create-announcement-modal.create-announcement-form.create-announcement-error-flag-description.nonfinal':
    '⁣⁢An error occured while creating your announcement. Please try again.⁡⁠⁪⁯⁠⁮؜‌⁡‌⁡⁠‍‌⁪‌⁬‍⁪⁯⁯⁣⁤',
  'dragonfruit-page-component-details.announcements.create-announcement-modal.create-announcement-form.create-announcement-error-flag-title.nonfinal':
    '⁣⁢Error creating announcement‍⁫‌⁯⁮⁫⁫⁪⁭⁡⁯‌؜‌⁡⁬؜⁫⁬‌⁠⁣⁤',
  'dragonfruit-page-component-details.announcements.create-announcement-modal.create-announcement-form.create-announcement-success-flag-title.nonfinal':
    '⁣⁢Successfully created announcement⁡‌⁠⁡⁪⁪⁠⁭⁫⁭⁭⁪⁠⁮⁮⁭⁠⁪؜⁠⁪⁣⁤',
  'dragonfruit-page-component-details.announcements.create-announcement-modal.create-announcement-modal-description.nonfinal':
    '⁣⁢Announcements will be sent to all dependencies.⁠⁮⁮⁭⁭⁪⁫⁭⁬⁬‍⁯‍⁡⁯⁯‍⁭⁠⁬؜‍⁠⁣⁤',
  'dragonfruit-page-component-details.announcements.create-announcement-modal.create-announcement-modal-title.nonfinal':
    '⁣⁢Create announcement⁪⁬⁭⁬⁫⁫⁮⁡⁪⁮⁫⁯⁡⁯⁫‌⁫⁫‍؜⁠⁡⁯؜⁯⁣⁤',
  'dragonfruit-page-component-details.announcements.update-announcement-modal.update-announcement-form.announcement-component-field-label.nonfinal':
    '⁣⁢From‍؜⁮‍⁯؜⁮‌⁠⁡⁮⁯⁯⁭⁯‍⁫⁠⁡‌⁯⁣⁤',
  'dragonfruit-page-component-details.announcements.update-announcement-modal.update-announcement-form.announcement-description-field-placeholder.nonfinal':
    '⁣⁢Enter an announcement description⁠⁫⁪⁡‍⁠⁮‌⁯⁠⁠⁡⁭‍؜⁪⁭⁠⁭‍⁭⁣⁤',
  'dragonfruit-page-component-details.announcements.update-announcement-modal.update-announcement-form.announcement-target-date-field-helper-message.nonfinal':
    '⁣⁢When the updates in the announcement will take effect.‌؜‍‌⁮⁡⁬⁪⁮؜⁮⁪⁪‍⁠⁪؜⁠⁫⁮‍⁫⁬‍⁭⁣⁤',
  'dragonfruit-page-component-details.announcements.update-announcement-modal.update-announcement-form.announcement-target-date-field-label.nonfinal':
    '⁣⁢Target date⁮⁫⁡⁬⁬⁯؜⁪؜⁡⁪⁮⁮⁯⁪⁭‌⁮⁠⁣⁤',
  'dragonfruit-page-component-details.announcements.update-announcement-modal.update-announcement-form.announcement-target-date-picker-placeholder.nonfinal':
    '⁣⁢Select a target date⁫⁮⁡⁫⁯‍⁮⁯‌؜⁯‍‌⁬⁭⁫⁬‍⁯⁣⁤',
  'dragonfruit-page-component-details.announcements.update-announcement-modal.update-announcement-form.announcement-title-field-label.nonfinal':
    '⁣⁢Title⁮⁫⁭⁫⁮⁯‍⁫⁡⁮⁡‌⁬⁮⁮⁬⁫⁬‌⁯⁣⁤',
  'dragonfruit-page-component-details.announcements.update-announcement-modal.update-announcement-form.announcement-title-field-placeholder.nonfinal':
    '⁣⁢Enter an announcement title⁬⁬⁭⁫⁪⁡⁡⁠؜⁬⁪⁡⁫‍⁯⁬⁮⁪⁪⁬⁠⁣⁤',
  'dragonfruit-page-component-details.announcements.update-announcement-modal.update-announcement-form.clear-acknowledgements-checkbox-label.nonfinal':
    '⁣⁢Clear acknowledgements⁠⁭؜⁮‍⁫⁪⁪‌⁠⁮⁭⁫‍‍⁡⁪⁡‌⁮⁮⁠‍⁯؜⁫⁮⁣⁤',
  'dragonfruit-page-component-details.announcements.update-announcement-modal.update-announcement-form.update-announcement-error-flag-description.nonfinal':
    '⁣⁢An error occured while updating your announcement. Please try again.؜؜⁬‌⁠⁫⁫⁯⁫‍‌⁬؜‌⁭⁡؜‍⁫⁯‌‍⁮⁣⁤',
  'dragonfruit-page-component-details.announcements.update-announcement-modal.update-announcement-form.update-announcement-error-flag-title.nonfinal':
    '⁣⁢Error updating announcement⁮⁭⁠⁮⁯؜⁬⁮⁪⁬⁭⁡⁮⁡⁪⁭⁪‍⁪⁪‍‍‌⁣⁤',
  'dragonfruit-page-component-details.announcements.update-announcement-modal.update-announcement-form.update-announcement-success-flag-title.nonfinal':
    '⁣⁢Successfully updated announcement⁭‍⁯⁯⁭⁡⁮⁬‍⁫⁡⁭⁬⁯‌⁯⁠⁠⁯⁣⁤',
  'dragonfruit-page-component-details.announcements.update-announcement-modal.update-announcement-modal-title.nonfinal':
    '⁣⁢Edit announcement⁡؜⁪⁮⁡⁯⁠⁡؜⁡⁮⁡⁭⁭؜⁯⁫⁯⁪‍⁮⁬⁮⁣⁤',
  'dragonfruit-page-component-details.common.relationships.component-not-found':
    '⁣⁢The component you are trying to edit could not be found. It may have been removed.⁬⁪⁭‌⁠⁡؜⁫⁭؜⁯⁡‍⁠⁠⁠⁮‌⁣⁤',
  'dragonfruit-page-component-details.common.relationships.error-creating-flag-description':
    '⁣⁢An error occurred while creating your dependency. Try adding the dependency again.⁠⁮⁪‍‍⁪‍‌⁫⁫⁫⁬⁬⁪‌⁠⁠⁠⁡⁪⁠⁬⁣⁤',
  'dragonfruit-page-component-details.common.relationships.error-creating-flag-title':
    '⁣⁢Error creating component dependency⁠⁪‌⁫⁫⁪⁠؜⁮‌⁫⁪‍؜⁮⁭‍‍‌⁡⁠⁡⁡⁭⁡⁭⁣⁤',
  'dragonfruit-page-component-details.component-main.announcements.acknowledgement-list.acknowledged-section-heading.nonfinal':
    '⁣⁢Acknowledged⁯‌‍⁡⁡⁪⁠⁪⁠⁯⁬⁮؜⁡⁫⁫⁭⁣⁤',
  'dragonfruit-page-component-details.component-main.announcements.acknowledgement-list.unacknowledged-section-heading.nonfinal':
    '⁣⁢Not acknowledged⁪⁮‌⁭⁭⁯‌⁬⁪‌‍⁯⁭⁮⁡‍‍⁭⁫‌⁫⁠⁭⁮⁯⁣⁤',
  'dragonfruit-page-component-details.component-main.announcements.announcements-view.create-announcement.nonfinal':
    '⁣⁢Create announcement⁭⁫⁫⁯⁬؜⁪⁭⁪⁬⁠؜⁡⁭⁯⁮⁪‌‍؜⁪⁠⁣⁤',
  'dragonfruit-page-component-details.component-main.announcements.announcements-view.empty-state-description.nonfinal':
    '⁣⁢Create announcements to share updates with any components that depend on {componentName}. For example:؜‍⁫⁡⁬⁫⁪⁭⁭⁯؜⁭⁡⁭‍⁫⁫⁭⁯⁬⁫؜⁫؜⁯⁬؜⁣⁤',
  'dragonfruit-page-component-details.component-main.announcements.announcements-view.empty-state-example1.nonfinal':
    '⁣⁢New features⁡⁡‌⁫‍‍⁪؜‍⁬⁠⁠⁭⁮⁪⁫⁬⁣⁤',
  'dragonfruit-page-component-details.component-main.announcements.announcements-view.empty-state-example2.nonfinal':
    '⁣⁢API deprecation‌⁫⁮‍⁡⁮⁠⁪⁫⁡⁠⁫⁠‍⁪⁯⁬‌⁭⁡⁫⁣⁤',
  'dragonfruit-page-component-details.component-main.announcements.announcements-view.empty-state-example3.nonfinal':
    '⁣⁢Scheduled downtime‍⁡⁡⁠⁠‌⁬‌⁬‍‍⁠⁬⁡⁮⁪‌⁫⁮⁠؜⁭⁯⁮⁣⁤',
  'dragonfruit-page-component-details.component-main.announcements.announcements-view.empty-state-header.nonfinal':
    '⁣⁢Broadcast upcoming changes⁭⁫‌‌‍‌⁯⁮⁬⁪⁪⁡⁪⁬‌⁯⁪⁪⁬‌⁪⁫⁭⁬⁡⁠⁡⁣⁤',
  'dragonfruit-page-component-details.component-main.announcements.announcements-view.error-message.nonfinal':
    '⁣⁢We couldn’t retrieve your dependencies⁠؜⁪⁫⁬‍⁬؜⁬⁠⁯‌‍⁬‍⁮‌‌⁠⁣⁤',
  'dragonfruit-page-component-details.component-main.announcements.component-announcements.actions-menu.actions-label.nonfinal':
    '⁣⁢Actions for announcement⁠⁭⁠⁠⁮⁬⁠‍‌⁬⁬؜‌‌⁫؜⁬⁫⁮⁡⁫⁡⁣⁤',
  'dragonfruit-page-component-details.component-main.announcements.component-announcements.actions-menu.delete-announcement.nonfinal':
    '⁣⁢Delete announcement‌⁠؜‌⁪⁮‌⁫⁡⁡‍⁮‍⁠⁠⁫⁪‌؜‌⁪⁯⁣⁤',
  'dragonfruit-page-component-details.component-main.announcements.component-announcements.actions-menu.edit-announcement.nonfinal':
    '⁣⁢Edit announcement‌⁬⁡⁫⁭⁪⁭⁫؜⁭؜‌‌⁫⁫⁭⁫⁯⁪‌⁭‌⁣⁤',
  'dragonfruit-page-component-details.component-main.announcements.component-announcements.component-announcement.acknowledgement-status.nonfinal':
    '⁣⁢{numAcknowledged} of {total} acknowledged‌⁮⁫⁠⁮‌⁠⁡⁭‍‌‌‌⁡⁮⁯⁮؜⁮⁫⁭⁣⁤',
  'dragonfruit-page-component-details.component-main.announcements.dependency-announcements-view.go-to-dependencies-button.nonfinal':
    '⁣⁢Set up dependencies‌⁪‌⁭⁭‌⁭⁮⁭⁯‌⁮⁮⁯⁯⁡⁭⁯‍؜⁠‍⁯⁣⁤',
  'dragonfruit-page-component-details.component-main.announcements.dependency-announcements-view.no-announcements-empty-state-description.nonfinal':
    "⁣⁢Any announcements from this component's upstream dependencies will appear here.⁯⁠⁮⁬⁠⁡⁮⁭⁠⁫⁪‍⁪‍⁬‍⁠⁠⁬⁪⁮⁠⁣⁤",
  'dragonfruit-page-component-details.component-main.announcements.dependency-announcements-view.no-announcements-empty-state-header.nonfinal':
    '⁣⁢No announcements from dependencies⁬⁬⁭⁭⁠⁡؜⁡‍‌⁫؜‌⁠⁮⁪⁭⁪⁭⁪⁭⁬‍؜⁣⁤',
  'dragonfruit-page-component-details.component-main.announcements.dependency-announcements-view.no-dependencies-empty-state-description.nonfinal':
    '⁣⁢Define upstream dependencies to stay up-to-date with any announcements that may affect this component.‌⁭⁪⁬⁪⁪⁭⁫؜⁮⁬⁪⁪⁯‌⁭⁯⁮⁬⁣⁤',
  'dragonfruit-page-component-details.component-main.announcements.dependency-announcements-view.no-dependencies-empty-state-header.nonfinal':
    '⁣⁢No dependencies have been defined⁮⁪⁬‌⁭⁯‌⁠⁯⁡⁠⁠⁫؜⁡⁭⁮؜⁫⁭⁭؜⁣⁤',
  'dragonfruit-page-component-details.component-main.announcements.dependency-announcements.acknowledge.nonfinal':
    '⁣⁢Acknowledge؜‌⁠⁡‍؜⁯‍⁬⁪⁪⁯⁡‌⁫⁪⁯‌⁡⁭⁭‍⁣⁤',
  'dragonfruit-page-component-details.component-main.announcements.dependency-announcements.acknowledged.nonfinal':
    '⁣⁢Acknowledged⁪‍⁠⁫؜⁬⁮⁫⁫⁡⁭‌⁯⁡؜⁭⁬⁬⁪‍⁬⁮⁣⁤',
  'dragonfruit-page-component-details.component-main.overview.labels-section.editor-add-value-format':
    '⁣⁢Add <b>&quot;{labelName}&quot;</b>‌⁯⁬⁡⁭⁪؜⁪‌⁭⁯⁪‍‍‌⁡⁠؜؜⁡⁣⁤',
  'dragonfruit-page-component-details.component-main.overview.labels-section.editor-no-options-message':
    '⁣⁢Start typing to add labels؜⁭⁯⁪⁡⁠⁮⁡⁠‌⁭⁡⁯⁪⁡⁯⁭‍‍‌⁪⁮⁯⁣⁤',
  'dragonfruit-page-component-details.component-main.overview.labels-section.editor-placeholder':
    '⁣⁢Add labels‌⁯⁭⁯⁬⁫⁭⁪⁭⁭⁭⁫⁬⁮؜⁬⁯⁮‌⁭‍⁠⁠‌⁠⁯⁣⁤',
  'dragonfruit-page-component-details.component-main.overview.labels-section.editor.no-results-found':
    '⁣⁢No results found⁪‍⁯⁭؜⁪⁡‍⁬⁡⁮⁠⁮⁮⁡⁫⁬‍⁯⁪⁬⁪⁣⁤',
  'dragonfruit-page-component-details.component-main.overview.labels-section.editor.search-failed-error':
    '⁣⁢Search failed. Start typing to search again⁬⁮⁮⁬⁡⁮⁪⁯⁫؜⁯⁬⁡⁡⁬⁯⁪⁡؜؜⁯؜⁬⁣⁤',
  'dragonfruit-page-component-details.component-main.overview.labels-section.editor.validation-label-already-added':
    '⁣⁢This label has already been added to the component⁡⁭⁠‌⁫⁯⁬⁯⁫⁠⁮⁭⁫⁪⁡⁭⁬⁫⁮⁯‌⁮⁫⁣⁤',
  'dragonfruit-page-component-details.component-main.overview.labels-section.editor.validation-label-max-length':
    '⁣⁢Label must be {characterLimit} characters or fewer‍⁬⁡؜؜⁡⁭⁭⁭⁡⁯⁬⁪⁬⁫⁫⁬؜؜⁠⁮⁠⁡⁬⁣⁤',
  'dragonfruit-page-component-details.component-main.overview.labels-section.editor.validation-limit-reached':
    '⁣⁢A component can have a maximum of {labelLimit} labels⁠⁪⁮‌⁯⁫⁪⁯‍⁯⁪‌؜‌⁠⁮⁬⁠؜⁯⁪⁠⁠⁣⁤',
  'dragonfruit-page-component-details.component-main.overview.labels-section.editor.validation-unknown-error':
    '⁣⁢An unknown error occurred. Please try again⁬⁯⁫؜‍⁮⁯‍⁡⁠⁬؜⁯⁡‌⁬⁫⁯⁪‍‍⁫⁠⁣⁤',
  'dragonfruit-page-component-details.component-main.overview.labels.editable-view.editor-view.error-flags.add-label-error-flag-title':
    '⁣⁢Error saving component label⁬⁪⁠⁡⁬⁮‌⁡⁭‌؜؜⁭⁭⁫⁠⁪⁬⁫⁮‌⁭‍⁣⁤',
  'dragonfruit-page-component-details.component-main.overview.labels.editable-view.editor-view.error-flags.component-not-found-error-flag-description':
    '⁣⁢The component you’re trying to edit could not be found, and may have been recently deleted.⁡⁭⁪⁫⁫‌⁡‌⁯⁬⁬‌‌⁭⁪⁭⁠‌⁬⁣⁤',
  'dragonfruit-page-component-details.component-main.overview.labels.editable-view.editor-view.error-flags.label-input-cannot-be-empty-error-flag-description':
    '⁣⁢The list of component labels is empty. Provide at least one label and try again.⁬⁡؜‌‍⁠⁯⁯‌؜‌⁬‌⁬‌⁠⁭⁯⁬؜⁠‍⁬⁪⁣⁤',
  'dragonfruit-page-component-details.component-main.overview.labels.editable-view.editor-view.error-flags.label-input-too-long-error-flag-description':
    '⁣⁢The list of component labels contains too many values. Try again with {labelInputLimit} or fewer labels.⁪‍‍⁠⁫؜⁡⁭⁬؜⁯⁭⁬⁬⁯‍⁮⁠⁭⁫⁮⁪؜‌⁯⁣⁤',
  'dragonfruit-page-component-details.component-main.overview.labels.editable-view.editor-view.error-flags.label-limit-reached-error-flag-description':
    '⁣⁢A component can have a maximum of {labelLimit} labels. Try reducing the number of labels associated with the component.⁭⁫⁪⁡⁮⁬‌⁯‌⁭⁬⁫⁡⁫؜‌⁠⁯‍‌؜⁪⁣⁤',
  'dragonfruit-page-component-details.component-main.overview.labels.editable-view.editor-view.error-flags.label-name-cannot-be-blank-error-flag-description':
    '⁣⁢A component label name cannot be blank. Provide a name and try again.⁬⁫؜⁠⁮‌‍⁮⁯⁮⁬⁡‌⁡⁬؜؜؜⁫‌⁬؜⁭⁫‌؜‌⁣⁤',
  'dragonfruit-page-component-details.component-main.overview.labels.editable-view.editor-view.error-flags.label-name-cannot-contain-uppercase-characters-error-flag-description':
    '⁣⁢The component label name must be in lowercase. Remove all uppercase characters and try again.⁠⁪⁯‌‍⁭⁯؜‌‌⁬‍‌⁮⁡⁯⁯⁪‌‍⁡⁭⁮⁫⁣⁤',
  'dragonfruit-page-component-details.component-main.overview.labels.editable-view.editor-view.error-flags.label-name-cannot-contain-whitespace-characters-error-flag-description':
    '⁣⁢The component label name contains whitespace characters. Remove all whitespace characters and try again.⁮⁬⁠‌⁡⁭؜‍⁡‍⁠⁯؜⁠⁡⁯⁫⁫⁠⁫⁠⁣⁤',
  'dragonfruit-page-component-details.component-main.overview.labels.editable-view.editor-view.error-flags.label-name-contains-invalid-character-error-flag-description':
    '⁣⁢The component label name contains invalid characters. Remove those characters and try again.⁪⁭⁠⁠‍‌‌؜⁪‍⁯؜⁡؜⁡؜⁫‍⁡‍⁮⁣⁤',
  'dragonfruit-page-component-details.component-main.overview.labels.editable-view.editor-view.error-flags.label-name-too-long-error-flag-description':
    '⁣⁢The component label name is too long. Try again with a name that is {characterLimit} characters or fewer⁮⁪⁫⁠؜⁠⁡⁯⁬⁭؜⁬⁮‌⁮⁡⁯‍⁠‍‌⁣⁤',
  'dragonfruit-page-component-details.component-main.overview.labels.editable-view.editor-view.error-flags.remove-label-error-flag-title':
    '⁣⁢Error removing component label⁠⁮‌‌‌⁪⁭‍⁠⁬⁪⁯⁠‍⁬⁫⁭⁭⁫⁬⁮⁪‌⁣⁤',
  'dragonfruit-page-component-details.component-main.overview.labels.section-title':
    '⁣⁢Labels‍⁭⁪⁮؜⁭⁭⁠⁮‍⁫⁠⁭؜‍؜⁬⁮⁫⁯‍⁡⁬⁠⁠⁣⁤',
  'dragonfruit-page-component-details.component-main.overview.labels.section.empty-state':
    '⁣⁢Add labels to describe this component⁪⁮⁡‌⁫⁡⁮⁫⁭⁪⁠‌‍⁭⁯⁠⁫⁮⁮⁮⁣⁤',
  'dragonfruit-page-component-details.component-main.relationships.add-relationship-form.depends-on':
    '⁣⁢Depends on⁠⁠⁠⁮⁬⁬⁠⁫‌‍⁮‍⁪⁬⁡‌⁡‍‍⁯⁠⁣⁤',
  'dragonfruit-page-component-details.component-main.relationships.add-relationship-form.relationship-already-exists-error':
    '⁣⁢Dependency already exists‍؜⁠⁡⁪‍؜⁬⁠⁭⁭⁫⁮⁡⁬⁪⁭⁪⁫⁬⁫⁠⁫⁣⁤',
  'dragonfruit-page-component-details.component-main.relationships.add-relationship-form.relationship-already-exists-error-flag-description':
    '⁣⁢This dependency already exists. Refresh your page to see the latest changes.⁠⁭⁪⁪⁪؜⁠‌⁭⁪⁠؜‍؜‍‍⁫؜‍⁠⁠⁪؜⁡⁣⁤',
  'dragonfruit-page-component-details.component-main.relationships.add-relationship-form.relationship-end-node-does-not-exist-error-flag-description':
    "⁣⁢The component you selected as a dependency doesn't exist. It may have been removed. Try again with an existing component.⁠⁡⁭⁮؜⁠⁭‍‌‌‌‌⁪⁯⁡⁠⁮⁬⁠⁣⁤",
  'dragonfruit-page-component-details.component-main.relationships.add-relationship-form.relationship-limit-reached-error':
    '⁣⁢Dependency limit reached⁡⁠⁠⁬⁯⁠⁪‌؜⁮‌⁫‌⁠⁯؜⁬⁣⁤',
  'dragonfruit-page-component-details.component-main.relationships.add-relationship-form.relationship-limit-reached-error-flag-description':
    '⁣⁢Dependency limit reached. The maximum number of dependencies a component can have is {limit}.⁡؜⁭⁡‍⁯⁬⁭؜⁪⁠⁫⁪‍⁠⁯⁪⁪⁪؜⁮⁭⁮⁫⁬‌؜⁯⁫⁯⁣⁤',
  'dragonfruit-page-component-details.component-main.relationships.add-relationship-form.relationship-self-referencing-error':
    "⁣⁢A component can't be dependent on itself, select another component.⁠⁫⁮⁭⁪‍⁫⁠‌⁮⁭⁮⁫‍⁡⁯⁮‌‌⁯⁠⁭⁣⁤",
  'dragonfruit-page-component-details.component-main.relationships.add-relationship-form.relationship-self-referencing-error-flag-description':
    "⁣⁢The component can't be dependent on itself. Select another component to create a dependency.⁪⁮⁯⁯‌⁫⁬؜⁭؜⁡⁠⁪⁡⁡⁭‍؜⁣⁤",
  'dragonfruit-page-component-details.component-main.relationships.add-relationship-form.relationship-start-node-does-not-exist-error-flag-description':
    '⁣⁢The component you are trying to create a dependency for does not exist. It may have been removed.‍⁫⁪⁫⁡⁬⁡⁬؜⁭⁭⁭⁪⁫‍⁡⁪⁠⁫؜؜⁭‌⁫؜⁯⁣⁤',
  'dragonfruit-page-component-details.component-main.relationships.add-relationship-form.search-for-a-component':
    '⁣⁢Search for a component‌⁪⁯⁮⁯⁡؜⁡⁭⁬⁮‌⁫⁪⁮⁡⁡⁮؜⁡؜؜⁮⁡⁡؜⁪⁭⁣⁤',
  'dragonfruit-page-component-details.component-main.relationships.empty-state-form.depends-on':
    '⁣⁢Depends on⁮؜⁯‌‌⁠⁪‌⁯⁬⁡⁫⁯‌⁮⁫⁡⁡‌⁪⁮⁣⁤',
  'dragonfruit-page-component-details.component-main.relationships.empty-state-form.submit-button':
    '⁣⁢Add dependency⁭⁯⁡⁫⁯⁡⁪⁡⁠⁫‍⁡⁡‍⁭⁭⁠⁭⁬‌‍⁣⁤',
  'dragonfruit-page-component-details.component-main.relationships.empty-state.empty-state-description':
    "⁣⁢Define upstream dependencies to understand whether you're affected if downtime occurs.⁪⁠⁭⁡⁠⁡⁠⁯‍⁡‌⁪⁫⁫⁬⁪⁪‍⁪⁯⁠⁣⁤",
  'dragonfruit-page-component-details.component-main.relationships.empty-state.empty-state-heading':
    '⁣⁢Map your software infrastructure⁯⁭⁮‍⁬‍‌⁠⁯⁬⁠⁫⁪⁫⁬‍⁪⁪⁠⁬؜⁣⁤',
  'dragonfruit-page-component-details.component-main.relationships.empty-state.learn-more':
    '⁣⁢Learn how to define dependencies in a compass.yml file.‍⁮⁠‌؜⁡⁠⁮⁪⁠‍⁮⁬⁫⁬⁮⁪⁯⁮‌⁡‌‌⁡⁣⁤',
  'dragonfruit-page-component-details.component-main.relationships.relationship-list-item.component-not-found':
    '⁣⁢The component you are trying to edit could not be found. It may have been removed.؜⁠⁪⁬‌⁪؜⁪⁯⁭⁫⁪⁮⁬⁬؜‍‍‌⁯⁠⁠⁮⁣⁤',
  'dragonfruit-page-component-details.component-main.relationships.relationship-list-item.deleteRelationshipWithComponent':
    '⁣⁢Delete relationship with {componentName}⁭‌‌⁡‍⁪⁯⁭⁯؜⁠⁡⁬⁡⁡‍⁮⁯‌⁪⁬⁪⁡⁡⁠⁯⁣⁤',
  'dragonfruit-page-component-details.component-main.relationships.relationship-list-item.error-deleting-dependency':
    '⁣⁢Error deleting component dependency⁫⁪⁪⁠؜⁪⁡⁪‍⁮⁡⁮⁮⁬⁯⁡؜⁮‌⁣⁤',
  'dragonfruit-page-component-details.component-main.relationships.relationship-list-item.error-deleting-relationship':
    '⁣⁢An error occurred while deleting this dependency. Try deleting the dependency again.⁪⁭⁡⁫‍‌⁬⁠⁪‌⁫⁠‌⁡⁫‍⁬⁠⁡⁫‌⁫⁮⁫⁣⁤',
  'dragonfruit-page-component-details.component-main.relationships.relationship-list-item.error-deleting-relationship-not-found':
    '⁣⁢The dependency you are trying to remove could not be found. It may have been removed already.⁡⁯‌⁬‌⁬⁭⁯⁭⁮⁡⁮⁯⁬؜⁫⁪⁭⁭⁫⁮⁫⁣⁤',
  'dragonfruit-page-component-details.component-main.relationships.relationship-list-item.remove-dependency-description':
    '⁣⁢The dependency between this component and <b>{componentName}</b> will no longer exist. You can add the dependency again if you ever need to.⁡‌⁮⁪⁡‌⁫⁮⁮⁠⁮⁪⁪؜‍⁡⁪⁬⁫‌⁪‍⁬؜⁪⁣⁤',
  'dragonfruit-page-component-details.component-main.relationships.relationship-list-item.remove-dependency-title':
    '⁣⁢Remove dependency?⁮⁡⁭‌⁠؜⁭⁯‍⁬⁫⁯⁬⁭⁫⁬⁬⁬‌⁣⁤',
  'dragonfruit-page-component-details.component-main.relationships.relationships-view.description':
    "⁣⁢Define upstream dependencies to understand whether you're affected if downtime occurs.⁯⁪؜⁮‌؜⁡‍⁡⁯‌⁭⁬⁪⁯⁭⁪‌⁡⁠‍⁣⁤",
  'dragonfruit-page-component-details.component-main.relationships.relationships-view.error-message':
    "⁣⁢We couldn't load your dependencies‌⁬⁭⁪⁯⁯⁫⁪⁬⁭⁬‌؜⁫⁯⁭‍⁪‍⁡⁣⁤",
  'dragonfruit-page-component-details.component-retrieval-error-message':
    "⁣⁢We couldn't load your component.⁬⁪‌⁭‌⁭⁯⁫⁠⁭‌؜‌⁠‍؜⁠⁡⁣⁤",
  'dragonfruit-page-component-details.data-manager-info.bottom-bar.nonfinal':
    '⁣⁢Managed by compass.yml in {forgeAppName}⁪⁯؜؜⁡⁭⁭⁠⁯‌⁬⁫⁮⁯‍⁬؜⁬⁠⁬⁭⁪⁫؜‍⁬⁣⁤',
  'dragonfruit-page-component-details.error-heading':
    '⁣⁢Something went wrong؜⁪⁡‍‌⁬⁮⁮‌⁮⁬⁯⁡⁫‌⁬⁡؜‍؜⁯⁡⁠؜‌⁪‌⁣⁤',
  'dragonfruit-page-component-details.header-dropdown.apply-scorecard-to-component-button-text':
    '⁣⁢Apply scorecard⁪⁮⁬‌⁮⁪⁭⁬⁮⁡⁮⁫‌⁭⁡⁬⁡⁭‌⁯⁡⁠⁮‍⁬⁣⁤',
  'dragonfruit-page-component-details.invalid-url-error-message':
    '⁣⁢Make sure the URL you entered is correct and try again.⁡⁭‍‍⁯⁯‌؜‍‌⁠⁫⁫⁠⁡⁡⁠⁪‍‌⁠؜⁣⁤',
  'dragonfruit-page-component-details.last-deployed':
    '⁣⁢Last deployed‌؜؜؜؜⁫؜⁮⁮؜⁫⁡⁡‌⁬‍⁫⁫⁠⁮⁪⁮⁬⁠؜⁣⁤',
  'dragonfruit-page-component-details.last-deployed.deployment':
    '⁣⁢Deployment؜⁪‌⁭⁮؜⁬⁬⁠⁭⁠⁮؜⁮⁭⁫⁡⁡⁡⁡⁣⁤',
  'dragonfruit-page-component-details.last-deployed.environment':
    '⁣⁢Environment‌⁬‌⁯⁪⁡⁮⁪‌⁯⁡⁮⁡⁡⁭‍⁮⁭⁮؜⁡⁪⁯⁠⁣⁤',
  'dragonfruit-page-component-details.left-sidebar-links.dependencies':
    '⁣⁢Dependencies⁯⁫⁭⁠‌⁮⁯⁯‍⁪⁫⁬⁬⁫‌⁮⁮⁪⁯⁭⁯؜⁮؜⁠⁮⁣⁤',
  'dragonfruit-page-component-details.left-sidebar-links.jira.nonfinal':
    '⁣⁢Jira Issues⁭⁮؜⁮⁯؜؜⁯‍⁠⁡⁠‍⁫⁮‍⁯‍⁭⁣⁤',
  'dragonfruit-page-component-details.left-sidebar-links.overview':
    '⁣⁢Overview‍؜⁬⁡⁪⁡‌؜⁬⁯⁮‍⁬⁮⁡‌‍⁪‌⁣⁤',
  'dragonfruit-page-component-details.left-sidebar-links.settings.nonfinal':
    '⁣⁢Component settings‌⁯⁬⁫⁡⁫⁪⁯⁬⁠⁮⁡⁪⁠⁯⁡‌⁮⁠⁪⁫⁬⁠⁠⁣⁤',
  'dragonfruit-page-component-details.right-panel-contents.header-dropdown.compass-yml-link-text':
    '⁣⁢Edit in compass.yml⁬⁬⁬⁡‍⁯⁭⁠⁪؜‌⁮؜‌⁪⁬⁡⁮⁠؜⁣⁤',
  'dragonfruit-page-component-details.right-panel-contents.header-dropdown.component-not-found':
    '⁣⁢The component you are trying to remove could not be found. It may have been removed already.⁭⁬⁫⁬⁮⁬⁪⁫⁮‍⁮⁯⁬⁯⁡‌⁡⁪⁬⁬⁭⁬⁮⁡‍⁠⁣⁤',
  'dragonfruit-page-component-details.right-panel-contents.header-dropdown.copy-component-id-button-text':
    '⁣⁢Copy ID⁪؜⁬⁬‍‍⁬⁪⁯⁡⁮⁯⁬⁪⁬⁪⁫⁪⁮⁬؜⁬⁭⁭⁯؜⁣⁤',
  'dragonfruit-page-component-details.right-panel-contents.header-dropdown.flags.copy-id-flag-failure-description':
    "⁣⁢ID couldn't be copied. Try again.⁬‍‌⁬⁬؜‍⁠⁭⁬؜⁮⁪⁬‍⁯⁮⁮⁮⁣⁤",
  'dragonfruit-page-component-details.right-panel-contents.header-dropdown.flags.copy-id-flag-success-title':
    '⁣⁢ID copied!‌⁪⁫⁭⁫⁬‌⁯⁫‍⁬⁬‍⁪⁫‍⁬⁣⁤',
  'dragonfruit-page-component-details.right-panel-contents.header-dropdown.remove-component-button-text':
    '⁣⁢Remove from Compass⁬⁭⁯⁮‍‌⁭⁠⁡⁫‌⁡؜⁯⁬؜⁬⁬⁬‌⁪⁯⁬⁣⁤',
  'dragonfruit-page-component-details.right-panel-contents.header-dropdown.remove-component-delete-modal-description':
    '⁣⁢This will remove <b>{componentName}</b> from Compass, but does not delete it in any other system. All dependencies, links, and ownership information will be permanently deleted.؜⁠⁫‍⁮⁫‌⁯⁪‌⁮؜؜⁪⁪؜‍⁬؜⁯⁪⁪⁣⁤',
  'dragonfruit-page-component-details.right-panel-contents.header-dropdown.remove-component-delete-modal-title':
    '⁣⁢Are you sure you want to remove this component?‍⁪⁮⁡⁠⁯⁠⁭⁠‌⁫⁠⁯⁠‍⁪⁪⁡‍⁭⁬⁪⁪⁯⁣⁤',
  'dragonfruit-page-component-details.right-panel-contents.header-dropdown.remove-component-error-flag-description':
    "⁣⁢<b>{componentName}</b> couldn't be removed. Try removing the component again.⁮⁬⁠‍؜‌⁬؜⁭⁪⁯⁭‍⁯⁪⁯⁮⁫⁫‌‌⁣⁤",
  'dragonfruit-page-component-details.right-panel-contents.header-dropdown.remove-component-error-flag-title':
    '⁣⁢Error removing component⁠⁯‍⁬‍⁡⁫‍⁬⁫⁣⁤',
  'dragonfruit-page-component-details.ui.announcements.page-description.nonfinal':
    '⁣⁢Share upcoming news or changes, and stay up to date with announcements that may affect this component.⁬‌⁠؜⁭⁭⁬⁪⁭‌⁯⁪⁭‌‍⁯⁯⁠؜⁫⁭⁯‍⁬⁣⁤',
  'dragonfruit-page-component-details.ui.announcements.page-header.nonfinal':
    '⁣⁢Announcements⁮؜⁫⁯⁮‍⁫⁬⁠‌⁮⁫‍⁯⁮⁭⁫⁪⁡⁯؜⁣⁤',
  'dragonfruit-page-component-details.ui.component-main.extension-point-page':
    '⁣⁢Error: Unable to render the extension⁮⁭⁫‌⁮⁡⁭؜⁪⁡⁫‍‍‍؜⁯⁠⁪⁡⁬⁡⁣⁤',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.coco-details':
    '⁣⁢This component is managed by the fields defined in the compass.yml file in the source repository.⁮⁭⁪⁮؜⁬⁯⁬⁭⁡⁡‌⁪⁡⁭⁭⁡⁪⁬⁣⁤',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.coco-instructions':
    '⁣⁢Add the compass.yml file to the component repository in {repository}.⁠⁮⁪‌⁬⁫⁫⁫⁯⁬⁫⁭⁭⁬⁭⁡⁠⁫؜⁮⁮⁣⁤',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.coco-recommendation':
    '⁣⁢We recommend using a configuration file to manage your components.‍‌؜‌⁪‍⁪⁫⁮⁭⁡⁯‍⁯؜⁠⁠⁫⁭‌⁮⁣⁤',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.compass-yml-link':
    '⁣⁢View compass.yml.⁫‌⁡⁯⁫⁫‌؜⁠‍⁪؜؜‍⁪⁫⁡⁯⁬⁪⁯⁬‍⁬⁣⁤',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.error-card-title':
    '⁣⁢Last sync failed⁮⁪⁬⁭‍⁮⁪؜‍⁬‍⁡⁫⁫؜⁬⁯‍⁬⁭⁣⁤',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.error-details-link':
    '⁣⁢See error details‌⁠⁡⁭⁯⁮‍‍⁡‍⁬؜⁠؜⁬‍⁫⁣⁤',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.error-learn-more':
    '⁣⁢Learn more about formatting a compass.yml file.⁠⁪؜‍⁮⁭⁭⁠⁮⁫⁬⁬⁠⁮⁯⁯⁯⁭⁭⁬⁭‍‌⁣⁤',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.error-modal-title':
    '⁣⁢Error details‍⁪⁪⁮‍‌‌⁠‌⁡⁮‍⁭⁮⁠؜⁫⁬⁡⁯؜⁠⁣⁤',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.learn-more':
    '⁣⁢Learn more about configuration files⁡⁮⁬⁫‍‌⁫⁠⁪⁮⁯⁫⁫؜⁬⁡⁪⁡⁠⁮؜⁡⁡⁣⁤',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.modal-error-notice':
    '⁣⁢The most recent compass.yml file had an error.⁮‌⁬⁠⁬⁬⁬⁫⁬؜؜⁭⁠⁫؜⁬⁯⁬⁪⁫⁭⁣⁤',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.server-card-error-notice':
    '⁣⁢Something went wrong. Try repushing the commit or checking our⁬⁫⁬⁭⁠‍‌⁡‍⁮⁯⁫⁯⁡‍؜⁭⁡؜⁠⁣⁤',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.source-link':
    '⁣⁢Go to compass.yml⁡⁡⁠؜‌⁡؜⁬⁭⁮‌‌⁡⁬⁫⁯⁯⁪⁬⁡‍⁣⁤',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.title':
    '⁣⁢Component manager‍⁪⁠‍‍⁯‌⁪‌⁫‍⁫‍‌؜⁯‍؜‌⁬⁭؜‍⁣⁤',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.user-card-error-notice':
    '⁣⁢There is something wrong with the most recent compass.yml.⁬‌‌⁡‌‍⁡⁪⁮⁫‌⁪⁪؜؜‍⁯⁭⁮⁮⁡⁭‍⁡⁣⁤',
  'dragonfruit-page-component-details.ui.component-manager.unlinked-card.bitbucket-link':
    '⁣⁢Configure for Bitbucket⁡⁮⁡⁭⁯⁭⁭⁬⁡⁮⁡‌⁭⁭؜‌⁯؜‍⁣⁤',
  'dragonfruit-page-component-details.ui.component-manager.unlinked-card.coco-modal-button':
    '⁣⁢Set up compass.yml‍⁡⁮‍؜⁫⁬؜⁠⁯⁫‍‌‌⁠⁮⁭⁬⁯⁬⁫⁫⁬‌⁣⁤',
  'dragonfruit-page-component-details.ui.component-manager.unlinked-card.nonadmin-configure-instructions':
    '⁣⁢Contact your Compass product admin to get started by setting up the Bitbucket app.⁯‍⁫⁫⁡‍‍⁬⁬⁪؜⁮⁭⁪⁮⁯؜⁫‍⁡⁡؜⁡⁪‍⁪⁣⁤',
  'dragonfruit-page-component-details.ui.component-manager.unlinked-card.title':
    '⁣⁢Manage this component with compass.yml⁯‌⁬‍⁠⁭⁮‌‌‌‌⁠‌⁯⁮‍⁭⁬⁪⁪⁯⁮⁡⁣⁤',
  'dragonfruit-page-component-details.ui.left-sidebar.back-to-components':
    '⁣⁢Back to components⁪⁠؜⁫⁪⁡⁭⁭⁬؜⁭⁮⁭⁭⁮‍‍⁠‍⁡⁠⁬⁣⁤',
  'dragonfruit-page-component-details.ui.overview.left-sidebar-skip-link-title':
    '⁣⁢Component navigation؜⁠⁬⁡‍‍‌⁡⁭‌⁠‍⁬⁡⁫⁯⁡⁣⁤',
  'dragonfruit-page-component-details.ui.overview.right-sidebar-skip-link-title':
    '⁣⁢Scorecards‌⁪‌‌‍⁪⁬⁡‍⁯⁭⁡؜⁭‌⁪⁬⁪⁫⁫⁡‍⁣⁤',
  'dragonfruit-page-component-details.ui.relationships.main-skip-link-title':
    '⁣⁢Component details⁮‍⁡⁠⁠؜⁮‍⁪⁪⁪‍⁫⁯⁮⁬⁫‍‍‌؜⁡‍‍⁣⁤',
  'dragonfruit-page-component-details.ui.relationships.page-header':
    '⁣⁢Dependencies⁫⁭⁯؜⁬‌⁮⁠⁮⁮⁠‌⁠؜‍⁯⁪⁯؜؜⁬⁪⁠⁠⁣⁤',
  'dragonfruit-page-component-details.ui.settings.empty-state.empty-state-description.nonfinal':
    '⁣⁢Use Bitbucket or another SCM tool to manage your components via configuration files. Compass automatically syncs with the configuration file to provide a source of truth.⁪⁡‌‌⁫‌⁯⁯⁮⁪⁠⁭⁪⁡⁪‌⁯⁠⁣⁤',
  'dragonfruit-page-component-details.ui.settings.empty-state.empty-state-heading.nonfinal':
    '⁣⁢Manage components from their source⁪⁯⁮⁪⁠‍⁠⁮⁪‌⁬⁪⁠⁪⁪⁬؜⁪‌؜؜⁣⁤',
  'dragonfruit-page-component-details.ui.settings.empty-state.install-scm-prompt.nonfinal':
    '⁣⁢Install and configure your SCM tool⁭⁮؜⁮⁪‍⁮⁭؜‌⁭‍⁪⁯⁭⁠⁠‌⁭⁭⁬⁣⁤',
  'dragonfruit-page-component-details.ui.settings.empty-state.learn-more.nonfinal':
    '⁣⁢Learn more about component management⁯⁪‍⁪⁡‌⁭⁯‌⁡⁡⁪⁯⁡⁮‌⁡⁮⁠⁡⁫⁣⁤',
  'dragonfruit-page-component-details.ui.settings.empty-state.section-message-description.nonfinal':
    '⁣⁢Contact your Compass product admin to get started by integrating with your SCM tool.⁡⁮‌؜⁡⁮⁯⁠⁪⁪⁭⁭⁯⁪⁪⁠⁭⁪⁠⁮⁣⁤',
  'dragonfruit-page-component-details.ui.settings.empty-state.section-message-heading.nonfinal':
    '⁣⁢You must be a Compass admin to set up component management⁮⁬⁠⁡⁫⁭⁫⁠‌‌⁭⁫⁭⁪⁫‍⁯؜⁭⁡؜‌⁫⁣⁤',
  'page-team-details.components-owner-card.empty-state-managed.add-button':
    '⁣⁢Define in compass.yml⁭⁪‌⁡⁯⁪⁬⁭⁠⁠⁮⁬⁯⁭⁫‌⁬⁮⁪‍⁣⁤',
};
