/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Italian
export default {
  'dragonfruit-page-component-details.common.relationships.component-not-found':
    'Impossibile trovare il componente che stai cercando di modificare. Potrebbe essere stato rimosso.',
  'dragonfruit-page-component-details.common.relationships.error-creating-flag-description':
    'Si è verificato un errore durante la creazione della dipendenza. Prova ad aggiungerla di nuovo.',
  'dragonfruit-page-component-details.common.relationships.error-creating-flag-title':
    'Si è verificato un errore durante la creazione della dipendenza del componente',
  'dragonfruit-page-component-details.component-main.overview.labels-section.editor-add-value-format':
    'Aggiungi <b>&quot;{labelName}&quot;</b>',
  'dragonfruit-page-component-details.component-main.overview.labels-section.editor-no-options-message':
    'Inizia a digitare per aggiungere etichette',
  'dragonfruit-page-component-details.component-main.overview.labels-section.editor-placeholder':
    'Aggiungi etichette',
  'dragonfruit-page-component-details.component-main.overview.labels-section.editor.validation-label-already-added':
    'Questa etichetta è già stata aggiunta al componente',
  'dragonfruit-page-component-details.component-main.overview.labels-section.editor.validation-label-max-length':
    "L'etichetta deve contenere al massimo {characterLimit} caratteri",
  'dragonfruit-page-component-details.component-main.overview.labels-section.editor.validation-limit-reached':
    'Un componente può avere un massimo di {labelLimit} etichette',
  'dragonfruit-page-component-details.component-main.overview.labels.editable-view.editor-view.error-flags.add-label-error-flag-title':
    "Errore durante il salvataggio dell'etichetta del componente",
  'dragonfruit-page-component-details.component-main.overview.labels.editable-view.editor-view.error-flags.component-not-found-error-flag-description':
    'Impossibile trovare il componente che stai cercando di modificare. Potrebbe essere stato eliminato di recente.',
  'dragonfruit-page-component-details.component-main.overview.labels.editable-view.editor-view.error-flags.label-input-cannot-be-empty-error-flag-description':
    "L'elenco delle etichette del componente è vuoto. Specifica almeno un'etichetta e riprova.",
  'dragonfruit-page-component-details.component-main.overview.labels.editable-view.editor-view.error-flags.label-input-too-long-error-flag-description':
    "L'elenco delle etichette del componente contiene troppi valori. Riprova usando al massimo {labelInputLimit} etichette.",
  'dragonfruit-page-component-details.component-main.overview.labels.editable-view.editor-view.error-flags.label-limit-reached-error-flag-description':
    'Un componente può avere un massimo di {labelLimit} etichette. Prova a ridurre il numero di etichette associate al componente.',
  'dragonfruit-page-component-details.component-main.overview.labels.editable-view.editor-view.error-flags.label-name-cannot-be-blank-error-flag-description':
    "Il nome dell'etichetta di un componente non può essere vuoto. Specifica un nome e riprova.",
  'dragonfruit-page-component-details.component-main.overview.labels.editable-view.editor-view.error-flags.label-name-cannot-contain-uppercase-characters-error-flag-description':
    "Il nome dell'etichetta del componente deve essere in minuscolo. Rimuovi tutti i caratteri maiuscoli e riprova.",
  'dragonfruit-page-component-details.component-main.overview.labels.editable-view.editor-view.error-flags.label-name-cannot-contain-whitespace-characters-error-flag-description':
    "Il nome dell'etichetta del componente contiene spazi. Rimuovi tutti gli spazi e riprova.",
  'dragonfruit-page-component-details.component-main.overview.labels.editable-view.editor-view.error-flags.label-name-contains-invalid-character-error-flag-description':
    "Il nome dell'etichetta del componente contiene caratteri non validi. Rimuovi questi caratteri e riprova.",
  'dragonfruit-page-component-details.component-main.overview.labels.editable-view.editor-view.error-flags.label-name-too-long-error-flag-description':
    "Il nome dell'etichetta del componente è troppo lungo. Riprova con un nome contenente al massimo {characterLimit} caratteri",
  'dragonfruit-page-component-details.component-main.overview.labels.editable-view.editor-view.error-flags.remove-label-error-flag-title':
    "Errore durante la rimozione dell'etichetta del componente",
  'dragonfruit-page-component-details.component-main.overview.labels.section-title':
    'Etichette',
  'dragonfruit-page-component-details.component-main.overview.labels.section.empty-state':
    'Aggiungi etichette per descrivere questo componente',
  'dragonfruit-page-component-details.component-main.relationships.add-relationship-form.depends-on':
    'Dipende da',
  'dragonfruit-page-component-details.component-main.relationships.add-relationship-form.relationship-already-exists-error':
    'La dipendenza esiste già',
  'dragonfruit-page-component-details.component-main.relationships.add-relationship-form.relationship-already-exists-error-flag-description':
    'Questa dipendenza esiste già. Aggiorna la pagina per vedere le ultime modifiche.',
  'dragonfruit-page-component-details.component-main.relationships.add-relationship-form.relationship-end-node-does-not-exist-error-flag-description':
    'Il componente selezionato come dipendenza non esiste. Potrebbe essere stato rimosso. Riprova con un componente che esiste.',
  'dragonfruit-page-component-details.component-main.relationships.add-relationship-form.relationship-limit-reached-error':
    'Limite di dipendenze raggiunto',
  'dragonfruit-page-component-details.component-main.relationships.add-relationship-form.relationship-limit-reached-error-flag-description':
    'Limite di dipendenze raggiunto. Il numero massimo di dipendenze che un componente può avere è {limit}.',
  'dragonfruit-page-component-details.component-main.relationships.add-relationship-form.relationship-self-referencing-error':
    'La dipendenza di un componente non può essere lo stesso componente. Selezionane un altro.',
  'dragonfruit-page-component-details.component-main.relationships.add-relationship-form.relationship-self-referencing-error-flag-description':
    'La dipendenza di un componente non può essere lo stesso componente. Seleziona un altro componente per creare una dipendenza.',
  'dragonfruit-page-component-details.component-main.relationships.add-relationship-form.relationship-start-node-does-not-exist-error-flag-description':
    'Il componente per cui stai tentando di creare una dipendenza non esiste. Potrebbe essere stato rimosso.',
  'dragonfruit-page-component-details.component-main.relationships.add-relationship-form.search-for-a-component':
    'Ricerca di un componente',
  'dragonfruit-page-component-details.component-main.relationships.empty-state-form.depends-on':
    'Dipende da',
  'dragonfruit-page-component-details.component-main.relationships.empty-state-form.submit-button':
    'Aggiungi dipendenza',
  'dragonfruit-page-component-details.component-main.relationships.empty-state.empty-state-description':
    'Definisci le dipendenze a monte per sapere quando il tempo di inattività ti interessa direttamente.',
  'dragonfruit-page-component-details.component-main.relationships.empty-state.empty-state-heading':
    'Mappa la tua infrastruttura software',
  'dragonfruit-page-component-details.component-main.relationships.empty-state.learn-more':
    'Scopri come definire le dipendenze in un file compass.yml.',
  'dragonfruit-page-component-details.component-main.relationships.relationship-list-item.component-not-found':
    'Impossibile trovare il componente che stai cercando di modificare. Potrebbe essere stato rimosso.',
  'dragonfruit-page-component-details.component-main.relationships.relationship-list-item.deleteRelationshipWithComponent':
    'Elimina la relazione con {componentName}',
  'dragonfruit-page-component-details.component-main.relationships.relationship-list-item.error-deleting-dependency':
    "Si è verificato un errore durante l'eliminazione della dipendenza del componente",
  'dragonfruit-page-component-details.component-main.relationships.relationship-list-item.error-deleting-relationship':
    "Si è verificato un errore durante l'eliminazione di questa dipendenza. Prova a eliminarla di nuovo.",
  'dragonfruit-page-component-details.component-main.relationships.relationship-list-item.error-deleting-relationship-not-found':
    'Impossibile trovare la dipendenza che stai cercando di rimuovere. Potrebbe essere già stata rimossa.',
  'dragonfruit-page-component-details.component-main.relationships.relationship-list-item.remove-dependency-description':
    'La dipendenza tra questo componente e <b>{componentName}</b> non verrà rimossa. Potrai aggiungere di nuovo la dipendenza se ne avrai bisogno.',
  'dragonfruit-page-component-details.component-main.relationships.relationship-list-item.remove-dependency-title':
    'Rimuovere la dipendenza?',
  'dragonfruit-page-component-details.component-main.relationships.relationship-section.add-dependency':
    'Aggiungi dipendenza',
  'dragonfruit-page-component-details.component-main.relationships.relationship-section.depends-on':
    'Dipende da',
  'dragonfruit-page-component-details.component-main.relationships.relationship-section.relationship-limit-reached-error-flag-description':
    'Il numero massimo di dipendenze che un componente può avere è {limit}.',
  'dragonfruit-page-component-details.component-main.relationships.relationship-section.relationship-limit-reached-error-flag-title':
    'Limite di dipendenze raggiunto',
  'dragonfruit-page-component-details.component-main.relationships.relationships-view.description':
    'Definisci le dipendenze a monte per sapere quando il tempo di inattività ti interessa direttamente.',
  'dragonfruit-page-component-details.component-main.relationships.relationships-view.error-message':
    'Impossibile caricare le tue dipendenze',
  'dragonfruit-page-component-details.component-retrieval-error-message':
    'Impossibile caricare il tuo componente.',
  'dragonfruit-page-component-details.description-placeholder':
    'Clicca qui per aggiungere una descrizione',
  'dragonfruit-page-component-details.disabled-description-placeholder':
    'Nessuna descrizione',
  'dragonfruit-page-component-details.error-heading':
    'Si è verificato un problema',
  'dragonfruit-page-component-details.header-dropdown.apply-scorecard-to-component-button-text':
    'Applica scorecard',
  'dragonfruit-page-component-details.invalid-url-error-message':
    "Assicurati che l'URL inserito sia corretto prima di riprovare.",
  'dragonfruit-page-component-details.left-sidebar-links.dependencies':
    'Dipendenze',
  'dragonfruit-page-component-details.left-sidebar-links.overview':
    'Panoramica',
  'dragonfruit-page-component-details.right-panel-contents.header-dropdown.compass-yml-link-text':
    'Modifica in compass.yml',
  'dragonfruit-page-component-details.right-panel-contents.header-dropdown.component-not-found':
    'Impossibile trovare il componente che stai cercando di rimuovere. Potrebbe essere già stato rimosso.',
  'dragonfruit-page-component-details.right-panel-contents.header-dropdown.copy-component-id-button-text':
    'Copia ID',
  'dragonfruit-page-component-details.right-panel-contents.header-dropdown.flags.copy-id-flag-failure-description':
    "Impossibile copiare l'ID. Riprova.",
  'dragonfruit-page-component-details.right-panel-contents.header-dropdown.flags.copy-id-flag-success-title':
    'ID copiato.',
  'dragonfruit-page-component-details.right-panel-contents.header-dropdown.remove-component-button-text':
    'Rimuovi da Compass',
  'dragonfruit-page-component-details.right-panel-contents.header-dropdown.remove-component-delete-modal-description':
    '<b>{componentName}</b> sarà rimosso da Compass, ma non sarà eliminato da altri sistemi. Tutte le informazioni su dipendenze, link e responsabilità saranno eliminate definitivamente.',
  'dragonfruit-page-component-details.right-panel-contents.header-dropdown.remove-component-delete-modal-title':
    'Sei sicuro di voler rimuovere questo componente?',
  'dragonfruit-page-component-details.right-panel-contents.header-dropdown.remove-component-error-flag-description':
    'Impossibile rimuovere <b>{componentName}</b>. Prova a rimuovere di nuovo il componente.',
  'dragonfruit-page-component-details.right-panel-contents.header-dropdown.remove-component-error-flag-title':
    'Errore nella rimozione del componente',
  'dragonfruit-page-component-details.ui.component-main.extension-point-page':
    "Errore: impossibile eseguire il rendering dell'estensione",
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.coco-details':
    'Questo componente è gestito dai campi definiti nel file compass.yml nel repository di origine.',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.coco-instructions':
    'Aggiungi il file compass.yml al repository dei componenti in {repository}.',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.coco-recommendation':
    'Ti consigliamo di utilizzare un file di configurazione per gestire i componenti.',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.compass-yml-link':
    'Visualizza compass.yml.',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.error-card-title':
    'Ultima sincronizzazione non riuscita',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.error-details-link':
    "Visualizza i dettagli dell'errore",
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.error-learn-more':
    'Scopri di più sulla formattazione di un file compass.yml.',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.error-modal-title':
    'Dettagli errore',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.learn-more':
    'Ulteriori informazioni sui file di configurazione',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.modal-error-notice':
    'Il file compass.yml più recente contiene un errore.',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.source-link':
    'Vai a compass.yml',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.title':
    'Gestione componenti',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.user-card-error-notice':
    'Si è verificato un errore con il file compass.yml più recente.',
  'dragonfruit-page-component-details.ui.component-manager.unlinked-card.bitbucket-link':
    'Configura per Bitbucket',
  'dragonfruit-page-component-details.ui.component-manager.unlinked-card.coco-modal-button':
    'Configura compass.yml',
  'dragonfruit-page-component-details.ui.component-manager.unlinked-card.nonadmin-configure-instructions':
    "Contatta l'amministratore del prodotto Compass per iniziare a configurare l'app Bitbucket.",
  'dragonfruit-page-component-details.ui.component-manager.unlinked-card.title':
    'Gestisci questo componente con compass.yml',
  'dragonfruit-page-component-details.ui.left-sidebar.back-to-components':
    'Torna ai componenti',
  'dragonfruit-page-component-details.ui.overview.left-sidebar-skip-link-title':
    'Navigazione tra componenti',
  'dragonfruit-page-component-details.ui.overview.right-sidebar-skip-link-title':
    'Scorecard',
  'dragonfruit-page-component-details.ui.relationships.main-skip-link-title':
    'Dettagli componente',
  'dragonfruit-page-component-details.ui.relationships.page-header':
    'Dipendenze',
  'page-team-details.components-owner-card.empty-state-managed.add-button':
    'Imposta in compass.yml',
};
