/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Korean
export default {
  'dragonfruit-page-component-details.common.relationships.component-not-found':
    '편집하려는 컴포넌트를 찾을 수 없습니다. 이미 제거되었을 수 있습니다.',
  'dragonfruit-page-component-details.common.relationships.error-creating-flag-description':
    '종속성을 만드는 동안 오류가 발생했습니다. 종속성을 다시 추가해 보세요.',
  'dragonfruit-page-component-details.common.relationships.error-creating-flag-title':
    '컴포넌트 종속성을 만드는 동안 오류',
  'dragonfruit-page-component-details.component-main.overview.labels-section.editor-add-value-format':
    '<b>&quot;{labelName}&quot;</b> 추가',
  'dragonfruit-page-component-details.component-main.overview.labels-section.editor-no-options-message':
    '입력하여 레이블을 추가하세요',
  'dragonfruit-page-component-details.component-main.overview.labels-section.editor-placeholder':
    '레이블 추가',
  'dragonfruit-page-component-details.component-main.overview.labels-section.editor.validation-label-already-added':
    '이 레이블을 이미 컴포넌트에 추가했습니다',
  'dragonfruit-page-component-details.component-main.overview.labels-section.editor.validation-label-max-length':
    '레이블은 {characterLimit}자 이하여야 합니다',
  'dragonfruit-page-component-details.component-main.overview.labels-section.editor.validation-limit-reached':
    '컴포넌트에는 최대 {labelLimit}개의 레이블이 있을 수 있습니다',
  'dragonfruit-page-component-details.component-main.overview.labels.editable-view.editor-view.error-flags.add-label-error-flag-title':
    '컴포넌트 레이블을 저장하는 동안 오류',
  'dragonfruit-page-component-details.component-main.overview.labels.editable-view.editor-view.error-flags.component-not-found-error-flag-description':
    '편집하려는 컴포넌트를 찾을 수 없습니다. 최근에 삭제되었을 수 있습니다.',
  'dragonfruit-page-component-details.component-main.overview.labels.editable-view.editor-view.error-flags.label-input-cannot-be-empty-error-flag-description':
    '컴포넌트 레이블의 목록이 비어 있습니다. 한 개 이상의 레이블을 제공하고 다시 시도하세요.',
  'dragonfruit-page-component-details.component-main.overview.labels.editable-view.editor-view.error-flags.label-input-too-long-error-flag-description':
    '컴포넌트 레이블의 목록에 너무 많은 값이 포함되어 있습니다. {labelInputLimit}개 이하의 레이블로 다시 시도하세요.',
  'dragonfruit-page-component-details.component-main.overview.labels.editable-view.editor-view.error-flags.label-limit-reached-error-flag-description':
    '컴포넌트에는 최대 {labelLimit}개의 레이블이 있을 수 있습니다. 컴포넌트와 연결된 레이블 개수를 줄여 보세요.',
  'dragonfruit-page-component-details.component-main.overview.labels.editable-view.editor-view.error-flags.label-name-cannot-be-blank-error-flag-description':
    '컴포넌트 레이블 이름은 비워둘 수 없습니다. 이름을 입력하고 다시 시도하세요.',
  'dragonfruit-page-component-details.component-main.overview.labels.editable-view.editor-view.error-flags.label-name-cannot-contain-uppercase-characters-error-flag-description':
    '컴포넌트 레이블 이름은 소문자여야 합니다. 모든 대문자를 제거하고 다시 시도하세요.',
  'dragonfruit-page-component-details.component-main.overview.labels.editable-view.editor-view.error-flags.label-name-cannot-contain-whitespace-characters-error-flag-description':
    '컴포넌트 레이블 이름에 공백 문자가 포함되어 있습니다. 모든 공백 문자를 제거하고 다시 시도하세요.',
  'dragonfruit-page-component-details.component-main.overview.labels.editable-view.editor-view.error-flags.label-name-contains-invalid-character-error-flag-description':
    '컴포넌트 레이블 이름에 유효하지 않은 문자가 포함되어 있습니다. 유효하지 않은 문자를 제거하고 다시 시도하세요.',
  'dragonfruit-page-component-details.component-main.overview.labels.editable-view.editor-view.error-flags.label-name-too-long-error-flag-description':
    '컴포넌트 레이블 이름이 너무 깁니다. {characterLimit}자 이하의 이름으로 다시 시도하세요',
  'dragonfruit-page-component-details.component-main.overview.labels.editable-view.editor-view.error-flags.remove-label-error-flag-title':
    '컴포넌트 레이블을 제거하는 동안 오류',
  'dragonfruit-page-component-details.component-main.overview.labels.section-title':
    '레이블',
  'dragonfruit-page-component-details.component-main.overview.labels.section.empty-state':
    '이 컴포넌트를 설명하는 레이블을 추가하세요',
  'dragonfruit-page-component-details.component-main.relationships.add-relationship-form.depends-on':
    '다음에 종속',
  'dragonfruit-page-component-details.component-main.relationships.add-relationship-form.relationship-already-exists-error':
    '종속성이 이미 있습니다',
  'dragonfruit-page-component-details.component-main.relationships.add-relationship-form.relationship-already-exists-error-flag-description':
    '이 종속성이 이미 있습니다. 페이지를 새로 고쳐 최신 변경 사항을 확인하세요.',
  'dragonfruit-page-component-details.component-main.relationships.add-relationship-form.relationship-end-node-does-not-exist-error-flag-description':
    '종속성으로 선택한 컴포넌트가 존재하지 않습니다. 이미 제거되었을 수 있습니다. 기존 컴포넌트를 사용하여 다시 시도하세요.',
  'dragonfruit-page-component-details.component-main.relationships.add-relationship-form.relationship-limit-reached-error':
    '종속성 한도에 도달했습니다',
  'dragonfruit-page-component-details.component-main.relationships.add-relationship-form.relationship-limit-reached-error-flag-description':
    '종속성 한도에 도달했습니다. 컴포넌트의 종속성의 최대 수는 {limit}개입니다.',
  'dragonfruit-page-component-details.component-main.relationships.add-relationship-form.relationship-self-referencing-error':
    '컴포넌트는 자체에 종속적일 수 없습니다. 다른 컴포넌트를 선택하세요.',
  'dragonfruit-page-component-details.component-main.relationships.add-relationship-form.relationship-self-referencing-error-flag-description':
    '컴포넌트는 자체에 종속적일 수 없습니다. 다른 컴포넌트를 선택하여 종속성을 만드세요.',
  'dragonfruit-page-component-details.component-main.relationships.add-relationship-form.relationship-start-node-does-not-exist-error-flag-description':
    '종속성을 만들려는 컴포넌트가 존재하지 않습니다. 이미 제거되었을 수 있습니다.',
  'dragonfruit-page-component-details.component-main.relationships.add-relationship-form.search-for-a-component':
    '컴포넌트 검색',
  'dragonfruit-page-component-details.component-main.relationships.empty-state-form.depends-on':
    '다음에 종속',
  'dragonfruit-page-component-details.component-main.relationships.empty-state-form.submit-button':
    '종속성 추가',
  'dragonfruit-page-component-details.component-main.relationships.empty-state.empty-state-description':
    '가동 중지 시간 발생 시 영향을 받는지 파악하려면 업스트림 종속성을 정의하세요.',
  'dragonfruit-page-component-details.component-main.relationships.empty-state.empty-state-heading':
    '소프트웨어 인프라를 매핑',
  'dragonfruit-page-component-details.component-main.relationships.empty-state.learn-more':
    'compass.yml 파일에서 종속성을 정의하는 방법을 알아보세요.',
  'dragonfruit-page-component-details.component-main.relationships.relationship-list-item.component-not-found':
    '편집하려는 컴포넌트를 찾을 수 없습니다. 이미 제거되었을 수 있습니다.',
  'dragonfruit-page-component-details.component-main.relationships.relationship-list-item.deleteRelationshipWithComponent':
    '{componentName}과(와) 관계 삭제',
  'dragonfruit-page-component-details.component-main.relationships.relationship-list-item.error-deleting-dependency':
    '컴포넌트 종속성을 삭제하는 동안 오류',
  'dragonfruit-page-component-details.component-main.relationships.relationship-list-item.error-deleting-relationship':
    '이 종속성을 삭제하는 동안 오류가 발생했습니다. 종속성을 다시 삭제해 보세요.',
  'dragonfruit-page-component-details.component-main.relationships.relationship-list-item.error-deleting-relationship-not-found':
    '제거하려는 종속성을 찾을 수 없습니다. 이미 제거되었을 수 있습니다.',
  'dragonfruit-page-component-details.component-main.relationships.relationship-list-item.remove-dependency-description':
    '이 컴포넌트와 <b>{componentName}</b> 간의 종속성이 더 이상 존재하지 않게 됩니다. 필요하면 종속성을 다시 추가할 수 있습니다.',
  'dragonfruit-page-component-details.component-main.relationships.relationship-list-item.remove-dependency-title':
    '종속성을 제거하시겠습니까?',
  'dragonfruit-page-component-details.component-main.relationships.relationship-section.add-dependency':
    '종속성 추가',
  'dragonfruit-page-component-details.component-main.relationships.relationship-section.depends-on':
    '다음에 종속',
  'dragonfruit-page-component-details.component-main.relationships.relationship-section.relationship-limit-reached-error-flag-description':
    '컴포넌트의 종속성의 최대 수는 {limit}개입니다.',
  'dragonfruit-page-component-details.component-main.relationships.relationship-section.relationship-limit-reached-error-flag-title':
    '종속성 한도에 도달했습니다',
  'dragonfruit-page-component-details.component-main.relationships.relationships-view.description':
    '가동 중지 시간 발생 시 영향을 받는지 파악하려면 업스트림 종속성을 정의하세요.',
  'dragonfruit-page-component-details.component-main.relationships.relationships-view.error-message':
    '종속성을 로드하지 못했습니다',
  'dragonfruit-page-component-details.component-retrieval-error-message':
    '컴포넌트를 로드하지 못했습니다',
  'dragonfruit-page-component-details.description-placeholder':
    '여기를 클릭하여 설명 추가',
  'dragonfruit-page-component-details.disabled-description-placeholder':
    '설명 없음',
  'dragonfruit-page-component-details.error-heading': '문제가 발생했습니다',
  'dragonfruit-page-component-details.header-dropdown.apply-scorecard-to-component-button-text':
    '성과 기록표 적용',
  'dragonfruit-page-component-details.invalid-url-error-message':
    '입력한 URL이 올바른지 확인하고 다시 시도하세요.',
  'dragonfruit-page-component-details.left-sidebar-links.dependencies':
    '종속성',
  'dragonfruit-page-component-details.left-sidebar-links.overview': '개요',
  'dragonfruit-page-component-details.right-panel-contents.header-dropdown.compass-yml-link-text':
    'compass.yml에서 편집',
  'dragonfruit-page-component-details.right-panel-contents.header-dropdown.component-not-found':
    '제거하려는 컴포넌트를 찾을 수 없습니다. 이미 제거되었을 수 있습니다.',
  'dragonfruit-page-component-details.right-panel-contents.header-dropdown.copy-component-id-button-text':
    'ID 복사',
  'dragonfruit-page-component-details.right-panel-contents.header-dropdown.flags.copy-id-flag-failure-description':
    'ID를 복사할 수 없습니다. 다시 시도하세요.',
  'dragonfruit-page-component-details.right-panel-contents.header-dropdown.flags.copy-id-flag-success-title':
    'ID를 복사했습니다.',
  'dragonfruit-page-component-details.right-panel-contents.header-dropdown.remove-component-button-text':
    'Compass에서 제거',
  'dragonfruit-page-component-details.right-panel-contents.header-dropdown.remove-component-delete-modal-description':
    '이렇게 하면 Compass에서 <b>{componentName}</b>을(를) 제거하지만 다른 시스템에서는 삭제되지 않습니다. 모든 종속성, 링크 및 소유권 정보가 영구적으로 삭제됩니다',
  'dragonfruit-page-component-details.right-panel-contents.header-dropdown.remove-component-delete-modal-title':
    '이 컴포넌트를 제거하시겠습니까?',
  'dragonfruit-page-component-details.right-panel-contents.header-dropdown.remove-component-error-flag-description':
    '<b>{componentName}</b>을(를) 제거할 수 없습니다. 컴포넌트를 다시 제거해 보세요.',
  'dragonfruit-page-component-details.right-panel-contents.header-dropdown.remove-component-error-flag-title':
    '컴포넌트를 삭제하는 동안 오류',
  'dragonfruit-page-component-details.ui.component-main.extension-point-page':
    '오류: 확장 기능을 렌더링할 수 없음',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.coco-details':
    '이 컴포넌트는 소스 리포지토리의 compass.yml 파일에 정의된 필드로 관리합니다.',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.coco-instructions':
    '{repository}의 컴포넌트 리포지토리에 compass.yml 파일을 추가하세요.',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.coco-recommendation':
    '구성 파일을 사용하여 컴포넌트를 관리하는 것이 좋습니다.',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.compass-yml-link':
    'compass.yml을 봅니다.',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.error-card-title':
    '마지막 동기화 실패',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.error-details-link':
    '오류 세부 정보 보기',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.error-learn-more':
    'compass.yml 파일의 형식 지정에 대해 자세히 알아보세요.',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.error-modal-title':
    '오류 세부 정보',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.learn-more':
    '구성 파일에 대해 자세히 알아보기',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.modal-error-notice':
    '가장 최근의 compass.yml 파일에 오류가 있습니다.',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.source-link':
    'compass.yml로 이동',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.title':
    '컴포넌트 관리자',
  'dragonfruit-page-component-details.ui.component-manager.managed-by-card.user-card-error-notice':
    '가장 최근의 compass.yml에 문제가 있습니다.',
  'dragonfruit-page-component-details.ui.component-manager.unlinked-card.bitbucket-link':
    'Bitbucket에 대해 구성',
  'dragonfruit-page-component-details.ui.component-manager.unlinked-card.coco-modal-button':
    'compass.yml 설정',
  'dragonfruit-page-component-details.ui.component-manager.unlinked-card.nonadmin-configure-instructions':
    'Bitbucket 앱을 설정하여 시작하려면 Compass 제품 관리자에게 문의하세요.',
  'dragonfruit-page-component-details.ui.component-manager.unlinked-card.title':
    'compass.yml로 이 컴포넌트 관리',
  'dragonfruit-page-component-details.ui.left-sidebar.back-to-components':
    '컴포넌트로 돌아가기',
  'dragonfruit-page-component-details.ui.overview.left-sidebar-skip-link-title':
    '컴포넌트 탐색',
  'dragonfruit-page-component-details.ui.overview.right-sidebar-skip-link-title':
    '성과 기록표',
  'dragonfruit-page-component-details.ui.relationships.main-skip-link-title':
    '컴포넌트 세부 정보',
  'dragonfruit-page-component-details.ui.relationships.page-header': '종속성',
  'page-team-details.components-owner-card.empty-state-managed.add-button':
    'compass.yml에서 설정',
};
